### ISSUE TITLE
Add ability to group columns/rows

### ISSUE THREAD

**Issue by juliusdanek** [burnash/gspread#1005]
**Is your feature request related to a problem? Please describe.**
It would be great if you were able to natively group columns and/or rows

This is relatively easy to achieve with batch_update. See below for the request that I am using. 

```python 
    request = {
        "addDimensionGroup": {
            "range": {
                "sheetId": tab_id,
                "dimension": dimension,
                "startIndex": start_index,
                "endIndex": end_index,
            },
        }
    }```

**Comment by lavigne958** [comment]
Hi @juliusdanek 

I just tried it, I did not know about that feature, this is very nice !

I can certainly add this in the next release (will be 5.3.0)

**Comment by juliusdanek** [comment]
Awesome! Thank you
