### ISSUE TITLE
Add ability to hide columns and/or rows

### ISSUE THREAD

**Issue by juliusdanek** [burnash/gspread#1006]
**Is your feature request related to a problem? Please describe.**
Add ability to hide columns and/or rows. This is achievable via batch_update using the request body below.

```   request = {
        "updateDimensionProperties": {
            "range": {
                "sheetId": tab_id,
                "dimension": dimension,
                "startIndex": start_index,
                "endIndex": end_index,
            },
            "properties": {
                "hiddenByUser": True,
            },
            "fields": "hiddenByUser",
        }
    }```

**Comment by lavigne958** [comment]
Hi @juliusdanek 

I tried it, it works like a charm, I can certainly add this to the next release (will be 5.3.0).

**Comment by juliusdanek** [comment]
Awesome! Thank you. I don't think you need to return the "fields". Works well though.

**Comment by lavigne958** [comment]
> I don't think you need to return the "fields"
sorry, I don't understand your point

Most if it's not every requests in gspread return the response from the API call to the user.

In this request we must set the value for the entry `fields` otherwise the API request is not valid.

**Comment by juliusdanek** [comment]
Ah got it! My bad :) Anyway, thanks for adding this!!
