### ISSUE TITLE
Add ability to protect entire sheet vs. protecting range

### ISSUE THREAD

**Issue by juliusdanek** [burnash/gspread#1009]
**Description**
It would be great to be able to protect an entire sheet vs. just hiding a range. See request below for how to do it:

```json
{
    "addProtectedRange": {
        "protectedRange": {
            "range": {"sheetId": tab_id},
            "warningOnly": False,
            "editors": {"users": ["test@test.com"]},
        }
    }
}
```

**Comment by lavigne958** [comment]
Hi, are you sure this will hide the entire sheet ?

this to me will only add a protected range, that will only prevent UI users from editing this range by showing a warning, then will let them edit the range. So this will not hide anything from what I understand.

**Comment by juliusdanek** [comment]
Sorry, there was a slight mistake between the title and my description. Just edited it. I meant "protected", not hidden. 

However, you are also able to hide sheets. I might file another request for that if I start using it.

**Comment by lavigne958** [comment]
This feature already exists in `gspread` see here:

- https://github.com/burnash/gspread/blob/53697fcd6b6ad8b9ebd36848cb260e163983d1dd/gspread/worksheet.py#L1280
- https://docs.gspread.org/en/latest/api.html#gspread.worksheet.Worksheet.add_protected_range

the underlying functions that handle from an A1 notation to a grid range will handle the empty range if you provide `""` as a range name. then it will return what you describe above in your example: `{"sheetId": "1234xyz"}`
which should work to protect the entire sheet.

I still need to test it to confirm it but I don't see any blocker in this process.

**Comment by juliusdanek** [comment]
@lavigne958 this does indeed work. I didn't understand that from the documentation. Would be great to make that clearer. 

I also added a convenience error handler for ranges that are already protected:

```
    try:
        tab.add_protected_range("", editor_users_emails=["info@sorare.tools"])
    except APIError as api_error:
        #https://stackoverflow.com/questions/4308182/getting-the-exception-value-in-python
        error_dict = api_error.args[0]
        if error_dict["code"] == 400 and "already has sheet protection" in error_dict["message"]:
            return
        raise Exception("Another error occurred")
```

I saw that you are already working on a method to find protected ranges so I will switch to that one later.

**Comment by lavigne958** [comment]
you're right a better documentation should be added, in fact before today I did know you could protect a full sheet and never thought about it but I will add it to the documentation.

thank you very much for helping.
