### ISSUE TITLE
HTTPError: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by timkofu** [burnash/gspread#101]
This code:

 for m in xrange(11): write_sheet.update_acell('a{}'.format(m), 'hi {}'.format(m))

Raises this exception:

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/home/tim/workbench/<ipython-input-23-0eb3def2b2db> in <module>()
----> 1 for m in xrange(11): write_sheet.update_acell('a{}'.format(m), 'hi {}'.format(m))

/usr/local/lib/python2.7/dist-packages/gspread/models.pyc in update_acell(self, label, val)
    405 
    406         """
--> 407         return self.update_cell(*(self.get_int_addr(label)), val=val)
    408 
    409     def update_cell(self, row, col, val):

/usr/local/lib/python2.7/dist-packages/gspread/models.pyc in update_cell(self, row, col, val)
    416         """
    417         feed = self.client.get_cells_cell_id_feed(self,
--> 418                                                   self._cell_addr(row, col))
    419         cell_elem = feed.find(_ns1('cell'))
    420         cell_elem.set('inputValue', unicode(val))

/usr/local/lib/python2.7/dist-packages/gspread/client.pyc in get_cells_cell_id_feed(self, worksheet, cell_id, visibility, projection)
    234                             visibility=visibility, projection=projection)
    235 
--> 236         r = self.session.get(url)
    237         return ElementTree.fromstring(r.read())
    238 

/usr/local/lib/python2.7/dist-packages/gspread/httpsession.pyc in get(self, url, **kwargs)
     66 
     67     def get(self, url, **kwargs):
---> 68         return self.request('get', url, **kwargs)
     69 
     70     def delete(self, url, **kwargs):

/usr/local/lib/python2.7/dist-packages/gspread/httpsession.pyc in request(self, method, url, data, headers)
     63             return request.urlopen(req)
     64         except HTTPError as e:
---> 65             raise e
     66 
     67     def get(self, url, **kwargs):

HTTPError: HTTP Error 400: Bad Request

I have tried to sleep 1 second between requests but the error persists. I'm on ipython.

**Comment by jmc-88** [comment]
I'm having the same problem when trying to read cell values with Worksheet.cell(), even though Worksheet.get_all_records() seems to work.

Any update on this issue?

**Comment by msuozzo** [comment]
@jmc-88, I think this is a different issue from the one you're encountering. Would you mind posting a separate issue where you could give some details about your situation? Thanks

I'm assuming this issue is resolved as it seems to have been fixed by a past update.
