### ISSUE TITLE
Credentials need to be from either oauth2client or from google-auth.

### ISSUE THREAD

**Issue by adiptamartulandi** [burnash/gspread#1014]
**Describe the bug**
Hello, before this days i have used same code to read gsheet and its worked and succeed, but today i try to run my code in google colab is getting error like the images below. wondering whats wrong with my code bcs iam not changing anything in my code.

here is my code
<img width="872" alt="image" src="https://user-images.githubusercontent.com/53418888/160520638-e238a869-8ee4-4492-95d6-3449a56313bc.png">

**Expected behavior**
i can read the gsheet

<img width="872" alt="image" src="https://user-images.githubusercontent.com/53418888/160520376-af445921-cc08-488b-9a9c-cdfca7e04cf3.png">

**Environment info:**
- Operating System [e.g. Linux, Windows, macOS]:
- Python version
- gspread version

**Stack trace or other output that would be helpful**

**Additional context**

**Comment by juaiasi** [comment]
i had the same problem now... i don't know if it's temporary or if it's some configuration in google cloud. Earlier today it was working normaly....

**Comment by talwrii** [comment]
I also have the same problem.

**Comment by hl3437** [comment]
I had the same problem today and has some research on it,
According to Gspread website (https://docs.gspread.org/en/latest/oauth2.html):
"Older versions of gspread have used [oauth2client](https://github.com/google/oauth2client). Google has [deprecated](https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html) it in favor of google-auth. If you’re still using oauth2client credentials, the library will convert these to google-auth for you, but you can change your code to use the new credentials to make sure nothing breaks in the future."

From this document: https://colab.research.google.com/notebooks/io.ipynb#scrollTo=6d0xJz3VzLOo
It seems like replacing the old code with the following solves the problem:

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

**Comment by lavigne958** [comment]
Yes gspread converts the credentials for you in the background for backward compatibility.

Yes this is the right code sample to use in order to use gspread in Google colab. I just created a new code snipet from the example "snippets sheets" and they provide you with the right code snipet to authenticate 🙂.

Thank you @hl3437 for solving this issue.

Closing this issue.

**Comment by WALLICK** [comment]
> I had the same problem today and had some research on it, According to Gspread website (https://docs.gspread.org/en/latest/oauth2.html): "Older versions of gspread have used [oauth2client](https://github.com/google/oauth2client). Google has [deprecated](https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html) it in favor of google-auth. If you’re still using oauth2client credentials, the library will convert these to google-auth for you, but you can change your code to use the new credentials to make sure nothing breaks in the future."
> 
> From this document: https://colab.research.google.com/notebooks/io.ipynb#scrollTo=6d0xJz3VzLOo It seems like replacing the old code with the following solves the problem:
> 
> ```python
> from google.colab import auth
> auth.authenticate_user()
> 
> import gspread
> from google.auth import default
> creds, _ = default()
> 
> gc = gspread.authorize(creds)
> ```
This worked like a charm.

**Comment by 210981-edu** [comment]
> Eu tive o mesmo problema hoje e fiz algumas pesquisas sobre ele, de acordo com o site Gspread ( https://docs.gspread.org/en/latest/oauth2.html ): "Versões mais antigas do [gspread](https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html) usaram [oauth2client](https://github.com/google/oauth2client) . O Google o desativou em favor do google-auth. Se você ainda estiver usando credenciais oauth2client, a biblioteca as converterá em google-auth para você, mas você pode alterar seu código para usar as novas credenciais para garantir que nada seja interrompido no futuro."[](https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html)
> 
> A partir deste documento: https://colab.research.google.com/notebooks/io.ipynb#scrollTo=6d0xJz3VzLOo Parece que substituir o código antigo pelo seguinte resolve o problema:
> 
> ```python
> from google.colab import auth
> auth.authenticate_user()
> 
> import gspread
> from google.auth import default
> creds, _ = default()
> 
> gc = gspread.authorize(creds)
> ```

**Comment by 210981-edu** [comment]
Man, 

> > Eu tive o mesmo problema hoje e fiz algumas pesquisas sobre ele, de acordo com o site Gspread ( [https://docs.gspread.org/en/latest/oauth2.html ): "Versões mais antigas do ](https://docs.gspread.org/en/latest/oauth2.html)[gspread](https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html) usaram [oauth2client](https://github.com/google/oauth2client) . O Google o desativou em favor do google-auth. Se você ainda estiver usando credenciais oauth2client, a biblioteca as converterá em google-auth para você, mas você pode alterar seu código para usar as novas credenciais para garantir que nada seja interrompido no futuro."[](https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html)
> > A partir deste documento: https://colab.research.google.com/notebooks/io.ipynb#scrollTo=6d0xJz3VzLOo Parece que substituir o código antigo pelo seguinte resolve o problema:
> > ```python
> > from google.colab import auth
> > auth.authenticate_user()
> > 
> > import gspread
> > from google.auth import default
> > creds, _ = default()
> > 
> > gc = gspread.authorize(creds)
> > ```
> 
> Isso funcionou como um encanto.

Resolveu aqui, obrigadão!

**Comment by 210981-edu** [comment]
Man, resolveu aqui, obrigadão!
