### ISSUE TITLE
gspread in Colab throws error when authorizing credentials

### ISSUE THREAD

**Issue by gretiere545** [burnash/gspread#1016]
**gspread in Colab throws error when authorizing credentials** 

Hey, 
This code always runs fine but today it gives an error.

from google.colab import auth
auth.authenticate_user()
import gspread
from gspread_dataframe import get_as_dataframe, set_with_dataframe
from gspread_formatting import *
from oauth2client.client import GoogleCredentials
**gc = gspread.authorize(GoogleCredentials.get_application_default())**

**Environment info:**
- Google Colab / Google Drive
- Python version is 3.7
- gspread version is current

**Trace info**
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-9-3c67835cbb9b>](https://localhost:8080/#) in <module>()
     22 from gspread_formatting import *
     23 from oauth2client.client import GoogleCredentials
---> 24 gc = gspread.authorize(GoogleCredentials.get_application_default())
     25 from airtable import Airtable
     26 get_ipython().system('export PYTHONIOENCODING=utf8')

2 frames
[/usr/local/lib/python3.7/dist-packages/gspread/utils.py](https://localhost:8080/#) in convert_credentials(credentials)
     59 
     60     raise TypeError(
---> 61         'Credentials need to be from either oauth2client or from google-auth.'
     62     )
     63 

TypeError: Credentials need to be from either oauth2client or from google-auth.

Thanks for your help.

Kind regards

Gilles

**Comment by melissaagill** [comment]
I received the same error a couple of minutes ago.

**Comment by juaiasi** [comment]
It was solved here:
https://github.com/burnash/gspread/issues/1014#issuecomment-1082446914

**Comment by lavigne958** [comment]
Thank you @gretiere545 for raising this issue but has been solved (as mentioned by @juaiasi ) in #1014.

Closing this issue.
