### ISSUE TITLE
Docs link in repo metadata is broken

### ISSUE THREAD

**Issue by timmc-edx** [burnash/gspread#1026]
In the repo's About box on Github, there's a link to <https://docs.gspread.org>, which redirects to <https://docs.gspread.org/en/v5.3.1/> -- a 404 page.

In contrast, the README links to <https://gspread.readthedocs.io/en/latest/>, redirecting to <https://docs.gspread.org/en/latest/> (which does work).

**Comment by lavigne958** [comment]
Thank you for pointing out this issue, I will fix it.

**Comment by lavigne958** [comment]
It's fixed now, thank you.

**Comment by timmc-edx** [comment]
Sorry, I should clarify -- the problem is the little box up to the right, as pictured here:

![image](https://user-images.githubusercontent.com/59623490/163197552-2cf1e46f-1b9b-41c6-9777-b9f1a1503e19.png)

**Comment by lavigne958** [comment]
Yes I understand, and the link you see now brings you to the latest version of the doc.

**Comment by timmc-edx** [comment]
Aha! It's a caching issue. Looks like it should resolve after about a day, if I'm reading the headers correctly.

(In a private browsing window, it does in fact redirect to the correct place now. Thank you!)
