### ISSUE TITLE
Expensive client.openall() can be replaced with undocumented function

### ISSUE THREAD

**Issue by sjvdm** [burnash/gspread#1034]
**Describe the bug**
client.open_all() causes a high number of APIError's from Google (ReadRequestsPerMinutePerUser) when you have a large number (in my case, more than 60) sheets - where this threshold is breached. The use case was just to get a list of sheets.

An undocumented and seemingly much cheaper method is client.list_spreadsheet_files() - the method description is missing from api.rst, so not auto populating on docs.

**To Reproduce**
```
from oauth2client.service_account import ServiceAccountCredentials
import gspread

scope = ['https://www.googleapis.com/auth/spreadsheets',
                'https://www.googleapis.com/auth/drive']
gsheet_creds = your_creds_json_file
creds = ServiceAccountCredentials.from_json_keyfile_name(gsheet_creds, scope)
client = gspread.authorize(creds)
client.openall()
```

**Expected behavior**
Docs should be added for list_spreadsheet_files, and the method of openall should be optimized (if possible) to not hit the API as hard.

**Operating System and environment**
- Centos 7
- Python version: 3.8.0
- gspread version: 5.3.2

**Additional context**
Not sure if this is a bug or more a suggestion. I probably could have done a pull request, but feels that other users might experience the API error and this might provide more context.

**Comment by lavigne958** [comment]
Hi thank you for raising this issue.

I agree the method `list_spreadsheet_files` does not have a docstring and this should be fixed.

On the other side the method `openall` uses the method `list_spreadsheet_files` to list all the spreadsheets then return a list of `Spreadsheet` instances.

You could use this method to list all the spreadsheets and then base your logic on the result. What you save, as per API calls, is 1 API call per spreadsheet you open (which can be a lot depending on the number of spreadsheets).

Side note: you can filter the spreadsheets you want to open by name which can help you reduce the number of API calls.

But this can be improved using some pattern matching (like with regex) and I will look into the API if I can find some filter that can return a list of spreadsheets marching the given argument `name` in case it can help reduce the number of API calls too.

**Comment by sjvdm** [comment]
Thanks. Our use case is just to check all existing sheets - which `list_spreadsheet_files` seems much cheaper.

**Comment by lavigne958** [comment]
do you mean `spreadsheets` or actual `sheet` ? just to clarify a `sheet` is the actual tab that you can add/reorder/remove/rename inside a single `spreadsheet`. a `spreadsheet` is the actual file stored in a Google Drive folder :slightly_smiling_face: 

If you mean `spreadsheet` then yes for sure the above method is much cheaper because is returns the list you are looking for in a single API call.

**Comment by sjvdm** [comment]
Apologies, my comment edited :) It's spreadsheets!

Thanks for an awesome lib.
