### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by jd-0001** [burnash/gspread#1037]
**Is your feature request related to a problem? Please describe.**
Dev community is loving the types and it also improves DX.

**Describe the solution you'd like**
Providing stub files for gspread package

**Describe alternatives you've considered**
None

**Additional context**
I am using mypy and getting this error 'Stub file not found for "gspread"'

![image](https://user-images.githubusercontent.com/47495003/165033235-37b5b12d-ecb2-4b15-86da-5d4fb03d039e.png)

**Comment by lavigne958** [comment]
Hi this is big subject for us, we already have a PR open about this.

I am working on it, it just takes time.

We currently have some circular dependencies that I need to solve, which implies to release a new major version of `gspread`.

It is currently planed for version 6.0.0

see issue #966 

closing this issue.
