### ISSUE TITLE
remove console flow authentication method

### ISSUE THREAD

**Issue by lavigne958** [burnash/gspread#1045]
## Overview

as mentioned in #1032  the authentication flow using `console_flow` has been deprecated by google and should be removed.

Any code related to it can be removed, we can update the dependency `google-auth-oauthlib`

This is a major change (even though people using it are already blocked due to the API beeing disabled) we must remove this part in a major release.

Update our dependencies on the way:
- google-auth
- google-auth-oauthlib

**Comment by lavigne958** [comment]
closed by feature/release_6_0_0

**Comment by brianjmurrell** [comment]
The documentation is still referring to this `console_flow` in https://docs.gspread.org/en/latest/api/auth.html#gspread.auth.oauth and https://docs.gspread.org/en/latest/api/auth.html#gspread.auth.oauth_from_dict.

But more to the point, does this mean the **only** way to authenticate it to have a browser available on the host where gspread is running?  What if such a host is "headless" without any physical display?

**Comment by alifeee** [comment]
hi @brianjmurrell thanks for the request :]

if you think your change will work, then you are welcome to try and test it, to see if it does

the best eventuality would be that if it works, you could suggest adding it. I'm not super clued up with how auth works though, so I would ask @lavigne958 to test it. not sure of their availability at the moment.
