### ISSUE TITLE
release v5.4.0

### ISSUE THREAD

**Issue by fcakyon** [burnash/gspread#1048]
Hello, thanks for this awesome package!

I need to use export feature but the latest gspread release does not have export feature.

Do you have any ETA for gspread v5.4.9 release?

**Comment by lavigne958** [comment]
Hi, you can find all of them in the milestone section here: https://github.com/burnash/gspread/milestones

Some of them may change (due date might be pushed back to wait for some features/bugfix), or may be some issues will not be in the next release as planned.

BTW: first result on google search (pip install package from github, https://stackoverflow.com/questions/8247605/configuring-so-that-pip-install-can-work-from-github :wink: ) so you can use the `export` feature before the coming release.

Closing this issue.
