### ISSUE TITLE
Unable to open / find spreadsheets

### ISSUE THREAD

**Issue by djwagyu** [burnash/gspread#105]
Hi,

I'm running on Python 3.3 on a mac, just loaded gspread and was typing in commands from the shell direct.

I am unable to open my spreadsheets, have tried using all 3 methods (open, open_by_key, open_by_url).

Here's my code from the command shell:
import gspread
mylogin = gspread.login('username','password')
spreadsheet = mylogin.open_by_url('https://docs.google.com/spreadsheets/d/1R8y14lGTdGlmY7naEbVK3pRidbR-JVzsDJ3NGVLAqn0/edit?pli=1#gid=0')

Here's the error:
Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    spreadsheet = mylogin.open_by_url('https://docs.google.com/spreadsheets/d/1R8y14lGTdGlmY7naEbVK3pRidbR-JVzsDJ3NGVLAqn0/edit#gid=0')
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/gspread/client.py", line 173, in open_by_url
    raise NoValidUrlKeyFound
gspread.exceptions.NoValidUrlKeyFound

The title of my test spreadsheet is 'test'.

When I used:
spreadsheet = mylogin.open('test')

I get:
Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    spreadsheet = mylogin.open('test')
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/gspread/client.py", line 130, in open
    raise SpreadsheetNotFound
gspread.exceptions.SpreadsheetNotFound

Using openall also yields an empty list.

Could you kindly advise on what I'm doing wrong? I'm relatively new to using modules like this, and would appreciate any help. Thanks!

**Comment by ror6ax** [comment]
Got 'gspread.exceptions.NoValidUrlKeyFound' for existing URL. Name lookup also gives error.
`openall` returns empty list.

See full helloworld app:

```
import gspread
import json
from oauth2client.client import SignedJwtAssertionCredentials

json_key = json.load(open('maps-9b48d3b264c2.json'))
scope = ['https://spreadsheets.google.com/feeds']
credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)
gc = gspread.authorize(credentials)
for i in gc.openall():
    print i

```

**Comment by msuozzo** [comment]
@ror6ax have you made sure to share the spreadsheet with the `client_email` email?

If that wasn't the issue please provide your:
* Python version
* OS
* gspread version

Best,
msuozzo

**Comment by ProgrammerMatt** [comment]
I'm having the same issue and I did share with the client email. In fact, it was working last night. I don't think I've made any changes since then.

**Comment by puneetkaura** [comment]
I am facing the same problem as faced by ror6ax above - Got 'gspread.exceptions.NoValidUrlKeyFound' for existing URL. Name lookup also gives error, openall returns empty list.

Help please
