### ISSUE TITLE
list_protected_ranges always returns an empty list

### ISSUE THREAD

**Issue by vincmarc** [burnash/gspread#1050]
**Describe the bug**
list_protected_ranges always returns an empty list, I tried several times with different worksheets and python codes.

```python
def get_gspread_client():
    gspread_client = gspread.service_account(
        filename="****************/credentials.json")
    return gspread_client

gspread_client = get_gspread_client()
sh = gspread_client.open_by_key(spreadsheet_id)
ranges=sh.list_protected_ranges(sheet_id)
```

- Operating System Windows 10
- Python version 3.9
- gspread version 5.3.2

**Comment by lavigne958** [comment]
Hi, I'm sorry but I need more context. Your code looks fine.
I tried it myself and I can list the protected ranges from a spreadsheet.

Are you sure you set the protected ranges ?
Are you sure this is the right sheet ID ?
If the method returns an empty list, either you don't have any protected ranges or it did not find the sheet ID.

**Comment by vincmarc** [comment]
Hi,
Yes I tried several times with different spreadsheets, sheets, all of them with protected ranges. I am using the credentials of a service account that perfectly works for other automation tasks. Which additional info do you need?

**Comment by lavigne958** [comment]
I don't have much clue about this, could you post here your code sample so we can have a look ?
Could you check if the spreadsheet file is in your drive or a shared drive or the drive of an organization ?
We try to check if the issue is somewhere else perhaps.

**Comment by n5y** [comment]
list_protected_ranges works for me but it does return an empty list instead of raising an error when given an invalid worksheet id.

**Comment by n5y** [comment]
Assuming that was the actual issue, replacing
```python3
try:
    sheet = finditem(
        lambda sheet: sheet["properties"]["sheetId"] == sheetid, sheets
    )

    return sheet["protectedRanges"]
except (StopIteration, KeyError):
    return []
```
with something like
```python3
try:
    sheet = finditem(
        lambda sheet: sheet["properties"]["sheetId"] == sheetid, sheets
    )
except StopIteration:
    raise WorksheetNotFound("id {} not found".format(sheetid))
return sheet.get("protectedRanges", [])
```
would fix it.

**Comment by lavigne958** [comment]
> list_protected_ranges works for me but it does return an empty list instead of raising an error when given an invalid worksheet id.

Hi this is interesting, I'll look at it, looks like we could do better in fact.

I might use your patch. thank you.
