### ISSUE TITLE
Add richt text support

### ISSUE THREAD

**Issue by jcfrt** [burnash/gspread#1052]
Google sheets now support adding multiple hyper links inside one cell, by the use of rich text.

**Potential solution**
A new class could be created in gspread to support rich text values for a cell?

**Additional context**
Some reference from the Google Sheets API reference: [RichTextValueBuilder](https://developers.google.com/apps-script/reference/spreadsheet/rich-text-value-builder), [RichTextValue](https://developers.google.com/apps-script/reference/spreadsheet/rich-text-value)

**Comment by lavigne958** [comment]
Ho this is a great proposal but you provided a link to the Google **AppScript** documentation, or we don't use it at all. We use the Google sheet API, which could you give us access to the following informations for a given sheet:

https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/cells#CellData

**Comment by jcfrt** [comment]
Woops indeed thanks for the correction. This looks promising anyway.

**Comment by lavigne958** [comment]
As we can't do it dur to API limitations, i am closing this issue
