### ISSUE TITLE
`gspread.oauth()` does not allow `authorized_user_filename` to be just a filename, e.g. `"authorized_user.json"`

### ISSUE THREAD

**Issue by josephlou5** [burnash/gspread#1056]
When calling `gspread.oauth()` and passing a custom `authorized_user_filename`, e.g., `"authorized_user.json"`, an error occurs:
```python
FileNotFoundError: [Errno 2] No such file or directory: ''
```
This is because of this line in `auth.py:store_credentials`:
```python
os.makedirs(os.path.dirname(filename), exist_ok=True)
```
Specifically, `os.path.dirname("authorized_user.json") = ''`, but `os.makedirs()` cannot accept an empty string.

A filepath with some directories before the filename works, e.g., `authorized_user_filename="config/authorized_user.json"`. It's only when there are no directories before the filename that this error occurs.

**Comment by lavigne958** [comment]
Hi thank you for raising this issue.

You're right it should be handled using `pathlib.Path` objects.

I am making a new release today (v5.4.0) so I can't include it in it but I can make it for V5.4.1
