### ISSUE TITLE
Implement equality on `Cell` objects

### ISSUE THREAD

**Issue by chisvi** [burnash/gspread#1061]
**Is your feature request related to a problem? Please describe.**
When writing tests for code that makes use of `gspread`, we found a pretty tedious task to compare `Cell` objects, since there's no way to directly compare one instance to another.

**Describe the solution you'd like**
Be able to comparte `Cell` objects instances (e.g. `cell == another_cell`). Taking a look at the code, two `Cell` instances should be equal when they are placed in the same `row` and `col` and contain the same `value`, so it should be easy to implement the corresponding `__eq__` method.

**Describe alternatives you've considered**
Right now, as a workaround, we're doing assertions on each `Cell` instance attributes (e.g. `cell.row == another_cell.row and cell.col == another_cell.col and cell.value == another_cell.value`).

**Additional context**
I've seen that this feature was already requested [here](https://github.com/burnash/gspread/issues/360), but was closed without an answer to this request, therefore I decided to open a specific feature request for it.

**Comment by lavigne958** [comment]
Hi this is a nice feature.

I can definitely add it to gspread. 

Yes it was requested a long time ago but back in that days the API used to represent objects using XML and a `Cell` object required a complete XML tree or now it's a simple API call that results a JSON with a list of values (meaning I don't want to blame the people that decided not to do it back in that days :wink: )

**Comment by chisvi** [comment]
That's great! I would like to contribute by adding this feature if that's ok 🙂
