### ISSUE TITLE
Add re-ordering OR re-naming of worksheets within a spreadsheet

### ISSUE THREAD

**Issue by monal** [burnash/gspread#107]
Basically,I want to delete the default 'Sheet 1' in my spreadsheet.Say,I want my worksheets to be indexed as 'SheetA', 'SheetB','SheetC',etc. I can achieve this if a renaming the worksheet feature is available(rename Sheet1 to SheetA; and add the other worksheets with their respective names).Note: I can't delete Sheet1 because its the first worksheet in the document.Instead,if I can push the Sheet1 behind newly created SheetA,SheetB etc, I can delete it altogether since its no longer the first worksheet.

**Comment by msuozzo** [comment]
This relies on the Google Drive API which is not currently supported. Integration with this API is being discussed/developed in #221.

**Comment by appierys** [comment]
#221 is already closed, but there seems to be still no functionality of re-ordering worksheets
