### ISSUE TITLE
Direct option to service.spreadsheets().values().append().execute()

### ISSUE THREAD

**Issue by fredericomattos** [burnash/gspread#1071]
As it seems to me to be a frequent topic on _StackOverflow_, I believe it has already been debated among the creators of the module, but I didn't find the direct reason, so I was curious.

Is there any reason why the module still doesn't have a function to do the same job as the `service.spreadsheets().values().append().execute()`?

"But what would this function be and why would it be necessary when the `update()` option already exists?"

When invoking `append()` you don't have to worry if you've reached the spreadsheet's row limit, if necessary it adds the number of rows needed for the new values, you don't have to worry about this issue or make multiple separate calls to calculate the total of lines, add new lines and only then do the update.

**Comment by lavigne958** [comment]
Right, if you have any more comment feel free to comment here.

In the meantime: closing this issue.
