### ISSUE TITLE
call col_values via letters identifying the column

### ISSUE THREAD

**Issue by fredericomattos** [burnash/gspread#1073]
When I need to append values in columns where there may be blank values, for example:
```
row 1
row 2
row 3


row 6
```
It is necessary to collect the column values to calculate which first row will be empty to append the new values:
```
sheet = client.open_by_key('XXX').worksheet("GSPREAD")
rows = sheet.col_values(3)
new = [['b'],['c'],['b'],['c'],['b'],['c']]
sheet.append_rows(new,table_range='C'+ str(len(rows)+1))
```
To reduce the risk of errors in updates, for example, I used to add values it to column 3 ('C'), now I'm going to add it to column 1 ('A'), sometimes accidentally forget to change one or the other for the difference display between letters and numbers.

Because `col_values` uses numbers.
`append_rows table_range` uses letters.

If there was an option to use letters in `col_values` I could create a single object (`col`) for both calls:
```
sheet = client.open_by_key('XXX').worksheet("GSPREAD")
col = 'C'
rows = sheet.col_values(col)
new = [['a'],['b'],['c'],['d'],['e'],['f']]
sheet.append_rows(new, table_range = col + str(len(rows)+1))
```

**Comment by lavigne958** [comment]
Hi if I understand correctly your need, it would be: the method `col_values` should accept either a string which hold the column **letter** or a number which holds the column **number** right ?

if so that seems possible but a little bit tricky, because I plan to introduce some typing in gspread very soon, so accepting either a string or a number does not help :smile: 

What if a new method is create to get the values of a column but you provide only a letter as argument ? would that suit your needs perhaps ? :thinking:

**Comment by fredericomattos** [comment]
@lavigne958 , if added something like this inside the `col_values` function to handle number or letter, it would totally solve it:

```
import itertools
import string

col_values = 'AA'

def col_letter_to_num(col, col_abs=False) -> int:
    col_num = col
    if col_num < 0:
        return None
    col_num += 1
    col_str = ''
    col_abs = '$' if col_abs else ''
    while col_num:
        remainder = col_num % 26
        if remainder == 0:
            remainder = 26
        col_letter = chr(ord('A') + remainder - 1)
        col_str = col_letter + col_str
        col_num = int((col_num - 1) / 26)
    return col_abs + col_str

if isinstance(col_values, int):
    col_num = col_values
elif isinstance(col_values, str):
    for i in itertools.count(start=0):
        if col_letter_to_num(i) == col_values:
            col_num = i+1
            break

print(col_num)
```

**Comment by fredericomattos** [comment]
Actually on `elif`, there needs to be a block against a possible input like:
```
YY5
```
If not, it would go into an eternal loop, right?

So not to take the risk it should be something like this:
```
elif isinstance(col_values, str) and not any(x in col_values for x in list(string.digits)):
```

**Comment by fredericomattos** [comment]
Sorry for the archaic way of reaching the expected result, but it's my low level of knowledge that limits me, but you can understand what the expected result is. haha

**Comment by lavigne958** [comment]
Hi that sounds interesting, in fact I will investigate a bit more but I would rather put that function in the `utils.py` and use it to convert some letter to column number (I think we already have a function that does in fact). so you could use is like:
`sheet.col_values(utils.col_letter_to_num('C'))`.
It's less intrusive and useful to anyone who may need it outside of the method `col_values` 

It solves my problem with typing:
- `col_values` keeps accepting only digits
- `col_letter_to_num` accept only letter and return a number

It should solve your issue:
- you can use a letter to identify a column
- It provides a new utility function for whoever may need it.

Would that suit you ? do you wish to open a PR?

**Comment by fredericomattos** [comment]
Really, this way could use it for all other functions instead of changing all the functions to accept letters and numbers, cool, I liked your idea of adding it to utils!

**Comment by lavigne958** [comment]
alright then, let's go for it, this goes to the milestone for the next release !
