### ISSUE TITLE
Add `client_factory` parameter to `auth` methods that call `gspread.Client()`

### ISSUE THREAD

**Issue by jlumbroso** [burnash/gspread#1074]
**Is your feature request related to a problem? Please describe.**
As noted, Google introduced [usage limits](https://developers.google.com/sheets/api/limits). While the behavior seems to not be well defined everywhere (in Drive API, the quota limit return 403 apparently undistinguishable by error code of an auth problem, for instance), in Sheets API the rate limit issue consistently returns 429. The existing `gspread.client.BackoffClient` class deals with this problem elegantly and effectively, and at the cost for the developer of one line change. Unfortunately the `auth` methods use `gspread.client.Client()` internally, in a hard-coded fashion.

**Describe the solution you'd like**
The feature introduces a parameter that is retrocompatible, as it defaults to the current behavior, but it also enables use of the `gspread.client.BackoffClient`.

**Describe alternatives you've considered**
- Modifying my local copy of the package only
- Catching the error at the higher level of my own code, but that seems sub-optimal, as it requires much more error catching code

**Additional context**
This is a small tweak, that is fully documented, that allows for better use of existing functionality of this package.

**Comment by lavigne958** [comment]
closed by #1075
