### ISSUE TITLE
What was the API breakage in gspread 5.0?

### ISSUE THREAD

**Issue by dgilman** [burnash/gspread#1084]
The changelog for 5.0 is a long list of commits and doesn't call out any one of them as a breaking change. Going over the list I can't see anything that looks breaking. Can you please call out in the changelog, and possibly in the API docs if necessary, what important changes went into the 5.0 release? https://github.com/burnash/gspread/releases/tag/v5.0.0

**Comment by lavigne958** [comment]
Hi I went through the list there is not much that can break your code when upgrading to release 5.0.0 except:
#912 

This changes the way some classes are imported in the code.
the single `models.py` has been split into multiple files, so when importing one of the classes in that file user are now required to change the file name where that class is located.

Lucky us prior to that changes the file `__init__.py` already includes these classes so any (prior to the changes) could do
`from gspread inport Spreadsheet` and now after the migration we kept it in the `__init__.py` so the user's import does not change. But if anyone was importing it using `from gspread.models import Worksheet` then it would break.

As there is no issue with gspread I am closing this issue but feel free to comment here if you have questions about the release process :wink:

**Comment by dgilman** [comment]
Thanks!
