### ISSUE TITLE
oauth_from_dict does not work

### ISSUE THREAD

**Issue by muddi900** [burnash/gspread#1087]
**Describe the bug**
The docs asks us to pass the credentials off like this.
```
credentials = {
    {
        "installed": {
            "client_id": "12345678901234567890abcdefghijklmn.apps.googleusercontent.com",
            "project_id": "my-project1234",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            ...
        }
    }
}
```

This is a `dict` inside of `set`. dicts are unhashable in Python, hence can't be an element in a set. I tried just passing off the `dict`:

```creds = {'installed': credentials}```

But then I get ValueError: `ValueError("Client secrets is not in the correct format.")`.  Passing off just the credentials lead to `ValueError: Client secrets must be for a web or installed app'

**To Reproduce**
Just try to authenticate with credentials from dict

**Expected behavior**
Authentications

**Environment info:**
- Windows 10 21H2
- Python version 10.5
- gspread version 5.4.0

Thank you

**Comment by lavigne958** [comment]
Hi thank you for opening this issue.

You're right, the documentation is wrong, there is a extra pair of curly brackets that should not be here.

I'll open right now a PR with the fix in the documentation.

Otherwise I tried it using:

- loading the credential files then passing it as a dict object :heavy_check_mark: 
- setting statically the dict in the code without the extra pair of brackets :heavy_check_mark: 

PR coming in a second.

**Comment by muddi900** [comment]
I have passed the argument without the extra brackets. As mentioned, I still get a ValueError.

The credentials are from my server session. They are from an end user that I have authorized using my custom flow.

**Comment by lavigne958** [comment]
this is strange, I tried it and it works fine, I used the exact same structure as above.

Oh ok, if you use a custom flow I can't help you much :slightly_frowning_face: is the exception raised in your custom flow or in gspread code when using the parsing the `authorized_user_info` ? or when constructing the client object ? :thinking:

**Comment by muddi900** [comment]
The exception is raised by gspread. I want to use gspread as part of my Flask application. The end-user uses Oauth to authorize me to use many different google api scopes. I want to pass off they user Oauth session data to gspread. I got the impression from the docs `oauth_from_dict` is the way to do it. If it's not, is there another way?
