### ISSUE TITLE
rework `sort` method signature

### ISSUE THREAD

**Issue by lavigne958** [burnash/gspread#1090]
## Overview
rework the signature of the method `Worksheet.sort` to expose the expected parameters.

## Details

The method `Worksheet.sort` uses some signature style that hides the possible argument for the method.
This is not needed and not useful for the user.

the current signature is `sort(*specs, **kwargs)` and expects the following arguments:
1. the list of tuples with `(the column, the sort order)`
2. the range where to apply this sort, if provided

the signature should be: `sort(*sorting_spec: List[Tuple[int, str]], range: Optional[str])`

**this update should not introduce any breaking change**.  the first argument must remain the list of positional arguments in order to maintain backward compatibility. The other key/value arguments can be updated to only accept `range`. This is the best we can do

**Comment by OskarBrzeski** [comment]
Arbitrary argument lists use the type of the individual arguments, so the typing there should be:
`*sorting_spec: Tuple[int, str]`.

With Python 3.8, we could go further and specify that the string in each tuple conforms to one of two options like so:
`*sorting_spec: Tuple[int, Literal["asc", "des"]]`.

**Comment by lavigne958** [comment]
Thanks for the tip, I'll use that ! Bad name the kwarg `range` so it's explicit
