### ISSUE TITLE
insert_permission to return permission id

### ISSUE THREAD

**Issue by kamikaze** [burnash/gspread#1109]
Please return permission id after the insert_permission() call so there is no need to list permissions just to get it back

**Comment by lavigne958** [comment]
Hi, this is already the case. 
It has been introduced in the latest release as of today (release v5.5.0)

You see it in the following commit which is part of the v5.5.0 release:

https://github.com/burnash/gspread/commit/50539cf9087a906adfea5789a114c80835f45b08

Closing this issue.

**Comment by kamikaze** [comment]
@lavigne958 is there any release today? I see v5.5.0 was released Aug 31, 2022

**Comment by kamikaze** [comment]
ooooh, my bad... sorry. Got it. And my initial thoughts were about sheet.share() call :( completely messed my feature request

**Comment by lavigne958** [comment]
ho yes, in that case,  I confirm `Spreadsheet.share()` does not return the newly created permission.

I can add that to the next release for sure.

Please next time you need to open a feature request use provided template.
