### ISSUE TITLE
API breakage in get_all_records / numericise_all fix

### ISSUE THREAD

**Issue by dgilman** [burnash/gspread#1118]
**Describe the bug**
The fix in #1082 accidentally broke API compatibility. When the default kwarg for get_all_records numericise_all was changed from None to an empty list this broke anyone who was passing in None explicitly as the function now assumes the argument will always be iterable.

**Code example***
Thanks to githuberto in https://github.com/dgilman/gspread_asyncio/issues/48 for finding this

**Comment by dgilman** [comment]
I am going to release an updated gspread_asyncio right now with the new function signature which will unbreak the gspread_asyncio users. So no need to worry about rushing out a new release on your part.

**Comment by lavigne958** [comment]
ok, great, thank you for taking the time to work around that issue.

**Comment by lavigne958** [comment]
@dgilman New release of gspread has been made. It i coudes the necessary fox to prevent API breaking change.

Let me know if you notice anything else 😉
