### ISSUE TITLE
client.copy method not parsing folder_id correctly after V3 Drive update (5.5.0+)

### ISSUE THREAD

**Issue by tomasobrien-vice** [burnash/gspread#1121]
**Describe the bug**
client.copy() is not respecting the folder_id parameter, when supplied. 
If a spreadsheet is copied, it is located in the source sheet's parent folder. This is expected behavior when 'parents' is/are not supplied in the API call, as per Google:
.."If not specified as part of a copy request, the file will inherit any discoverable parents of the source file."...

**To Reproduce**
1. Copied a spreadsheet with 5.4.0 and specified folder_id ==> success, new sheet created in expected parent folder
2. Same function call with 5.5.0+ ==> sheet created in parent folder of source sheet

I believe the source of the issue is the change from V2 to V3 of the Drive API. Specifically the parent payload parameter was changed from "a collection of parent folders" to "a list of IDs". This change was addressed within the create() method but not copy().
In 5.6.0 client.py lines 314-315 show:
` if folder_id is not None:
            payload["parents"] = [{"id": folder_id}]`

Where I believe it should be (as in client.py 225-226):
` if folder_id is not None:
            payload["parents"] = [folder_id]`

**Environment info:**
- Operating System Linux
- Python version 3.10
- gspread version 5.5.0+

**Comment by lavigne958** [comment]
Hi @tomasobrien-vice thank you for opening this issue 

You're right, the API has slightly changed, I will update the method to copy a file.

**Comment by lavigne958** [comment]
Hi @tomasobrien-vice 
would you like to open a PR for that fix and be part of the contributors for gspread ?
Otherwise I'll do it. Just let me know before friday 21st of october (21/10/22).
