### ISSUE TITLE
Get unformatted effective values (numeric suffixes and prefixes, percentage, money, etc)

### ISSUE THREAD

**Issue by carlosdelfino** [burnash/gspread#1122]
Get numeric values without any formatting, numbers like currency values, percentage are returned with prefixes or prefixes. as in the example below:
```
>>> capa.get_values()
['Consumo Cíclico', 'Comércio', 'Eletrodomésticos', 'R$ 4,15', 'R$ 14,26', '-70,90%', '0,00%', '-468,21', '2,56', '0,81', '25,45%', '-0,13', '-0,17', '-609,19', '-716,30', '-107,11', '0,45', '0,79', '3,58', '-2,3', '1,64', '-0,55', '-0,17', '-6,96', '0,32', '0,68', '1,02', '29,98', '0,00', 'R$ 799.162.819,77']
```

There is a property in the Google Sheet API that suggests returning the cell's effective value, so the suggestion is to create a `ws.get_efetive_values()` function.
```
>>> capa.get_efetive_values()
['Consumo Cíclico', 'Comércio', 'Eletrodomésticos', 4,15', 14,26', '-70,90', '0,00', '-468,21', '2,56', '0,81', '25,45', '-0,13', '-0,17', '-609,19', '-716,30', '-107,11', '0,45', '0,79', '3,58', '-2,3', '1,64', '-0,55', '-0,17', '-6,96', '0,32', '0,68', '1,02', '29,98', '0,00', '799.162.819,77']
```

**Comment by carlosdelfino** [comment]
An alternative is for the `get_values()' function to receive a parameter equivalent to the one suggested in this link: https://developers.google.com/sheets/api/reference/rest/v4/ValueRenderOption

**Comment by lavigne958** [comment]
Hi, the method `get_values()` accepts the following keyword as argument `value_render_option` which you can set to `ValueRenderOption.unformatted` then it won't format the values.

closing this issue.
