### ISSUE TITLE
transfer_ownership returns a 403

### ISSUE THREAD

**Issue by msubel** [burnash/gspread#1141]
**Describe the bug**
transfer_ownership method returns a 403 when attempting to transfer ownership from a ServiceAccount to a regular user (both belonging to the same domain)
`APIError: {'code': 403, 'message': 'The target user cannot be a pending owner on this file.', 'errors': [{'message': 'The target user cannot be a pending owner on this file.', 'domain': 'global', 'reason': 'targetUserCannotBePendingOwnerOnFile'}]}`

**To Reproduce**
Given current owner A (service account) and future owner B (user account in the same domain), the following steps are executed as A
1. Open a Spreadsheet
2. Retrieve permission id of B
3. Transfer_ownership to B

**Expected behavior**
Spreadsheet is owner by B and A has write access

**Code example***
```
sh = gc.open_by_key(gdrive_file_id)
permissions = sh.list_permissions()
permission_id = next(item for item in permissions if item["emailAddress"] == future_owners_email)["id"]
sh.transfer_ownership(permission_id)
```

**Screenshots**

**Environment info:**
- Operating System [e.g. Linux, Windows, macOS]: Ubuntu 20.04.5 LTS
- Python version: 3.8.10
- gspread version: 5.6.2

**Stack trace or other output that would be helpful**
```
APIError                                  Traceback (most recent call last)
/tmp/ipykernel_1592/1208181321.py in <cell line: 12>()
     10 permissions = sh.list_permissions()
     11 permission_id = next(item for item in permissions if item["emailAddress"] == future_owners_email)["id"]
---> 12 sh.transfer_ownership(permission_id)

/opt/conda/lib/python3.8/site-packages/gspread/spreadsheet.py in transfer_ownership(self, permission_id)
    605         }
    606 
--> 607         return self.client.request("patch", url, json=payload)
    608 
    609     def accept_ownership(self, permission_id):

/opt/conda/lib/python3.8/site-packages/gspread/client.py in request(self, method, endpoint, params, data, json, files, headers)
     90             return response
     91         else:
---> 92             raise APIError(response)
     93 
     94     def list_spreadsheet_files(self, title=None, folder_id=None):

APIError: {'code': 403, 'message': 'The target user cannot be a pending owner on this file.', 'errors': [{'message': 'The target user cannot be a pending owner on this file.', 'domain': 'global', 'reason': 'targetUserCannotBePendingOwnerOnFile'}]}
```

**Additional context**
I'm sensing that the implementation here:
[spreadsheet.py:603](https://github.com/burnash/gspread/blob/master/gspread/spreadsheet.py#L603)

should rather say `"role": "owner"` and I'm not sure that `"pendingOwner: True" is needed.

Additionally, according to the the Google Drive API docs, there should be an additional query param that sets `transferOwnership` to `True`

**Comment by msubel** [comment]
After looking at the code, I started thinking that the implementation of `accept_ownership` is actually what I'd expect to happen during `transfer_ownership`

I can't say if this is working as expected because I've stumbled on a problem of changing ownership across domains. Turns out my service account (although part of the same organization) is technically under a different domain…

**Comment by lavigne958** [comment]
Hi thank you for the analysis.

I was about to comment: the error seems that google does not allow you to do so.

The `transfer_ownership` method has been tested and works. 

My major concern for you is that I could not find any details about your issue online and the error message does not tell you *why* you can't transfer the ownership ☹️😔

As there is issue with gspread itself I am closing this issue.

Feel free to comment here if you find anything that should be updated in gspread.

**Comment by jalakoo** [comment]
I get exactly the same error as @msubel when attempting to use either `transfer_ownership` or `share(<email>, perm_type='user', role='owner')`.  

Share with the `writer` role works for me.
