### ISSUE TITLE
columns_auto_resize

### ISSUE THREAD

**Issue by soved** [burnash/gspread#1146]
**Describe the bug**
columns_auto_resize does not consider bolt format of text

**To Reproduce**
1. gsheet = gclient.open_by_url(url)
2. worksheet1 = gsheet.worksheet(sheet)
3. worksheet1.append_row(["Uitvoeringsdatum", 'Laatste sync databron', 'Aantal'],
                          value_input_option='USER_ENTERED')

4. worksheet1.format('1', {'textFormat': {'bold': True}})
5. worksheet1.columns_auto_resize(0, len(worksheet1.get_all_values()[0]))

**Expected behavior**
'Laatste sync databron' should be completely displayed but due to the bold format the 'n' is excluded

**Screenshots**
![image](https://user-images.githubusercontent.com/35339385/202274945-fc190d4e-77f0-46cf-9222-1d40666f0297.png)

**Environment info:**
- Operating System [e.g. Linux, Windows, macOS]: Windows
- Python version: 3.10
- gspread version: 5.4.0

**Comment by lavigne958** [comment]
Hi i see your issue.

Unfortunately, this has nothing to do with gspread 🙄, we send the request to auto resize the columns to the Google servers and that's it. Of it does not display nicely then it's a UI bug.

We can't do anything.

Closing this issue.
