### ISSUE TITLE
Accessing `worksheet.isSheetHidden` property raises KeyError

### ISSUE THREAD

**Issue by NodeJSmith** [burnash/gspread#1149]
**Describe the bug**
Accessing `worksheet.isSheetHidden` raises KeyError.

**To Reproduce**
1. Get a spreadsheet using gspread
2. Get a worksheet from that spreadsheet
3. call `isSheetHidden`

**Expected behavior**
A True/False bool value is returned

**Environment info:**
- OS - Windows 10 - WSL - Ubuntu 20.04
- Python version - 3.10
- gspread version - 5.7.1

**Stack trace or other output that would be helpful**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/username/source/company/google_sheet_ingestion/venv/lib/python3.10/site-packages/explor.py", line 378, in explore
    explore_object(thing, show_hidden=show_hidden, folding=folding)
  File "/home/username/source/company/google_sheet_ingestion/venv/lib/python3.10/site-packages/explor.py", line 214, in explore_object
    data = _extract_members(thing)
  File "/home/username/source/company/google_sheet_ingestion/venv/lib/python3.10/site-packages/explor.py", line 271, in _extract_members
    data["Modules"] = [
  File "/home/username/source/company/google_sheet_ingestion/venv/lib/python3.10/site-packages/explor.py", line 272, in <listcomp>
    item for item in items if inspect.ismodule(getattr(thing, item))]
  File "/home/username/source/company/google_sheet_ingestion/venv/lib/python3.10/site-packages/gspread/worksheet.py", line 147, in isSheetHidden
    return self._properties["hidden"]
KeyError: 'hidden'
```

**Additional context**
From what I can tell, and contrary to the [docs](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/sheets#SheetProperties), it looks like the `hidden` field is only in properties if the value is True.  If that is correct, we should use setdefault to set that value to True if it's not in the dictionary. I'm happy to create a PR for the fix.

**Comment by lavigne958** [comment]
Hi i checked the documentation and it does not mention anything particular about this property.

I will run some manual tests with hidden sheets and visible sheets to check.

My guess is: the properties of the sheet are not pulled from the servers so the property is not set or when pulling the properties we don't pull this specific one.

I'll come back after some testing

**Comment by NodeJSmith** [comment]
@lavigne958 Is the link I included at the bottom of my initial comment not the correct documentation? It shows the `hidden` property.

![image](https://user-images.githubusercontent.com/8505845/203426104-8bf1fae9-1020-41e0-91bd-ed4a5eda93e4.png)

I checked multiple spreadsheets when I was looking into it and only one returned `sheetProperties` with the `hidden` field populated at all. The others had no key for `hidden`. So it is returned, but it's not consistent.

**Comment by lavigne958** [comment]
Yes that the documentation I refer to. It does not mention that the property is _missing_ when it's `false` unless there is something I miss here, which happens more often than not 😄

**Comment by lavigne958** [comment]
Hi I ran some tests and yes the documentation does not mention it but the property is only set if it's `True`.
Through we can't assume just because it's set the value is `True`, for sure if it's not set we can assume it's `False`.

thank you for raising this issue.
