### ISSUE TITLE
AttributeError: 'Spreadsheet' object has no attribute 'transfer_ownership'

### ISSUE THREAD

**Issue by bellgriffin** [burnash/gspread#1156]
Code:
`import gspread

sa = gspread.service_account(filename="service_account.json")
test = sa.create('Test')
test.share('example@email.com', perm_type='user', role='writer', notify=False)
for i in test.list_permissions():
    if i['emailAddress'] == 'example@email.com':
        print(i['emailAddress'])
        test.transfer_ownership(i['id'])`

Traceback:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/gbell/Documents/Apps/territory-reporting/test.py in <cell line: 1>()
      [11](file:///Users/gbell/Documents/Apps/territory-reporting/test.py?line=10) if i['emailAddress'] == 'rmoss@qualtrics.com':
      [12](file:///Users/gbell/Documents/Apps/territory-reporting/test.py?line=11)     print(i['emailAddress'])
----> [13](file:///Users/gbell/Documents/Apps/territory-reporting/test.py?line=12)     test.transfer_ownership(i['id'])

AttributeError: 'Spreadsheet' object has no attribute 'transfer_ownership'

**Comment by lavigne958** [comment]
Hi please use the provided template for any big you encounter in gspread.
