### ISSUE TITLE
Sub sheet name changing automatically sometimes by adding some suffix like `_conflict2130205573`

### ISSUE THREAD

**Issue by raviteja1766** [burnash/gspread#1160]
my sub sheet name is updating while adding some rows to it.
sub sheet name: 'Main_1' but it changed to 'Main_1_conflict2130205573'
How can it be possible, is this meaning that cells are merged or cleared for this subsheet?

**Comment by lavigne958** [comment]
Hi could you please explain the concept of "sub sheet" ? I don't see any part of gspread code renaming a sheet without the user consent. That might be some google spreadsheet behavior in some scenarios.

it can be documented for sure, I just need to have a bit more context so I know where to look.

**Comment by raviteja1766** [comment]
I refer `worksheet` as `subsheet`.
we are just adding some bulk amount of rows to a worksheet. Then this issue araises.
Can you know why?
`That might be some google spreadsheet behavior in some scenarios.`
Can you elaborate the above statements?

**Comment by WBETHERI** [comment]
I've seen _conflict sheet names before using apps script rather than the python API.

Typically, the behavior is because changes are not fully synced to the sheet when doing something like:
1) Remove sheet named ```Main```
2) Copy sheet named ```Main``` from another sheet

_At this point, if the changes have not been saved (or in apps script land, haven't called SpreadsheetApp.flush()) it can end up with this "conflict" on the new sheet, after which the original ```Main``` sheet finally deletes_


How this behavior would occur when only adding rows to an existing sheet is baffling to me...

**Comment by lavigne958** [comment]
> I refer `worksheet` as `subsheet` here.

Ok I see. 

> we are just adding some bulk amount of rows(1000) to a worksheet. Then this issue araises.
> Can you know why?
> `That might be some google spreadsheet behavior in some scenarios.`
> Can you elaborate the above statement?

Alright I understand better now, then I misunderstood your issue, so my point about some behavior from Google is:

- you add some rows in a sheet
- at the same time someone changes something in the sheet
- then it conflicts.


Are you adding the rows using parallel threads ? Ok using 2 scripts in parallel ?

Apart from something like that I don't have mush idea on about why your sheet name changed.

I'll try to look for answers on spreadsheet doc.

**Comment by lavigne958** [comment]
> I've seen _conflict sheet names before using apps script rather than the python API.
> 
> Typically, the behavior is because changes are not fully synced to the sheet when doing something like:
> 1) Remove sheet named ```Main```
> 2) Copy sheet named ```Main``` from another sheet
> 
> _At this point, if the changes have not been saved (or in apps script land, haven't called SpreadsheetApp.flush()) it can end up with this "conflict" on the new sheet, after which the original ```Main``` sheet finally deletes_
> 
> 
> How this behavior would occur when only adding rows to an existing sheet is baffling to me...

Yes that's what I thought, about what is the actual issue. So it's a concurent access to your sheet that creates a conflict. You should be able to resolve it by preventing concurent access, by pulling the values before you change something.

**Comment by lavigne958** [comment]
not an issue with gspread code.

closing this issue.
