### ISSUE TITLE
Missing params in Worksheet.set_basic_filter

### ISSUE THREAD

**Issue by njahncke** [burnash/gspread#1161]
**Describe the bug**
The docstring (and api ref) for `set_basic_filter` indicate that it takes numeric params for first/last row/col. The actual function sig only accepts a name param.

**Environment info:**
- gspread version: 5.7.2

**Comment by njahncke** [comment]
Really fantastic work, btw. Thank you very much for creating / contributing to this project!

**Comment by lavigne958** [comment]
> **Describe the bug**
> The docstring (and api ref) for `set_basic_filter` indicate that it takes numeric params for first/last row/col. The actual function sig only accepts a name param.
> 
> **Environment info:**
> - gspread version: 5.7.2
> 

Hi, I think you misunderstood, the method can be used 2 different ways, they are both valid. The signature of the method exposes the main way to use it. But you can use the alternative way too.

First way of using it:

```
worksheet.set_basic_filter("A1:B3")
```

Second way:

```
worksheet.set_basic_filter(1, 1, 2, 3)
```

**Comment by lavigne958** [comment]
> Really fantastic work, btw. Thank you very much for creating / contributing to this project!

Thank you, much appreciated mate. 🤗
