### ISSUE TITLE
tab_color does not support themeColor

### ISSUE THREAD

**Issue by MikesAtMIT** [burnash/gspread#1167]
### Bug

The `Worksheet.tab_color` property does not support Google's `themeColor` objects and raises an error.

### To Reproduce

1. Create a new Google Sheet
2. Go to File > Import and choose Upload and upload the attached [xlsx file](https://github.com/burnash/gspread/files/10572131/tab_color_test.xlsx)
3. In the Google Sheets app itself, you should notice that Sheet3 is missing a tab color, even though it was assigned in Excel
4. Load the Google Sheet in gspread and try to access the `tab_color` property of Sheet3

### Context

The current implementation of `Worksheet.tab_color` assumes the data comes in as an `rgbColor` dict, and raises a `KeyError: 'rgbColor'` if the data contains a `themeColor` instead. I only ran into this when I imported an xlsx file into Google Sheets, then tried to open it in gspread and get the tab color. I haven't figured out how to recreate it natively in Google Sheets because it doesn't seem like the UI for changing the color of a tab gives you access to the theme. And in fact, when you do that import in Google Sheets, the app itself doesn't know how to render the color of that tab and it just looks like it has no color (which would make it hard to track down the source of the issue if you didn't realize this was the problem).

Excel:
![image](https://user-images.githubusercontent.com/3474108/216410535-ccd0e2fe-34a0-461f-8ef8-1591a8532058.png)

Google:
![image](https://user-images.githubusercontent.com/3474108/216410635-5fb68331-4e6e-45d1-b8da-a3873ab49d29.png)

From [Google's docs for tab colors](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/other#colorstyle):
```
{

  // Union field kind can be only one of the following:
  "rgbColor": {
    object ([Color](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/other#Color))
  },
  "themeColor": enum ([ThemeColorType](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/other#ThemeColorType))
  // End of list of possible types for union field kind.
}
```

So really, some of this is on Google for having this data structure that even it doesn't seem to know how to handle properly. 🤷 

I'm not sure what the best solution here is. I could see a few possibilities:

### Option 1: Return the `themeColor`

If you inspect the sheet properties, for a sheet with a themeColor, the data looks like: `'tabColorStyle': {'themeColor': 'ACCENT1'}}`. So the easy thing to do is to update the `tab_color` property to return either the `rgbColor` dict or the `themeColor` string name. But unless what you were trying to do was programmatically replace all the offending `themeColor` data for the tab colors with their respective `rgbColor`, I don't really see how getting this information would be all that useful. But it is maybe the "safest" and most intuitive result.

### Option 2: Return the `rgbColor` of the `themeColor`

I did some more digging and in the spreadsheet properties, there is a `spreadsheetTheme` property, with a list of `themeColors` that have a `colorType` and a `color`. The `color` has an `rgbColor`. So maybe you do that lookup and eventually return the appropriate `rgbColor` dict for the `themeColor`. 

```
# Spreadsheet['properties']
{
    ...,
    'spreadsheetTheme': {
        'primaryFontFamily': 'Calibri',
        'themeColors': [
            {
                'colorType': 'TEXT',
                'color': {'rgbColor': {}},
            },
            ...,
            {
                'colorType': 'ACCENT1',
                'color': {'rgbColor': {'red': 0.26666668, 'green': 0.44705883, 'blue': 0.76862746}},
            },
            ...,
        ],
    },
}

# for a tab with themeColor = 'ACCENT1'
>>> tab.tab_color
{'red': 0.26666668, 'green': 0.44705883, 'blue': 0.76862746}

```

Downside of this is that it assumes that the user specifically wants the RGB values of the color and is not interested in which themeColor it is. Also, it would not align with what the user is actually seeing in Google because those tabs render without a tab color.

### Option 3: Return the actual `tab_color` dict

Leave out the ambiguity and just return the full dict. Even "safer" than Option 1, but more useless since almost all the time it will be an rgbColor that you want, when it exists.

### Option 4: Do nothing

Honestly, maybe the current behavior is appropriate? It's effectively an error on Google's side too since they don't render the color. So maybe it should be raising an error in gspread too.

**Comment by lavigne958** [comment]
Hi, thank you for raising this issue.

After thinking about it I would choose do _do nothing_ properly

What I mean is:
- I don't want to handle cases that the UI itself does not handle in regard of something you that is only useful for the UI (in this case the tab color).
- in the other hand this is an easy error to catch, so we coule create a new gspread exception and raises it when we notice the color is not an RGB color.

In a way I'll go for option 4.

Would that suit you by the way ? 🤔

**Comment by MikesAtMIT** [comment]
Yeah, I think I agree. There's maybe some value in creating an explicit gspread exception so that it's a little more informative what's going on? But probably not that much value.

**Comment by lavigne958** [comment]
I solve the issue itself, I did not go for the extra exception, this was faster and simpler to do. it solve the bug and we agreed that adding extra code to handle cases that we can't see it not worth it :upside_down_face: 

Hope that solves your issue too. making a new release ASAP
