### ISSUE TITLE
Typographical error in documentation 

### ISSUE THREAD

**Issue by raboba2re** [burnash/gspread#1171]
**Describe the bug**
There is a typographical error in the documentation, in the **Clear A Worksheet** sub-section. 

**Expected behavior**
The statement should be "Clear one or multiple **cells** ranges at once", and not "Clear one or multiple **celle** ranges at once"

**Comment by burnash** [comment]
Thanks for spotting this! 
Would you be interested in submitting a pull request with a fix?

**Comment by raboba2re** [comment]
Yes, sure.

**Comment by raboba2re** [comment]
Hello @lavigne958 , can go ahead and create a PR for this?

**Comment by lavigne958** [comment]
Sure go ahead, I'll review it when I get a chance 😉

**Comment by lavigne958** [comment]
Hi @raboba2re any news on the coming PR?
