### ISSUE TITLE
Closing connection early/on-demand, close() quit() dispose()

### ISSUE THREAD

**Issue by andrewtvuong** [burnash/gspread#1172]
**Is your feature request related to a problem? Please describe.**
I am requesting a feature where we can close the client connection early/ on-demand. I have a use case where I run my program involving client.open() very rapidly, this leads to overlapping users on my sheet and causes sync issues.

**Describe the solution you'd like**
I would like to implement or get help implementing a way to close the connection early/on-demand for example:

`gc.quit()` `gc.close()` `gc.dispose()`

**Describe alternatives you've considered**
No alternative exists

**Additional context**

**Comment by lavigne958** [comment]
Hi It took me some time but I finally managed to track one of the requests to the Google API.

I can confirm that the current implementation does not maintain open connection to the Google API.

So each time `gspread` does a request it creates a new connection, then sends the request then closes the connection.

Each time a method from any gspread object returns, the connection is closed.

This feature request does not apply.

closing this issue.
