### ISSUE TITLE
Unable to transfer the ownership

### ISSUE THREAD

**Issue by Mahima-ai** [burnash/gspread#1192]
**Describe the bug**
I want to transfer the ownership of my files from my google service account to the google account.

**To Reproduce**
I followed two methods to transfer the ownership.Steps to reproduce the behavior:
Method 1:
1. Create the spreadsheet.
2. Share the spreadsheet with the owner role.

Method 2:
1. Create the spreadsheet.
2. Insert the permissions for the new account with owner role. This will result in error. So you can try it with writer role to follow step 3.

Both these methods lead to the transferOwnership error. Therefore, as a step 3 do the following:
3. List the permission on the file
4. Transfer the ownership using permission id.

**Expected behavior**
The owner of the file should be changed.

**Code example***

Method 1:
```
import gspread

gc = gspread.service_account()
sh = gc.create('A new spreadsheet')
sh.share(email_address='abc@gmail.com', 
        perm_type='user', role='owner', notify=True, email_message=None, with_link=False)
```

Method 2:
```
import gspread

gc = gspread.service_account()
sh = gc.create('A new spreadsheet')
gc.insert_permission(sh.id, value='abc@gmail.com',
                     perm_type='user',
                     role='writer', notify=True, email_message=None, with_link=False)
```
Step 3:
```
sh.list_permissions()
sh.transfer_ownership('06225724308219458760')
```
**Environment info:**
- Operating System [e.g. Linux, Windows, macOS]: Linux
- Python version: 3.9.16
- gspread version: 5.9

**Stack trace or other output that would be helpful**
Method 1 & 2:
![Screenshot from 2023-05-23 13-07-35](https://github.com/burnash/gspread/assets/61821487/6ab86509-94ad-4372-8843-5797f6287e61)

Step 3:
![Screenshot from 2023-05-23 13-06-52](https://github.com/burnash/gspread/assets/61821487/be68dfc2-c355-44b8-a66d-31c38ad8a127)

**Additional context**
A functionality to  pass params in the [insert_permissions method](https://github.com/burnash/gspread/blob/master/gspread/client.py#L462)

To change the pendingOwner attribute in payload in [transfer_ownership method]( https://github.com/burnash/gspread/blob/master/gspread/spreadsheet.py#L582)

**Comment by lavigne958** [comment]
Hi I tried again your scenario, yes it does not work.

But this is not the right procedure.

you should:

1. share the new spreadsheet with the new user, when doing so use the parameter: `role="writer"` that is the key !
2. transfer ownership to the new user
3. the user can accept the ownership then using the UI

I'll have a look again to the documentation to make it clearer.

**Comment by Mahima-ai** [comment]
Hey @lavigne958, in Method 2, I gave the writer role to the new account, and while listing the permissions it displays the following dictionary (for privacy reasons I have changed the displayName, photoLink and emailAddress):
```
{'id': '06225724308219458760',
  'displayName': 'abc',
  'type': 'user',
  'kind': 'drive#permission',
  'photoLink': 'link.com',
  'emailAddress': 'abc@gmail.com',
  'role': 'writer',
  'deleted': False,
  'pendingOwner': False}
```
But still I get the same error on using the `share()` method and `insert_permission()` method.

**Comment by lavigne958** [comment]
Hi, you do well by hiding personal information.

The permission looks good to me. Now you just need to call the method: `transfer_ownership` with the permission you show here, then the user `abc@gmail.com` will be granted the new ownership.

**Comment by Mahima-ai** [comment]
Hi @lavigne958 , As mentioned in the original post it results in the error.  I have attached the screenshot below:
![Screenshot from 2023-05-29 15-14-59](https://github.com/burnash/gspread/assets/61821487/fb72b256-26f5-4f4a-907a-0ccb51dd97ec)

**Comment by lavigne958** [comment]
Hum this could be a different problem, like the email address for the new owner is out of your Google workspace etc or something like that.

**Comment by Mahima-ai** [comment]
@lavigne958 
The service account is something@google_account_project_name.**iam.gserviceaccount.com** and I want to transfer the ownership of the files created by service account from the service account to the account (google_account_name@**company_name.com**) which created the service account.  

So how can we do that because I assume in every case the accounts will belong to different organization/workspace as the domain will be different for the service account and the other gmail account. If there is any other way to do this, then please let me know.

Thanks.

**Comment by lavigne958** [comment]
I understand, i have the tools to test the same situation, let me run some tests I'll come back to you

**Comment by lavigne958** [comment]
This is what I found:

- I faced the same issue using some google workspace account: returned an error, cannot transfer the ownership to this user.
- I found from the documentation: `Only populated for user type permissions for files that are not in a shared drive`, meaning it does not work with shared drives. [here](https://developers.google.com/drive/api/reference/rest/v3/permissions)
- I found from the documentation: `can be transferred from one Google Workspace account to another account in the same organization` [here](https://developers.google.com/drive/api/guides/manage-sharing#transfer-organization-account)

From what I understand here: you tried to transfer ownership of a file created by a service account from your personal google cloud console [Can be seen here](https://console.cloud.google.com/apis/dashboard).
Or if you wish to create service accounts from your org and share them with your org you should login to the google cloud console using your org google workspace email address. 

Facing that this is not an issue with gspread itself, I am closing this issue
