### ISSUE TITLE
Support Other Authentication Methods

### ISSUE THREAD

**Issue by musicist288** [burnash/gspread#120]
Have you considered incorporating other authentication systems into this package? For example, using a Service Account to authenticate?  I think it would be a nice enhancement.  I don't know if you're trying to keep this library light on dependencies, but it could use the google-api-python-client.  Here's a gist of a simple auth method: https://gist.github.com/musicist288/10734575

**Comment by burnash** [comment]
@musicist288 sorry for a very long delay in reply. Thanks for sharing a gist. The OAuth2 was finally added in 0.2.1 (f7e581b57), and I used similar to the gist approach in docs to show the Signed Credentials usage.
