### ISSUE TITLE
Retrieve URL from Google Sheets Chip

### ISSUE THREAD

**Issue by hawkash** [burnash/gspread#1203]
![Capture-12](https://github.com/burnash/gspread/assets/37810955/4247dac8-f51a-4b45-ba80-7ca3bb656522)

**Comment by hawkash** [comment]
i don't know if this would help.
https://developers.google.com/apps-script/add-ons/editors/gsao/preview-links

**Comment by lavigne958** [comment]
Hi unfortunately this is not possible using the Google Sheet HTTP API (on which gspread rely).

sorry, until google provides a way to retrieve the chip link we can't obtain it.

closing this issue.

**Comment by floriankilian** [comment]
Hi!

Couldn't find a final answer to my question, but it is similar to the question above (I think).

Is there a way to retrieve the "link" link, or is it stored the same way and not accessible with the Google Sheet HTTP API?

![CleanShot Google Chrome 2023-09-07 at 16 02 45@2x](https://github.com/burnash/gspread/assets/34104015/630114af-8973-4207-8b79-cc602e791569)

**Comment by alifeee** [comment]
Hi. Please have a look at #1276 (specifically [this comment](https://github.com/burnash/gspread/issues/1276#issuecomment-1683884966)). I think that is your issue. Let me know if it is irrelevant and I can try to help further.
