### ISSUE TITLE
Create multiple link in a single row

### ISSUE THREAD

**Issue by erwin-d-austria** [burnash/gspread#1204]
Is gsheets can create multiple link in single cell like this on on google SpreadsheetApp.

const value = SpreadsheetApp.newRichTextValue()
.setText("foo no baz")
.setLinkUrl(0, 3, "https://bar.foo/")
.setLinkUrl(7, 10, "https://abc.xyz/")
.setTextStyle(7, 10, boldStyle)
.build();

**Comment by lavigne958** [comment]
Hi thank you for the information.

Gspread is separate product not provided by Google but community based. 

We know we are not completly compliant with the spreadsheet App but we try to keep up.

If you have any feature request please open one using the provided template and we'll have a look if we can implement it :wink: 

Closing this issue.
