### ISSUE TITLE
REFACTOR: Change how colors are handled internally (& externally) with update_tab_color

### ISSUE THREAD

**Issue by alifeee** [burnash/gspread#1213]
There are many problems with how colors are currently set/read. See #1199.

The main issue is that if you send a color of `0.5` to Google, the color is set to `0.49803922` (closest 8-bit value).

This issue proposes that we change how colors are implemented to align to this 8-bit-ness.

## old

```python
color = {
  "red": 0,
  "green": 0.5,
  "blue": 1
}
```

## new

unsure which of these is best

```python
color = "#FF8000"
color = [255, 128, 0]
color = {
  "red": 255,
  "green": 128,
  "blue": 0
}
```

More discussion in #1199 

> Thinking about it:
>
>  - the API uses float values
>  - but colors are always set using integer between [0:255]
>  - why do we have to ask the user for a float and then change it 🧐
>
> Can't we use whol numbers from 0 to 255 do the computation for the API and then return the appropriate value for the user ?
>
> You see what I mean?
>
> Btw: that's a breaking change 😛

> 
> 1. a new method to set the color of a tab, something like: set_tab_color(hex_color) that takes only a color as hex value
> 1. a new function in utils.py that can convert a color from 3 arguments to a hex value: convert_colors_to_hex_value(red, gree, blue) this > way a user can use it 2 in ways seamlessly:
>     1. using direct argument assignment: ..._hex_value(123,43,12)
>     1. using named arguments: ..._hex_value(red=123, green=43, blue=12)

**Comment by lavigne958** [comment]
closed by #1270
