### ISSUE TITLE
Update supported python versions (remove Python 3.7 Support)

### ISSUE THREAD

**Issue by alifeee** [burnash/gspread#1214]
Python 3.7 End of life is [2023-06-27](https://devguide.python.org/versions/)

Here we can gather the things that must be done for removing Python 3.7 support.

- [x] Remove Python 3.7 from [Workflows](https://github.com/burnash/gspread/tree/master/.github/workflows)
- [x] Approve #1150 (now #1236)
- [x] Approve #1165 
- [x] Update " Requires: Python >=3.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.* " on PyPi (automate?)
- [x] Update " Programming Language " on https://pypi.org/project/gspread/ (automate?)
- [x] bump sphinx to latest version (#1235 #1239)

**Comment by alifeee** [comment]
@lavigne958 added to 6.0.0 because I believe this is a "breaking change" that you often mention...

**Comment by alifeee** [comment]
If Python 3.7 is removed from the workflow I think it is definitely breaking

**Comment by alifeee** [comment]
not sure what you mean by "tox classifier", do you mean this?

https://github.com/burnash/gspread/blob/20a2209308f01eb12855307c58a7630923c9d537/tox.ini#L1-L2

> everyone using gpsread on python 3.7 won't be able to use it.

This is the intention, no? For the 6.0.0 release at least, you will not be able to use Python 3.7. If you want to, you must specify gspread v5.

**Comment by lavigne958** [comment]
> not sure what you mean by "tox classifier", do you mean this?
> 
> https://github.com/burnash/gspread/blob/20a2209308f01eb12855307c58a7630923c9d537/tox.ini#L1-L2
> 
> > everyone using gpsread on python 3.7 won't be able to use it.
> 
> This is the intention, no? For the 6.0.0 release at least, you will not be able to use Python 3.7. If you want to, you must specify gspread v5.

sorry my mistake, I meant: the classifier in `setup.py`

which is metadata for pypi to understand thinkgs like which version is compatible with this package.

**Comment by lavigne958** [comment]
Add a new task:

- [ ] bump sphinx to latest version

**Comment by alifeee** [comment]
> bump sphinx to latest version

done in https://github.com/burnash/gspread/commit/d7e968a4b48bdf6815146fe2dfdd91346b8c89da

**Comment by alifeee** [comment]
somehow we should remember to put this in the changelog?

**Comment by lavigne958** [comment]
I don't know yet... we merged in 6.0.0, so we can't tell yet. 
We'll see when we merge 6.0.0 into master branch :grimacing:
