### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by alifeee** [burnash/gspread#1216]
These branches are stale?

- https://github.com/burnash/gspread/tree/3.3.x
- https://github.com/burnash/gspread/tree/feature/improce_sort_method_signature

**Comment by lavigne958** [comment]
Yes they are. The 3.3.x was here when I got here I thought I leave it there if the owner needs it. But now it has been long enough.

I'll delete them.

**Comment by lavigne958** [comment]
done :heavy_check_mark:
