### ISSUE TITLE
Update `tox -e build` script

### ISSUE THREAD

**Issue by alifeee** [burnash/gspread#1218]
`tox -e build` runs [`setup.py`]

https://github.com/burnash/gspread/blob/fde332b9d59c4825207b5d4c56dfe41d299780e6/tox.ini#L44-L47

Some things in [`setup.py`] are outdated

[`setup.py`]: https://github.com/burnash/gspread/blob/master/setup.py

Here we can gather a list of things to update:

- [x] #1230
- [x] update the commands
- [x] update [required python versions](https://github.com/burnash/gspread/blob/fde332b9d59c4825207b5d4c56dfe41d299780e6/setup.py#L55) (automate? - linked to #1214)
- [ ] make sure we deliver the same generated packages for PyPi repository
- [x] add [maintainer](https://github.com/burnash/gspread/blob/fde332b9d59c4825207b5d4c56dfe41d299780e6/setup.py#L50-L51) (me) :)
- [x] [distutils.core](https://github.com/burnash/gspread/blob/fde332b9d59c4825207b5d4c56dfe41d299780e6/setup.py#L11) is deprecated

n.b., some items in the above list are not so clear. you should be able to edit this comment(?)

**Comment by lavigne958** [comment]
Hi thank you I was about to open that issue.

Well can tackle it soon.

**Comment by lavigne958** [comment]
Btw here is the documentation on how to replace old commands with new commands: [new build commands](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html#summary)

**Comment by lavigne958** [comment]
> 

Hi, yes diff the source code you extract from the archive is good way to check we provide the same thing using 2 different build commands.

other ways (not sure it will work) could be checking the md5sum of the resulting archive.
It might be different if the archive contains a timestamp of when the archive is generated but if not. then the md5sumd before and after should be the same.

you can check something:

1. build the package
2. check md5sum of the generated files
3. clean the build directory
4. generate again the packages
5. check the md5sum, if it's the same
6. then we should be able to generate the exact same package with the new build system
7. meaning the md5sum *should* be the same.

though extracting the files and verifying the file list is may be safer.

We'll need to do it once only once we know it works then we can just use it as is (the new build command)

About the test packages Pypi:

- yes can do that too as a final check what ever we choose for the checks
- you can create some credentials to upload packages to test.pypi.org (they have a doc online for that)
- then you uninstall gspread from you computer
- install it using the `pip` command with the argument that allows you to specify the server where to look for packages (something like --package-server or --server-url or somethig like that, it's in the doc too)
- If it installs ifne and you can run some gspread code we're good ! :partying_face:

**Comment by alifeee** [comment]
The md5sum is a good idea. However, some things are different, like the included/excluded files, inclusion of `egg-info`, and the `PKG-INFO` is different as the new build uses the readme instead of the file.

More discussion in #1231
