### ISSUE TITLE
remove property: `gspread.Worksheet.updated`

### ISSUE THREAD

**Issue by alifeee** [burnash/gspread#1224]
I am not sure of best practises in terms of deprecation, for software (with SemVer etc).

Thus, it may be a better idea to leave this in. If this is the case, feel free to close this issue.

However, this property has been deprecated since V4, and doesn't even return anything. It could be removed in v6?

https://github.com/burnash/gspread/blob/20a2209308f01eb12855307c58a7630923c9d537/gspread/worksheet.py#L154-L167

**Comment by lavigne958** [comment]
sure we can do that ! isn't it removed in the feature branch `feature/release_6_0_0` ?

**Comment by alifeee** [comment]
so it is! I didn't realise :)
