### ISSUE TITLE
REFACTOR: homepage badges

### ISSUE THREAD

**Issue by alifeee** [burnash/gspread#1248]
The project badges could be updated

![image](https://github.com/burnash/gspread/assets/13833017/03e55873-332d-44f7-a2cb-cbe516c817fe)

Badge services:

- <https://shields.io/>
- <https://badge.fury.io/> (for version number only)

**Comment by lavigne958** [comment]
I believe we can use shield.io for all of them.

I found the following badges that I think we should have and are provided by the website:

- last build status on master branch: https://shields.io/badges/git-hub-workflow-status-with-event
- read the doc last build status on master branch: https://shields.io/badges/read-the-docs
- GitHub latest tag download: https://shields.io/badges/git-hub-release-latest-by-sem-ver-including-pre-releases
- pypi downloads: https://shields.io/badges/py-pi-downloads
- GitHub licence: https://shields.io/badges/py-pi-license
- pypi compatible python versions ( which seems that we need to take a look at that it only shows up to python 3.9 😬) https://shields.io/badges/py-pi-python-version
- pypi package version: https://shields.io/badges/py-pi


Anything missing? 🤔

**Comment by lavigne958** [comment]
I forgot it would be fun to add the logo for GitHub when it's from GitHub and pypi (if it exists) when it's from pypi

**Comment by alifeee** [comment]
these look great to me!
