### ISSUE TITLE
Update compatible version for PyPi

### ISSUE THREAD

**Issue by lavigne958** [burnash/gspread#1252]
## Overview

PyPi classifier only states the following python versions:
- 3.7
- 3.8
- 3.9

But we support the following versions:
- 3.7
- 3.8
- 3.9
- 3.10
- 3.11

Update the classifier in the pyproject.yaml with the missing versions.

## Note

We keep 3.7 until we make a new major release.

**Comment by alifeee** [comment]
I have updated this on `feature/clean_readme_badges` branch.

**Comment by alifeee** [comment]
closed as I assume #1251 will be merged soon
