### ISSUE TITLE
Certificate verification

### ISSUE THREAD

**Issue by sbirch** [burnash/gspread#126]
I think that httplib / http.client don't perform certificate verification. It's a bit of a tricky issue in general, but since this library only deals with Google's API it might be more straightforward to bundle them (looks like their certificates are good for ~2 years). Are there any plans for this? (And for that matter, does anyone know if there's a best-practice to do this with Python?)

**Comment by msuozzo** [comment]
Not sure about support for cert validation. Should be revisited when requests is merged.

**Comment by msuozzo** [comment]
I just realized that I believe this was addressed by #255. My mistake.
