### ISSUE TITLE
Function for getting the background from a cell

### ISSUE THREAD

**Issue by kxvvv** [burnash/gspread#1261]
**Is your feature request related to a problem? Please describe.**
I need to get the background from the cell

of course, there are options to get the background in a different way, but it's a torment

**Comment by alifeee** [comment]
Hi, thanks for the issue.

This is not in the current scope of gspread. If you want to do formatting, please have a look at https://github.com/robin900/gspread-formatting/, where you can do what you describe.

If you need to use gspread only, you can find the information you want manually, by using [`Spreadsheet.fetch_sheet_metadata({"includeGridData": "true"})`]

[`Spreadsheet.fetch_sheet_metadata({"includeGridData": "true"})`]: https://github.com/burnash/gspread/blob/739b8fca7e91d798d71a446e8849f42b950c2840/gspread/spreadsheet.py#L237-L245

**Comment by kxvvv** [comment]
> If you need to use gspread only, you can find the information you want manually, by using [`Spreadsheet.fetch_sheet_metadata({"includeGridData": "true"})`](https://github.com/burnash/gspread/blob/739b8fca7e91d798d71a446e8849f42b950c2840/gspread/spreadsheet.py#L237-L245)

unfortunately, there is no background information for each cell here, I found only merging

**Comment by alifeee** [comment]
Hi. 
I am able to get background information with the code:

```python
import json
import gspread

gc = gspread.service_account(filename="google_credentials.json")

spreadsheet = gc.open_by_key("<spreadsheet_id>")

metadata = spreadsheet.fetch_sheet_metadata(params={"includeGridData": "true"})

with open("grid_data.json", "w", encoding="utf-8") as f:
    json.dump(metadata, f, indent=4)

## get colour of cell B3
# get metadata
metadata = spreadsheet.fetch_sheet_metadata({"includeGridData": "true"})
sheets = metadata["sheets"]
worksheet = [s for s in sheets if s["properties"]["sheetId"] == 0][0]

cell_data = worksheet["data"]
cell_b3 = cell_data[0]["rowData"][2]["values"][1]

b3_background_color = cell_b3["effectiveFormat"]["backgroundColor"]
print(f"b3 has color:\n{b3_background_color}")
```

I get the output:

```bash
b3 has color:
{'red': 1}
```

Are you sure you are including grid data with `{"includeGridData": "true"}`?

I am happy to help if you encounter further problems :)

**Comment by kxvvv** [comment]
> `{"includeGridData": "true"}`?

omg, i missed this arg, my bad, thanks you so much

**Comment by alifeee** [comment]
> > `{"includeGridData": "true"}`?
> 
> omg, i missed this arg, my bad, thanks you so much

no worries! :) all good

I hope you get what you need!

As I said if you want to do a lot of formatting stuff, you might be better off trying to use https://github.com/robin900/gspread-formatting/

**Comment by kxvvv** [comment]
> As I said if you want to do a lot of formatting stuff, you might be better off trying to use https://github.com/robin900/gspread-formatting/

ok, thanks
