### ISSUE TITLE
worksheet.get(ValueRange) not fetching empty cells if last in the row.

### ISSUE THREAD

**Issue by Zylvian** [burnash/gspread#1284]
**Describe the bug**
When using the `worksheet.get(ValueRange)` function, a data cell will not be parsed if a) it is empty AND b) it is the last cell in the row being parsed.

**To Reproduce**
1. Fill in any value in A1 and B1 of your Google Sheet, leaving C1 empty.
2. Parse the ValueRange using `data = worksheet.get("A1:C1").`
3. Note how the data entry list `data[0]` only contains two values, when 3 are expected.

**Expected behavior**
Empty cells are expected to be parsed as empty entries in the data list. In a range A1:C1, if B1 is empty, it will be parsed as an empty entry as expected. However, if C1 is empty, it is not parsed at all.

**Code example***
Following the example Sheet presented in "To Reproduce":

```
@dataclass
class SheetData:
    name: str
    message: str
    number: str

gc = gspread.service_account()
sh = gc.open_by_key(sheet_id)

ws = sh.get_worksheet(worksheet_index)
data = ws.get("A1:C1")
for entry in data:
    print(entry.count())
    # This line will fail, as the 3 expected values are not in the data.
    sh_data = SheetData(*entry)
```

**Environment info:**
- Operating System [e.g. Linux, Windows, macOS]: Windows
- Python version: 3.11.5
- gspread version: 4.10

--- 

Note: I did glance at the Gspread source code itself, and it might be a problem on Google's side. Would like developer confirmation on this.

```
       url = SPREADSHEET_VALUES_URL % (self.id, quote(range))
        r = self.client.request("get", url, params=params)
        return r.json()```

**Comment by Zylvian** [comment]
Upon further inspection, the get() call will drop all trailing cells given that they are empty.

Data in: A1:C1
Empty: D1:E1
Fetch range: A1:E1
Actual return: A1:C1
Expected return: A1:E1

However, if a string of trialing empty data cells are interrupted by a populated cell, the get() function will parse the intermediary cells.


Data in: A1:C1 + E1
Empty: D1 + F1:G1
Fetch range: A1:G1
Actual return: A1:E1
Expected return: A1:G1

**Comment by alifeee** [comment]
Hi, thanks for the lovely-formatted issue. Your problem is very clear and readable.

This issue is the same as #947 (correct me if I'm wrong). That issue is a bit messy but a proposed fix was outlined by https://github.com/burnash/gspread/issues/947#issuecomment-1637123784. This is being worked on in #1281. It would be great if you also wanted to help, as it seems useful to you. For me there is a small sticking point as we do not always know the size of the area requested ("A3:C5" is obviously 3x3, but "Sheet1" or "A3:C" are ambiguous in size).

p.s., I was under the impression that using `Worksheet.get` was not reccomended, and we suggest instead that you use `Worksheet.get_values`. @lavigne958 please correct me?

**Comment by Zylvian** [comment]
> Hi, thanks for the lovely-formatted issue. Your problem is very clear and readable.
> 
> This issue is the same as #910 and #947 (correct me if I'm wrong). That latter issue is a bit messy but a proposed fix was outlined by [#947 (comment)](https://github.com/burnash/gspread/issues/947#issuecomment-1637123784). This is being worked on in #1281. It would be great if you also wanted to help, as it seems useful to you. For me there is a small sticking point as we do not always know the size of the area requested ("A3:C5" is obviously 3x3, but "Sheet1" or "A3:C" are ambiguous in size).
> 
> p.s., I was under the impression that using `Worksheet.get` was not recommended, and we suggest instead that you use `Worksheet.get_values`. @lavigne958 please correct me?

Hi! 
Looking at #947, it seems like you guys have indeed already worked on this issue. I do believe the `maintain_shape=True` should be the default as the issue I pointed out is pretty unexpected behavior, but as you also note in the same issue, it would indeed be a breaking change.

When reading through the documentation, I could also not find any concrete examples of `.get_values `being recommended over `.get`, but I might have skimmed over it.

Re: the ambiguous size, I suppose the best way would be to drop the "maintain shape" logic all together if there is no defined range? The alternative would be to recursively fill in earlier rows when a wider one is discovered, but that seems like it could be a O(n^2) scenario lurking.

**Comment by alifeee** [comment]
With regards to `get` vs `get_values`, I think I was mis-remembering [`get_all_values`](https://docs.gspread.org/en/v5.10.0/api/models/worksheet.html#gspread.worksheet.Worksheet.get_all_values), which *is* deprecated.

Thank you for your thoughts. I will write up my thoughts around this issue so we can think of a good fix.

**Comment by alifeee** [comment]
superceded by #1289

**Comment by alifeee** [comment]
> Re: the ambiguous size, I suppose the best way would be to drop the "maintain shape" logic all together if there is no defined range? The alternative would be to recursively fill in earlier rows when a wider one is discovered, but that seems like it could be a O(n^2) scenario lurking.

This is a nice suggestion, but we already do this. If you draw a square around the spreadsheet data (see #1289), the "inner" gaps are always returned. It is the "outer" gaps that are not (by Google's API - thus, no way of knowing the true size of an ambiguous region).
