### ISSUE TITLE
size of range returned by get and get_values can be smaller than the input size

### ISSUE THREAD

**Issue by alifeee** [burnash/gspread#1289]
`Worksheet.get` and `Worksheet.get_values` return a smaller area than asked for if some of it is empty. For example, see this call of `worksheet.get("E7:I11")

![Screenshot of spreadsheet](https://github.com/burnash/gspread/assets/13833017/5adff5f3-5035-4d16-bcaa-dca2da4ac354)

## Replication

```python
import gspread
gc = gspread.service_account(filename="google_credentials.json")
spreadsheet = gc.open_by_key("<spreadsheet_key>")
worksheet = spreadsheet.sheet1

values = worksheet.get("E7:I11")
print(values)
```

### expected output (size 5 x 5)
```bash
[
 ['', '', '', '', ''],
 ['', 'data', 'data', 'data', ''],
 ['', '', 'data', '', ''],
 ['', '', 'data', 'data', ''],
 ['', '', '', '', '']
]
```

### actual output (size 4 x 4)
```bash
[
 ['', '', '', ''],
 ['', 'data', 'data', 'data'],
 ['', '', 'data', ''],
 ['', '', 'data', 'data']
]
```

## Related issues

#910, #947, #1284

## Attempted fixes

#985, #1281

## steps to fix

- [x] add a boolean kwarg to [`Worksheet.get`] and [`Worksheet.get_values`], something like `maintain_size`
- [x] if `maintain_size` is true
  - [x] if the size is knowable (see below)
    - [x] get the size (number of rows/cols) asked for by the user from `range_name` using [`a1_to_rowcol`]
    - [x] use [`utils.fill_gaps`] to fill the empty values and return this
- [x] add test, i.e., `WorksheetTest.test_get_values_and_maintain_size`

[`Worksheet.get_values`]: https://github.com/burnash/gspread/blob/739b8fca7e91d798d71a446e8849f42b950c2840/gspread/worksheet.py#L352
[`Worksheet.get`]: https://github.com/burnash/gspread/blob/817ebb86fd1b98e2eb643eb2e06ffd5bd63544ca/gspread/worksheet.py#L784
[`utils.fill_gaps`]: https://github.com/burnash/gspread/blob/739b8fca7e91d798d71a446e8849f42b950c2840/gspread/utils.py#L538-L573
[`a1_to_rowcol`]: https://github.com/burnash/gspread/blob/817ebb86fd1b98e2eb643eb2e06ffd5bd63544ca/gspread/utils.py#L297

## Problems

There are many ways to define a range with Google Sheets. See the [documentation for a1 notation](https://developers.google.com/sheets/api/guides/concepts#a1_notation). Here is a summary. In green are the ranges we can know the size of. In red the ones we can't.

![Screenshot of Google Sheets documentation](https://github.com/burnash/gspread/assets/13833017/2865ba85-5369-43fb-b03a-672c8e6e5b57)

What we could do is resize the data if the size is knowable (cases 1 and 5 above) and leave it as-is if not (cases 2, 3, 4, 6, 7, 8 above).

## Questions

Should this be the default behaviour?

**Comment by alifeee** [comment]
Thinking about it, if the user does not know the size of the region they request (cases 2,3,4,7,8 above) then they cannot complain when we return the "wrong" size region. This is only not the case for named ranges, which have a defined size when you create them.

**Comment by botcs** [comment]
Can we not query the sheet's size?
Here's a related SO [question](https://stackoverflow.com/questions/67336050/find-sheet-size-using-google-sheets-api)

**Comment by Zylvian** [comment]
> Thinking about it, if the user does not know the size of the region they request (cases 2,3,4,7,8 above) then they cannot complain when we return the "wrong" size region. This is only not the case for named ranges, which have a defined size when you create them.

Re: my comment in #1284 as well as your statement above: should the default behavior not be to maintain the shape, given that the region is specified? As in: 
case 1, 5 -> maintain shape
case 2,3,4,6,7,8 -> return unspecified region

**Comment by alifeee** [comment]
I agree with what is said here.

> Can we not query the sheet's size?

We can, and we do. We store this as properties in the worksheet object.

https://github.com/burnash/gspread/blob/817ebb86fd1b98e2eb643eb2e06ffd5bd63544ca/gspread/worksheet.py#L173-L181

> should the default behavior not be to maintain the shape, given that the region is specified?

I too believe this should be the default.

See this table for the ways (I believe) a user can use `worksheet.get()`. For most of them, we know the expected size, and could pad the result to be this way (as in my above instructions).

| Case | Example | Known size | Can we know row/col count? |
| --- | --- | --- | --- |
| 1 |  Sheet1!A1:B2 | col + row | ✅ |
| 2 | Sheet1!A:A | col | ☑ |
| 3 | Sheet1!1:2 | row | ☑ |
| 4 | Sheet1!A5:A | col | ☑ |
| 5 | A1:B2 | col + row | ✅ |
| 6 | Sheet1 | | ☑ |
| 7 | 'My Custom Sheet'!A:A | col | ☑ |
| 8 | 'My Custom Sheet' | col | ☑ |
| 9 | `named range` | | ❌ |

✅ - columns and rows are explicit in the notation
☑ - columns and rows are not explicit, but can be obtained via [`col_count`] and/or [`row_count`] props
❌ - size of region cannot be obtained

However, it is a known issue that the `col_count` and `row_count` props are not kept up to date very well (#881, #1211, #1201), so using these for this feature (the blue ☑ above) may result in nasty bugs.

For now, I suggest we implement padding with `a1_to_rowcol` and `utils.fill_gaps` for only cases 1 and 5 above. I think this will be enough.

For this, we simply need a regex match which can determine between cases 1 and 5, and the rest, and then to apply the logic stated in the instructions above. We already use regex in a similar way in the module:

https://github.com/burnash/gspread/blob/817ebb86fd1b98e2eb643eb2e06ffd5bd63544ca/gspread/utils.py#L25-L26

I suggest something like `([A-Za-z]+)(\d+):([A-Za-z]+)(\d+)` would work ([see on regex101](https://regex101.com/r/gIe8yh/1)).

[`col_count`]: https://github.com/burnash/gspread/blob/817ebb86fd1b98e2eb643eb2e06ffd5bd63544ca/gspread/worksheet.py#L178-L181
[`row_count`]: https://github.com/burnash/gspread/blob/817ebb86fd1b98e2eb643eb2e06ffd5bd63544ca/gspread/worksheet.py#L173-L176

**Comment by alifeee** [comment]
Technically, the (unexpected) behaviour is in [the documentation for `get_values`](https://docs.gspread.org/en/latest/api/models/worksheet.html#gspread.worksheet.Worksheet.get_values)

![image](https://github.com/burnash/gspread/assets/13833017/281c38e2-b8d6-4cd8-a378-d11e1f75f059)

However, it is still unexpected. I will continue my work.
