### ISSUE TITLE
API error 403 since 5.11.0 [auth without browser]

### ISSUE THREAD

**Issue by DamonDay** [burnash/gspread#1290]
## this is how I auth without browser:
1. generate a token creds locally using browser (_client secret_)
2. hash the token then read it on databricks notebook (sort of Google Colab)<br>
## This method can help me complete Google authentication in a no-browser scenario, because I cannot do browser authentication on the server side
(due to company regulation, I cannot use service account solution.)
## however, since 5.11.0, this way fails (even locally):
`
import gspread
import pickle

secret = dbutils.secrets.getBytes(scope="gar", key="token") # use databricks API get secret token

creds = pickle.loads(secret)

gc = gspread.authorize(creds)

gc.open_by_key("GOOGLE_SHEET_ID")
`

`Traceback (most recent call last):
  File "/opt/miniconda3/envs/py395/lib/python3.9/site-packages/gspread/client.py", line 199, in open_by_key
    spreadsheet = Spreadsheet(self, {"id": key})
  File "/opt/miniconda3/envs/py395/lib/python3.9/site-packages/gspread/spreadsheet.py", line 40, in __init__
    drive_metadata = self.client.get_file_drive_metadata(self._properties["id"])
  File "/opt/miniconda3/envs/py395/lib/python3.9/site-packages/gspread/client.py", line 110, in get_file_drive_metadata
    res = self.request("get", url, params=params)
  File "/opt/miniconda3/envs/py395/lib/python3.9/site-packages/gspread/client.py", line 94, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 403, 'message': 'Request had insufficient authentication scopes.', 'errors': [{'message': 'Insufficient Permission', 'domain': 'global', 'reason': 'insufficientPermissions'}], 'status': 'PERMISSION_DENIED', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'ACCESS_TOKEN_SCOPE_INSUFFICIENT', 'domain': 'googleapis.com', 'metadata': {'service': 'drive.googleapis.com', 'method': 'google.apps.drive.v3.DriveFiles.Get'}}]}`

**Comment by AugustoBarros** [comment]
I also had the same issue, even using a service account.

"Downgrading" the package to 5.10.0 resolved my issue.

**Comment by alifeee** [comment]
Hi both. This is now fixed in the patch v5.11.1. You should be able to update to v5.11.1 and your code should work.

https://github.com/burnash/gspread/releases/tag/v5.11.1

> I also had the same issue, even using a service account.

I think your issue is different, see #1286. Or don't, because it should work now :)
