### ISSUE TITLE
delete_row(idx)

### ISSUE THREAD

**Issue by ac001** [burnash/gspread#13]
Currently its not possible to remove a row apart from resizing and in this case the row needs to be at the end..

I have a situation where I need to delete a row in the "middle"..

Keep up the good work Anton ;-)))

**Comment by msuozzo** [comment]
Bump. `delete_row` should be added.

**Comment by synth3tk** [comment]
Is this ever going to happen?

**Comment by NotLeet** [comment]
I think we need to give him some more time. I mean, it's only been like, four and a half years.

**Comment by burnash** [comment]
@NotLeet you could always help to make it happen faster. The referenced PR misses a test suite and for now I don't have enough time to write it myself. I'm sure that not every gspread user will be happy if I merge all incoming PRs without any prior testing.

This is a non-commercial, open source project. If you use gspread and need something — please contribute to the project.

**Comment by NotLeet** [comment]
Alright, I created a fork and built on amleczko's work. I added the ability to delete by row numbers, delete a list of rows without it failing silently and wrote some more tests.

I've submitted a PR. It's passing all tests and there's no merge conflicts. #390

**Comment by burnash** [comment]
`delete_row()` was added in #337, v0.5.0. I will add code from #161 and #390 in future releases. I'm closing this issue.
