### ISSUE TITLE
Improve test error when cassette is missing or outdated

### ISSUE THREAD

**Issue by alifeee** [burnash/gspread#1304]
Currently, if a test is run and a cassette is:

- missing
- has the wrong requests

The error is quite verbose. For an example, see https://github.com/burnash/gspread/actions/runs/6309082420/job/17133268616

We could attempt some sort of try/catch, and re-raise the error with a slightly more helpful error message. A lot of new contributors (including myself) get confused by this

**Comment by lavigne958** [comment]
I tried to tackle this issue, and I couldn't find a way to improve the error message.
I tried using pytest fixtures etc and it can't work.

If you want to give it a try, please do so, may the 4th be with you :star: hope you'll find some ways to do it.
