### ISSUE TITLE
Set maintain_size to `True` by default

### ISSUE THREAD

**Issue by alifeee** [burnash/gspread#1306]
This behaviour should be default, as discussed in.

#1289

However, this is a breaking change - so should be added at the next major release (6.0.0)

**Comment by alifeee** [comment]
(since `get` is one of the most used methods, this "breaking change" should be carefully considered)

**Comment by alifeee** [comment]
@lavigne958 this is the final issue left in 6.0.0

it requires thought.

For now, I suggest we leave it as `False`, so it works the same way as before, for maximum backwards compatibility,, and close this issue with no change. What do you think?

**Comment by lavigne958** [comment]
Agreed let's leave it like this for now.
