### ISSUE TITLE
Return value of list_spreadsheet_files changed without documentation/changelog

### ISSUE THREAD

**Issue by mephinet** [burnash/gspread#1307]
When @alifeee  improved SpreadsheetNotFound and other exceptions a few weeks ago with #1277, commit c3736d95b516e58199a8158f10b735ca934cbbb2, the signature of `list_spreadsheet_files` changed:

Before, it returned `list[dict]`, now it returns `tuple[list[dict], Response]`, breaking any code that iterates over the return value.

IMHO the return type is missing in the docstring of the method, and the API change needs a prominent mention in the HISTORY.rst

**Code example***
```py
for f in gspread.list_spreadsheet_files():
    print(f["name"])
```

**Environment info:**
- Operating System: Arch Linux
- Python 3.11.5
- gspread 5.11.2

**Stack trace or other output that would be helpful**
> TypeError: list indices must be integers or slices, not str

**Comment by alifeee** [comment]
oops

I think I thought it was an internal method... not sure how that got through.

thanks for the issue. I will revert it soon. I don't see a reason to change it in a breaking way.

**Comment by lavigne958** [comment]
Hi @mephinet sorry for the inconvenience.

We'll make the necessary changes ASAP.

@alifeee how do you want to proceed? Do you want to revert the whole PR and we'll do it again with better care on the return signature or just change the return signature?

If we choose option 2 what's your proposal for the new signature and the new way to return the `Response` object? 

I'll think about it too and propose something here if I have an idea.

**Comment by mephinet** [comment]
No big deal!
In this case, maybe change the existing method to private, and create a wrapper:

```py
def list_spreadsheet_files(...) -> List[Dict[str, Any]]:
    files, _ = self._list_spreadsheet_files(...)
    return files
```

**Comment by lavigne958** [comment]
That would be the easiest way and would give us some time to prepare for the changes.

**Comment by alifeee** [comment]
good plan. I am away at the moment but could change this in a few days.

**Comment by lavigne958** [comment]
Same here unfortunately 😑 I can only do it from the 1st of October

**Comment by mephinet** [comment]
I'll see if I can come up with a pull request...

**Comment by lavigne958** [comment]
Thank you very much, I can review it and post some proposals and suggestions too so we should be able to solve this.

**Comment by alifeee** [comment]
I have found time.

I will fix this at 22:30 BST (in 2hr)

**Comment by mephinet** [comment]
I've tried to fix the issue by making `list_spreadsheet_files` return a list again. For the internal use case of `open`, the tuple version is still available as a private method.
Unittest added.
