### ISSUE TITLE
Get only rows matching a criteria: get_all_values(filtercriteria)

### ISSUE THREAD

**Issue by stevennt** [burnash/gspread#1316]
**Is your feature request related to a problem? Please describe.**
I have a huge sheet that I want to query, but only query the rows where a certain column is not null. 
get_all_values() queries the entire google sheet which is way more than I need.

**Describe the solution you'd like**
Add a filter criteria to get_all_values() so it only return the rows matching that filter criteria.

**Describe alternatives you've considered**
get_all_values() then filter in the code, but that's very inefficient.

Thanks.

**Comment by lavigne958** [comment]
Hi unfortunately this can't be done :cry: 

The Google Spreadsheet API does not allow us to query a cell range only based on the content of the celle.
The only available option is:
- query a range a cells based on the cell coordinates (like `A1:d4` or a named range).

We have no filtering option.

The way we implemented the `Worksheet.filter` method is:
1. get all the data
2. locally filter the data
3. return the filtered data

closing this issue.
