### ISSUE TITLE
new style spreadsheet: formatted numbers aren't autocasted

### ISSUE THREAD

**Issue by brammator** [burnash/gspread#132]
Formatting numbers like '2,000,000.01' in new-style spreadsheets breaks automatic type detection.

| floatValue |
| --- |
| 2,000,000.01 |
| 2,000,000.01 |
| 2,000,000.01 |

```
>>> oldw.cell(5, 8)
<Cell R5C8 '2000000.01'>
>>> oldw.get_all_records()[3]
{'floatValue': 2000000.01}
>>> neww.cell(5, 8)
<Cell R5C8 '2,000,000.01'>
>>> neww.get_all_records()[3]
{'floatValue': '2,000,000.01'}

```

**Comment by brammator** [comment]
gspread.utils.numericise() in spread 3.0.0 doesn't work on it too.

**Comment by lavigne958** [comment]
I confirm this, the gspread lib does not handle number if they contain a comma to separate digits every thousands.

I might have a solution that fix some cases, but not all as GoogleSpreadSheet offer too many types and custom types.
But covering this type could help quiet a few of us.

something like that:
https://github.com/burnash/gspread/blob/810183bd5d4d441e9f4d797114d3f49b80939969/gspread/models.py#L2119
```
def numeric_value(self):
        try:
            return float(self.value.replace(",", "")
        except ValueError:
            return None
```

should do the trick.
