### ISSUE TITLE
Fix release action warnings

### ISSUE THREAD

**Issue by lavigne958** [burnash/gspread#1327]
## Overview

Release action has some warning, we should fix them:

1. From the `Publish to TestPypi` we must update the input name to match the new input name for `repository_url`
```
Input 'repository_url' has been deprecated with message: The inputs have been normalized to use kebab-case. Use `repository-url` instead.
```
2. We should enable trusted publishers in order to publish packages to TestPypi and Pypi without the need of passwords and username. (Don't know if we need it but it's worth checking-out)

**Comment by alifeee** [comment]
fixed by https://github.com/burnash/gspread/commit/f6d1b1b79752503012230f595a4f55ebd231a702?

**Comment by lavigne958** [comment]
partially yes.
Number 1 is, not number 2.

Let's close this one, and remove number 2. We'll have a look later to number 2 which seems way longer to setup
