### ISSUE TITLE
worksheet.set_basic_filter doesn't actually accept documented alternate params

### ISSUE THREAD

**Issue by deekue** [burnash/gspread#1347]
https://github.com/burnash/gspread/blob/67759c7ffe88c0a4650d1eaf8bea20156c7d0e31/gspread/worksheet.py#L2413

from the [docs](https://docs.gspread.org/en/latest/api/models/worksheet.html#gspread.worksheet.Worksheet.set_basic_filter) this should work
`worksheet.set_basic_filter(first_col=4)` 

actually returns `set_basic_filter() got an unexpected keyword argument 'first_col'`

**Comment by lavigne958** [comment]
Hi @deekue thank you for raising this issue, I'm sorry but the documentation is not clear, you can't use the argument `first_row` as a named argument.

This method `Worksheet.set_basic_filter` can be used in 2 different ways:
1. using a range name: `my_sheet.set_basic_filter("A1:F1")` , in python you could use too: `my_sheet.set_basic_filter(name="A1:F1")`
2. using integer for the range coordinates: `my_sheet.set_basic_filter(1, 1, 1, 7)`
Bot above call to `set_basic_filter` will result in the same result.

we should improve documentation with an example usage with integer coordinates I suppose.

**Comment by lavigne958** [comment]
stale issue, closing this issue.
