### ISSUE TITLE
cell color fills?

### ISSUE THREAD

**Issue by Kyle772** [burnash/gspread#135]
I currently have gspread set up to put in values every 15 minutes or so and it sometimes becomes tiresome to look at in detail. Is it possible to make it set positive values to one color and negative values to another? Does Gspread even have a fill cell function?

**Comment by msuozzo** [comment]
Yes. Manually configuring Conditional Formatting is the best way to do this.

**Comment by abdulwahid24** [comment]
not sure why this one is closed as Won't fix. In the v4 of Sheets API the following is available:
1. https://developers.google.com/sheets/api/samples/formatting 
2. https://developers.google.com/sheets/api/samples/conditional-formatting
3. https://developers.google.com/sheets/api/samples/rowcolumn

You can even hide columns, by using a batch request as explained in https://stackoverflow.com/a/42451662/682317

**Comment by wookayin** [comment]
This should be reopened!

**Comment by wookayin** [comment]
For those who might find this, the following library works in a minimal manner:

https://pypi.org/project/gspread-formatting/

**Comment by jiuyuejiu** [comment]
> For those who might find this, the following library can do the job in a minimal manner:
> 
> https://pypi.org/project/gspread-formatting/

@wookayin  Thank you very much, your link helps me a lot.

**Comment by BenHagan** [comment]
It looks like gspread can handle formatting as of version 3.3:

https://gspread.readthedocs.io/en/latest/api.html?highlight=.find#gspread.models.Worksheet.format
