### ISSUE TITLE
Header whitespace regression in 5.12.0

### ISSUE THREAD

**Issue by timmc-edx** [burnash/gspread#1354]
5.12.0 no longer tolerates sheets with filled-in cells that are not under a header. (For example, there might be a summary table off to the side of the main data.)

## Repro data

aaa | bbb |   |  
-- | -- | -- | --
w | x |   |  
y | z |   | other

```
worksheet.get_all_records(expected_headers=['aaa'])
```

## Expected (old) behavior:

In 5.11.3 the output is `[{'aaa': 'w', 'bbb': 'x', '': ''}, {'aaa': 'y', 'bbb': 'z', '': 'other'}]`

## Unexpected (new) behavior:

5.12.0 raises `gspread.exceptions.GSpreadException: the header row in the worksheet contains multiple empty cells`

## Environment info

- Operating System: Ubuntu Linux
- Python version: 3.8
- gspread version: 5.12.0

**Comment by alifeee** [comment]
hi! thanks for the issue :) 

This bug was fixed by https://github.com/burnash/gspread/pull/1353 after issue https://github.com/burnash/gspread/issues/1352 was filed.

This fix will be released in 5.12.1, which will release in the next month.

**Comment by timmc-edx** [comment]
Oh, thanks! Somehow I missed that in my issue search.

**Comment by timmc-edx** [comment]
Hmm... I think this is actually a different issue. I can still repro it with current master (093235844b00267).

**Comment by alifeee** [comment]
yep

> Though we should keep in mind that in this particular scenario column C and D have empty headers so would collide in the check and will fail but in this case that is the wanted behavior. to prevent key/value overriding when building the dict.

Here, `expected_headers` is provided as `[]`, showing that the user wants to ignore duplicate headers.
