### ISSUE TITLE
make 5.12.2 release

### ISSUE THREAD

**Issue by alifeee** [burnash/gspread#1358]
### Changes

* Many fixes for `get_records` by @alifeee in https://github.com/burnash/gspread/pull/1357

**Comment by lavigne958** [comment]
You take this one ? I take #1359 ?

Should we wait may be after 5.12.2 so users get the update etc we make sure we don't have regressions and then we release 6.0.0 , something like 2 weeks should cover us from any major issue I suppose?

**Comment by alifeee** [comment]
> You take this one ? I take https://github.com/burnash/gspread/issues/1359 ?

Sure, sounds good :) will do #1359 as soon as #1362 is merged 👍

> Should we wait may be after 5.12.2 so users get the update etc we make sure we don't have regressions and then we release 6.0.0 , something like 2 weeks should cover us from any major issue I suppose?

I think it doesn't matter because if there is an issue with 5.12.2, it will be an issue with the new `get_records` code, and

- `get_records` is not a common method (I have no evidence for this other than there were not many issues about it being quite broken)
- if we need to make a patch (e.g., 5.12.3) we can just make a branch based off of the 5.12.2 branch, and merge the fix into v6 (via master)

So we do not have to wait to make the 6.0.0 release

**Comment by alifeee** [comment]
@lavigne958 I think we should do the 6.0.0 release either in the next week or after Christmas, so we have time either way to fix issues. We should have a video call about 6.0.0 :)

**Comment by lavigne958** [comment]
agreed, I'll contact you to arrange the call, next week should be good.

**Comment by alifeee** [comment]
done https://github.com/burnash/gspread/releases/tag/v5.12.2
