### ISSUE TITLE
Document creation of a Pandas DataFrame from gspread

### ISSUE THREAD

**Issue by sudar** [burnash/gspread#138]
Would be a nice feature to have.

**Comment by jimrockey** [comment]
That would be an awesome feature.

**Comment by msuozzo** [comment]
So it appears this is a very easy operation every without a dedicated call. I don't think it warrants a change to the code but it might be useful to add this to the documentation in case anyone else has this use-case.

**Comment by lavigne958** [comment]
Gspread -> Pandans is covered in the documentation: [Examples](https://docs.gspread.org/en/latest/user-guide.html#using-gspread-with-pandas)
Pandas -> Gspread is not intended to be covered here but it is using the following libraries: [gspread-pandas](https://github.com/aiguofer/gspread-pandas) && [gspread-dataframe](https://github.com/robin900/gspread-dataframe)

Closing this issue.
