### ISSUE TITLE
Client has no attribute set_timeout

### ISSUE THREAD

**Issue by Natim** [burnash/gspread#1393]
**Describe the bug**
Using gspread 6.0.0 I have a `'Client' object has no attribute 'set_timeout'` error.

**To Reproduce**
```
        import gspread
        gspread_service = gspread.service_account(GSHEET_SERVICE_ACCOUNT_PATH)
        gspread_service.set_timeout(120)
```

**Expected behavior**
Update the timeout

**Screenshots**
![image](https://github.com/burnash/gspread/assets/229453/bdab3254-6689-4c5a-ab86-898b747a5b72)

**Environment info:**
- Operating System **Linux**
- Python version **3.11**
- gspread version **6.0.0**

**Comment by Natim** [comment]
```
In [4]: gspread_service.set_timeout(300)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 gspread_service.set_timeout(300)

AttributeError: 'Client' object has no attribute 'set_timeout'

In [5]: gspread_service
Out[5]: <gspread.client.Client at 0x7fe652783290>
```

**Comment by Natim** [comment]
```

In [6]: dir(gspread_service)
Out[6]: 
['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_list_spreadsheet_files',
 'copy',
 'create',
 'del_spreadsheet',
 'export',
 'get_file_drive_metadata',
 'http_client',
 'import_csv',
 'insert_permission',
 'list_permissions',
 'list_spreadsheet_files',
 'open',
 'open_by_key',
 'open_by_url',
 'openall',
 'remove_permission']
```

**Comment by Natim** [comment]
I believe we should use `gspread_service.http_client` now

**Comment by Natim** [comment]
https://docs.gspread.org/en/v6.0.0/api/http_client.html

**Comment by lrhazi** [comment]
So how does one go from 
```
        import gspread
        gspread_service = gspread.service_account(GSHEET_SERVICE_ACCOUNT_PATH)
        gspread_service.set_timeout(120)
```
to using [http_client.html](https://docs.gspread.org/en/v6.0.0/api/http_client.html) ? 

and that document says this is not meant for the users to use!

**Comment by lavigne958** [comment]
True that! I will update the gspread client. So you can keep the same code and keep it working.

**Comment by Natim** [comment]
> So how does one go from
> 
> ```
>         import gspread
>         gspread_service = gspread.service_account(GSHEET_SERVICE_ACCOUNT_PATH)
>         gspread_service.set_timeout(120)
> ```
> 
> to using [http_client.html](https://docs.gspread.org/en/v6.0.0/api/http_client.html) ?
> 
> and that document says this is not meant for the users to use!

I personally did it like that:

```
import gspread
gspread_service = gspread.service_account(GSHEET_SERVICE_ACCOUNT_PATH)
gspread_service.http_client.set_timeout(120)
```
