### ISSUE TITLE
AttributeError: 'module' object has no attribute 'authorize'

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [burnash/gspread#140]
I'm somewhat new to Python. How do I pass an Oauth2 access code to gspread.authorize as a simple string?

The json object already obtained has this (access_token is fictitious for the purpose of this example):

<pre>
{
  "access_token" : "ya99.QADpw1lSDiI-SyCCCCDL452_-n_tTlnxxQU3RpdLVJbEN2EYw-6deE768wAapA",
  "token_type" : "Bearer",
  "expires_in" : 3600
}
</pre>

I decode the raw json with:

<pre>
import json
decoded_data = json.loads(raw_json)
at = decoded_data['access_token']
print at
</pre>

The 'print at' gives what I would expect: 

<code>ya99.QADpw1lSDiI-SyCCCCDL452_-n_tTlnxxQU3RpdLVJbEN2EYw-6deE768wAapA</code>

And then I try: 

<pre>
import gspread
gc = gspread.authorize(at)
sh = gc.open("TestWorksheet")
worksheet_list = sh.worksheets()
print worksheet_list
</pre>

But I don't get past gspread.authorize():

<pre>
Traceback (most recent call last):
  File "gspread-test", line 35, in <module>
    gc = gspread.authorize(at)
AttributeError: 'module' object has no attribute 'authorize'
</pre>

**Comment by jdorfman** [comment]
@burnash I have been getting the same error no matter what I do or upgrade.  My current env:

* `Darwin Kernel Version 14.5.0 (OS X Yosemite 10.10.5)`
* `Python 2.7.10`
* `gspread==0.2.5`, `pyOpenSSL==0.15.1`, `oauth2client==1.4.12`, `pycrypto==2.6.1`

Error (using demo code you have on [RTD](http://gspread.readthedocs.org/en/latest/oauth2.html)):
```
gc = gspread.authorize(credentials)
AttributeError: 'module' object has no attribute 'authorize'
```
Thank you in advance.

**Comment by burnash** [comment]
@jdorfman Can you share a detailed error traceback?

**Comment by jdorfman** [comment]
Hey @burnash sure thing:

```bash
$ python gspread.py
Traceback (most recent call last):
  File "gspread.py", line 2, in <module>
    import gspread
  File "/Users/jdorfman/data/tests/gspread.py", line 10, in <module>
    gc = gspread.authorize(credentials)
AttributeError: 'module' object has no attribute 'authorize'
```

**Comment by burnash** [comment]
@jdorfman Try to use a different name for your script (not gspread.py), I guess it tries to import itself.

**Comment by jdorfman** [comment]
@burnash holy shit.  Mystery solved.  Thanks!

**Comment by ryantuck** [comment]
if you make the mistake of making a file entitled `gspread.py` and fix it, remember to `rm gspread.pyc` as well, or else your script will continue to attempt to import the `gspread` from whatever directory you're in.

**Comment by malinplpl** [comment]
Guys, I need hell, I try run this script for raspery:
https://raw.githubusercontent.com/adafruit/Adafruit_Python_DHT/master/examples/google_spreadsheet.py
and a get error:
('Google sheet login failed with error:', AttributeError("'module' object has no attribute 'authorize'",))

I download Json file for auth google ;/

**Comment by akalshiro12** [comment]
E:\bot-apiV1>python gspread2.py
Traceback (most recent call last):
  File "gspread2.py", line 1, in <module>
    import gspread
  File "E:\bot-apiV1\gspread.py", line 20, in <module>
    readMyGsheet()
  File "E:\bot-apiV1\gspread.py", line 8, in readMyGsheet
    client = gspread.authorize(kredensial)
AttributeError: partially initialized module 'gspread' has no attribute 'authorize' (most likely due to a circular import)


i've tried change script name and checked the credential on json too but i don't get past gspread.authorize()
