### ISSUE TITLE
py.typed is not included

### ISSUE THREAD

**Issue by musou1500** [burnash/gspread#1401]
**Describe the bug**
mypy reports following error when import gspread v6.0.0.
> Skipping analyzing "gspread": module is installed, but missing library stubs or py.typed markerMypy [import-untyped](https://mypy.readthedocs.io/en/latest/_refs.html#code-import-untyped)

The cause of this seems to be py.typed marker is not included.

[PEP561](https://peps.python.org/pep-0561/#packaging-type-information) says that
> Package maintainers who wish to support type checking of their code MUST add a marker file named py.typed to their package supporting typing.

**Comment by lavigne958** [comment]
Hi thank you for this issue.

Well take a look at the specs.

This fix might **not** be included in the next patch release but the one after that, so  6.0.2
