### ISSUE TITLE
AttributeError: 'Spreadsheet' object has no attribute 'del_worksheet'

### ISSUE THREAD

**Issue by ghost** [burnash/gspread#141]
I cannot delete worksheets. I'm fairly new to python and tried a few things but here is some same code test1.py:

```
#!/usr/bin/python3
import gspread

#Google account details 
email = ' '
password = ' '
filename = 'TEST'

gc = gspread.login(email, password)
spreadsheet = gc.open(filename)
worksheet = spreadsheet.add_worksheet(title = "TestWorksheet", rows = 100, cols = 2)
spreadsheet.del_worksheet(worksheet)
```

and this is the error:

```
python test1.py
Traceback (most recent call last):
  File "test1.py", line 12, in <module>
    spreadsheet.del_worksheet(worksheet)
AttributeError: 'Spreadsheet' object has no attribute 'del_worksheet'
```

The code successfully creates worksheet "TestWorksheet" and there are 2 worksheets in total. The code is pretty much similar to https://github.com/burnash/gspread/issues/69#issuecomment-25860701 where it was confirmed working. Running script on Raspbian.

**Comment by msuozzo** [comment]
Hello ghost,
Have you been able to resolve this issue? This seems like it may be a Python 3 issue. Unfortunately, the code snippet no longer works because google has disabled username-password authentication. See the [doc page](http://gspread.readthedocs.org/en/latest/oauth2.html) for a guide to implement OAuth2 authentication.

**Comment by john1jan** [comment]
I am using Oauth2 authentication. as per the the sam `[doc](http://gspread.readthedocs.io/en/latest/oauth2.html).` I am able to read the work sheet. But cannot create a new work sheet
i am using this code
```
import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds']

credentials = ServiceAccountCredentials.from_json_keyfile_name('aadsddas.json', scope)
gc = gspread.authorize(credentials)
sh = gc.open("MyTest").sheet1
list_of_lists = sh.get_all_values()
worksheet = sh.add_worksheet(title="A worksheet", rows="100", cols="20")
print list_of_lists
```


This throws me this error 

````
Traceback (most recent call last):
    worksheet = sh.add_worksheet(title="A worksheet", rows="100", cols="20")
AttributeError: 'Worksheet' object has no attribute 'add_worksheet'

```

**Comment by burnash** [comment]
@john1jan `sh` in your case is a worksheet, not a spreadsheet. (see in `sh = gc.open("MyTest").sheet1`, sheet1 returns the first worksheet). So you have a legitimate error when trying to call a non-existing method.
