### ISSUE TITLE
Reorder gspread client init arguments

### ISSUE THREAD

**Issue by lavigne958** [burnash/gspread#1411]
## Overview
Re-order gspread client `init()` argument in order to be backward compatible.

it was before:
`def __init__(self, auth, session=None)`

it now:
`def __init__(self, auth, httpClientType=HTTPClient, Session=None)`

it should be:
`def __init__(self, auth, session=None, httpClientType=HTTPClient)`

This will allow anyone using the previous version of gspread to keep using it.

see: https://github.com/aiguofer/gspread-pandas/issues/100

**Comment by alifeee** [comment]
the other note is, I only stumbled across the gspread-pandas issue by chance. We were not aware of it via issues in this repository.

In this way, we could do some searches for gspread issues that might not have been reported in this repo, but elsewhere?
