### ISSUE TITLE
A way to add DataValidation

### ISSUE THREAD

**Issue by muddi900** [burnash/gspread#1420]
**Is your feature request related to a problem? Please describe.**
The API allows to setup data validation on a range via the `batchUpdate` end point: https://developers.google.com/sheets/api/samples/data#data-validation

**Describe the solution you'd like**
Since it is part of the `batchUpdate` endpoint, anyone can use the low-level method to pass through the data. However, there should be a high-level method. or a kwarg in the low-level [`values_update`](https://github.com/burnash/gspread/blob/4a48fbdc4bc56724d3a1d8fcdb7f5793fb58f160/gspread/http_client.py#L138) method.  We should create a class `DataValidation` class, which will have all the options provided by the API.

It would have `to_json` method, that will be passed to the update payload when sending the request.

**Describe alternatives you've considered**
Passing a `kwarg` to the update methods to pass through json data.

**Comment by alifeee** [comment]
Hi. This is a nice idea.

I think it is quite large in scope. I do not have time to implement such a large feature. If you wanted to, I could help you think about it.

For now, I suggest using [`Spreadsheet.batch_update`](https://github.com/burnash/gspread/blob/cb1a63e563164546189472944927830f1bb01c4e/gspread/spreadsheet.py#L88-L97), and building the request yourself with help from [Google's docs](https://developers.google.com/sheets/api/samples/data#data-validation). For example, using the example from that page, this works for me:

```python
import gspread

gc = gspread.service_account(filename="google_credentials.json")
sh = gc.open("gspread test spreadsheet")

sh.batch_update(
    {
        "requests": [
            {
                "setDataValidation": {
                    "range": {
                        "sheetId": sh.sheet1.id,
                        "startRowIndex": 0,
                        "endRowIndex": 10,
                        "startColumnIndex": 0,
                        "endColumnIndex": 4,
                    },
                    "rule": {
                        "condition": {
                            "type": "NUMBER_GREATER",
                            "values": [{"userEnteredValue": "5"}],
                        },
                        "inputMessage": "Value must be > 5",
                        "strict": True,
                    },
                }
            }
        ]
    }
)
```

**Comment by muddi900** [comment]
I can implement it myself.

**Comment by alifeee** [comment]
> I can implement it myself.

Radical, do let me know if you need any help. See the [contributing guide](https://github.com/burnash/gspread/blob/master/.github/CONTRIBUTING.md) if you are interested. :)

**Comment by muddi900** [comment]
I have contributed before, but those were minor. So thank you for the offer. I will sure to ask for it.

**Comment by muddi900** [comment]
So i have started work on this. What are specs for the docstrings?

**Comment by alifeee** [comment]
docstrings use Sphinx. See a guide here

<https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html>
