### ISSUE TITLE
Missing py.typed marker

### ISSUE THREAD

**Issue by broken-wheel** [burnash/gspread#1421]
First of all, thank you for adding type information to `gspread`.

The package is missing `py.typed` marker. Because of this, _mypy_ skips type checking for the library (https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker). I verified manually that adding `py.typed` file to the package does fix the issue.

This will not show up during type checking of the repo itself (i.e., `tox -e lint`), but only when a downstream user uses the library.

**Comment by lavigne958** [comment]
Hi thank you for this, I will work on this and add the missing marker file.

Duplicates #1401 
closing issue
