### ISSUE TITLE
lint failure

### ISSUE THREAD

**Issue by alifeee** [burnash/gspread#1478]
The linting is failing now

<https://github.com/burnash/gspread/actions>

What has changed? I am not sure.

Here is a working workflow <https://github.com/burnash/gspread/actions/runs/9259695428/job/25472114091>

[working.txt](https://github.com/user-attachments/files/15746025/working.txt)

Here is a broken one <https://github.com/burnash/gspread/actions/runs/9259695827/job/25472115123>

[workingnot.txt](https://github.com/user-attachments/files/15746026/workingnot.txt)

I don't see a big difference in the lint step

![image](https://github.com/burnash/gspread/assets/13833017/f15e8d8a-3fb6-439c-91de-ecbcf2b99364)

This requires more investigating.

**Comment by lavigne958** [comment]
I checked, 

On this workflow:
https://github.com/burnash/gspread/actions/runs/9259695827/job/25472115123

We use a more recent version of codespell which triggers on new errors. At least it triggers some errors on false positive checks. It triggers on code or it should only trigger in pure text. 

So this is why I closed the associated PR.

My concern is on this issue:

https://github.com/burnash/gspread/actions/runs/9332077295/job/25687472543

But I'll open a PR today to skip this check. Any check or safety on pip we don't care so much.
