### ISSUE TITLE
HTTP 413 Error when update_cells request too large

### ISSUE THREAD

**Issue by jason79** [burnash/gspread#148]
Has anybody tried updating more than 50k cells at once? 

http://stackoverflow.com/questions/24196879/gspread-update-cells-in-batch-50k-limit

**Comment by msuozzo** [comment]
I tested this and it looks like an inherent limit of Google's API. I get a 413 Request Entity Too Large.

We might consider looking into segmenting an update like this into multiple queries to skirt this limitation.

**Comment by burnash** [comment]
gspread has been ported to a newer Sheets API v4. I believe upgrading to the latest version should solve this issue. Could you please try with the newer version?
It [has been reported](https://github.com/burnash/gspread/issues/384#issuecomment-375841751) that the problem goes away.

I'm closing this issue for now. Feel free to reopen if you have any questions.
