### ISSUE TITLE
How to get to end of the worksheet for a very big document?

### ISSUE THREAD

**Issue by seemantadutta** [burnash/gspread#153]
First of all, many thanks for writing this awesome library! It has made life so simple for me.

However, at this point I have an issue that I am not sure how to resolve.
I have a document that is being updated every minute and therefore it is a quite big document. In order to append a new row every time an update happens, I am using the following code:

       all = worksheet.get_all_values()
       end_row = len(all) + 1

Here, end_row indicates the row# where I can add my data. 

This code works, but the problem with this code is that when the sheet is big, get_all_values() takes a long time to run. The delay starts to add up pretty soon.

So my question is: is there a less time consuming way to get to the end of the document? 

P.S. I tried using the row_count property, but that returns 1000 which is of no use because I want to get to the end where I can insert a new row, not the end of the document necessarily.

**Comment by msuozzo** [comment]
Google spreadsheets initializes all worksheets to have 1000 rows. If you want to change this, after creating a new worksheet, call `Spreadsheet.resize` to set the number of rows you want the sheet to have.

**Comment by WolfClaw009** [comment]
Hello @seemantadutta 
I know I am very late. I have recently started coding in Python and saw this question. The solution to this is 
print(len(worksheet.get_all_values()))
This will give you the length of the list which will be equal to the number of rows in your spreadsheet.

**Comment by Adesh3832** [comment]
Create that new row in other worksheet, Which take no time and keep doing it for few entries and after that insert that worksheet data into your final sheet, like a batch process.

This will help to save time as code doesn't have to initialize all the data.

**Comment by mohamad-islam** [comment]
> Hello @seemantadutta
> I know I am very late. I have recently started coding in Python and saw this question. The solution to this is
> print(len(worksheet.get_all_values()))
> This will give you the length of the list which will be equal to the number of rows in your spreadsheet.

thanks man that helped me

**Comment by anhquanhua189** [comment]
> Hello @seemantadutta
> I know I am very late. I have recently started coding in Python and saw this question. The solution to this is
> print(len(worksheet.get_all_values()))
> This will give you the length of the list which will be equal to the number of rows in your spreadsheet.

Hi WolfClaw,

The problem with this is the fact that you still have to call for get_all_values().

OP was wandering for a method (so was I) to address the last row in the spreadsheet since he was dealing with a large amount of data and it was taking a while for get_all_values() to be called.

Your proposed solution did not address his problem correctly.

**Comment by JoeCharlieH** [comment]
> Create that new row in other worksheet, Which take no time and keep doing it for few entries and after that insert that worksheet data into your final sheet, like a batch process.
> 
> This will help to save time as code doesn't have to initialize all the data.

Exactly, you can count non-blank cells within a full column with the Google Sheets core functions:

`=COUNTA(A1:A)`

 This is a simple example that counts non-blank cells, but it also counts empty strings "" .
