### ISSUE TITLE
v 0.2.1 append_row function succeeds or fails based on time interval between repeated calls

### ISSUE THREAD

**Issue by e024576** [burnash/gspread#157]
I'm using gspread api to log sensor data by repeatedly appending rows to google spreadsheet.  Everything works fine if the interval between appending rows is 60 seconds, but if the interval is 300 seconds - it fails every time.  I don't know the exact interval between success and failure.  

Per Adafruit, I created an 'old style' spreadsheet.  https://g.co/oldsheets

The problem occurs with Raspberry Pi model B 512MB running Raspbian connected via wifi or even when connected with ethernet cable directly to my router.  I just did apt-get update upgrade - no effect.

The traceback report is given below, and python 2.7 program code below that.  The last program line controls the interval.

Please help, this problem is way beyond my abilities to solve.

Thanks
Paul

pi@raspberrypi ~ $ sudo python daniel.py
Traceback (most recent call last):
  File "daniel.py", line 51, in <module>
    worksheet.append_row(values) #write to the spreadsheet
  File "/usr/local/lib/python2.7/dist-packages/gspread-0.2.1-py2.7.egg/gspread/models.py", line 513, in append_row
    self.add_rows(1)
  File "/usr/local/lib/python2.7/dist-packages/gspread-0.2.1-py2.7.egg/gspread/models.py", line 498, in add_rows
    self.resize(rows=self.row_count + rows)
  File "/usr/local/lib/python2.7/dist-packages/gspread-0.2.1-py2.7.egg/gspread/models.py", line 479, in resize
    feed = self.client.get_feed(self_uri)
  File "/usr/local/lib/python2.7/dist-packages/gspread-0.2.1-py2.7.egg/gspread/client.py", line 248, in get_feed
    r = self.session.get(url)
  File "/usr/local/lib/python2.7/dist-packages/gspread-0.2.1-py2.7.egg/gspread/httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gspread-0.2.1-py2.7.egg/gspread/httpsession.py", line 72, in request
    response = self.connections[uri.scheme+uri.netloc].getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

python code:

#!/usr/bin/python2.7
 
import os, glob, time, gspread, sys, datetime
 
#Google account details
email = 'foo.bar@gmail.com'
password = 'Foo_Bars_Password'
spreadsheet = 'Temperature_log' #the name of the spreadsheet already created
 
#attempt to log in to your google account
try:
    gc = gspread.login(email,password)
except:
    print('fail')
    sys.exit()
 
#open the spreadsheet
worksheet = gc.open(spreadsheet).sheet1
 
#initiate the temperature sensor
os.system('modprobe w1-gpio')
os.system('modprobe w1-therm')
 
#set up the location of the sensor in the system
device_folder = glob.glob('/sys/bus/w1/devices/28*')
device_file = [device_folder[0] + '/w1_slave', device_folder[1] + '/w1_slave']
 
 
def read_temp_raw(): #a function that grabs the raw temperature data from the sensor
    f_1 = open(device_file[0], 'r')
    lines_1 = f_1.readlines()
    f_1.close()
    f_2 = open(device_file[1], 'r')
    lines_2 = f_2.readlines()
    f_2.close()
    return lines_1 + lines_2
 
 
def read_temp(): #a function that checks that the connection was good and strips out the temperature
    lines = read_temp_raw()
    while lines[0].strip()[-3:] != 'YES' or lines[2].strip()[-3:] != 'YES':
        time.sleep(0.2)
        lines = read_temp_raw()
    equals_pos = lines[1].find('t='), lines[3].find('t=')
    temp = float(lines[1][equals_pos[0]+2:])/1000, float(lines[3][equals_pos[1]+2:])/1000
    return temp
 
while True: #infinite loop
    temp = read_temp() #get the temp
    values = [datetime.datetime.now(), temp[0], temp[1]]
    worksheet.append_row(values) #write to the spreadsheet
    time.sleep(300) #wait 5  minutes

**Comment by ankostis** [comment]
Wouldn't it make sense to catch internally that the session has expired and issue a more specific exception?

(thanks for this lib by the way)

**Comment by msuozzo** [comment]
Yes this will be handled internally. Implementation progress will be tracked in #302.
