### ISSUE TITLE
question on oAuth2

### ISSUE THREAD

**Issue by jason79** [burnash/gspread#162]
Hello all,

I'm current using a Two step verification on my Google account so I have created app specific password.  I have been using this line of code to gain access 

gc = gspread.login('thedude@abid.es', 'password')

Does the above line use oAuth1? Since oAuth1 is deprecated, must I switch over to oAuth2 at some point? or will the above code always work. 

I don't understand how authentication works behind the scene.

**Comment by msuozzo** [comment]
I'm assuming this is either resolved or stale due to its age. If I'm incorrect, please feel free to reopen the issue.
