### ISSUE TITLE
non-ascii characters fail on worksheet.append_row()

### ISSUE THREAD

**Issue by bwest87** [burnash/gspread#166]
If you send any non-ascii characters to the "append_row" function, the method fails with a UnicodeDecodeError. 

This is because append_row calls python's "unicode" function, and the default encoding for that is ascii. 

This can be replicated by doing the following.

1.login
2. pull any worksheet
3. do worksheet.append_row(é)

I suggest either...
1. letting append_row take a 'encoding' parameter that could be passed to the unicode call
2. Just defaulting the unicode call to use 'utf-8'. 

If there are issues with the suggested approach, let me know. Otherwise, I could do a PR for it.

**Comment by msuozzo** [comment]
I believe this issue is fixed (possibly with 90d62248675aadc4c9546c7e87f28197f071345c) as it appears to work properly in my testing.

If you still run into this problem, feel free to reopen this.
