### ISSUE TITLE
Writing UTF-8 encoded values

### ISSUE THREAD

**Issue by ghost** [burnash/gspread#17]
I have problems with writing UTF-8 encoded non-Ascii values to spreadsheets.
Browsing through the code l of update_cell lead me to:

self.client.put_feed(uri, ElementTree.tostring(feed))   and I saw that

xml.etree.ElementTree.tostring(element, encoding="us-ascii", method="xml")
Generates a string representation of an XML element, including all subelements. element is an Element instance. encoding [1] is the output encoding (default is US-ASCII). method is either "xml", "html" or "text" (default is "xml"). Returns an encoded string containing the XML data.

So an option would be to allow encoding='utf-8' for those who need it. Or I got it wrong and the problem is somewhere else.

**Comment by pita2k** [comment]
same here...
gspread 0.2.5
python 2.7

worksheet.update_cell(1,1, u'Артур')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 29-33: ordinal not in range(128)
