### ISSUE TITLE
HTTP errors - intermittent

### ISSUE THREAD

**Issue by deltaGPhys** [burnash/gspread#170]
I'm getting intermittent HTTP errors when reading or (more frequently) writing to sheets. I moved to Gspread from GoogleCL, and I've been happy with ease and speed, but now I'm getting more of these errors. It works most of the time, but not consistently. Thanks in advance!

My code for writing is (essentially) here:

    def SaveHistory(History, reassesslist, todaydict, date,did):
        username = '...'
        password = '...'
        sheetname = "Re"

        client = gspread.login(username, password)
        spreadsheet = client.open(sheetname)
    
        worksheet = spreadsheet.sheet1
        worksheet.resize(rows=1,cols=12)

        for row in reassesslist:
            worksheet.append_row(temp)    

The error (or at least the most recent one that I've gotten):
Exception in Tkinter callback
Traceback (most recent call last):
   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gspread/client.py", line 137, in open
    feed = self.get_spreadsheets_feed()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gspread/client.py", line 223, in get_spreadsheets_feed
    r = self.session.get(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gspread/httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gspread/httpsession.py", line 75, in request
    raise HTTPError(response)
HTTPError

**Comment by gregroberts** [comment]
I've encountered this issue as well.
I'm running:
     Python 2.7.5 | Anaconda 1.6.2 (32-bit) | (default, Jul  1 2013, 12:41:55) [MSC v.1500 32 bit (Intel)] on win32

On Windows 7 Professional.

The script I'm running opens a connection using:
    client = gspread.login('email','pw')

The script basically just iterates through a column, reading the cell values via 
    sheet.acell('A1').value 
and writing using 
    sheet.update_acell('A1', 'value')


I know this isn't really a solid answer but I've found:
If I run the script whilst being logged into the same Google account in a browser and/or viewing the sheet the script is interacting with, I will sometimes receive this error, sometimes the script will hang on the cell write line, definitely one of these two will happen at some point.

If I log out of my Google account in the browser, I do not encounter either of these errors.

**Comment by raj2569** [comment]
Same issue for me.

My code was working fine and then suddenly stopped working. 
```
    gc = gspread.authorize(auth)                                                
    try:                                                                        
        wks = gc.open_by_key(cf['doc_id']).sheet1                               
    except:                                                                     
        logger.exception("Failed to open connection to google")                 
        sys.exit()                                                              
```
```
2015-04-02 19:19:56,633 __main__ ERROR Failed to open connection to google
Traceback (most recent call last):
  File "calc-contrib.py", line 59, in <module>
    wks = gc.open_by_key(cf['doc_id']).sheet1
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 156, in open_by_key
    feed = self.get_spreadsheets_feed()
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 220, in get_spreadsheets_feed
    r = self.session.get(url)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 75, in request
    raise HTTPError(response)
```
Python: 2.7.3
gspread:  0.2.3 (latest)

The worse part is that there is no clue as to what type of HTTPError I am getting. If there is a means to see the actual error message from Google that would give a clue as to what is wrong.

**Comment by burnash** [comment]
Is it always failing right now?

**Comment by raj2569** [comment]
Yes.

**Comment by burnash** [comment]
Can you try to open a spreadsheet by its name?

**Comment by raj2569** [comment]
Did try that too... Same result:

```2015-04-02 20:18:28,255 __main__ ERROR Failed to open connection to google
Traceback (most recent call last):
  File "calc-contrib.py", line 60, in <module>
    wks = gc.open('2020 Contributions').sheet1
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 134, in open
    feed = self.get_spreadsheets_feed()
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 220, in get_spreadsheets_feed
    r = self.session.get(url)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 75, in request
    raise HTTPError(response)
HTTPError
```

**Comment by burnash** [comment]
Can you try to run your script with debugger?

    $ python -m pdb <your_script.py>

Enter `cont` when the program starts and when it fails inspect the response.

**Comment by raj2569** [comment]
Here is the error message returned from server. Let me know if you need any other info.

```
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/local/lib/python2.7/dist-packages/gspread/httpsession.py(75)request()
-> raise HTTPError(response)
(Pdb) print response
<httplib.HTTPResponse instance at 0x1bf4e18>
(Pdb) !response.status
401
(Pdb) !response.reason
'Token invalid - Invalid token: Token not found'
```

**Comment by burnash** [comment]
Great! Thank you!

**Comment by raj2569** [comment]
Any progress on this....

**Comment by burnash** [comment]
Can't reproduce it. Could you elaborate on how you've obtained the `auth` in your code sample?

**Comment by raj2569** [comment]
The full code is:

```
import gspread                                                                  
                                                                                
token = "the access token from google"                                                                  
                                                                                
class Credentials (object):                                                     
    def __init__ (self, access_token=None):                                     
        self.access_token = access_token                                        
    def refresh (self, http):                                                   
        pass                                                                    
                                                                                
                                                                                
if __name__ == '__main__':                                                      
    auth = Credentials(token)                                                   
    gc = gspread.authorize(auth)                                                
    #wks = gc.open_by_key('doc_id from url').sheet1                                  
    wks = gc.open('sheet name').sheet1                                  

```

**Comment by burnash** [comment]
Good, thanks. And how did you get your `token`?

**Comment by raj2569** [comment]
From Google Developer Console. I created a test project and got the Auth credentials from it. I basically followed this howto:

https://github.com/burnash/gspread/wiki/How-to-get-OAuth-access-token-in-console%3F

**Comment by burnash** [comment]
It could be outdated. I need to check. 

Presently I'm using a different approach for oAuth: http://gspread.readthedocs.org/en/latest/oauth2.html
This guide is incomplete. I'll try to extend it when I get time.

**Comment by raj2569** [comment]
Since I am editing my own spread sheet, I will try this method, just wanted to know what is `SIGNED_KEY` in this? 

```
credentials = SignedJwtAssertionCredentials('developer@example.com', SIGNED_KEY, scope)
```

I have `Client ID`, `Client secret` and `Redirect URIs` in the Credentials page of my test project.

**Comment by burnash** [comment]
Yeah, this part of the ref needs more details.

You need to go to [Google Developers Console](https://console.developers.google.com/project). Create a new project (or select the one you have.)

![credentials-page](https://cloud.githubusercontent.com/assets/264674/7033101/5d335e4a-dd80-11e4-96c0-fce81919ec2d.png)

Under "API & auth", in the API enable "Drive API". 

![enabled-apis](https://cloud.githubusercontent.com/assets/264674/7033107/72b75938-dd80-11e4-9a9f-54fb10820976.png)

Go to "Credentials" and hit "Create new Client ID".

![Create Client ID](https://cloud.githubusercontent.com/assets/264674/7032990/6dfaceb2-dd7f-11e4-8071-1490a5b19c8e.png)

Select "Service account". Hitting "Create Client ID" will generate a new Public/Private key pair. You will automatically download a JSON file with this data.

![download-credentials](https://cloud.githubusercontent.com/assets/264674/7033081/3810ddae-dd80-11e4-8945-34b4ba12f9fa.png)

This is how this file looks like:

```json
{
  "private_key_id": "2cd … ba4",
  "private_key": "-----BEGIN PRIVATE KEY-----\nNrDyLw … jINQh/9\n-----END PRIVATE KEY-----\n",
  "client_email": "473 … hd@developer.gserviceaccount.com",
  "client_id": "473 … hd.apps.googleusercontent.com",
  "type": "service_account"
}
```

You need `client_email` and `private_key` (yes, that's a `SIGNED_KEY`)

Now you can read this file, and use the data when constructing your credentials:

```python
import json
import gspread
from oauth2client.client import SignedJwtAssertionCredentials

json_key = json.load(open('gspread-april-2cd … ba4.json'))
scope = ['https://spreadsheets.google.com/feeds', 'https://docs.google.com/feeds']

credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)
gc = gspread.authorize(credentials)
```

Don't forget to share your spreadsheet with an email you have in your `json_key['client_email']`.

**Comment by raj2569** [comment]
Thanks a lot! It's working now.

raj

**Comment by burnash** [comment]
Good, I'm glad it helped you.
