### ISSUE TITLE
update_cell(): can't update cell with non-latin symbols.

### ISSUE THREAD

**Issue by Idealistik** [burnash/gspread#173]
worksheet.update_cell( row, col, str )
Can't update cell with non-latin symbols.

There is no output error, but string is corrupted in spreadsheet after update, seems like encode-decode problem.

There is similar issue with gdata solved with workaround:
https://code.google.com/p/gdata-python-client/issues/detail?id=628

**Comment by msuozzo** [comment]
This issue should be fixed in 90d62248675aadc4c9546c7e87f28197f071345c.
