### ISSUE TITLE
New Error on Row Append: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by deltaGPhys** [burnash/gspread#174]
Any ideas about this error message? It came up while updating a spreadsheet with code that has worked many times before. This is different from the previous issue. 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "/Users/jgates/Desktop/LaTeX/genieautopickdirs.py", line 1545, in <lambda>
    Button(Rewin, text='Did it', command=lambda:DidIt(todaylist,Rebox.curselection(),chosendate,History,reassesslist,Rewin,"y")).pack(side=LEFT)
  File "/Users/jgates/Desktop/LaTeX/genieautopickdirs.py", line 297, in DidIt
    SaveHistory(History, reassesslist, todaydict, date, didtext)
  File "/Users/jgates/Desktop/LaTeX/genieautopickdirs.py", line 765, in SaveHistory
    worksheet.append_row(row)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gspread/models.py", line 518, in append_row
    new_row = self.row_count
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gspread/models.py", line 194, in row_count
    return int(self._element.find(_ns1('rowCount')).text)
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by soend** [comment]
Having exact same issue, is anybody looking into the problem?

**Comment by fatelei** [comment]
@soend I also meet this problem, and I fix it via reducing HTTPS request.  The code is below.

```
import grspread

gs = gspread.login(username, password)
worksheet = gs.open('xx')
sheet = worksheet.worksheet('sheet name')

# Firstly, fetch cells.
cells_list = sheet.range('A1:Z19')  # Range can be anywhere

# Secondly, update the cell value.
# Suppose, values_list holds all new values.

values_list = [...all new values...]

for cell, value in zip(cells_list, values_list):
     cell.value = value 

# Last, update all value through one HTTP(S) request.
sheet.update_cells(cells_list)
```

Hope this will be helpful for you.

**Comment by ravikumars** [comment]
Got the error too when i was using username/password for authentication. 

I then switched to OAuth2 and the error is not happening anymore. Using the oauth2client module from google.

This way I can add one row at a time instead of getting a range of cells and setting their values.

**Comment by msuozzo** [comment]
This may have been solved by migration to OAuth2. If anyone else runs into this error, please reopen the issue and post details.
