### ISSUE TITLE
OAuth Token invalid after one hour - not using refresh token

### ISSUE THREAD

**Issue by Pashbee** [burnash/gspread#181]
I have a Oauth Store like so (edited out the tokens with garble):-

{"_module": "oauth2client.client", "token_expiry": "2014-11-05T15:34:46Z", "access_token": "ggrgrgrgrg", "token_uri": "https://accounts.google.com/o/oauth2/token", "invalid": false, "token_response": {"access_token": "ggrgrgrgrg", "token_type": "Bearer", "expires_in": 3600, "refresh_token": "ggrgrgrgrgggrgrgrgrg"}, "client_id": "clid", "id_token": null, "client_secret": "nonononon", "revoke_uri": "https://accounts.google.com/o/oauth2/revoke", "_class": "OAuth2Credentials", "refresh_token": "ggrgrgrgrgggrgrgrgrg", "user_agent": null}

The initial token when authorised is produced and the expiry is set for an hour, I can then access my google sheet data. However, when the hour is up, there is never an attempt to refresh the token. The last commit mentions this should work, but it doesn't for me.

**Comment by expntly** [comment]
@burnash Looking at the code, it looks like the refresh is only done at Client.login() time?  i.e. it looks like I can't just hold a worksheet object, and make modifications on it forever -- when the token expires I'll get an exception.

If that's the case that's fine I'll make sure I just call login() before the token expires or when the exception is raised, but I just need you to confirm this is the intended behavior from users.

**Comment by burnash** [comment]
@expntly you're right it's only done at `Client.login`. I guess there's a need for some logic to to handle expired token exception and refresh the token.

**Comment by expntly** [comment]
@burnash Do you know what exception is thrown specifically, or is there a way I can say "lifetime=3s" to test?

**Comment by burnash** [comment]
@expntly unfortunately I don't know. I haven't seen it yet. If you get this exception, please share.

**Comment by expntly** [comment]
I'll just literally do

    if credentials.access_token_expired: cli.login()

**Comment by daldridge-cs** [comment]
@expntly, do you have to cli.open() etc. after logging in again, or will any original spreadsheet and worksheet references from previous connections still work?

**Comment by expntly** [comment]
@daldridge-cs 

```
import gspread
from oauth2client.client import SignedJwtAssertionCredentials

creds = SignedJwtAssertionCredentials(...)

def add_row(row):
  try:
    gs_client = gspread.authorize(creds)
    gs_worksheet = gs_client.open("foo").sheet1
    if creds.access_token_expired:
      gs_client.login()  # refreshes the token
    gs_worksheet.append_row(row)
  except Exception, e:
    traceback.print_exc()
```

This has been up and running for two months without issues now.
