### ISSUE TITLE
delete_row(x) urgently needed (data logging)

### ISSUE THREAD

**Issue by robert-winkler** [burnash/gspread#186]
For guys, who want to use gspread for data logging, a "delete_row" command would be more than helpful. Such simple function would allow to delete the first data row, and to append the new data at the end; like this the spreadsheet size would be maintained the same, which is great for graphical representation of the data and online data visualization. Currently, an implementation is very complicated (reading out and re-writing cell values.., which causes lot of traffic and costs time).
Best, Robert.

**Comment by chrism2671** [comment]
+1

**Comment by g0t0wasd** [comment]
+1!

**Comment by Ralithune** [comment]
Why isn't this already in?

**Comment by XtinaSchelin** [comment]
Commenting to, ideally, bump this up. This is what would make Gsheet syncing truly real for me.

**Comment by burnash** [comment]
Added in #337, v0.5.0
