### ISSUE TITLE
insert_row: empty cell seeminly impossible

### ISSUE THREAD

**Issue by mweinelt** [burnash/gspread#193]
```python
foo = ['foo', 'bar', None, 'baz']
bar = ['foo', 'bar', '', 'baz']
```

None of these lists would set the third cell to empty in the newly inserted row. This is a problem, because it might be overwritten by a multi-cell formula result.

**Comment by msuozzo** [comment]
I'm not sure what you mean by this. `bar` from your example seems to insert an empty cell at the third position. This may just be that the implementation of `insert_row` has changed since you asked your question. Has this problem persisted?

Thanks

**Comment by mweinelt** [comment]
Script is not in use anymore, cannot tell, sorry.

**Comment by msuozzo** [comment]
Alright thanks anyway. Hope you don't run into that issue again. Please reopen if you do.
