### ISSUE TITLE
del_worksheet():  ValueError: list.remove(x): x not in list 

### ISSUE THREAD

**Issue by Allard-Timothy** [burnash/gspread#195]
I get the above error for del_worksheet() when I loop through the worksheets of a spreadsheet and use del_worksheet on a single spreadsheet.  If I comment out...

 99.     self._sheet_list.remove(worksheet)

It will proceed without error.  Even adding a check...

  98.    self.client.del_worksheet(worksheet)
  99.    if worksheet not in self._sheet_list:
100.        self._sheet_list.remove(worksheet)

still results in a ValueError. When I comment out 'self._sheet_list.remove(worksheet)', run the loop and then call sheet.worksheets(), the prior instances of deleted worksheets aren't returned, only the remaining worksheets in the spreadsheet.  Do we need this line? It seems to do more harm then good.

**Comment by Allard-Timothy** [comment]
For what it's worth, I'll happily branch and then PR if you're ok with that.

**Comment by ryantuck** [comment]
can confirm this is still an issue with the latest 0.6.2 version of gspread. would suggest re-opening.
