### ISSUE TITLE
Feature Release to PYPI 

### ISSUE THREAD

**Issue by Allard-Timothy** [burnash/gspread#197]
Was hoping you could provide an updated release to PYPI.  For instance the PR that was merged:

https://github.com/burnash/gspread/pull/149

Does not reflect in the package that is available on PYPI.  A new release including the most recent features would be a huge help.  Thanks so much.

**Comment by alexstrat** [comment]
Thanks!

**Comment by burnash** [comment]
Sorry for the long pause guys. The newest gspread version [is on PyPI](https://pypi.python.org/pypi/gspread) now.
