### ISSUE TITLE
HTTP request: *** CannotSendRequest, *** ResponseNotReady: error

### ISSUE THREAD

**Issue by mosesmc52** [burnash/gspread#199]
Hi burnash, 

I have been using your python gspread library for the past several months. Today, I'm started receiving an httprequest error while attempting to open a google spreadsheet file. I'm not quite sure what change. If you have any insight the source this error may possibly be occurring, I will greatly appreciate. 

Regard,

Moses

**Comment by burnash** [comment]
Hi Moses, could you post your code sample please? Full stack trace can be also helpful.

**Comment by mosesmc52** [comment]
Here is my traceback error:

Traceback (most recent call last):
  File "gspread_test.py", line 12, in <module>
    wks = gc.open(file_name)
  File "/Users/mosesmccall/.virtualenvs/gspread/lib/python2.7/site-packages/gspread/client.py", line 134, in open
    feed = self.get_spreadsheets_feed()
  File "/Users/mosesmccall/.virtualenvs/gspread/lib/python2.7/site-packages/gspread/client.py", line 221, in get_spreadsheets_feed
    r = self.session.get(url)
  File "/Users/mosesmccall/.virtualenvs/gspread/lib/python2.7/site-packages/gspread/httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
  File "/Users/mosesmccall/.virtualenvs/gspread/lib/python2.7/site-packages/gspread/httpsession.py", line 75, in request
    raise HTTPError(response)
gspread.httpsession.HTTPError

I dug a little deeper and noticed that the script is failing on line 228  of client.py

r = self.session.get(url)

After printing out the url ( https://spreadsheets.google.com/feeds/spreadsheets/private/full) and running it within my browser, I see this error message. 

"We're sorry, a server error occurred. Please wait a bit and try reloading your spreadsheet."

Hope this helps. 

Thanks for your help and quick response.

**Comment by mosesmc52** [comment]
I tried rerunning the script using another google account. The script ran without any erors. Looks like the problem occurs specifically to the account.

**Comment by burnash** [comment]
Just for the record: was it your _gmail.com_ account or google apps account?

**Comment by mosesmc52** [comment]
Google apps account related to a different domain. After a few hour, everything started working without any errors.

**Comment by burnash** [comment]
Good, thanks for sharing!

**Comment by zzhjerry** [comment]
Hi Burnash,

Appreciate the library you wrote. But I'm running into the same problem here when I'm trying to get a column of data with worksheet.col_values(0).

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.pyc in request(self, method, url, body, headers)
   1051     def request(self, method, url, body=None, headers={}):
   1052         """Send a complete request to the server."""
-> 1053         self._send_request(method, url, body, headers)
   1054
   1055     def _set_content_length(self, body, method):

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.pyc in _send_request(self, method, url, body, headers)
   1085             skips['skip_accept_encoding'] = 1
   1086
-> 1087         self.putrequest(method, url, **skips)
   1088
   1089         if 'content-length' not in header_names:

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.pyc in putrequest(self, method, url, skip_host, skip_accept_encoding)
    933             self.__state = _CS_REQ_STARTED
    934         else:
--> 935             raise CannotSendRequest()
    936
    937         # Save the method we use, we need it later in the response phase

CannotSendRequest:

So now I can't retrieve any data.May I know how to get over of this?

**Comment by burnash** [comment]
@zzhjerry are you using OAuth to log in? Could you share a sample of your code?
