### ISSUE TITLE
gspread.exceptions.SpreadsheetNotFound

### ISSUE THREAD

**Issue by traxio** [burnash/gspread#201]
I use an older version of gspread for a long time now to pull out data from a spreadsheet to Python 2.7. However today it seems Google forcefully updated my spreadsheet to a new version so gspread is not working for me right now. The message is: 
Traceback (most recent call last):
  File "C:\Python27\*********************.py", line 6545, in worksht
    sht=c.open_by_key('0Au_-***************************************************')
  File "C:\Python27\lib\site-packages\gspread\client.py", line 146, in open_by_key
    raise SpreadsheetNotFound
gspread.exceptions.SpreadsheetNotFound

I don't even know where to start looking...

**Comment by timbeadle** [comment]
I have the same issue, but gc.open("Name of sheet") works ok

**Comment by ysekky** [comment]
I have the same issue, but one whose version 0.2.1 works ok

**Comment by chandruxp** [comment]
me too having this issue.. cloud is not under control..

**Comment by canercandan** [comment]
I also got this issue and solved it by removing uncommon characters on the title such as a non-break spaces. Hope you will find a way to solve yours.

**Comment by agroszer** [comment]
see:
https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?can=2&start=0&num=100&q=label%3AAPI-Spreadsheets&colspec=Stars%20Opened%20ID%20Type%20Status%20Summary%20API%20Owner&groupby=&sort=&id=3703

**Comment by agroszer** [comment]
we did:
```
FEED_ENTRY = """
    <entry xmlns='http://www.w3.org/2005/Atom' xmlns:openSearch='http://a9.com/-/spec/opensearchrss/1.0/'>
        <id>https://spreadsheets.google.com/feeds/spreadsheets/private/full/%(id)s</id>
        <updated>2015-03-30T04:03:23.047Z</updated>
        <category scheme='http://schemas.google.com/spreadsheets/2006' term='http://schemas.google.com/spreadsheets/2006#spreadsheet' />
        <title type='text'>%(title)s</title>
        <content type='text'>%(title)s</content>
        <link rel='http://schemas.google.com/spreadsheets/2006#worksheetsfeed' type='application/atom+xml' href='https://spreadsheets.google.com/feeds/worksheets/%(id)s/private/full' />
        <link rel='alternate' type='text/html' href='https://docs.google.com/spreadsheets/d/%(id)s/edit' />
        <link rel='self' type='application/atom+xml' href='https://spreadsheets.google.com/feeds/spreadsheets/private/full/%(id)s' />
        <author>
            <name>*ID*</name>
            <email>*ID*@developer.gserviceaccount.com</email>
        </author>
    </entry>
"""

def our_get_sheet(gs, id):
    xml = FEED_ENTRY % {'id': id,
                        'title': 'dummy'}
    from xml.etree import ElementTree
    elem = ElementTree.fromstring(xml)
    from gspread.models import Spreadsheet
    sheet = Spreadsheet(gs, elem)
    return sheet
```

basically creating the feed entry based on the sheet ID

**Comment by philfreo** [comment]
As of today I'm getting a SpreadsheetNotFound when using `open_by_key`. I haven't changed auth methods (still using an app-specific password on a 2-factor google apps account) but authentication still works because `openall()` returns all my sheets and `open(by_name)` works -- the only thing that stopped working is `open_by_key`.

**Comment by philfreo** [comment]
.... and today (looks like I'm not the only one) this method also stopped working and I had to generate the Oauth2 credentials.

**Comment by Shiva-Shinde** [comment]
File "/Library/Python/2.7/site-packages/gspread/client.py", line 150, in open
    raise SpreadsheetNotFound
gspread.exceptions.SpreadsheetNotFound

Hi @philfreo I am having the same problem. As you said, I tried with open("name of sheet"), still same error. I have run OAUTH2.0 crdentials.

Any suggestions?

**Comment by philfreo** [comment]
- double check the oauth2 instructions
- double check the spreadsheet name
- Make sure the email address of the oauth2 login (its random) has been invited to the spreadsheet

**Comment by Shiva-Shinde** [comment]
Thanks phil, I have shared email addresses etc. So strange, my script runs fine with no errors, no exceptions nothing. But its unable to open the sheet. Any suggestions?

**Comment by EamonnONeill** [comment]
I'm getting the exact same error "SpreadsheetNotFound" when opening by name or ID. Any ideas?

**Comment by Shiva-Shinde** [comment]
Open your .JSON file which you downloaded automatically. Search for 'client_email', copy that thing and share with your spreadsheet which you are trying to open. I am sure this will work!!

**Comment by msuozzo** [comment]
Have either of these issues been resolved?

**Comment by EamonnONeill** [comment]
Yes thank you!

**Comment by msuozzo** [comment]
Fantastic. Glad to hear it.

**Comment by plandrem** [comment]
@philfreo  your trick worked great for me! Share the doc with whatever email was in the JSON credentials file.
