### ISSUE TITLE
Delete and Add spreadsheet fails

### ISSUE THREAD

**Issue by helgisteinar** [burnash/gspread#202]
I needed to clear a worksheet and tried to delete it and re-create it.  This fails if I do it in the same script.

import gspread
gc = gspread.login('boo@boo.com','kdkdkd')
con=gc.open("201501test")

wrklist = con.worksheets()
for l in wrklist:
    if l.title == "rog":
        work = con.worksheet("rog")
        con.del_worksheet(work)
con2=gc.open("201501test")
con2.add_worksheet(title="rog",rows="300",cols="18")

**Comment by burnash** [comment]
I've updated gspread so now it shows an error message. Can you rerun your code and post the error?
