### ISSUE TITLE
make copy

### ISSUE THREAD

**Issue by sarathsp06** [burnash/gspread#208]
Ability to make  spreadsheet cop
----
Is it possible to make a copy of a template workbook using gspread  ?

**Comment by zxwild** [comment]
I'll join to this question (actually it's the feature request).

Explanation:
Google docs API doesn't allow to make other things than just insert / update / delete cells and worksheets. And there is only way to create a document, with for example auto filter, it's copying "template" file and update it as needed.
Uploading a template doesn't solve the problem also, a lot of formating loses after this operation.

**Comment by sarathsp06** [comment]
Yeah its a feature request and i was in a hurry sorry  i posted it as a bug
report.
What i wanted to know is  there is any way to emulate or do what 'file ->
makeCopy' does
Thank you

**Comment by zxwild** [comment]
It's a google drive functionality, something like:

```python
copied_file = {'title': 'new file name'}
service.files().copy(fileId=origin_file_id, body=copied_file).execute()
```

**Comment by sarathsp06** [comment]
awesome i will try .. was trying to do some appscript automations and got
stuck  stuck at this.
Thanks dude
