### ISSUE TITLE
Possible to specify cell formatting?

### ISSUE THREAD

**Issue by carolinux** [burnash/gspread#213]
Hello!
First of all, congrats for the library. It seems to have a far more sane API than anything I've seen so far that interfaces with Google Spreadsheets. I especially like that you added the functionality to insert a row anywhere in the spreadsheet - other APIs stubbornly refuse to see that this would be useful. 

I wanted to ask - I don't see how I can specify the formatting of each cell (font, font size, bg color etc) (or get the formatting of a cell). When I'm using the spreadsheet manually, the style of the previous row is inherited somehow. Do you think it's an easy change to make? Can you point me to the relevant classes? I could take a crack at it. Is it a matter of doing some more parsing of the cell_element in the Cell model ?

Thanks

**Comment by burnash** [comment]
@carolinux, thank you for the feedback!

Unfortunately this feature is not supported at the moment. There's [no official way](https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?id=37) to todo formatting and styling of cells with Google's API. However there is some experimental code from @archeg where he is [working with notes](https://gist.github.com/archeg/5652752) in a spreadsheet (this feature is also not included in Google's API). Take a look at it and give it a try.

If it does work, you can try to peek at a [node-spreadsheets action9.js way of using the API](https://github.com/EastCloud/node-spreadsheets/blob/master/lib/spreadsheets/action9.js#L25) and apply it to @archeg's script.

**Comment by VanushVaswani** [comment]
@burnash Isn't this now supported in Sheets API v4?!

**Comment by ewengillies** [comment]
+1
