### ISSUE TITLE
Issue with lack of access token after call to get signed credentials

### ISSUE THREAD

**Issue by abelmolina** [burnash/gspread#214]
Just reporting an issue I had in case someone else runs into it - following the guide in http://burnash.github.io/gspread/oauth2.html resulted in issues when calling authorize because the signed credentials didn’t have an access token. This got fixed by itself eventually after trying some approaches along the lines in this question: http://stackoverflow.com/questions/21420777/how-would-one-convert-wrap-a-httplib2-instance-as-a-session.

**Comment by msuozzo** [comment]
Can you elaborate a bit more? What version of python? Are you able to post the problem code and the code with your fix?

Thanks for reporting this.

**Comment by abelmolina** [comment]
No problem : ) I just took a look at the docs again, and it seems quite a bit less terse compared with what it was back in the spring, and my code doesn't seem meaningfully different from the one in it.

In any case, sharing some details in case it's helpful

- I don't have access to the same environment anymore, but I think it's some version of 2.7, and most likely 2.7.5.

- I don't have the error code either, but my working code is:
```python
    scope = ['https://spreadsheets.google.com/feeds', 'https://docs.google.com/feeds']
    with open("myCredentialFile") as f:
        p = f.read()
    credentials = SignedJwtAssertionCredentials('someString@developer.gserviceaccount.com',
                                                p,
                                                scope)
    gc = gspread.authorize(credentials)
```

**Comment by msuozzo** [comment]
Apologies for misreading your original post. I had thought this was a problem you were encountering. Glad the docs have improved.

Thanks again
