### ISSUE TITLE
Migrate from docs.google.com/feeds to drive api?

### ISSUE THREAD

**Issue by vinayan3** [burnash/gspread#218]
I got an email indicating the Documents List API will stop functioning on April 20th, 2015. 

The email says:
```
In your Google Apps Admin console, review Managing API Client Access for any approved scopes for this discontinued API. The Documents List API uses the following scopes:

https://docs.google.com/feeds/
https://docs.googleusercontent.com/
```

Any chance for updating spread to handle the new API?

**Comment by burnash** [comment]
Is it the same message as in #217?

**Comment by vinayan3** [comment]
Yes this is a duplicate sorry.

**Comment by burnash** [comment]
I don't think we need it. The only reference to this address is in [the oAuth docs](https://gspread.readthedocs.org/en/latest/oauth2.html):

```python
scope = ['https://spreadsheets.google.com/feeds', 'https://docs.google.com/feeds']
```

I've just stripped `'https://docs.google.com/feeds'` from the scope and rerun a test script and it works fine. I'll fix the docs.

**Comment by vinayan3** [comment]
Thank you so much. You are awesome!

**Comment by mhaith** [comment]
At the end of my rope.  Do I need to download the .json file from google sheets to the R Pi?  I downloaded it to a Windows desktop and transferred it to the R Pi with WinSCP.  google_spreadsheet.py reads the ..json file, as I have it print it out when the program runs but I get "unable to log in ....".  The email, ID, and key all look fine (except the key is missing a few digits just before the ""\n ---End Private Key", that is the print matches the contents of the .json file.  I've tried this with three different spreadsheets and three different ..json files and have followed the instructions diligently;  My program, incidentally, has worked perfectly for months - before the switch to the new authorization scheme.  If I need to download the .json file to the Pi directly, I need help in doing so: I've tried the Pi browsers, and I can't get to my spreadsheets.

Or, maybe I have to migrate my spreadsheets?  But I don't know what that means.

Thanks for the help.

**Comment by burnash** [comment]
@mhaith What Python version are you using on your Pi?

Yes you do need to put your key (in json file or any other form) to an environment your Python script is running in. 

My wild guess is that there's something wrong with key encoding as in #238 #239

**Comment by mhaith** [comment]
Hi,

Thanks so much for your response. I was hopeful that #239  would work.  I was able to generate a .json file without the offending characters, “\u003d …” at the end of the key, but I still get the  “login_open_sheet” line.  I’m going to go on vacation for a week and try again when I get back.  I may do another posting, but I’ll try first to start again from scratch.

BTW, thanks for the “insert row” addition to gspread.  I had a workaround, but you approach is much faster.

Thanks again,

Marshall Haith

**Comment by mhaith** [comment]
BTW, I am using Python 2.7.3.
