### ISSUE TITLE
Create, delete and clear worksheet function

### ISSUE THREAD

**Issue by ollieglass** [burnash/gspread#22]
Worksheet level functions to create, delete and clear sheets would be very helpful.

**Comment by sagunsh** [comment]
Yes a clear method would be great, if not at least a overwrite method then.

**Comment by wiffel** [comment]
for those people like me, clear feature is available `worksheet.clear()` :) "https://gspread.readthedocs.io/en/latest/api.html#gspread.models.Worksheet.clear
