### ISSUE TITLE
Spreadsheet on GoogleDrive folder

### ISSUE THREAD

**Issue by alex1a** [burnash/gspread#229]
Hello, i'm using google_speadsheet python script by adafruit to submit my dht11 data to google drive. it's possible to logging a a foldered google spreadsheet.

I try to change the string to this format and doesn't work:
Any help ?

GDOCS_SPREADSHEET_NAME = '<folder>\<spreadsheet>'
GDOCS_SPREADSHEET_NAME = '<folder>/<spreadsheet>'
worksheet = gc.open(<folder>/<spreadsheet>).sheet1
worksheet = gc.open(<folder>\<spreadsheet>).sheet1

Thanks
Alex

**Comment by burnash** [comment]
I guess you need to use a proper spreadsheet name instead of '/'? What exact error are you getting?

**Comment by alex1a** [comment]
i don't have errors if i put spreadsheet file in main folder on googledrive, but i want to put in a subfolder.
how can i access with this format ? gc.open(<subfolder>/<spreadsheetname>)

**Comment by burnash** [comment]
I'm afraid folders and subfolders are not supported yet. `gc.open` is working only with titles of spreadsheets.

**Comment by alex1a** [comment]
ok, i think wasn't a problem. i will open the spreadsheet in another way :) thanks

**Comment by githubbla** [comment]
please add support for subfolders... i feel like MS DOS 1.0 when i must use root folder, there also limitation on file quantity with windows/osx clients.
