### ISSUE TITLE
Set/Modify sheet protection

### ISSUE THREAD

**Issue by ghost** [burnash/gspread#23]
I ran into some problems when other people modify the Google doc while my script is processing.
Is it possible to set the sheet protection  (Tools->Protect Sheet "Who is allowed to modify the sheet") to "Only by me" while via the module and then set it back to its initial status after having finished the editing?
Does your current implementation allow to easily use 'http://code.google.com/apis/documents/docs/3.0/developers_guide_protocol.html#AccessControlLists' ?

If so I could try to add this (it might take some time though as I am new to Python.

**Comment by msuozzo** [comment]
Merging this with #293 as both deal with the Drive API and sharing.
