### ISSUE TITLE
SpreadsheetNotFound for open_by_key, openall if there are >500 spreadsheets

### ISSUE THREAD

**Issue by piarkusze** [burnash/gspread#233]
Hello,

It seems that there is a limit (500 sheets-entries) in Google's API. Thus, calling `open_by_key()` which uses `get_spreadsheets_feed()` causes `gspread.exceptions.SpreadsheetNotFound` if spreadsheet is among these that are excluded because of the limit.

Same issue with `openall()`.

At first glance, solution for the first problem would be, probably, easy - calling sth like `get_worksheets_feed(id_spreadsheet)` instead of `get_spreadsheets_feed()`

For the second, I don't know - maybe there is a way to get all entries without limits.

We have just exceed number of spreadsheet - there are more than 500, thus we faced described issue.

**Comment by piarkusze** [comment]
Ok, it seems that solution for the first problem won't be that easy. XML structure is different, thus creating Spreadsheet from '''get_worksheets_feed()''' is difficult.

**Comment by msuozzo** [comment]
Nice to know there is a limitation here. Added as a bug.

Thanks for the heads up

**Comment by burnash** [comment]
@piarkusze thanks for reporting this.

gspread is now using API v4 for `Client.open_by_key()` and Google Drive API v3 for `Client.openall()`. These methods have been rewritten from scratch. The last default limit was removed in #522. I can not reproduce the issue any longer. I'm closing this. Please feel free to re-open the issue if you still receive this error.
