### ISSUE TITLE
AuthenticationError: Unable to authenticate. 404 code

### ISSUE THREAD

**Issue by gngrwzrd** [burnash/gspread#234]
Has anyone experienced this error?

	File "/Users/aaronsmith/Development/Apptitude/_epsilon/epsilon-partnersconnect/out/handlers/localization.py", line 50, in post
	    gc = gspread.login(username,password)
	  File "/Users/aaronsmith/Development/Apptitude/_epsilon/epsilon-partnersconnect/out/gspread/client.py", line 317, in login
	    client.login()
	  File "/Users/aaronsmith/Development/Apptitude/_epsilon/epsilon-partnersconnect/out/gspread/client.py", line 120, in login
	    "Unable to authenticate. %s code" % ex.code)
	AuthenticationError: Unable to authenticate. 404 code

The gspread library was working fine, I haven't changed anything in my code and all of the sudden I'm getting this error. I've double checked that the spreadsheet on google hasn't changed.

Not sure why this would be happening. Any ideas?

**Comment by gngrwzrd** [comment]
Note, I updated to the latest version of gspread and I now get this error:

	File "/Users/aaronsmith/Development/Apptitude/_epsilon/epsilon-partnersconnect/out/handlers/localization.py", line 50, in post
	    gc = gspread.login(username,password)
	  File "/Users/aaronsmith/Development/Apptitude/_epsilon/epsilon-partnersconnect/out/gspread/client.py", line 322, in login
	    client.login()
	  File "/Users/aaronsmith/Development/Apptitude/_epsilon/epsilon-partnersconnect/out/gspread/client.py", line 125, in login
	    "Unable to authenticate. %s" % ex.message)
	AuthenticationError: Unable to authenticate. 404: https://developers.google.com/accounts/docs/AuthForInstalledApps

Any ideas? Thanks!

**Comment by astroboi22** [comment]
I am also experiencing this issue. Running Python 2.7.9 on Ubuntu 14.04 LTS:

Traceback (most recent call last):
  File "topHundred.py", line 17, in <module>
    gc = gspread.login('achiang@indeed.com', 'ywqojcspkpgokjgx')
  File "/home/achiang/Projects/theHundreds/gspread/client.py", line 313, in login
    client.login()
  File "/home/achiang/Projects/theHundreds/gspread/client.py", line 116, in login
    "Unable to authenticate. %s code" % ex.code)
gspread.exceptions.AuthenticationError: Unable to authenticate. 404 code

**Comment by burnash** [comment]
Email & password authentication was [deprecated by Google on April 20th](https://developers.google.com/accounts/docs/AuthForInstalledApps?csw=1). You need to use [oAuth2](http://gspread.readthedocs.org/en/latest/oauth2.html) to access your spreadsheets.

**Comment by astroboi22** [comment]
Awesome, thank you for your prompt response!!

**Comment by joyalexandre** [comment]
Same for me, it stopped working today. I've managed to find that was because Google deprecated the email and password login like you said. 

The problem is that I tried to follow the doc to use oAuth2 here: http://gspread.readthedocs.org/en/latest/oauth2.html.

I can't manage to make the authentication to work. I thonk I'm missing something. After the tutorial done I got this error: 
oauth2client.client.CryptoUnavailableError: No crypto library available

I imported the "PyOpenSSL" library. Then I got this error: 
TypeError: 'str' does not support the buffer interface

Is it because I'm running with Python3?

**Comment by burnash** [comment]
@joyalexandre check the issue #224 it looks like a similar problem.

**Comment by joyalexandre** [comment]
Thanks it helped me a lot. :-)
Thanks for your fast support!

**Comment by burnash** [comment]
You're welcome.

**Comment by barroca** [comment]
Thanks for the support! :)

**Comment by p5a0u9l** [comment]
I had this problem too. Will you be updating the library accordingly? By the way, I second the great support I've seen here.

**Comment by felagund** [comment]
In python 3, one needs to read the key in binary (or bytes if you store it in file).

**Comment by stevage** [comment]
Just ran into this. Btw the word "deprecated" isn't right - ClientLogin was "deprecated" (that is, discouraged, but still accessible) in 2012, and has now been **disabled**: https://developers.google.com/identity/protocols/AuthForInstalledApps

**Comment by burnash** [comment]
@stevage You're right. Thank you.

**Comment by vivek2007** [comment]
Hi all, i am facing with OAuth version can you please help me

request error 404: https://developers.google.com/accounts/docs/AuthForInstalledApps
/home/vivek/.rvm/gems/ruby-1.9.2-p290/gems/gdata_19-1.1.5/lib/gdata/auth/clientlogin.rb:85:in `get_token'
/home/vivek/.rvm/gems/ruby-1.9.2-p290/gems/gdata_19-1.1.5/lib/gdata/client/base.rb:157:in `clientlogin'
/home/vivek/Documents/GTFS1/inc/ft.rb:10:in `init'
/home/vivek/Documents/GTFS1/inc/ft.rb:99:in `getTable'
/home/vivek/Documents/GTFS1/inc/ft.rb:28:in `update'
/home/vivek/Documents/GTFS1/Rakefile:435:in `block (3 levels) in <top (required)>'
/home/vivek/Documents/GTFS1/Rakefile:434:in `each'
/home/vivek/Documents/GTFS1/Rakefile:434:in `block (2 levels) in <top (required)>'
/home/vivek/.rvm/gems/ruby-1.9.2-p290/bin/ruby_executable_hooks:15:in `eval'
/home/vivek/.rvm/gems/ruby-1.9.2-p290/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => project:deploy_fusiontables
(See full trace by running task with --trace)
vivek@vivek:~/Documents/GTFS1$ rake project:deploy_fusiontables
07:41:35 +0 : START Fusion Tables INSERTs
rake aborted!
request error 404: https://developers.google.com/accounts/docs/AuthForInstalledApps
/home/vivek/.rvm/gems/ruby-1.9.2-p290/gems/gdata_19-1.1.5/lib/gdata/auth/clientlogin.rb:85:in `get_token'
/home/vivek/.rvm/gems/ruby-1.9.2-p290/gems/gdata_19-1.1.5/lib/gdata/client/base.rb:157:in `clientlogin'
/home/vivek/Documents/GTFS1/inc/ft.rb:10:in `init'
/home/vivek/Documents/GTFS1/inc/ft.rb:99:in `getTable'
/home/vivek/Documents/GTFS1/inc/ft.rb:28:in `update'
/home/vivek/Documents/GTFS1/Rakefile:435:in `block (3 levels) in <top (required)>'
/home/vivek/Documents/GTFS1/Rakefile:434:in `each'
/home/vivek/Documents/GTFS1/Rakefile:434:in `block (2 levels) in <top (required)>'
/home/vivek/.rvm/gems/ruby-1.9.2-p290/bin/ruby_executable_hooks:15:in `eval'
/home/vivek/.rvm/gems/ruby-1.9.2-p290/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => project:deploy_fusiontables
(See full trace by running task with --trace)

**Comment by felagund** [comment]
Vivek, gspread is a python library, you are using ruby.
