### ISSUE TITLE
OAuth 2 with no site

### ISSUE THREAD

**Issue by deltaGPhys** [burnash/gspread#236]
My local app's use of gspread broke today, which is because of the Oauth2 authentication need, I gather (https://github.com/burnash/gspread/issues/224). When I try to follow the directions, I get to the admin.google.com login screen, but it doesn't recognize my login. I'm not using Google App Engine or anything like that - I'm using gspread through a local python script. Is there a different set of stuff that I should do to make this work?

Thanks!

**Comment by burnash** [comment]
Have you followed this guide: http://gspread.readthedocs.org/en/latest/oauth2.html ?
You don't need to use Google App Engine with that and can go on using your local script.

**Comment by deltaGPhys** [comment]
Thanks for the pointer - I'm all set now. Consider adding the need for authentication packages into those docs; other than that, it was relatively smooth sailing. Thanks!

**Comment by burnash** [comment]
Do you mean `oauth2client`?

**Comment by deltaGPhys** [comment]
Yes, that's what I'm using. I had to install pyopenssl to get it running.

**Comment by burnash** [comment]
Done. Thanks for the suggestion.
