### ISSUE TITLE
Oauth2 Not working

### ISSUE THREAD

**Issue by jonathanng** [burnash/gspread#237]
I'm on Windows, using Python 2.7. I've updated gspread and oauth2client-1.4.11.

I followed the steps [here](https://github.com/burnash/gspread/issues/224).

My preference would to not do the solution [here](https://github.com/burnash/gspread/issues/224), as I would really like to keep all my keys, passwords, etc on a single file.

My code:

    GOOGLE_SPREADSHEET_CLIENT_EMAIL = '***@developer.gserviceaccount.com'
    GOOGLE_SPREADSHEET_PRIVATE_KEY  = "-----BEGIN PRIVATE KEY-----\n***\n-----END PRIVATE KEY-----\n"

    def account():

        credentials = SignedJwtAssertionCredentials(
            service_account_name = GOOGLE_SPREADSHEET_CLIENT_EMAIL,
            private_key          = GOOGLE_SPREADSHEET_PRIVATE_KEY,
            scope                = ['https://spreadsheets.google.com/feeds']
        )

        return gspread.authorize(credentials)

        # return gspread.login(
        #     settings.GOOGLE_SPREADSHEET_USERNAME,
        #     settings.GOOGLE_SPREADSHEET_PASSWORD
        # )

Error:

        c:\development\test\google_spreadsheets.pyc in account()
           16     )
           17 
        ---> 18     return gspread.authorize(credentials)
           19 
           20     # return gspread.login(

        C:\Anaconda\lib\site-packages\gspread\client.pyc in authorize(credentials)
          333     """
          334     client = Client(auth=credentials)
        --> 335     client.login()
          336     return client
          337 

        C:\Anaconda\lib\site-packages\gspread\client.pyc in login(self)
           96 
           97                 http = httplib2.Http()
        ---> 98                 self.auth.refresh(http)
           99 
          100             self.session.add_header('Authorization', "Bearer " + self.auth.access_token)

        C:\Anaconda\lib\site-packages\oauth2client\client.pyc in refresh(self, http)
          596         request.
          597     """
        --> 598     self._refresh(http.request)
          599 
          600   def revoke(self, http):

        C:\Anaconda\lib\site-packages\oauth2client\client.pyc in _refresh(self, http_request)
          767     """
          768     if not self.store:
        --> 769       self._do_refresh_request(http_request)
          770     else:
          771       self.store.acquire_lock()

        C:\Anaconda\lib\site-packages\oauth2client\client.pyc in _do_refresh_request(self, http_request)
          793       AccessTokenRefreshError: When the refresh fails.
          794     """
        --> 795     body = self._generate_refresh_request_body()
          796     headers = self._generate_refresh_request_headers()
          797 

        C:\Anaconda\lib\site-packages\oauth2client\client.pyc in _generate_refresh_request_body(self)
         1423 
         1424   def _generate_refresh_request_body(self):
        -> 1425     assertion = self._generate_assertion()
         1426 
         1427     body = urllib.parse.urlencode({

        C:\Anaconda\lib\site-packages\oauth2client\client.pyc in _generate_assertion(self)
         1552     private_key = base64.b64decode(self.private_key)
         1553     return crypt.make_signed_jwt(crypt.Signer.from_string(
        -> 1554         private_key, self.private_key_password), payload)
         1555 
         1556 # Only used in verify_id_token(), which is always calling to the same URI

        C:\Anaconda\lib\site-packages\oauth2client\crypt.pyc in from_string(key, password)
          163       parsed_pem_key = _parse_pem_key(key)
          164       if parsed_pem_key:
        --> 165         pkey = crypto.load_privatekey(crypto.FILETYPE_PEM, parsed_pem_key)
          166       else:
          167         if isinstance(password, six.text_type):

        C:\Anaconda\lib\site-packages\OpenSSL\crypto.pyc in load_privatekey(type, buffer, passphrase)
         2008 
         2009     if evp_pkey == _ffi.NULL:
        -> 2010         _raise_current_error()
         2011 
         2012     pkey = PKey.__new__(PKey)

        C:\Anaconda\lib\site-packages\OpenSSL\_util.pyc in exception_from_error_queue(exceptionType)
           20                 text(lib.ERR_reason_error_string(error))))
           21 
        ---> 22     raise exceptionType(errors)
           23 
           24 

        Error: []

        > c:\anaconda\lib\site-packages\openssl\_util.py(22)exception_from_error_queue()
           21 
        ---> 22     raise exceptionType(errors)
           23 

Thanks for your help!

**Comment by burnash** [comment]
Can you post all three digits of your Python's version? (eg 2.7.X)

Did you try using this guide? http://gspread.readthedocs.org/en/latest/oauth2.html

**Comment by jonathanng** [comment]
I followed the guide exactly. The only thing I did differently was instead of reading in the JSON, I copied the email and key into a settings file.

I'm using 2.7.9.

**Comment by burnash** [comment]
Thanks. You might hit the issue with the ssl in the latest Python version (#228). There's a pull request with a fix for it. I haven't test it though. Can you try @danielcb's fix to see if it works for you?

This is how you can get it:

    git clone -b feature-ssl-verification https://github.com/danielcb/gspread.git

**Comment by jonathanng** [comment]
Just tried that.  Didn't work.

I'm confused of why there just isn't an error. Why would this occur?

       Error: []

**Comment by danielcb** [comment]
Hi,

not completely sure, but I don't think that has anything to do with #228. The traceback here looks like there's something wrong with the key you're trying to parse.

``` --> 165         pkey = crypto.load_privatekey(crypto.FILETYPE_PEM, parsed_pem_key)```

**Comment by jonathanng** [comment]
Figured it out. The key was unicode.

Needed to do this:

        GOOGLE_SPREADSHEET_PRIVATE_KEY  = u"-----BEGIN PRIVATE KEY-----\n***\n-----END PRIVATE KEY-----\n"
