### ISSUE TITLE
Feed empty after getting it from get_spreadsheets_feed()

### ISSUE THREAD

**Issue by grigorisg9gr** [burnash/gspread#242]
I am trying to convert my code based on the OAuth2 and I do login all-right, however I cannot open any spreadsheet. Tried all the open functions, i.e. open, open_by_key, open_all. 

The reason is that the function client.open() has an empty feed.findall(_ns('entry')), which is not obviously the case.

**Comment by brovador** [comment]
Same here, I've got an old script (1 year or more) that stop working by the oauth change.  I've changed the auth system from password to oauth and now is connecting and logging in but when I request for a spreadsheet always return empty. I've tried by name, id, url and get all, and all of them return empty data.

**Comment by jonathanng** [comment]
Are you sharing the spreadsheets to the email address?

> Go to Google Sheets and share your spreadsheet with an email you have in your json_key['client_email']. Otherwise you’ll get a SpreadsheetNotFound exception when trying to open it.

**Comment by burnash** [comment]
@jonathanng is right, try to share your spreadsheet with an email you got in your oAuth2 creds.

**Comment by grigorisg9gr** [comment]
Indeed, this solved the issue for me. Thanks for the quick responses. 

I just noticed that it was in the initial readthedocs. Maybe rephrasing it would help avoiding this question in the future.

**Comment by brovador** [comment]
Solved too, thanks! I missed that part in the readthedocs manual too

**Comment by burnash** [comment]
@grigorisg9gr you're right. I'll put a note on the github's page as well.
