### ISSUE TITLE
Unable to login and get spreadsheet. 

### ISSUE THREAD

**Issue by Micchiu** [burnash/gspread#246]
I had to update my simple temperature and humidity code that used gspread and accessed my file on google sheets by simple undername and password.
Now, I had to update the code for the new auth system.
As end user, I strictly (I think that at least) followed the instructions provided, but I obtain the message "Unable to login and get spreadsheet. ". I am using the phyton code provided by Adafruit.
I lost night and nights trying to understand where is my error, with no success.
Have someone had the same issue and can help me?
thx!

**Comment by burnash** [comment]
Are you running on PI? What is your Python version? Can you post your stacktrace with the error?

**Comment by Micchiu** [comment]
Hello, thank you for you interest in my problem.
The Python version should be:
Python 2.7.3 (default, Mar 18 2014, 05:13:23)
[GCC 4.6.3] on linux2

Then for the "stacktrace", being a newcomer, I would request your help to get it......how can I get that?

**Comment by klvs** [comment]
I am using the same stack as Micchiu. Raspian but also python 2.7.3. 

Interestingly my pip freeze says I'm still on gspread==0.2.2 but I can't seem to upgrade (0.2.5 exists according to pip's website). Perhaps another issue, perhaps related. Sounds like Micchiu is experiencing the same issue I am. Here is the code that's throwing the exception and printing the message.

        try:
                gc = gspread.login(email, password)
                worksheet = gc.open(spreadsheet).sheet1
                return worksheet
        except:
                print 'Unable to login and get spreadsheet.  Check email, password, spreadsheet name.'
                sys.exit(1)

Failing on either login or getting the worksheet. Will be testing more but wanted to offer insight to anyone tackling the issue before I can get to it.

**Comment by Micchiu** [comment]
That one is the old method and it is not working anymore since Google changed the APIs.
I used that one for months and the python simple code I did worked perfectly with no interventions from my side for weeks and weeks.
One day I noticed that readings were no more recorded and so I went back to understand why.

Then I now know that a new (much more complex) access procedure is to be applied.
So I took inspiration from the new Adafruit Python code issued meantime and applied it to my code with no modifications (just adaptations like *.json file and then the email in google and slight changes to the calls for functions).

What i can add is that (to try debug myself) I added to my pyhton code few lines to have the email and keys the code is sending to Goolge printed on screen and they are correct.
This should mean that  the code reads the *.json file and data correctly.

I did the process two times, independently, with two different authorization requested to Google, w differen *.json files, emails, etc etc .
No results.

So or I am missing something fundamental, or there is something really stupid I am doing wrong!

Thank you for you help.

**Comment by burnash** [comment]
Thanks @klvs for good suggestion. @Micchiu are you running the latest gspread version? For a simple check do a pip freeze do: 

~~~sh
pip freeze | grep gspread
~~~

Make sure the version is 0.2.5. If it's not, you need to update the library.

The stacktrace (or traceback) is all of the lines before the final error message, starting with the sentence: 

~~~
Traceback (most recent call last):
~~~

**Comment by swordeh** [comment]
Not sure if this is directly related, but writing to Sheets over the last few days has been very temperamental for me. I've had to wrap my range() and update_cells() functions in 
```
while True:
    try:
        blah
        break
    except Exception as e:
        print "Trying again"
```

Not amazing, but gets it done. Point is, it might not be you. It might be the API crapping out. Never had this issue up until now.

**Comment by Micchiu** [comment]
@burnash  
the version of python is "gspread==0.2.5".

Actually, it seems I do not get any error from the code, that simply ends up with:
"Press Ctrl-C to quit.
Unable to login and get spreadsheet.  Check OAuth credentials, spreadsheet name, and make sure spreadsheet is shared to the client_email address  in the OAuth .json file!"

I did that, and most probably I am missing something, but how can I understand what?

**Comment by Micchiu** [comment]
One thing, the new piece of code I used has everywhere a strange format, as below:
credentials = SignedJwtAssertionCredentials(json_key['client_email'], 
													json_key['private_key'], 
													['https://spreadsheets.google.com/feeds'])

I corrected that, deleting the spaces after the commas.
why that strange format?

**Comment by swordeh** [comment]
@Micchiu are you definitely loading the json file correctly?

Can you post more of your code?

**Comment by Micchiu** [comment]
@swordeh 
yes I guess so, as when I printout the keys (like the email) they seem correct.

Also, @burnash, I do not get any Traceback errors.

**Comment by burnash** [comment]
@Micchiu Didn't notice it before but this error `Unable to login and get spreadsheet.` doesn't seem to belong to the gspread itself. Are you using some library that in turn uses gspread?

I've googled the error and found the possible source code: https://github.com/adafruit/Adafruit_Python_DHT/blob/master/examples/google_spreadsheet.py

Is it the code you're using?

@swordeh What kind of errors are you getting? Maybe you can open a separate issue for it?

**Comment by Micchiu** [comment]
@burnash,
that is the code I am using. Before the security change, it worked perfectly.
The error is generated while using gspread

**Comment by burnash** [comment]
You need to remove the `try / except` wrapper from the [login_open_sheet function](https://github.com/adafruit/Adafruit_Python_DHT/blob/master/examples/google_spreadsheet.py#L74).

 The `except` is hiding the original gspread's exception, thus removing any chance to trace the source of the error.

**Comment by Micchiu** [comment]
@burnash 
thx for the hint.
here what I obtain now on the screen:

Traceback (most recent call last):
  File "./google_spreadsheet-emilio-ver2.0.py", line 76, in <module>
    worksheet = login_open_sheet(GDOCS_OAUTH_JSON, GDOCS_SPREADSHEET_NAME)
  File "./google_spreadsheet-emilio-ver2.0.py", line 60, in login_open_sheet
    credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], ['https://spreadsheets.google.com/feeds'])
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 1504, in __init__
    _RequireCryptoOrDie()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 1458, in _RequireCryptoOrDie
    raise CryptoUnavailableError('No crypto library available')
oauth2client.client.CryptoUnavailableError: No crypto library available

**Comment by Micchiu** [comment]
any idea??
I am really lost

**Comment by burnash** [comment]
@Micchiu as you can see the error comes from Google's oauth2client library. 

[Googling](https://www.google.com/search?q=oauth2client.client.CryptoUnavailableError%3A+No+crypto+library+available) "oauth2client.client.CryptoUnavailableError: No crypto library available" gives us a list of possible solutions. Try [this one from StackOverflow](http://stackoverflow.com/questions/27305867/google-api-access-using-service-account-oauth2client-client-cryptounavailableerr).

The same error was mentioned in #224.

**Comment by Micchiu** [comment]
@burnash 
hello, most probably that was fixed. 
I will keep yo informed.
thank you for your help and support.

However, FYI and to my great surprise, it is 2 days thast the "old" system with username and pwd restarted to work.
Maybe our friends at Google made up their minds? :-)

**Comment by Micchiu** [comment]
@burnash 
just an update.
My program with the new oauth2client is keeping working correctly.
Again, thank you for your help!
However (unless this should be clear to experienced GutHub users) i would highlight the necessity of the software indicated in #224 or in that one obtains by Googling.

**Comment by burnash** [comment]
@Micchiu I'm glad it finally works for you.

> However (unless this should be clear to experienced GutHub users) i would highlight the necessity of the software indicated in #224 or in that one obtains by Googling.

Yes, that's a good idea. I'm short on time, but it definitely makes sense to update docs with this sort of info.

**Comment by burnash** [comment]
@Micchiu I've added [a brief reference](https://github.com/burnash/gspread/blob/master/docs/oauth2.rst#oauth2clientclientcryptounavailableerror-no-crypto-library-available) to this issue. Can you take a look to see if there're more useful info I can add to the docs?

**Comment by burnash** [comment]
@Micchiu do you think you can close the issue?

**Comment by Micchiu** [comment]
@burnash 
hello. yes indeed, that brief reference is clear.
Thank you for precious assiastance and efforts.
Yes indeed I am closing the issue.
