### ISSUE TITLE
CannotSendRequest exceptions under WSGI

### ISSUE THREAD

**Issue by foxylad** [burnash/gspread#249]
First, thanks for an awesome project. It's made my life much easier.

I'm using gspread from a Python 2.7 WSGI application, in case that makes a difference. Usually gspread works fine, but occassionally I'll get an exception (like  BadStatusLine) and then it stops working completely - I get CannotSendRequest every time. Restarting apache fixes this. 

I'm wondering if httpsession is caching connections when it shouldn't, but I haven't spent long enough to find out exactly what is going on. Does anyone have a less destructive way of resetting connections than restarting the webserver?

```
[Fri Jun 05 17:20:39 2015] [error]   File "/var/local/capo/googlesheet.py", line 63, in get_cells
[Fri Jun 05 17:20:39 2015] [error]     return self.worksheet.range(range_string)
[Fri Jun 05 17:20:39 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/gspread/models.py", line 334, in range
[Fri Jun 05 17:20:39 2015] [error]     'return-empty': 'true'})
[Fri Jun 05 17:20:39 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 250, in get_cells_feed
[Fri Jun 05 17:20:39 2015] [error]     r = self.session.get(url)
[Fri Jun 05 17:20:39 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 79, in get
[Fri Jun 05 17:20:39 2015] [error]     return self.request('GET', url, **kwargs)
[Fri Jun 05 17:20:39 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 71, in request
[Fri Jun 05 17:20:39 2015] [error]     uri.scheme + uri.netloc].request(method, url, data, headers=request_headers)
[Fri Jun 05 17:20:39 2015] [error]   File "/usr/lib/python2.7/httplib.py", line 958, in request
[Fri Jun 05 17:20:39 2015] [error]     self._send_request(method, url, body, headers)
[Fri Jun 05 17:20:39 2015] [error]   File "/usr/lib/python2.7/httplib.py", line 986, in _send_request
[Fri Jun 05 17:20:39 2015] [error]     self.putrequest(method, url, **skips)
[Fri Jun 05 17:20:39 2015] [error]   File "/usr/lib/python2.7/httplib.py", line 856, in putrequest
[Fri Jun 05 17:20:39 2015] [error]     raise CannotSendRequest()
[Fri Jun 05 17:20:39 2015] [error] CannotSendRequest
```

**Comment by burnash** [comment]
Sorry for the late reply. Yes it could be due to a httpsession's connection caching. 

I played with the code a bit and I think I may have a possible solution to your problem (if it still persists.)

I'm migrating the code to a state where `gspread.Client` will be able to use a [requests.Session](http://docs.python-requests.org/en/latest/user/advanced/#session-objects) instead of gspread's session module. The interfaces of both modules are similar since I modelled the httpsession after requests.Session.

**Comment by foxylad** [comment]
Thanks for getting back to me. This is a frustrating bug because it only happens once in a while - every few days - but it is still happening.

Let me know when you have integrated the requests module, and I'll test it. As soon as we get the first error I'll be able to tell you if the problem is fixed.

And again, thanks for your work on this project!

**Comment by msuozzo** [comment]
Added #302 to address this.
