### ISSUE TITLE
gspread.exceptions.HTTPError not found attribute 'message'

### ISSUE THREAD

**Issue by irov** [burnash/gspread#251]
if ex.message.strip() == '403: Error=BadAuthentication':
AttributeError: 'HTTPError' object has no attribute 'message'

it's Python 3.5

**Comment by burnash** [comment]
This needs to be a bit more verbose to be useful. When do you get this error? What is your OS? What's your Python version? What traceback are you getting?

**Comment by irov** [comment]
sorry.. Python 3.5

**Comment by burnash** [comment]
And what about the rest of the questions? What traceback are you getting?

**Comment by irov** [comment]
Python 3.5
class 'Exception' not have attribute "message" but override operator __str__ or __repr__

and for 3.5 need replace this line like this

if str(ex).strip() == '403: Error=BadAuthentication':

*sorry for my poor engilsh

**Comment by burnash** [comment]
Can you paste whole traceback? It's really hard to guess what's going on.

**Comment by irov** [comment]
Traceback (most recent call last):
  File "d:\Projects\Burritos\Bin2/XLSXEX~1\gspread\client.py", line 114, in logi
n
    r = self.session.post(url, data)
  File "d:\Projects\Burritos\Bin2/XLSXEX~1\gspread\httpsession.py", line 85, in
post
    return self.request('POST', url, data=data, headers=headers)
  File "d:\Projects\Burritos\Bin2/XLSXEX~1\gspread\httpsession.py", line 75, in
request
    raise HTTPError("%s: %s" % (response.status, response.read()))
gspread.exceptions.HTTPError: 403: b'Error=BadAuthentication\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Projects\Burritos\Bin2/XLSXEX~1\xlsxExporter.py", line 53, in export
    exportGoogleSpreadsheet(projectName, ProjectPath, ParamsPath, "Database", "R
esources", "Scripts/Database", "PathGoogleSpreadsheets.xlsx", createDatabaseORM)

  File "d:\Projects\Burritos\Bin2/XLSXEX~1\xlsxExporter.py", line 451, in export
GoogleSpreadsheet
    client = gspread.login(username, password)
  File "d:\Projects\Burritos\Bin2/XLSXEX~1\gspread\client.py", line 322, in logi
n
    client.login()
  File "d:\Projects\Burritos\Bin2/XLSXEX~1\gspread\client.py", line 121, in logi
n
    if ex.message.strip() == '403: Error=BadAuthentication':
AttributeError: 'HTTPError' object has no attribute 'message'

**Comment by irov** [comment]
And

client.py 282 line
           if ex.code == 403:

HTTPError no attribute 'code'

**Comment by burnash** [comment]
What version of gspread are you using?

**Comment by irov** [comment]
last master
https://github.com/burnash/gspread/archive/master.zip

**Comment by burnash** [comment]
In your code I can see

~~~python
client = gspread.login(username, password)
~~~

username / password login is no longer supported by Google. This is the source of your problem. Use oAuth2 instead. Refer to this guide for the details:

http://gspread.readthedocs.org/en/latest/oauth2.html
