### ISSUE TITLE
AttributeError: 'HTTPError' object has no attribute 'code'

### ISSUE THREAD

**Issue by tjanez** [burnash/gspread#252]
Hi!

I'm having a problem using `gspread`.

Here are the steps to reproduce the problem:

```bash
tadej@biobash-pc:~# pip freeze | grep gspread
gspread==0.2.4
tadej@biobash-pc:~# python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gspread
>>> gspread.login('<removed>', '<removed>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 313, in login
    client.login()
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 106, in login
    if ex.code == 403:
AttributeError: 'HTTPError' object has no attribute 'code'
>>> 
```

**Comment by burnash** [comment]
Thanks for the detailed issue description. This should be a true example of a proper issue report. :)

1. You have an old version of gspread. As of today the latest is 0.2.5. Please update.
2. The gspread.login is no longer available. [Google has disabled the API for email/password authorization](https://developers.google.com/identity/protocols/AuthForInstalledApps) if favor of oAuth2 authorization method. Check [the docs](gspread.readthedocs.org/en/latest/oauth2.html) on how to use oAuth2 to log in

**Comment by tjanez** [comment]
@burnash, thanks for a very quick reply!

I followed your instructions and started using OAuth2. Thanks!

I'm closing this issue.
