### ISSUE TITLE
Unable to open the sheet.

### ISSUE THREAD

**Issue by Shiva-Shinde** [burnash/gspread#256]
Code runs perfectly fine with no errors etc. But it is unable to open the sheet. Please refer the code below. Unable to figure whats wrong here. Thanks!

    import os
    import ast
    import requests, gspread
    from oauth2client.client import SignedJwtAssertionCredentials
    def authenticate_google_docs():
        f = file(os.path.join('Shiva-c1c5516ecf00.p12'), 'rb')
        SIGNED_KEY = f.read()
        f.close()
        scope = ['https://spreadsheets.google.com/feeds', 'https://docs.google.com/feeds']
        credentials = SignedJwtAssertionCredentials('x@gmail.com', SIGNED_KEY, scope)
        data = {
            'refresh_token' : '241/ZLTD2DyOdiFJkN37mOZnmV-LtRu8wxY97o8Wn-nBkM4',
            'client_id' : '2434760852908-5vi7v8ebilde26mvlran6ike982ovuhs.apps.googleusercontent.com', 
            'client_secret' : '24EDI-HPmWBjvoTlm_NzJkcBmp',
            'grant_type' : 'refresh_token',
                  }
        r = requests.post('https://accounts.google.com/o/oauth2/token', data = data)
        credentials.access_token = ast.literal_eval(r.text)['access_token']
        gc = gspread.authorize(credentials)
        return gc
    gc = authenticate_google_docs()
    sh = gc.open("Hero")

I tried sh=gc.open("Hero").sheet1 (didn't work either)

**Comment by burnash** [comment]
What is your Python version? Did you share your spreadsheet with the email in json as the docs says?

Also, try using the code from the docs: http://gspread.readthedocs.org/en/latest/oauth2.html

Side note: please use code formatting in your markdown. It's not easy to read python without spaces. 
Check [GitHub's markdown reference](https://guides.github.com/features/mastering-markdown/).

**Comment by Shiva-Shinde** [comment]
Hi burnash,

I did share the client_email of my JSON file. 

print(sys.version)
2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]

I tried 2 ways using .p12 file & .JSON file. I have pasted the .p12 file code here in this issue. I have even tried .JSON one (http://gspread.readthedocs.org/en/latest/oauth2.html) you are pointing at. I am having same problem, code is working fine but I am unable to open the sheet. Thanks!!

**Comment by burnash** [comment]
No, you should be able to run it with 2.7.6 without any problem. Do you see any other spreadsheets?

Try to run `gc. openall()` after you logged in and check the returned value.

**Comment by Shiva-Shinde** [comment]
Running fine but not opening the sheet.  
   
    import json
    import gspread
    from oauth2client.client import SignedJwtAssertionCredentials
    json_key = json.load(open('Santa-05bfb3bd2059.json'))
    scope = ['https://spreadsheets.google.com/feeds']
    try:
        credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)
    except TypeError:
        credentials = SignedJwtAssertionCredentials(json_key['client_email'], bytes(json_key['private_key'], 'utf-8'), scope)
        credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)

    gc = gspread.authorize(credentials)

    sh = gc.openall()

**Comment by burnash** [comment]
What is a value of `sh`?

**Comment by Shiva-Shinde** [comment]
Not sure, whats the value. I think, its an object which holds gc.open("some worksheet name"). Please correct me if I am wrong!!

**Comment by burnash** [comment]
`openall` returns an array. I'm trying to find a source of the problem. 

Try to do a `print sh` in your code above after you have `sh = gc.openall()` or do a `print gc.openall()` and  post the output.

**Comment by Shiva-Shinde** [comment]
Thanks a ton. This the output!!
[<gspread.models.Spreadsheet object at 0x10d970490>, <gspread.models.Spreadsheet object at 0x10d9704d0>]

**Comment by burnash** [comment]
This looks like gspread has fetched 2 spreadsheets, and your authorization is working properly. You can go further and print titles of these spreadsheets:

~~~python
for s in gc.openall():
    print s.title
~~~

The output will tell you what spreadsheets you have access to.

**Comment by Shiva-Shinde** [comment]
Awesome. Exactly, when it can print why its unable to open?

[<gspread.models.Spreadsheet object at 0x103185490>, <gspread.models.Spreadsheet object at 0x1031854d0>]
New Metrics NuoDB
Hero

**Comment by burnash** [comment]
This is strange. Try with your "New Metrics".

After you do `sh = gc.open("Hero")` (or "New Metrics"), run `print sh.worksheets()`

**Comment by Shiva-Shinde** [comment]
Yeah, I read so many docs regarding this, run different scripts. I have no idea why is this happening. Is it more of http related one? unable to open a sheet because of http or what?
This is the output for what you said. Once again, thanks for your time.    
    [<gspread.models.Spreadsheet object at 0x101dbd490>, <gspread.models.Spreadsheet object at 0x101dbd4d0>]

New Metrics 
Hero
[<Worksheet 'Sheet1' id:od6>]

**Comment by burnash** [comment]
~~~python
[<Worksheet 'Sheet1' id:od6>]
~~~

This means that you do have a worksheet.

**Comment by Shiva-Shinde** [comment]
I am almost end of the road, but for some reason I am stuck. Its not working for some strange reason, Any alternatives to authorize, create & print something into Google Sheets other than GSpread?.

**Comment by burnash** [comment]
I don't really understand why you're saying that you stuck. You have your worksheet object, just proceed with the docs and call the required methods on it. That's about it.

GData is an alternative Python client library from Google: https://github.com/google/gdata-python-client

**Comment by Shiva-Shinde** [comment]
Its working now. Thanks a ton @burnash. gc.open() didn't work at that point, now working fine. :+1:

**Comment by arulmr** [comment]
@Shiva-Shinde If your issue is resolved, please close this issue.
