### ISSUE TITLE
AttributeError: 'HTTPError' object has no attribute 'code' when looping?

### ISSUE THREAD

**Issue by fmarquezg** [burnash/gspread#257]
I'm running gspread on Python 2.7. I connect to my spreadsheets and update cells however I will get the following error randomly (as in if I rerun my script a few times I will eventually get it to finish, and the error doesn't show at the same position in the loop)

The command I use is :
for i in list:
  sheet.update_cell(row, i )

And the error message is the following:
#####################
Traceback (most recent call last):
  File "test.py", line 68, in <module>
    sht2.update_cell(row,3,i[2])
  File "/usr/local/lib/python2.7/dist-packages/gspread/models.py", line 445, in update_cell
    self.client.put_feed(uri, ElementTree.tostring(feed))
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 282, in put_feed
    if ex.code == 403:
AttributeError: 'HTTPError' object has no attribute 'code'
########################

My guess is that I'm disconnecting from the spreadsheet?

**Comment by stanzheng** [comment]
I've gotten this error from when I run out of space in row/columns on my sheet. Have you tried adding extra row/columns and checking what cell youre trying to update.

**Comment by Minji57** [comment]
Check your row size. I had this error because row length is out of range

**Comment by rv816** [comment]
I get the same error -- row/col is correct. I'm able to get the cell using acell or cell, but not update.

**Comment by NilsRG** [comment]
The problem is twofold. The first problem is that the HTTPError is returned as a string, not an error object. Thus it has no attribute "code". Try adding a "print ex" just after the "except HTTPError as ex:" line in client.py.

That should give you an idea of what is triggering the HTTPError in the first place.

**Comment by dundeemt** [comment]
I am seeing the same error but only intermittently:

```python
  File "/home/jlh/Projects/gdocaad/src/gss.py", line 76, in update_cell
    
  File "/home/jlh/Projects/gdocaad/local/lib/python2.7/site-packages/gspread/models.py", line 445, in update_cell
    self.client.put_feed(uri, ElementTree.tostring(feed))
  File "/home/jlh/Projects/gdocaad/local/lib/python2.7/site-packages/gspread/client.py", line 282, in put_feed
    if ex.code == 403:
AttributeError: 'HTTPError' object has no attribute 'code'
```
