### ISSUE TITLE
How to pass a list of hash/dict to the new google spreadsheets ?  

### ISSUE THREAD

**Issue by vincegoyal** [burnash/gspread#258]
How to do it such that the dicts get added to the new empty rows above the already filled rows? insert_row seems to be only taking a list or a list of list, but with list of dicts, it gives exception error., adds empty rows only and outputs 0 on the command prompt.

**Comment by msuozzo** [comment]
The elements of the list must either be strings or numeric types. You need to cast the dictionaries to strings.
