### ISSUE TITLE
Python 2.7.5 issue

### ISSUE THREAD

**Issue by petulla** [burnash/gspread#259]
Hi

I'm having an issue on my implementation where Gspread cannot load sheets. Is there a minimum Py version? 2.7.5 is failing for me. 2.7.8 seems OK.

**Comment by burnash** [comment]
What error are you getting? Can you post traceback? It should work fine with 2.7.* as well as with 2.6.*

**Comment by petulla** [comment]
My script works fine on several of my computers. On one with Python 2.7.5 I throw this error:

```Traceback (most recent call last):
  File "scrape_google.py", line 8, in <module>
    json_key = json.load(open('{{my key}}'))
IOError: [Errno 2] No such file or directory: '{{my key}}'```

**Comment by burnash** [comment]
This indicates that you don't have the file `{{my key}}`. It looks like it has nothing to do with gspread.

**Comment by petulla** [comment]
@burnash The same script works perfectly on other machines with no changes.

**Comment by burnash** [comment]
Double check if you have `{{my key}}` on this machine.

**Comment by petulla** [comment]
Really embarrassing. Thanks.

**Comment by Shiva-Shinde** [comment]
Hi @petulla  I am working on GSpread, Python 2.75, GSpread works absolutely fine on 2.75.
