### ISSUE TITLE
Memory leak in find and findAll

### ISSUE THREAD

**Issue by barroca** [burnash/gspread#261]
Sorry about the lack of example, but I've noticed that the functions find and findAll take too long to execute an might have some memory leak, since it's causing the process to be killed when running on low memory environment.

i had this code:

```
    date_query = date_to_run.strftime("%d/%m/%Y")
    cell_list = wks.findall(date_query)
    if len(cell_list) > 0:
        print "Please remove data for {} from spreadsheet before running, we can't update data".format(date_query)
        return
```

Used to check if the script had runned before. The process is beeing killed for too much memory usage. 

I've changed for:

```
    date_query = date_to_run.strftime("%d/%m/%Y")
    cell_list = wks.find(date_query)
```

To check if it works, but the same behaviour happens. 
My spreadsheet has 9 columns and 21000 rows.

**Comment by TimmyCarbone** [comment]
+1

**Comment by burnash** [comment]
@barroca @TimmyCarbone do you still experience the issue? Could you try to upgrade to the latest version of the library and test?

It's an old issue so I'm closing it for now. Feel free to reopen it.

**Comment by barroca** [comment]
man this is old... :) 

If I experience this again I let you know, but for now I'm not using gspread anymore..

Thank you

**Comment by TimmyCarbone** [comment]
Same as above!

Thanks :)
