### ISSUE TITLE
Frequent connection breaks with spreadsheet clients

### ISSUE THREAD

**Issue by sr-murthy** [burnash/gspread#262]
I have a script which does a daily update of a spreadsheet with multiple worksheets, using OAuth 2.0 credentials.  Getting an authenticated client is done using `gspread.authorize()`, and then `insert_row()` of worksheet objects to do the insert.  But I've noticed that if I replace with the authentication method with `Client()` (and the appropriate OAuth 2.0 credentials object as argument) then `insert_row` almost always fails because the client does not get any spreadsheets - so `openall()` shows an empty list if I use `gspread.Client()` instead of `gspread.authorize()`.

Is this a known issue?

Also, even when I use `gspread.authorize()` I notice that almost every time, within a few minutes of getting a worksheet and calling its methods, I have re-acquire the connection because it breaks.  Here is some code I use to get the spreadsheet:

    OAuth2_credentials = SignedJwtAssertionCredentials(
        OAuth2_JSON_key['client_email'],
        OAuth2_JSON_key['private_key'],
        OAuth2_JSON_key['client_auth_scope']
    )

    def acquire_connection(OAuth2_credentials):
        spreadsheet_client = gspread.authorize(OAuth2_credentials)
        spreadsheet_client.session.headers['Connection'] = 'Keep-Alive'

    def get_spreadsheet(spreadsheet_key):
        spreadsheet = spreadsheet_client.open_by_key(spreadsheet_key)

I have now put these in a utility method that can be called on demand, whenever the connection breaks, using a "try twice" method to call worksheet methods.

    spreadsheet_client = None
    spreadsheet = None

    def try_by_reacquiring(func, *args, **kwargs):
        try:
            return func(*args, **kwargs)
        except:
            spreadsheet_client = acquire_connection(OAuth2_credentials)
            spreadsheet_key = OAuth2_credentials['spreadsheet_key']
            spreadsheet = get_spreadsheet(spreadsheet_key)
            return func(*args, **kwargs)

This makes the code slower than it should be - each time I have to call some method on the worksheet I cannot be sure that the connection still exists and I have to re-acquire the connection.  Here's the traceback from when I call the worksheet method `row_values()` after say 5-6 minutes after getting the spreadsheet client and spreadsheet:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "gspread/models.py", line 404, in row_values
    lambda cell: cell.row == row)
      File "gspread/models.py", line 381, in _list_values
    cells_list = self._fetch_cells()
      File "gspread/models.py", line 226, in _fetch_cells
    feed = self.client.get_cells_feed(self)
      File "gspread/client.py", line 250, in get_cells_feed
    r = self.session.get(url)
      File "gspread/httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
      File "gspread/httpsession.py", line 71, in request
    uri.scheme + uri.netloc].request(method, url, data, headers=request_headers)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
        self.putrequest(method, url, **skips)
          File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
        raise CannotSendRequest()
    httplib.CannotSendRequest

There must be a better way of improving the gspread `Client` code to ensure that it manages the HTTP session and connection better.

**Comment by ianawilson** [comment]
I also have frequent connection breaks -- need to reacquire the connection to avoid it.

**Comment by longhotsummer** [comment]
I have the same issue. Basically, you can't cache gspread's client, you should re-create it every time you want to use it, which is a bit frustrating.

An idea would for gspread to re-create a new connection with every request and not re-use the same connection. eg. lean on `requests` to handle the connection details and just use `requests.get`

**Comment by msuozzo** [comment]
Added #302 to address this.
