### ISSUE TITLE
newline chars lost during cell update

### ISSUE THREAD

**Issue by klaszlo** [burnash/gspread#27]
Hi,

worksheet.update_cells(cell) does not update the cells correctly.
All newline chars in the cell get erased. So if you have a multiline entry in your table's cell, and you retrieve it with gspread and save it back, the multiline cell transformed into a single line.

This is rather annoying bug for me, that is the only one preventing me using gspread daily.

Best,
 Laszlo

**Comment by shahar-agile** [comment]
So... what's the secret solution ?
Out of the box, right now, running   "gspread.update(cells)"  ignores all newlines \n & tabs \t

**Comment by burnash** [comment]
@shahar-agile could you post an example of the code you're using to update cells?

**Comment by shahar-agile** [comment]
from gspread.models import Cell
cell = Cell(row=2, col=3 value='hello')
sheet.update_cells(cells)

**Comment by burnash** [comment]
@shahar-agile could you describe the issue you're having with this code? It looks like there are no newlines.
