### ISSUE TITLE
gspread.exceptions. HTTPError: 500:

### ISSUE THREAD

**Issue by ShivaShinde** [burnash/gspread#272]
Anybody facing this error? How to catch this exception? and re-run the script?. One of the reasons for this exception, I guess, processing heavy data from Spreadsheets into Google servers and getting back from them.

Stack Trace:

   ```
 Traceback (most recent call last):
      File "range.py", line 57, in <module>
        worksheet.insert_row(no_of_bugs_weekly, 2) 
      File "/Users/ssindhe/Downloads/gspread/gspread/models.py", line 603, in insert_column
        newcell = self.cell(c, col + (index - 1))
      File "/Users/ssindhe/Downloads/gspread/gspread/models.py", line 324, in cell
        self._cell_addr(row, col))
      File "/Users/ssindhe/Downloads/gspread/gspread/client.py", line 271, in get_cells_cell_id_feed
        r = self.session.get(url)
      File "/Users/ssindhe/Downloads/gspread/gspread/httpsession.py", line 79, in get
        return self.request('GET', url, **kwargs)
      File "/Users/ssindhe/Downloads/gspread/gspread/httpsession.py", line 75, in request
        raise HTTPError("%s: %s" % (response.status, response.read()))
        gspread.exceptions.HTTPError: 500: 
   <!DOCTYPE html><html lang="en" ><head><meta        name="description" content="Web word processing, presentations and spreadsheets"><link rel="shortcut icon" href="//ssl.gstatic.com/docs/common/drive_favicon1.ico"><title>Google Drive Error</title><link href="//fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet" type="text/css"><style>/* Copyright 2015 Google Inc. All Rights Reserved. */
.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}#drive-logo{color:#91959c;font-family:"Open Sans",Arial,sans-serif;font-size:27px;font-weight:300;position:absolute;text-shadow:0 1px 1px white;white-space:nowrap}#drive-logo img{padding:0 0.4em 0 0;position:relative;top:2px;vertical-align:middle}#drive-logo a{color:#91959c;text-decoration:none}#drive-logo span.goog-inline-block{margin-top:2px;vertical-align:top}</style><style type="text/css">body {background-color: #fff; font-family: Arial,sans-serif; font-size: 13px; margin: 0; padding: 0;}a, a:link, a:visited {color: #112ABB;}</style><style type="text/css">.errorMessage {font-size: 12pt; font-weight: bold; line-height: 150%;}</style></head><body><div style="margin: auto; max-width: 750px;"><div style="margin: 80px 40px 20px 40px; position:relative; "><div style="position: absolute; top: -80px;"><h1 id="drive-logo"><a href="/"><img src="//www.google.com/images/logos/google_logo_41.png" width="116" height="41" alt="Google logo" ><span class="goog-inline-block">Drive</span></a></h1></div><p style="padding-top: 15px">Google Docs encountered an error. Please try reloading this page, or coming back to it in a few    minutes.</p><p>To learn more about the Google Docs editors, please visit our <a href="https://support.google.com/docs/?hl=en_US&p=error_help" target="_blank">help center</a>.</p><p><br><b>We're sorry for the inconvenience.</b><br><i>- The Google Docs Team</i></p></div></div></body></html> 
```

**Comment by msuozzo** [comment]
Do you have any other context (past issues, code snippets) that you could share?

**Comment by ShivaShinde** [comment]
@msuozzo thanks a lot. Its hapenning on a big sheet with 120 columns * 100 rows. So, I made my sheet shorter. Now, it works absolutely fine. So, I guess the problem is not with the script?

This could be because Google's servers unable to process such huge data, raising <strong>500: Internal Server Error</strong>. I don't think we can do anything about this. I would be happy, if you still have something to offer, in terms solving this issue.

**Comment by msuozzo** [comment]
Hmm. Strange. It may have been an API hiccup. Regardless, glad everything's working. If the problem recurs, this issue can be re-opened but until then, everything seems to be in order.

**Comment by ustroetz** [comment]
I am encountering the same issue. I just retry after a few seconds
```           
try:
    request ...
except gspread.exceptions.HTTPError:
    logging.warning("Cannot access Google Drive. Retry one more time in 10 seconds to access it.")
    time.sleep(10)
    request ...
```

**Comment by Abner1990** [comment]
gspread.exceptions.HTTPError: 500: This server no longer owns the lock of D$632936858023.69513257854

**Comment by nedcrest** [comment]
Hi there guys! I do have the same issue as @Abner1990 

> gspread.exceptions.HTTPError: 500: This server no longer owns the lock of D$XXXXXXXXXXXX.XXXXXXXXXXXX

Can somebody explain why this exception is raising? Can it be the matter of some kind of timeout issue?

**Comment by Syed-SnapLogic** [comment]
Guys, I encountered the same error today as @nedcrest and @Abner1990 .  Any solution/workaround found for this so far?

**Comment by rustanacexd** [comment]
same here

**Comment by benquike** [comment]
same here

**Comment by KrystianAparta** [comment]
Same here.

**Comment by rich7** [comment]
I think this is an error you get when your connection with Google spreadsheet is lost. Like a time out. You can only be so long (60 min or so) connected with Google. Otherwise you need to connect again. For me a reboot always work to get things work again. I'm looking now for a better solution, but since I saw so many suffer from this, I wanted to share this already

**Comment by RedRyan111** [comment]
I fixed this is jupyter notebook by restarting the kernel and running all.
