### ISSUE TITLE
'Spreadsheet' object has no attribute 'get_all_values'

### ISSUE THREAD

**Issue by jaysig** [burnash/gspread#273]
I am having an issues with get_all_values()
```javascript
import json
import gspread
from oauth2client.client import SignedJwtAssertionCredentials
from gmail_variables import *

json_key = json.load(open('key7367.json'))
scope = ['https://spreadsheets.google.com/feeds']

credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)

gc = gspread.authorize(credentials)


wks = gc.open_by_url('https://docs.google.com/a/test.com/spreadsheets/d/1-cAg..sLt5Ho/edit?usp=sharing')

recipients = wks.get_all_values()
```
I am trying to write an email program and when I try to run it; I get the error. 
'Spreadsheet' object has no attribute 'get_all_values'

Any help is appreciated.

**Comment by airween** [comment]
(I'm new in gspread)

Looks like you had to want to open a spreadsheet, instead of worksheet IN A spreadsheet.

Try this:
```python
spr = gc.open_by_url('https://docs.google.com/a/test.com/spreadsheets/d/1-cAg..sLt5Ho/edit?usp=sharing')
wks = spr.worksheet('Worksheet1')  # or the correct name of requested worksheet
```
Hope this help.

**Comment by AndreasHassing** [comment]
Like @airween said, you're running `get_all_values()` on a Spreadsheet and not on a Worksheet as intended. Simply run something like:

```python
spr = gc.open_by_url('https://docs.google.com/a/test.com/spreadsheets/d/1-cAg..sLt5Ho/edit?usp=sharing')

recipients = spr.sheet1.get_all_values()
```

`sheet1` is a shortcut for getting the first sheet: https://gspread.readthedocs.org/en/latest/#gspread.Spreadsheet.sheet1

**Comment by Sur2801** [comment]
@AndreasHassing 
Thanks a lot for solving such error.
