### ISSUE TITLE
Spreadsheet not found issue

### ISSUE THREAD

**Issue by deepakag123** [burnash/gspread#277]
Sorry If I am doing something wrong here . I am unable to open any spreadsheet - tried using name, key and url
/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/deepakambattu/PycharmProjects/untitled/test
Traceback (most recent call last):
  File "/Users/deepakambattu/PycharmProjects/untitled/test", line 13, in <module>
    wks = gc.open('test')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gspread/client.py", line 150, in open
    raise SpreadsheetNotFound
gspread.exceptions.SpreadsheetNotFound

my code

import json
import gspread
from oauth2client.client import SignedJwtAssertionCredentials

json_key = json.load(open('json.txt'))
scope = ['https://spreadsheets.google.com/feeds']

credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)

gc = gspread.authorize(credentials)

wks = gc.open('test')

Is there a known issue in accessing the spreadsheets?

**Comment by ShivaShinde** [comment]
json_key = json.load(open('json.txt'))

@deepakag123 your json file should have .json extension not .txt.

**Comment by rybo449** [comment]
@ShivaShinde I'm having the same issue as @deepakag123 
```
    json_key = json.load(open(abspath(join(abspath(eliot.settings.__file__), "..", "..", "data", "client_secrets.json"))))
    scope = ['https://spreadsheets.google.com/feeds']
    credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)
    gc = gspread.authorize(credentials)
    sh1 = gc.open()
```
It turns out that my drive is empty. Is there a way to find out if you are connected to the right drive?
Thanks a lot!

**Comment by ShivaShinde** [comment]
@rybo449 by drive, you mean google drive (sheet) right?

    sh1 = gc.open()

where is the name of the sheet here? 

wks = gc.open('test') will not open the sheet for you physically, like a window popping out. 

When you run gc.open('title'), you are essentially, connected to your spreadsheet using this script, it just means connection open (). Now, you can play aroung by adding what ever data you want to add. Only, after adding some data you can see, your cells in spreadsheet populating something like a 'popcorn'. Till then, nothing can be seen.

**Comment by rybo449** [comment]
@ShivaShinde Thanks for replying so fast. I figured out the issue. I had to share the spreadsheets with my `client_address` which did not contain any spreadsheets. Now it works like a charm :)

**Comment by chrisspen** [comment]
I'm also getting this error. I followed the steps in the [oauth docs](http://gspread.readthedocs.org/en/latest/oauth2.html) for enabling Drive API access, and my script can login just fine, but trying to retrieve any spreadsheet by title or key throws a SpreadsheetNotFound exception.

@rybo449  What do you mean you had to share it with your "client_address"? You mean your literally IP address? Google Drive doesn't support sharing to specific IP addresses.

**Comment by tacy** [comment]
@chrisspen   json_key['client_email']

**Comment by msuozzo** [comment]
It seems as if this issue has been resolved. Anyone have objections to it being closed?

**Comment by ibushong** [comment]
I also ran into this issue, and sharing the sheet with the client_email also solved it.

This should be added to the README as it's not obvious.

**Comment by burnash** [comment]
@ibushong It's in the guide already (see right before the [Troubleshooting](http://gspread.readthedocs.org/en/latest/oauth2.html#troubleshooting) section.) What do you think is a better way to put it?

**Comment by ibushong** [comment]
Wow. My mistake. Totally missed that!

**Comment by Arjay7891** [comment]
hah I also totally missed this and just spend an hour searching for the solution!
burnash, I don't think it's a matter of the choice of words, it's probably more that everybody stops reading after the "If using oauth2client < 2.0.0" disclaimer.

could be good to highlight step 7 more by putting it before the "If using oauth2client < 2.0.0" with an "IMPORTANT!!!!!" disclaimer or something, it's quite easy to miss right now

**Comment by physicsistic** [comment]
Understand that the issue is closed, but want to echo the above comment by @Arjay7891, can we change the documentation for point #7 to be in the troubleshooting section or something so that it is not so easy to overlook?

**Comment by vallettea** [comment]
Also missed it and lost two hours. Should be mentioned in the readme.

**Comment by s3afroze** [comment]
The documentation is very well written. I will see if I can update this because I was stuck on that issue as well and apparently many people new to the library have the same experience.

Share the file using the email in your token.

If this does not work, there might be a problem with the name(my experience)

The name of the file should match up with what you in gc.open(file) and not the sheet name for instance.
