### ISSUE TITLE
get_worksheets_feed hangs forever?

### ISSUE THREAD

**Issue by Ralithune** [burnash/gspread#278]
I think Google Spreadsheets API may be down right now.  Is there a quick way to tell?

Gspread isn't able to return any worksheets for me.

**Comment by jnozsc** [comment]
same issue here, can open a spreadsheet, but all of get_worksheet functions fail

**Comment by jacobabennett** [comment]
Having the same issue here. Started around an hour ago.

**Comment by tekromancr** [comment]
I am also having this issue

**Comment by seansli** [comment]
Same - sounds like it's an API issue, but no red lights on any of the dashboards.

**Comment by Ralithune** [comment]
It started around 2 hours ago for me jacobabennett.  I'm having to write workarounds in all my utilities since production can't handle down time like this.

**Comment by cheeseinvert** [comment]
Also seeing the same issue but we already fall back to a cached copy of the spreadsheet so we are ok for now

**Comment by creade** [comment]
Someone from tabletop opened this: https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?id=3939

**Comment by felixpelletier23** [comment]
Same here. It was working 2-3 hours ago.

**Comment by Wu4m4n** [comment]
The same here!

**Comment by Wu4m4n** [comment]
Now is solved!

**Comment by tekromancr** [comment]
Yes. This was solved around 5 EST yesterday. Things seem pretty shiny now!

**Comment by msuozzo** [comment]
Everything seems to have been resolved. Should this issue remain open?

**Comment by seansli** [comment]
Nope - looks like it was an API issue on Google's part; good to close.
