### ISSUE TITLE
Change cell's background color

### ISSUE THREAD

**Issue by klaszlo** [burnash/gspread#28]
Is it possible to change a cell's background color?

I made a workaround, I upload the rows with the color as text in the first column, then I wrote/adapted a 
serverside (they call google apps script) script to change from text to color, and an another one from color back to text.

Now when I modify a row's color, I always run this little helper script. The problem with this solution, 
that google's scripts are awesomely slow, a 400 rows table takes approximately 3 minutes to be finished.
And also it is still manual work. (and I need to remember who modified the table last the user or the program).

If I could somehow modify the background color using gspread, I would immediately switch to it.

On the serverside script, I use these methods (if it is any help):
  var range = SpreadsheetApp.getActiveSheet().getDataRange();
  range.setBackgroundColor("#ff0000");

I can post the full serverside script, if it helps. I dont mind to share at all.

Best, 
 Laszlo

**Comment by shvechikov** [comment]
@burnash Could you please show your experimental code. Is it possible to read/change cell styles? It there some undocumented API for that? Thanks!

**Comment by burnash** [comment]
@shvechikov I'd love to, but I discarded the code long ago (sorry.) @archeg has a way more [advanced example](https://gist.github.com/archeg/5652752) in his gist. This is an old undocumented stuff so I'm not sure if it still works. If it does work, you can try to peek at a [node-spreadsheets action9.js way of using the API](https://github.com/EastCloud/node-spreadsheets/blob/master/lib/spreadsheets/action9.js#L25) and apply it to @archeg's script. 

Good luck, and please share your findings.
