### ISSUE TITLE
gspread.exceptions.SpreadsheetNotFound in previously working code.

### ISSUE THREAD

**Issue by infamy** [burnash/gspread#282]
I have code that connects into a spreadsheet that about 4-5 days ago started tossing a spreadsheet not found. Everything is setup and was working for months before this happen. 

Oauth2 was put in place a few month back without issues.

Email from the 0auth account is setup as shared.

Anyone else experience this recently?

**Comment by picoding** [comment]
Hi,

Maybe it is related with my issue: https://github.com/burnash/gspread/issues/233

or 

Issue with request package: http://www.indjango.com/access-google-sheets-in-python-using-gspread/#comment-2079691404

**Comment by infamy** [comment]
I solved this yesterday. Seems a change with google for my domain and access control.

If you have doc created on a non gmail account, and share it to a gmail account, the share to the Oauth api account seems to not work.

Closing, but this is either a gspread issue, or a google issue. Unknown at this time.
