### ISSUE TITLE
Slow Retrieval of Records

### ISSUE THREAD

**Issue by joshglenn** [burnash/gspread#285]
Just using gspread for the first time in a django project. Got everything installed, and functioning, but veeeerrrrryyy slowly. To run the following code, it takes 40 seconds. And I'm only returning one row from a spreadsheet.

```
    gc = authenticate_google_docs()
    sh = gc.open_by_key('spreadsheet-key-here') 
    worksheet = sh.worksheet("spreadsheet_title") 
    row1values = worksheet.row_values(1)
    print row1values
```

Any idea why?

Could it have anything to do with this message that I am receiving? :

```
 InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```
Did I ask this question in the right place?

**Comment by msuozzo** [comment]
1) Installing `pycrypto` may get rid of these errors. It worked for me in the past but I haven't tried it in a while.
2) How large is the spreadsheet you're loading? The current implementation of `Worksheet.row_values` fetches all values from the worksheet (maybe not the best choice but that's the state of things). One workaround would be to use `Worksheet.range` with the following snippet:
```python
def get_row(row_ind):
  start_cell = wks.get_addr_int(row_ind, 1)
  end_cell = wks.get_addr_int(row_ind, wks.col_count)
  row_cells = wks.range("%s:%s" % (start_cell, end_cell))
  return [cell.value for cell in row_cells]
print get_row(1)
```

Let me know if either of those solutions work.
