### ISSUE TITLE
How to Update Data Retrieved from get_all_records()

### ISSUE THREAD

**Issue by joshglenn** [burnash/gspread#290]
The get_all_records() function returns a list with dictionary items for each row in my spreadsheet. That much is working fine. I can edit the values in the dictionaries no problem. But how to I update my spreadsheet with the new data after editing the dictionary entries? I'm looking for something like this:

```
     sheet = worksheet.get_all_records()
     for dict_obj in sheet:
        dict_obj['somekey'] = 'new value'
     update_records_from_list_of_dictionaries(sheet)
```

Any ideas? Am I going about things the wrong way?

**Comment by msuozzo** [comment]
Check out the [Update Cells](https://github.com/burnash/gspread#updating-cells) section of the docs first.

Working with `Cell` objects is likely the best way of performing bulk updates as the `update_cells` call uses just 1 API call (so 1 HTTP roundtrip) as opposed to looping through cells and using `update_cell` or `update_acell`.

Getting `Cell` objects _en masse_ is not as straightforward as it could be. The best way of doing so is using the `range` function and providing the range of the entire sheet (which you must calculate yourself :/). Check out `get_addr_int` to convert row/col coordinates to the format used to define ranges in Spreadsheets.
