### ISSUE TITLE
How to add a row in above

### ISSUE THREAD

**Issue by astritsinani** [burnash/gspread#292]
I am updating logs of a system , and till now I just can add data in the first row.
Worksheet.add_rows(1) is adding rows in the end of it.  I was reading on worksheet.resize but still not getting it. If you can help me with something strait forward? 
Like in gdata was 
response = gd_client.InsertRow(entry, spreadsheet_key, worksheet_id)

Thanks

**Comment by msuozzo** [comment]
Check out `Worksheet.insert_row`. To insert at the top of the spreadsheet, I believe the call is:
```python
sheet.insert_row(['these', 'are', 'my', 'cells'], index=1)
```

Let me know if that works for you. Cheers.
