### ISSUE TITLE
Allow programmatically sharing the sheet

### ISSUE THREAD

**Issue by limdauto** [burnash/gspread#293]
Thank you for this library. I have a quick question. Is there a way to programmatically share the spreadsheet with someone else?

**Comment by msuozzo** [comment]
This feature is supported by the Drive RESTful API. Gspread currently only wraps the Spreadsheets API but it is not inconceivable that this extension be made.

What workflow are you looking to solve with this?

There's a lot of work to do on this project in other areas, but this is an interesting addition and one that should be pursued.

**Comment by limdauto** [comment]
@msuozzo Oh sorry I forgot about this. I actually solved this problem and ofc you are right. This feature uses Drive API, not Spreadsheets API. It's great to hear you think this addition is worth pondering.

I write automation tool for the content team where I work. One use case is to be able to pull information out of the database, put it in a spreadsheet and share it with our content team. It's very easy to achieve with Google Drive API now that I know how to but it'd be nice to have it in gspread.

**Comment by msuozzo** [comment]
Thanks for the background. I'll see what I can do.

**Comment by burnash** [comment]
Added in #429, #386, v0.6.0
