### ISSUE TITLE
Token invalid - AuthSub token has wrong scope

### ISSUE THREAD

**Issue by ghost** [burnash/gspread#295]
I'm getting this error when I'm trying to open a spreadsheet. Can someone help me with this?

raise HTTPError("%s: %s" % (response.status, response.read()))
gspread.exceptions.HTTPError: 401: <HTML>
<HEAD>
<TITLE>Token invalid - AuthSub token has wrong scope</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">

<H1>Token invalid - AuthSub token has wrong scope</H1>

<H2>Error 401</H2>

</BODY>
</HTML>

Thanks :)

**Comment by danielemichilli** [comment]
I had the same problem, I'm writing general updated instructions to deal with the new OAuth2 credentials
@burnash you could add these to the readme. They recently changed the console.developers.google.com website and it's difficult to find updated instructions online.

1) Go to console.developers.google.com -> APIs & auth -> APIs -> Drive API -> Enable API
2) Credentials -> Add credentials -> Service account -> JSON -> Create
    This will download a .json file
3) Open the .json file with a text editor and copy the email address. 
    Open your sheet, go to Share and paste the email address and share with it.
4) Use the following lines:
  import json
  import gspread
  from oauth2client.client import SignedJwtAssertionCredentials
  json_key = json.load(open('NAME_OF_DOWNLOADED.json'))
  scope = ['https://spreadsheets.google.com/feeds']
  credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)
  gc = gspread.authorize(credentials)
  wks = gc.open("SHEET_NAME").sheet1
  
  wks is your sheet and its methods will modify it.
  Try:
  wks.append_row(['test1','row_appended'])
  This will append a row at the end of the sheet (usually a new sheet has 1000 void rows and therefore you need to scroll down to the 1001st to find it).

**Comment by msuozzo** [comment]
I believe this has been fixed as the images in the README appear to be consistent with the current dashboard (although there may soon be a new developers console so another update to the docs may be required).

Thanks @danielemichilli

**Comment by msuozzo** [comment]
On closer inspection, there are definitely some inconsistencies.

**Comment by vishalzanzrukia** [comment]
Thanks, it's working :)

**Comment by msuozzo** [comment]
Fantastic! Glad to here it.

I'm gonna leave this open as the documentation screenshots could use an update to the new Google Cloud interface.

**Comment by shouguolisc** [comment]
Any update? I'm seeing the same error when I use google credential
`credentials` = GoogleCredentials.get_application_default()`

I know my credential is good, since I can use the same credential to access other services like big query, etc.

**Comment by the1plummie** [comment]
Any update? I'm seeing the same error when I use google credential
`credentials = GoogleCredentials.get_application_default()`

I know my credential is good, since I can use the same credential to access other services like big query, etc.

**Comment by lgilz** [comment]
Apparently SignedJwtAssertionCredentials has been removed. 
Please refer to https://github.com/google/oauth2client/issues/401
and use `from oauth2client.service_account import ServiceAccountCredentials instead. `

**Comment by eanxgeek** [comment]
I'm writing a python program and running it against my spreadsheet, that is shared with "who ever has the link can ..." 

I have created a custom Service Account because I am not running this on any Google cloud offering, rather I'm running it from my own system.  

`
SCOPES = ['https://www.googleapis.com/auth/spreadsheets']
CRED = 'keyfile.json'
credentials = ServiceAccountCredentials.from_json_keyfile_name(CRED, scopes=SCOPES)
sheet_id = '....'
c = gspread.authorize(credentials)
c.open_by_id(sheet_id)
`

Results in 
> Traceback (most recent call last):
>   File "test_cred.py", line 14, in <module>
>     c.open_by_id(...)
>   File "/usr/lib/python2.7/site-packages/gspread/client.py", line 137, in open_by_url
>     return self.open_by_key(m2.group(1))
>   File "/usr/lib/python2.7/site-packages/gspread/client.py", line 102, in open_by_key
>     feed = self.get_spreadsheets_feed()
>   File "/usr/lib/python2.7/site-packages/gspread/client.py", line 165, in get_spreadsheets_feed
>     r = self.session.get(url)
>   File "/usr/lib/python2.7/site-packages/gspread/httpsession.py", line 76, in get
>     return self.request('GET', url, **kwargs)
>   File "/usr/lib/python2.7/site-packages/gspread/httpsession.py", line 72, in request
>     response.status_code, response.content))
> gspread.exceptions.HTTPError: 401: <HTML>
> <HEAD>
> <TITLE>Token invalid - AuthSub token has wrong scope</TITLE>
> </HEAD>
> <BODY BGCOLOR="#FFFFFF" TEXT="#000000">
> <H1>Token invalid - AuthSub token has wrong scope</H1>
> <H2>Error 401</H2>
> </BODY>

The custom service account has project owner privileges.  Further when I execute the google-api-python-client quickstart against this same spreadsheet it works, the only difference being a service account v. a Oauth Client ID.

**Comment by keliomer** [comment]
I'm not sure if public sheet access is supported. (Bump)
