### ISSUE TITLE
cell value is a hyperlink?

### ISSUE THREAD

**Issue by brendangree** [burnash/gspread#297]
Everything is working swimmingly after getting OAuth2 sorted out..  Thank you!

One question I have encountered is how to retrieve a hyperlink from a cell's value.  Several cells have values that are hyperlinks, yet the call to retrieve the value only results in the actual value, with no info about the underlying hyperlink.  I'm assuming that this is considered "formatting" and is not supported by the API, but I was wondering if someone could confirm that there is no way to retrieve this.  Thanks again!

**Comment by msuozzo** [comment]
I believe this is similar to #284. If I'm correct, I'll provide you with the gspread terminology that this issue concerns.

When you say "hyperlink" are you referring to a cell value of the form "=A1+B1"? If so, this called `cell.input_value` in gspread. On the bright side, this is absolutely supported by the API. On the not so bright side, many elementary functions in gspread don't modify cells using their `cell.input_value`s, but instead use `cell.value` which is the parsed form. However this behavior is not without some supporting logic. Many operations on the sheet would only break those links and result in garbage values (_e.g._ moving rows or columns).

There doesn't seem to be a plan to address this just yet (it requires some thought and likely some substantial changes to the API).

In any case, did I completely misunderstand your question?

**Comment by brendangree** [comment]
I am referring to when a cell has a value of `=HYPERLINK("https://www.google.com/some/link","An example value")` and yes, thank you, the `cell.input_value` attribute contains the url reference that I am seeking.  I guess this is an undocumented feature, as I didn't see it anywhere in the docs.  Might be good to include in the docs as I could see other people utilizing this.

Thank you!
