### ISSUE TITLE
Atomic Writes / Journaled Changes?

### ISSUE THREAD

**Issue by jkrauska** [burnash/gspread#303]
This could be done in application logic, but I felt it might also make sense in the tool itself.

I'd like to think about how one could make writes more 'atomic'.

Right now if a user is editing a doc while a script it trying to make changes, there's the possibility of edits being inconsistent.  (eg. user inserts a row, and then script updates the wrong row)

This could also presumably happen with concurrent scripts editing the doc.

I'd imagine one thing that would be helpful would be some sort of global lock to only allow one script to edit at a time.  (eg. a LOCKS worksheet, where a script requests a time window lock, and then confirms)

In the same vein, I'd imagine having a rolling journal of edits made by scripts (again perhaps contained on a new sub worksheet) might be handy to potentially revert bad edits.
eg. Edited cell A32 at time t, old data 'Foo', new data 'Foo', full row data .....

I'm certain others are more well versed in making distributed systems and would have other/better ideas.  Have you thought about these concerns?

**Comment by msuozzo** [comment]
Interesting proposal but I think this falls out of the scope of the project. My initial thought is that this is definitely not in the spirit of Spreadsheets' realtime editing thing. Any modification that takes place externally to your journal would essentially invalidate it.

If I had a system for which journaling was desirable, I would create another "source of truth," meaning a document only accessible by through your journaling scheme and periodically update a spreadsheet using gspread that mirrored the current document's contents.

This is in no way to discourage you from creating this. On the contrary: If you intend on starting a journaling-with-gspread project, please share it. I'd be happy to contribute.

**Comment by jkrauska** [comment]
I meant this less as a bug as a discussion/question.

I'm beginning to consider using gspread as the ONLY writer to a document, and just give humans 'read-only' access and more API driven changes.

Mostly my main gripe is every time I start doing cool things with gspread, a user interacts with a document and ruins it for me, so I'm trying to think up some better approaches..
