### ISSUE TITLE
something like get_all_values but returning cells? get_all_cells?

### ISSUE THREAD

**Issue by Kuzmin** [burnash/gspread#304]
The get_all_values method is awesome, but sometimes I want to be able to get everything in a matrix, update it, and then push it back up. I guess having the option to return the Cell instead of the string value of each cell would solve that.

Would you accept a PR for this? I could implement it by more-or-less parroting get_all_values

Thanks!

**Comment by burnash** [comment]
I certainly like the idea. An open question for me is the method name. This functionality seems to me quite generic. So a good name might be just `get_rows` or even `rows`. 

On the other hand I see the possibility of working with [list-based feeds](https://developers.google.com/google-apps/spreadsheets/data#work_with_list-based_feeds) via gspread in the future. That way, there should be a consistent naming between the two access methods.

@msuozzo what do you think?

**Comment by msuozzo** [comment]
`get_all_cells` feels like it goes along with the existing interface however I think adding more to `Worksheet` risks creating clutter. That being said, it is very simple to implement. The following should work:
```python
def get_all_cells(self):
  bottom_right = self.get_addr_int(self.row_count, self.col_count)
  return self.range('A1:%s' % bottom_right)
```

I haven't looked at list-based feeds that closely but sorting, querying, etc. on Google's side would be very efficient. #161 implements them and uses `Row` as a class. I'm not sure how well it fits with the simplicity of gspread but I definitely think `delete_row` is worthwhile.

**Comment by miklevin** [comment]
I second this. Has anyone cobbled this together by efficiently getting range boundaries (filtering out unexpected blanks) and translate it into a worksheet.range() call to get a cell_list back? Effectively the same thing. Thinking of coding that up now for my purposes, but thought I'd ask on this open feature request issue.

**Comment by lavigne958** [comment]
Hi, this result can be obtained by using the method `range()` with no range (empty string).

This is not documented and might not be expected.

I will open an issue to update the doc to include this example: `sheet.range(""): returns all cells of the sheet`
I might add extra things in the new issue like: add new method `get_all_cells` that will simply do the above method call but will be explicit.

Closing this issue.
