### ISSUE TITLE
Google API Error

### ISSUE THREAD

**Issue by jchalo99** [burnash/gspread#305]
I consider myself a novice in programming. I am working on an Access Log, for my Fire Department.
It is running on a Raspberry Pi. Debian Jessie. I will try to attach my code later (Raspberry Pi is in a remote location, and doesn't have FTP Setup yet.)

The Code is basic. Open Spreadsheet. Append Row With Program Started + The Date+Time. Every 5 seconds update Cell with "Uptime". When Door Is Opened, Append Row (different Sheet) with an "Index", "Date+Time", "Dialog", "Link To Picture". Dialog being what sensor tripped. Link To Picture being an imgur link showing what the camera took.
If Program Fail's I have it Appending a Row with "Program Failed" + "Date+Time" + a capture of the exception. Than Rebooting the RPI and it works again.

After just shy of an hour, I used to get errors. Fixed that by manually refreshing my token.

Now i get "('500: We&#39;re sorry, a server error occurred. Please wait a bit and try reloading your spreadsheet.',)" OR a longer version of the same. after a random amount of time (1 - 6 hours)

See Link for the Spreadsheet. With Error's. https://docs.google.com/spreadsheets/d/1e_TyPM3_mexy7UYfueWc_UaWOqrl0XqAtIdxX5-jRmE/edit?usp=sharing

**Comment by burnash** [comment]
I'm not sure, but I think there might be some certain limits in a number of API calls or update frequency. The code snippet you're using may shed some light as well so please share it.

**Comment by burnash** [comment]
Great project by the way.

**Comment by jchalo99** [comment]
Thank you,
I have included the code.... pretty much all of it. blanked out usernames and password type stuff i hope.

```python
#!/usr/bin/python
import pyimgur
import time
import picamera
import json
import gspread
import RPi.GPIO as GPIO
from oauth2client.client import SignedJwtAssertionCredentials
from subprocess import call
import sys

######## Begin gspread setup ########
#####################################

json_key = json.load(open('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.json'), stri$
scope = ['https://spreadsheets.google.com/feeds']
credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key[$

gc = gspread.authorize(credentials)

RPI_LOG = gc.open_by_url('xxxxxxxxxxxxxxxxxxx’)
worksheet_list = RPI_LOG.worksheets()
worksheet = RPI_LOG.worksheet("RPI_LOG")

###################################
######## End gspread setup ########
###################################

CLIENT_ID = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
im = pyimgur.Imgur(CLIENT_ID)

camera = picamera.PiCamera()
camera.vflip = True
camera.hflip = True

DoorPin = 23

GPIO.setmode(GPIO.BCM)
#GPIO.cleanup()

GPIO.setup(DoorPin, GPIO.IN, pull_up_down=GPIO.PUD_UP)

def Door_Opened(DoorPin):
        gc = gspread.authorize(credentials)
        RPI_LOG = gc.open_by_url('https://docs.google.com/spreadsheets/d/1e_TyP$
        worksheet = RPI_LOG.worksheet("RPI_LOG")
        now = time.strftime("%m/%d/%Y %H:%M:%S")
        now_pic = time.strftime("%Y%m%d-%H%M%S")
        print('Door Open')
        img_path = "/home/pi/Pictures/DOOR/" + now_pic + ".jpg"
        camera.capture(img_path)
        uploaded_image = im.upload_image(img_path, title=img_path)
        print(uploaded_image.link)
        all_data = worksheet.get_all_values()
        worksheet.append_row([len(all_data)+1,now,"DOOR Opened",uploaded_image.$

GPIO.add_event_detect(DoorPin, GPIO.RISING, callback= Door_Opened, bouncetime=2$

now = time.strftime("%m/%d/%Y %H:%M:%S")
worksheet = RPI_LOG.worksheet("Status")
all_data = worksheet.get_all_values()
worksheet.append_row([len(all_data)+1,now,"Program Started",""])
print "program started"
start_time = time.time()
try:
        while True:
                time.sleep(2)
                worksheet = RPI_LOG.worksheet("Status")
                worksheet.update_acell('A1', "Uptime: "+str(int(time.time()-sta$
                print("Still " + str(time.time()-start_time))
                if(time.time()-start_time)>3000:
                        credentials = SignedJwtAssertionCredentials(json_key['c$
                        gc = gspread.authorize(credentials)
                        RPI_LOG = gc.open_by_url('https://docs.google.com/sprea$
                        worksheet = RPI_LOG.worksheet("RPI_LOG")

except KeyboardInterrupt:
        e = sys.exc_info()[1]
        print "Program Closed"
        now = time.strftime("%m/%d/%Y %H:%M:%S")
        worksheet = RPI_LOG.worksheet("Status")
        all_data = worksheet.get_all_values()
        worksheet.update_acell('A1', 'Program Closed')
        worksheet.append_row([len(all_data)+1,now,"Program Closed",e.args])

except:
        e = sys.exc_info()[1]
        print "program failed"
        now = time.strftime("%m/%d/%Y %H:%M:%S")
        worksheet = RPI_LOG.worksheet("Status")
        all_data = worksheet.get_all_values()
        worksheet.update_acell('A1', 'Program Failed')
        worksheet.append_row([len(all_data)+1,now,"Program Failed",e.args])
        call(["sudo","reboot"])

finally:
        GPIO.cleanup()
```

**Comment by burnash** [comment]
Thanks for the code snippet. I still think that you may try to decrease the update frequency. I believe Google Sheets is not the best choice for reliable frequent writes.

**Comment by jchalo99** [comment]
I am thinking of getting rid of the "Uptime" it was only needed to see when
it failed. If I get rid of the uptime, the only time the sheet should be
updated is when program starts. Closes. Or fails. And when the door opens.

Than I should see less failures?

**Comment by burnash** [comment]
Might be. I don't have access to Google API server logs so the nature of those server errors is unknown to me. Your guess is as good as mine.

I suggest you to reduce the frequency of requests. However, keep the error log. Just use some alternative medium for it. [Logging can come in handy](https://pymotw.com/2/logging/) for that.

**Comment by jchalo99** [comment]
Thanks for the link. I'll check it out.

**Comment by jchalo99** [comment]
Increasing the "Sleep" time resulting in less API Calls has allowed an "uptime" of 2.5 days and counting. i am right now using a sleep time of 30 seconds. Thank You.

**Comment by msuozzo** [comment]
Fantastic! So glad to hear everything's going well. If the problem crops up again, don't hesitate to reach out.

Thanks for using gspread!
