### ISSUE TITLE
Detect API quota limitations and provide a helpful error

### ISSUE THREAD

**Issue by msuozzo** [burnash/gspread#314]
API quota limits have been reported on numerous occasions (_e.g._ https://github.com/burnash/gspread/issues/216#issuecomment-101727929, https://github.com/burnash/gspread/issues/305) and there is currently no clear indication of the root cause of the problem.

If possible, a helpful error message should be reported to the user.

**Comment by lavigne958** [comment]
I will have a look if the api can reply how many requests are left or if the return HTTP reponses contains any help.

**Comment by lavigne958** [comment]
Their are actual error codes returned from the HTTP call that the gspread could match but it will mean updating the error handling, keeping the `APIError` exception class but adding some paring in it that will extract that error message from the API.

**Comment by burnash** [comment]
Thanks for the link @lavigne958 I think we can now close this

**Comment by lavigne958** [comment]
@burnash perhaps you mixed this issue with issue: #722 ? 
This issue can be addresses, at least I can try to address it and try to improve the exception error handling from the requests to the google drive API.

**Comment by burnash** [comment]
@lavigne958 I'm not sure we need to address it now. The thing is, this issue predates API v4, and if I'm not mistaken since Sheets API got updated the quota error is very explicit. Here's what I get now when I'm running too many tests locally:

```
gspread.exceptions.APIError: {
    'code': 429, 
    'message': "Quota exceeded for quota group 'WriteGroup' and limit 'Write requests per user per 100 seconds' of service 'sheets.googleapis.com' for consumer 'project_number:XXXXXXXX'.", 
    'status': 'RESOURCE_EXHAUSTED', 
    'details': [{
        '@type': 'type.googleapis.com/google.rpc.Help', 
        'links': [{
            'description': 'Google developer console API key', 
            'url': 'https://console.developers.google.com/project/XXXXXXXX/apiui/credential'
        }]
    }]
}
```

Of course, one improvement is to raise a more specific exception in gspread. This could be useful. Are you interested in implementing this?

**Comment by lavigne958** [comment]
Yes I am, I will have a look on it.
