### ISSUE TITLE
Emphasize that the client_email should be shared with the spreadsheet

### ISSUE THREAD

**Issue by msuozzo** [burnash/gspread#315]
#185 and others have improperly carried out this part of the [OAuth2 instructions](http://gspread.readthedocs.org/en/latest/oauth2.html). This indicates that the instructions are not clear enough or need to be emphasized more.

I would recommend that a screenshot be added to draw attention to this step (it's the last step and can be missed).

**Comment by jcushman** [comment]
+1 -- I read the instructions twice and didn't figure out what I was doing wrong until I found this bug.

**Comment by JackRough** [comment]
I don't know about others, but what happened to me was that I assumed that the email used to sign into the account of the owner of the doc was the same as `client_email`, so I didn't bother even bother to check.

**Comment by lavigne958** [comment]
This has been done. We now have a step that start with: "Very important! Go to your spreadsheet and share it with a client_email from the step above."

Which emphasize the fact that you must share it with the client email generated just above.

Closing this issue.
