### ISSUE TITLE
Error: "pointer being freed was not allocated" when running gspread.authorize(credentials)

### ISSUE THREAD

**Issue by zzhjerry** [burnash/gspread#316]
I made a testing script to write data into a spreadsheet by following the example given in README.md. But after the first few successfully running, I encountered this error:

```bash
python(51308,0x7fff7b087300) malloc: *** error for object 0x10f2e1df0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[1]    51308 abort      python test_gspread.py
```

Then I never succeeded to make it work again. I tried to run the script line by line and found problem lies in 

`gc = gspread.authorize(credential)`

Has anyone else ever met this problem? I searched a lot of web pages and can't find an proper answer.

I'm using python 2.7.10 on Mac OS Yosemite. Here are my codes:

```python
import json
import gspread
from oauth2client.client import SignedJwtAssertionCredentials

json_key = json.load(open("My Project-2341919c5dab.json"))
scope = ["https://spreadsheets.google.com/feeds"]

credentials = SignedJwtAssertionCredentials(
    json_key['client_email'], json_key['private_key'], scope)

gc = gspread.authorize(credentials)
#
#ss = gc.open("test python script")
#worksheet = ss.get_worksheet(0)
#worksheet.update_acell("A1", "Bingo")
```

All my other python script are working fine except for this one.

**Comment by zzhjerry** [comment]
Sorry, I think this issue is not a gspread related issue because I changed a computer it's working back

**Comment by RaiseDataScience** [comment]
I've been encountering this error every time I try to use gspread lately.  Haven't changed my hardware, and yet... crashes galore.

**Comment by cmutzel** [comment]
I am having the same problem:

import json
import gspread
from oauth2client.client import SignedJwtAssertionCredentials
json_key = json.load(open(...path to my credentials...))
scope = ['https://spreadsheets.google.com/feeds']
credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'].encode(), scope)
gc = gspread.authorize(credentials)

python(72440,0x7fff7a76c310) malloc: *** error for object 0x1031e7d00: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

It seems to fail here:

line 104 in gspread.client self.auth.refresh(http) 
SignedJwtAssertionCredentials -> refresh -> _refresh -> _do_refresh_request -> _generate_refresh_request_body -> _generate_assertion()

Here are my details:
mutzel$ python --version
Python 2.7.9

installed...
cffi==1.5.0
cryptography==1.2.2
enum34==1.1.2
gdata==2.0.18
google-api-python-client==1.4.2
gspread==0.3.0
httplib2==0.9.2
idna==2.0
ipaddress==1.0.16
oauth2client==1.5.2
pyOpenSSL==0.15.1
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
requests==2.9.1
rsa==3.3
simplejson==3.8.1
six==1.10.0
uritemplate==0.6
wsgiref==0.1.2
