### ISSUE TITLE
requests gspread library fails to pip install because dependency requests library missing

### ISSUE THREAD

**Issue by mosesmc52** [burnash/gspread#317]
Hi, 

I regularly install this library in to a virtual environment using the pip install command. After last Friday, the gspread library fails to install because it didn't pre-install the dependent requests library. Here is the stack trace error I see. This is the command line argument I use to install the gspread library. 

pip install https://github.com/burnash/gspread/archive/master.zip

Moses

File "/var/folders/dl/jt5zsvy91gx3g8_pflz9c5680000gp/T/pip-zaKdHf-build/setup.py", line 6, in <module>

    import gspread

  File "gspread/\_\_init\_\_.py", line 21, in <module>

    from .client import Client, login, authorize

  File "gspread/client.py", line 19, in <module>

    from .httpsession import HTTPSession, HTTPError

  File "gspread/httpsession.py", line 11, in <module>

    import requests

ImportError: No module named requests

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /var/folders/dl/jt5zsvy91gx3g8_pflz9c5680000gp/T/pip-zaKdHf-build
Storing debug log for failure in /Users/user/.pip/pip.log

**Comment by msuozzo** [comment]
This is a consequence of the way in which the version string is centralized in gspread's `__init__.py ` file. `setup.py` wants to import gspread to get the `__version__` string for the module but `__init__.py` also imports all of the modules' exports (_e.g._ `from .client import Client, login, authorize`). This import statement runs `import requests` which has not yet been triggered by the `setup()` function later in `setup.py`.

A likely consequence of this is that gspread cannot be imported from `setup.py`. This means the versions string will need to live in two places (not the worst thing in the world).

@burnash: Do you have a preference as to how this should be handled?
Unfortunately, this is one of the many costs of adding dependencies :-(

**Comment by msuozzo** [comment]
Never mind. `requests` to the rescue:
```python
version = ''
with open('requests/__init__.py', 'r') as fd:
  version = re.search(r'^__version__\s*=\s*[\'"]([^\'"]*)[\'"]',
                       fd.read(), re.MULTILINE).group(1)
```

**Comment by msuozzo** [comment]
Thanks a ton for reporting this @mosesmc52!

**Comment by mosesmc52** [comment]
Thanks for responding promptly. Anytime, Gspread is a great tool.

**Comment by burnash** [comment]
@mosesmc52 many thanks for spotting this.
@msuozzo Totally agree with this. Many other projects handle the version string in a similar way including Flask.

Talking about versions, I believe it's time to bump up the gspread's minor version to 3 and release the lib on the PyPI.

**Comment by ilprincipecolo** [comment]
> OK. Solution is found. Need to point full path:

 import sys
sys.path.append('/home/usename/.local/lib/python2.7/site-packages/')
 import gspread

> from https://www.pythonanywhere.com/forums/topic/13265/
