### ISSUE TITLE
Continuous Integration Testing Parity

### ISSUE THREAD

**Issue by msuozzo** [burnash/gspread#318]
The current continuous integration service being used, Travis CI, is incompatible with the primary testing scheme. This is due to the fact that Travis will not allow Google API credentials to be kept secret during testing. As such, the current testing suite must be augmented with tests that do not directly use the Spreadsheets API.

I'm presently on working on bringing the mock-based testing scheme to parity with the current API-based one. I just wanted to have this here to track/discuss progress.

**Comment by lavigne958** [comment]
This is not applicable anymore. The new CI uses github Actions and does not let us hold some service account credentials but let us connect to the google API if we want to.

Closing this issue.
