### ISSUE TITLE
Remove ClientLogin Authentication

### ISSUE THREAD

**Issue by msuozzo** [burnash/gspread#319]
Client Login, the username/password-based authentication method used by the Google APIs previous to Oauth, has been on its way out for the better part of 4 years.

The associated gspread functions should either raise an exception or be removed all together.

**Comment by iandees** [comment]
Also, the documentation shouldn't recommend that you use a "Service" credential type (which essentially is e-mail/password-based).

**Comment by burnash** [comment]
Removed in #389
