### ISSUE TITLE
Edit url can't be located

### ISSUE THREAD

**Issue by ghost** [burnash/gspread#320]
The update_cells function is giving me a StopIteration error. A few days ago, the same script worked fine...
~~~
  File "gspread\models.py", line 485, in update_cells
    feed = self._create_update_feed(cell_list)
  File "gspread\models.py", line 468, in _create_update_feed
    cell.element.findall(_ns('link')))
  File "gspread\utils.py", line 18, in finditem
    return next((item for item in seq if func(item)))
StopIteration
~~~
After a little searching I could see that the edit url can't be retrieved anymore. This was (apparently) previously located in a 'http://www.w3.org/2005/Atom'}link attribute of a cell.element object. Now the only 'link' is an entry object. Has Google changed something or is it possible that I have to change worksheet settings?

Any ideas are welcome.

**Comment by msuozzo** [comment]
The `update_cells` tests are still passing. That doesn't mean Google _isn't_ changing the XML structure but it does give evidence to the contrary.

If you're able to, would you mind dumping the `cell.element` that's causing the error? If you have any questions on how to do this, I may be able to walk you though it.

**Comment by Mxm0320** [comment]
I think you need this: (btw, this is printed in the forloop of _create_update_feed() at models.py).
`cell.element`:
{'attrib': {}, 
'tag': '{http://www.w3.org/2005/Atom}entry', 
'_children': [\<Element '{http://www.w3.org/2005/Atom}id' at 0x591f080>, 
\<Element '{http://www.w3.org/2005/Atom}updated' at 0x591f0f0>, 
\<Element '{http://www.w3.org/2005/Atom}category' at 0x591f160>, 
\<Element '{http://www.w3.org/2005/Atom}title' at 0x591f1d0>,
\<Element '{http://www.w3.org/2005/Atom}content' at 0x591f240>, 
\<Element '{http://www.w3.org/2005/Atom}link' at 0x591f2b0>, 
\<Element '{http://schemas.google.com/spreadsheets/2006}cell' at 0x591f320>]
}

And the `Atom link` element:
{'attrib': {'href': 'https://spreadsheets.google.com/feeds/cells/1eJnq6UlL1dXGkv
fevKHfLT4I4Bd01hSA597nbyc0x4A/od6/private/full/R3C1', 'type': 'application/atom+
xml', 'rel': 'self'}, 'tag': '{http://www.w3.org/2005/Atom}link', '_children': [ ]}
Where the program is looking for a link element which has the attribute *'rel' : 'edit'*

Hope you can help!

**Comment by msuozzo** [comment]
Alright I haven't been able to reproduce this behavior. My theory was that it had to do with a loss of editing permission. I've tried:
* Changing sheet permission during API session.
* Setting and then attempting to update a protected range

Time for some background:
* What version of python are you using?
* What OS/version are you running?
* Have there been any recent changes in sheet permissions?

Also, would you be able to print `ElementTree.tostring(cell.element)` to get a full text dump of the XML block?

**Comment by Mxm0320** [comment]
Specifications:
Python 2.7
Windows 8
No changes, to my knowledge

Full text dump:
<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.goo
gle.com/spreadsheets/2006"><ns0:id>https://spreadsheets.google.com/feeds/cells/1
eJnq6UlL1dXGkvfevKHfLT4I4Bd01hSA597nbyc0x4A/od6/private/full/R3C1</ns0:id><ns0:u
pdated>2015-10-24T15:00:25.924Z</ns0:updated><ns0:category scheme="http://schema
s.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/200
6#cell" /><ns0:title type="text">A3</ns0:title><ns0:content type="text">22/10/20
15</ns0:content><ns0:link href="https://spreadsheets.google.com/feeds/cells/1eJn
q6UlL1dXGkvfevKHfLT4I4Bd01hSA597nbyc0x4A/od6/private/full/R3C1" rel="self" type=
"application/atom+xml" /><ns1:cell col="1" inputValue="22/10/2015" numericValue=
"42299.0" row="3">22/10/2015</ns1:cell></ns0:entry>

And again, it all worked a few days ago. I don't remember changing anything on the script or Spreadsheet.

Thanks for your help!

**Comment by burnash** [comment]
gspread has been ported to a newer Sheets API v4, which uses JSON instead of XML. I believe this issue is no longer relevant. I'm closing this issue, feel free to re-open if you have any questions.
