### ISSUE TITLE
Importing csv data to worksheet using a bulk insert/update

### ISSUE THREAD

**Issue by sr-murthy** [burnash/gspread#321]
Is it possible to import csv files directly into the worksheets of a Google spreadsheet using some kind of bulk insert/update?

**Comment by msuozzo** [comment]
You can do so by:
* checking the dimensions of your csv file
* resize your gspread worksheet to these dimensions
* call `Worksheet.range` specifying the range of the entire sheet
* iterate through each cell, updating its value to the corresponding cell in the csv
* call `Worksheet.update_cells` on the same group of cells

Or you could upload the file through the google drive GUI.

Or maybe in the future you could perform the upload directly from gspread (#97).
