### ISSUE TITLE
Provide API for up-to-date check based on modification-time on metadata of the document

### ISSUE THREAD

**Issue by ankostis** [burnash/gspread#323]
It is possible to provide a function for checking last modification-time for some document?
The reason is to avoid reloading a remote-document if no changes have been performed, by simply checking the modifiedDate, according to this google-API page: https://developers.google.com/drive/v2/reference/files/get

**Comment by jlp78** [comment]
This is already possible.  Here's what I use...

```python
import gspread
import time
import os
import os.path
import sys
...
sh = gc.open_by_key('yourkeyhere')
worksheet = sh.get_worksheet(0)
updated = time.strptime(worksheet.updated, '%Y-%m-%dT%H:%M:%S.%fZ')
updated_time = time.mktime(updated)
print "last updated", time.asctime(updated), "UTC"
...
if os.path.isfile(some_file) and updated_time <= os.path.getmtime(some_file):
    print "existing file {} is newer, aborting".format(some_file)
    sys.exit(0)
```

Might be an easier way to do this, but this worked for me and for what I was doing.  HTH.

**Comment by ankostis** [comment]
That was what i was looking for!
Strangely I couldn't find the `updated` attribute. Probably I had an older version.

And excellent response time ;-) thanks!
