### ISSUE TITLE
How to make the script work in a private google domain?

### ISSUE THREAD

**Issue by arthurnyc** [burnash/gspread#325]
I followed all the steps and could make it work fine in my private account, but when I tried to use in my company that uses a google private domain (our emails are my_name@mycompany.com) I can't execute the step 7, when I try to share the document there's a message saying:
"Sorry, an item cannot be shared outside of [my company name]."
Do we have some workaround to make it work besides allowing sharing documents outside the company?

**Comment by arthurnyc** [comment]
Looks like I have to configure this part of Custom Domains. Somebody had the same problem? More info here: https://cloud.google.com/appengine/docs/using-custom-domains-and-ssl?hl=en

**Comment by msuozzo** [comment]
Glad you figured that out. This is definitely good information to have for future users.
