### ISSUE TITLE
sort column

### ISSUE THREAD

**Issue by mgarito** [burnash/gspread#330]
I'd like to be able to sort a worksheet by a specified column.

Something like:
worksheet.col_sort_asc("column_name")  # Sort ascending 
worksheet.col_sort_des("column_name")  # Sort descending

**Comment by XSchelin** [comment]
Plus one, please.

**Comment by xomri** [comment]
I can use that too

**Comment by rshipskind** [comment]
It looks like sorting the sheet isn't something the sheets API v3 can do, but the API v4 can. I think it might require reworking the entire API call structure to use the newer version of the API to make this happen.

**Comment by shindig21** [comment]
Plus one please :)

**Comment by Nstremmel** [comment]
This would be very helpful!

**Comment by kadebeem** [comment]
Going to plus one this as well. I'm having to do it manually before running a script. Not a huge deal, but would rather my script take care of it.

**Comment by Rurquhart** [comment]
+1, this would be awesome!

**Comment by dhs2635** [comment]
+1 for me!

**Comment by Romanmc72** [comment]
+1 ditto

**Comment by plomdawg** [comment]
+1 would be great

**Comment by veronika-petrenko** [comment]
# Sort sheet A -> Z by column 'B'
wks.sort((2, 'asc'))

# Sort range A2:G8 basing on column 'G' A -> Z
# and column 'B' Z -> A
wks.sort((7, 'asc'), (2, 'des'), range='A2:G8')
