### ISSUE TITLE
New version 0.2.6

### ISSUE THREAD

**Issue by kvarga** [burnash/gspread#331]
It looks like there has been significant work done in HEAD, but no releases on github or pypi since April.

Is it time to release a new version?

**Comment by msuozzo** [comment]
I agree. @burnash?

**Comment by burnash** [comment]
@msuozzo @kvarga I agree. Let's release it.

**Comment by burnash** [comment]
Released a new version on PyPI. The number is 0.3.0 since there are many important changes. Kudos to  @msuozzo for a lot of hard work and pushing the project forward.

**Comment by msuozzo** [comment]
:-)
