### ISSUE TITLE
Getting spreadsheet creation date

### ISSUE THREAD

**Issue by mdmadhu** [burnash/gspread#332]
Does anyone know how, if possible, one could get the creation date of various spreadsheets that I can list using 'openall()'. If this is not currently possible, could the ability to filter spreadsheets by metadata be added sometime? Thanks.

**Comment by burnash** [comment]
I didn't find a way to get creation date in Sheets API v3 we're currently using. The only date they provide is `updated`. Will it work for your task? If yes, I've implemented  `updated` property in #426 and it soon will be merged.

**Comment by lavigne958** [comment]
Found the following documentation on Google Api [Drive API file list](https://developers.google.com/drive/api/v3/reference/files#resource) , it is possible to get the creation date. I will check it in details soon.

**Comment by lavigne958** [comment]
@mdmadhu I found a way to get the creation and last update time when opening a spreadsheet.

See linked PR for details.
