### ISSUE TITLE
How do I get a refresh token?

### ISSUE THREAD

**Issue by Abbie2020** [burnash/gspread#333]
I have a web2py web app that is reading a cell from a spreadsheet and selects a random cell each time the page is refreshed. This works the first few times the user refreshes the page, but then errors after that. I think this is from refreshing the access token too many times but I can't work out how to get a refresh token.

I tried using:

    if creds.access_token_expired:
        gs_client.login()

as mentioned here: https://github.com/burnash/gspread/issues/181#issuecomment-127789385 but that hasn't stopped the errors.

This is the code I am using:

    json_file = open(os.path.join(current.request.folder, 'private', 'quote_generator.json'))     
    
    json_key = json.load(json_file)

    scope = ['https://spreadsheets.google.com/feeds']

    credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)

    gc = gspread.authorize(credentials)    
    if credentials.access_token_expired:
        gc.login()

**Comment by LarryRiedel** [comment]
I don't know if this helps, because I don't use SignedJwtAssertionCredentials, but here is what I do for tokens:


```
import httplib2
from oauth2client.file import Storage
from oauth2client.client import OAuth2WebServerFlow
CLIENT_ID = '...'
CLIENT_SECRET = '...'
OAUTH_SCOPE = 'https://spreadsheets.google.com/feeds'
REDIRECT_URI = 'urn:ietf:wg:oauth:2.0:oob'
credentialsFile = '...'
flow = OAuth2WebServerFlow(
        client_id=CLIENT_ID, client_secret=CLIENT_SECRET,
        scope=OAUTH_SCOPE, redirect_uri=REDIRECT_URI,
        access_type='offline', approval_prompt='force')
authorize_url = flow.step1_get_authorize_url()
print('Go to the following link in your browser: ' + authorize_url)
code = raw_input('Enter verification code: ').strip()
credentials = flow.step2_exchange(code)
Storage(credentialsFile).put(credentials)
```

That creates a JSON credentials file, which you may already have, so you don't need to care about the above, but the credentials file I get has a refresh_token field in it.

Then later on, in a different script, I use this to read the file and get authorized:

```
storage = oauth2client.file.Storage(credentialsFile)
credentials = storage.get()
http = httplib2.Http()
http = credentials.authorize(http)
credentials.refresh(http)
gc = gspread.authorize(credentials)
```

I have been using the same credentialsFile for months with this and never had any problems

**Comment by Abbie2020** [comment]
I don't want to speak to soon but I kept everything as I had before but included:

    http = httplib2.Http()
    http = credentials.authorize(http)
    credentials.refresh(http)
    gc = gspread.authorize(credentials)

and so far it seems to be working. Thanks!

**Comment by JustinS-B** [comment]
I had identical problems, but followed @Abbie2020 above & mine seems to work really well now too:
```
import json
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import httplib2

# this uses the JSON file from Google
# & the spreadsheet shared to the email address in it
json_key = json.load(open('/FULL_PATH/123456789.json')) 
scope = ['https://spreadsheets.google.com/feeds']

http = httplib2.Http()
http = credentials.authorize(http)
credentials.refresh(http)

if credentials.access_token_expired:
    gc.login()
wks = gc.open("SPREADSHEET_NAME").worksheet("WORKSHEET_NAME")
```

**Comment by LarryRiedel** [comment]
FWIW, that code, used with the same version of the libraries as at the time of the post, still works as well for me as it ever did.
