### ISSUE TITLE
Crypto library Not available in google-app-engine environment.

### ISSUE THREAD

**Issue by satwikkansal** [burnash/gspread#334]
As recommended in your docs I installed PyOpenSSL and its working fine without Google App Engine but when I run my app in Google App Engine Environment It shows the error. I've read google app engine docs and tried installing lib directory but still the issue remains unsolved.
![screenshot 18](https://cloud.githubusercontent.com/assets/10217535/11763893/16b56abc-a143-11e5-91eb-42461bb6803b.png)

**Comment by msuozzo** [comment]
Check out [this page](https://cloud.google.com/appengine/docs/python/tools/libraries27?hl=en). If you haven't already, you need to enable `pycrypto` in the `libraries` section of your default module yaml file.

Let me know if that worked for you.

**Comment by satwikkansal** [comment]
I've already tried that but it's not working. Please see my code in the stackoverflow question I asked , here is the link
http://stackoverflow.com/questions/34245249/google-app-engine-no-crypto-library-available-error

**Comment by msuozzo** [comment]
I think I may have found a workaround for you in [this](https://code.google.com/p/google-api-python-client/issues/detail?id=133) oauth2client bug report. Try swapping out your `SignedJwtAssertionCredentials` for `AppAssertionCredentials`.

In the event that this works, a note should be made in the gspread documentation as this seems like a sufficiently common use case.

**Comment by satwikkansal** [comment]
Tried AppAssertionCredentials too, there is a problem with authorize function , If I use the App Assertion
method as suggested here https://developers.google.com/api-client-library/python/guide/google_app_engine , the object returned by credentials.authorize(...) is http type which can't be used to open spreadsheets.
On the other hand If I do gspread.authorize(...) on these credentials , this error is thrown

 File "G:\dtuwiki\ocdtu\parse_sheet.py", line 48, in <module>
    sheet =gc.open_by_url('https://docs.google.com/spreadsheets/d/1_XoHZcI2_pCYD8HVvc_yzXjW-sbZyJ4ZiWpelTedLhg/edit#gid=1567697220').get_worksheet(0)
  File "G:\dtuwiki\ocdtu\lib\gspread\client.py", line 201, in open_by_url
    return self.open_by_key(m2.group(1))
  File "G:\dtuwiki\ocdtu\lib\gspread\client.py", line 165, in open_by_key
    feed = self.get_spreadsheets_feed()
  File "G:\dtuwiki\ocdtu\lib\gspread\client.py", line 229, in get_spreadsheets_feed
    r = self.session.get(url)
  File "G:\dtuwiki\ocdtu\lib\gspread\httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
  File "G:\dtuwiki\ocdtu\lib\gspread\httpsession.py", line 75, in request
    raise HTTPError("%s: %s" % (response.status, response.read()))
HTTPError: 401: <HTML>
<HEAD>
<TITLE>Token invalid - Invalid token: Cannot parse referred token string</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Token invalid - Invalid token: Cannot parse referred token string</H1>
<H2>Error 401</H2>
</BODY>
</HTML>
INFO     2015-12-14 22:49:13,552 module.py:809] default: "GET / HTTP/1.1" 500 -

I am stuck.. please help me out!

**Comment by burnash** [comment]
@satwikkansal were you able to get around this?

**Comment by satwikkansal** [comment]
@burnash Actually no, I had to switch to something else.
