### ISSUE TITLE
Wrong versioning

### ISSUE THREAD

**Issue by danielemichilli** [burnash/gspread#335]
Hello, 

I'm not sure whether this is a rational choice made for some reasons obscure to me but in tags you use sometimes the format 'vXXX' and others just 'XXX' without the 'v'.

If this is not a choice, it is very inconvenient since the last version is considered an old one and no the current one.

Thanks,
Daniele

**Comment by burnash** [comment]
@danielemichilli That indeed is my mistake. Thanks for spotting that.

I've made a new release on GitHub and fixed the version number: https://github.com/burnash/gspread/releases
