### ISSUE TITLE
Is gspread doc outdated ?

### ISSUE THREAD

**Issue by tjyang** [burnash/gspread#336]
Hi,

I am trying to following http://gspread.readthedocs.org/en/latest/oauth2.html# doc and found the screenshot is outdated with current Google developer console. See screenshot below.

![image](https://cloud.githubusercontent.com/assets/378638/11842380/e270b314-a3c8-11e5-84b5-63b967c58c7b.png)

**Comment by bearbin** [comment]
The documentation is not outdated, just that you missed that you need to create a Service Account and not a one of the other things on the previous step to this.

**Comment by msuozzo** [comment]
I'm pretty sure the docs are outdated. There was an interface update to GCP
recently.

**Comment by murtraja** [comment]
i am having the same problem following from the tutorial given at readthedocs!
