### ISSUE TITLE
Feature request: Insert row(s) at location

### ISSUE THREAD

**Issue by dbyler** [burnash/gspread#34]
Is it possible to create a method that would insert n rows in a specific location? The end of a spreadsheet is not always the desired place for new data. :)

p.s. Thanks for publishing gspread! It's saved me a _ton_ of time and hassle.

**Comment by miklevin** [comment]
The InsertRow() method of gdata inserts on the first blank row, and not way at the bottom of the document. Trying to switch from gdata to gspread. This is a big showstopper. I can provide examples of how gdata does it. Generally it looks like:

entry = gdata.InsertRow(adict, dockey, wkskey)

**Comment by thejoestory** [comment]
One workaround I found was to count the values in a column, use the resize method to resize the worksheet, and then use the append_row to add the row. This may not work for everyone but worked well for what I needed. 
```python
x = 0
for values in wks.col_values(1):
	x = x + 1
rowToAdd = ['test','test2']
wks.resize(x)
wks.append_row(rowToAdd)
```

**Comment by miklevin** [comment]
Yep. I have a project making extreme use of GSpread, and I have a similar workaround. In here, you'll find the InsertRows function that takes a sheet object, a list-of-lists and last-row-used and inserts the list-of-lists at the end of the sheet, making room for it as necessary https://github.com/miklevin/pipulate/blob/e38029ccf647183f5d094efd67067e9eb04eabc2/common.py

**Comment by tom-lowe** [comment]
I've found the insert_row function to be kind of slow for some reason but updating cells one-by-one does the job for me, maybe not in all scenarios.
```
def updateRowCells(row, rowIndex, sheet):
	cellRow = []
	i = 1
	for col in row:
		cellValue = row[i-1]
		sheet.update_cell(rowIndex,i, cellValue)
		i += 1
```

**Comment by patelmonalisa** [comment]
Not sure how it worked, but if I deleted the first 1000 rows of the Googlesheets the new updates started happening at the end of row normally.

**Comment by burnash** [comment]
I'm closing this request. `insert_row()` was implemented in #171

**Comment by viralsingh** [comment]
is there any method to insert the column as well ? Like the insert_row() ?

**Comment by officialrahulmandal** [comment]
hey viralsingh ,
you can do this with the help of following links:-
https://gspread.readthedocs.io/en/latest/api.html?highlight=batch#gspread.models.Spreadsheet.batch_update
https://developers.google.com/sheets/api/samples/rowcolumn#insert_an_empty_row_or_column
