### ISSUE TITLE
Incorrect parsing of URLs in "gc.open_by_url" (new Drive URL format?)

### ISSUE THREAD

**Issue by symbolt** [burnash/gspread#349]
I tried using "gc.open_by_url" for the first time, and got a "gspread.exceptions.NoValidUrlKeyFound." My URL looked like this (key modified): 

```
baselinedata = gc.open_by_url("https://docs.google.com/spreadsheets/d/1qTqNDk5xYnapVa2Uuc2jIFL9qUuZ7iDMxB388w3L99c")
```

The key itself is correct. My suspicion was that possibly the Google Drive URLs may have themselves changed, since the example you give in the guide is different: "https://docs.google.com/spreadsheet/ccc?key=0Bm...FE&hl'" (so, it has no ".../d/..." and mine doesn't have the "/ccc?key=" part).

**Comment by burnash** [comment]
I think the handling of the new drive url format was added in #128. However, I checked the regex responsible for parsing the key and it looks like it fails to parse the url if `/edit` suffix is missing (as in your case).

**Comment by Bonobo791** [comment]
Latest
