### ISSUE TITLE
Unicode DecodeError

### ISSUE THREAD

**Issue by rai2048iiit** [burnash/gspread#350]
Hi,
I'm facing UnicodeDecodeError

xyz = 'Kosynier\xf3w Ko\x1aciuszkowskich 13'
cell_list[0].value = xyz
**worksheet.update_cells(cell_list)**

Error:
File "build/bdist.macosx-10.10-intel/egg/gspread/models.py", line 475, in update_cells
File "build/bdist.macosx-10.10-intel/egg/gspread/models.py", line 466, in _create_update_feed
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 8: ordinal not in range(128)

Platform info:
gspread: v0.3.0
python: 2.7.6

Debugging:
1.
xyz = xyz.decode('utf-8', 'replace') 
result will be u'Kosynier\ufffdw Ko\x1aciuszkowskich 13'
but when I'm saving this I'm not getting any error but data is also **not saved** in the sheet.
2.
cell_list[0].value = unicode(xyz,errors='ignore')
no errors but same data is not populated to sheet
3.
   worksheet.update_cell(0, 0,unicode(xyz, errors='ignore'))
  File "build/bdist.linux-x86_64/egg/gspread/models.py", line 438, in update_cell
  File "build/bdist.linux-x86_64/egg/gspread/client.py", line 278, in put_feed
  File "build/bdist.linux-x86_64/egg/gspread/httpsession.py", line 84, in put
  File "build/bdist.linux-x86_64/egg/gspread/httpsession.py", line 71, in request
gspread.exceptions.HTTPError: 400: An invalid XML character (Unicode: 0x1a) was found in the value of attribute &quot;inputValue&quot; and element is &quot;ns1:cell&quot;.

Fields causing issues: example: Country VARCHAR(50) CHARACTER SET UNICODE CASESPECIFIC (teradata)

**Comment by rai2048iiit** [comment]
I didn't found the solution but tried some workaround by avoiding all the unicode character.
for row in rows:
                for col in row:
                    if isinstance(col, basestring):
                        col = re.sub('[\x1a]+','', col)
                        col= re.sub('[^\x00-\x7F]+','', col)
                        #9,10,13,32-126
                        _col=''
                        for i in col:
                            if(ord(i) in [9,10,13] or 32 <= ord(i) <= 126):
                                _col = _col+i
                            else:
                                _col = _col+' '
                        col=_col
                    cell_list[index].value = col

**Comment by burnash** [comment]
Sorry for the late response.

gspread has been ported to a newer Sheets API v4, which uses JSON instead of XML. I believe upgrading to the latest version should solve this issue. 

I'm closing this issue, feel free to re-open it if you still experience the error.
