### ISSUE TITLE
gspread fails to work with latest requests 2.9.1, but is working fine with requests 2.3

### ISSUE THREAD

**Issue by voscausa** [burnash/gspread#353]
libs used:
- gspread 0.3.0
- httplib 0.9.2
- oauth2client
- requests 2.3.0 or the latest: 2.9.1

**When I use 2.9.1 the log shows:**
.......\requests\adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: Can't connect to HTTPS URL because the SSL module is not available.

I added [SSL support](https://cloud.google.com/appengine/docs/python/sockets/ssl_support) in the app.yaml. The log shows:

.......\adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))

With request 2.3.0 without the SSL support, it works fine.

**gcloud info --project voscausa-test**
Google Cloud SDK [92.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]]
Python Location: [C:\python27\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2016.01.12]
  app-engine-python: [1.9.30]
  bq-win: [2.0.18]
  core-win: [2016.01.12]
  gcloud: []
  windows-ssh-tools: [2015.09.21]
  gsutil: [4.16]
  bq: [2.0.18]
  gsutil-win: [4.16]
System PATH: ......
Cloud SDK on PATH: [True]

Installation Properties: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\properties]
User Config Directory: [C:\Users\rober\AppData\Roaming\gcloud]
User Properties: [C:\Users\rober\AppData\Roaming\gcloud\properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

**Comment by burnash** [comment]
It looks like it's not related to gspread. Closing this for now.

**Comment by robincrlee** [comment]
I encountered this issue when using gspread with Google App Engine. I was able to run in production with requests 2.18

In case gspread users encountere similar issue, here's a link to relevant discussion. the solution is to use request-tool-belt
https://stackoverflow.com/questions/9604799/can-python-requests-library-be-used-on-google-app-engine
