### ISSUE TITLE
oauth2client error cannot import name SignedJwtAssertionCredentials

### ISSUE THREAD

**Issue by perrycannon** [burnash/gspread#357]
I receive an error
from oauth2client.client import SignedJwtAssertionCredentials
ImportError: cannot import name SignedJwtAssertionCredentials

I have received the same error on different raspberry pis. Each had a fresh install of Jessie.

I received the error. Then installed Librium-dev, upgrade PyOpenSSL, with the same result.

I don't know how to resolve this error

Thank you
Perry

**Comment by vagelim** [comment]
Ran into this issue myself. 

The solution that worked for me:
`pip install oauth2client==1.5.2`

**Comment by perrycannon** [comment]
Vagelim thank you for your help. Installing oauthclient 1.5.2 resolved the error.

Now I receive this error.
"Unable to login and get spreadsheet.  Check OAuth credentials, spreadsheet name, and make sure spreadsheet is shared to the client_email address in the OAuth .json file!
Google sheet login failed with error: No crypto library available"

I have rechecked all of my entires, everything is correct. I have previously installed libffi-dev and PyOpenSSL.

Thank you
Perry

**Comment by JMensch** [comment]
Please see my correction to their documentation [here](https://github.com/burnash/gspread/pull/356). This will solve your problem.

**Comment by perrycannon** [comment]
Thank you. I really appreciate your help. I am now able to write to google sheets from my raspberry pi. I've been working on this for awhile. I wasn't able to get help from the creator of the project I emulated. He would only refer me to blog posts or generic guides.
