### ISSUE TITLE
Add ability to create a new spreadsheet

### ISSUE THREAD

**Issue by mouramario** [burnash/gspread#36]
Should be possible create a new spreadsheet

gc = gspread.login( 'user', 'password' )

spreadsheet_name =  'My spreadsheet Name' 
new_spreadsheet = gc.new( spreadsheet_name )

wks = gc.open(  spreadsheet_name  ).sheet1

....

Best Regards and congratulations, gspread is very cool!

**Comment by fialovy** [comment]
Thanks, adamruhl, for the extremely useful info! 

Is there a way to use docs_client.ClientLogin with OAuth credentials - or otherwise copy an existing sheet with them? I've been digging around the docs forever, too, and haven't had much luck. 

Or maybe something with construct_url provided here?

**Comment by fialovy** [comment]
I figured out a way to do it with google-api-python-client. Hopefully, it will be helpful to others:

```python
import httplib2
from apiclient import errors
from apiclient.discovery import build
from oauth2client.client import SignedJwtAssertionCredentials

to_copy = '<id/key_string_from_desired_file_url>'
# Service account e-mail from Google dev console
drive_id = '<my_long_service_account_string>@developer.gserviceaccount.com'
# Get the right permissions
drive_scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']    
# pem key converted from p12 key generated in dev console
with open(os.path.abspath('my_key.pem'), 'rb') as keyfile:
    drive_key = keyfile.read()

credentials = SignedJwtAssertionCredentials(drive_id, drive_key, drive_scope)

http = httplib2.Http()
http = self.credentials.authorize(http)
drive_service = build('drive', 'v2', http=http)
file_copy = {'title': title}

try:               
    drive_service.files().copy(fileId=to_copy, body = file_copy).execute()
except errors.HttpError, error:
    print error
```

**Comment by 00gavin** [comment]
Is it just me, or is the Google gdata API incredibly confusing?  To compound matters, its documentation is horrible.  And further more, all of the examples found no longer are functional due to API changes.  For instance, the above gdata example from @adamruhl gives the error:  "The Doclist API has been shut down. Please use the new Drive API, https://developers.google.com/drive/."  

Can someone recommend the easiest way, one that works, for creating a new sheet?  Cheers.

**Comment by herrsergio** [comment]
That would be a pretty nice feature.

**Comment by maybelinot** [comment]
Hi @00gavin and @herrsergio 
Take a look on [df2gspread](https://github.com/maybelinot/df2gspread) library, which provides this possibility!

**Comment by miohtama** [comment]
Here is updated example for ``oauth2client`` version 2.0:

https://gist.github.com/miohtama/f988a5a83a301dd27469

I am wiling to incorporate this to `Client` class if there is green light for this.

**Comment by Ralithune** [comment]
@miohtama Please do it.  I'm not @burnash but this would be really helpful.

I'm going to look at your linked example and see if I can do it manually :/

**Comment by patelnidhice** [comment]
#fialovy, why have you used self? Your code is not working, gives error for "self"

**Comment by fialovy** [comment]
@patelnidhice I wrote the code within a class and modified things after paste; will edit

**Comment by patelnidhice** [comment]
Thanks, SignedJwtAssertionCredentials doesn't work.
This is my code which I am trying to run:

import webapp2
from oauth2client.service_account import ServiceAccountCredentials
import gspread
from apiclient.discovery import build
import os
import httplib2

SCOPES = ['https://spreadsheets.google.com/feeds']

credentials = ServiceAccountCredentials.from_json_keyfile_name('myabc.json', SCOPES)

http = httplib2.Http()
http = credentials.authorize(http)
drive_service = build('drive', 'v2', http=http)
file_copy = {'title': "new_copy"}
	
to_copy = '<x/something>'

# Service account e-mail from Google dev console
drive_id = 'something@something.gserviceaccount.com'

# Get the right permissions
drive_scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']    

drive_service.files().copy(fileId=to_copy, body = file_copy).execute()	

Getting error:
    drive_service.files().copy(fileId=to_copy, body = file_copy).execute()
  File "/usr/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/googleapiclient/http.py", line 832, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v2/files/%3Cd%2F1oBkNa-yCEtLVFbBfEv39UnLwo5BxsdKd-MCG1CqGO0Y%3E/copy?alt=json returned "Insufficient Permission">

Can you please help in resolving this issue?

**Comment by patelnidhice** [comment]
I am able to copy spreadsheet, but unable to open it, and also can't see the location also. I am using gmail account for original spreadsheet, same I want to copy. Not sure why it is asking for permission, is there any way to handle this? Please help.

**Comment by burnash** [comment]
Added in #253
