### ISSUE TITLE
Accessing named ranges without specifying the worksheet

### ISSUE THREAD

**Issue by vokimon** [burnash/gspread#365]
I want to use named ranges in order my script to cope with user edits like row insertions, worksheet manipulation... Named ranges are suposed to be defined spreadsheed wide and be more robust but...

You can access named ranges using WorkSheet.range(). This forces you to get the WorkSheet either by index, which is fragile on tab moves, or by title which is fragile on worksheet retitles.

Couldn't be useful a spreadshet range() method you can provide a named range name without having to locate the worksheet?

PD: It could be also usefull for providing range with the worksheet specification like 'My Sheet''!G61:J75

**Comment by lavigne958** [comment]
Hi this is not how gspread is architectured unfortunately. the function you mention is used to access different kind of ranges: using A1 notation, or using indexes or named ranges. 

What could be done here is create a new function in a `SpreadSheet` object to access **only** named ranges as they are SpreadSheet wide and not tight to a particular sheet.

**Comment by lavigne958** [comment]
Closing this issue in favor of #876
