### ISSUE TITLE
Append Row Question

### ISSUE THREAD

**Issue by Wayne91** [burnash/gspread#367]
Hi,
I'm hoping that I just missed something obvious, but I am having an issue with Append_Row where it takes each character of the string and assigns it to a separate column in the same row.   Are there some examples?

So when I do this:

wks.append_row(value)      where abc is a variable containing a number I get a spreadsheet return of 
v	a	l     u    e
each in it's own cell.

I fixed it by using the wks.append_row({value1, value2, value3})

However this is where I found a new problem... which was that value1 was not always on the first column.  It would cycle out of order in each new row entry.

Any ideas why?

Thanks

**Comment by keliomer** [comment]
append_row should be passed a list of values that you want to add in a brand new row. If you pass it a string it will assume that you want to read the string as a list of characters.

if you do
wks.append_row([value,]) you should see the results you want.

Also if you do
append_row({x,y,z}) 
you'll be iterating over a dictionary which in Python does not have a fixed iteration order.

Hope this helps.
