### ISSUE TITLE
Tutorial refers to outdated functions in Google API

### ISSUE THREAD

**Issue by jbarlow83** [burnash/gspread#374]
The [tutorial](https://gspread.readthedocs.org/en/latest/oauth2.html#troubleshooting) includes the following example code:

```
from oauth2client.client import SignedJwtAssertionCredentials
```

As explained here, https://github.com/google/oauth2client/issues/401, SignedJwtAssertionCredentials has been phased out.

The new method is

```
import oauth2client.service_account
credentials = oauth2client.service_account.ServiceAccountCredentials.from_json_keyfile_dict(json_key, scope)
```

**Comment by ChrisSmith123** [comment]
I've done this and being new to python I don't know what I'm doing wrong, its still giving me this error:

AttributeError: 'module' object has no attribute 'ServiceAccountCredentials'

**Comment by jbarlow83** [comment]
@ChrisSmith123 I think you need to `pip install PyOpenSSL`.

**Comment by ChrisSmith123** [comment]
Thanks, I've tried that but the system is telling me its up to date.

**Comment by ChrisSmith123** [comment]
well, I think I'm making progress but now its telling me that permission is denied.

**Comment by ChrisSmith123** [comment]
Got it working, it was a typo on my part. Thanks for the help.
