### ISSUE TITLE
connection aborted error when too many cells are selected

### ISSUE THREAD

**Issue by ryantuck** [burnash/gspread#375]
I get the following error when attempting to pull about 1000 rows x 60 columns worth of data via `cells = sheet.range('a1:bh1000')`:

```
requests.exceptions.ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))
```

When i limit the pull to 100 rows x 60 columns, I can pull successfully, and have implemented list chunking in my code to read and update the relevant cells. 

Seems like this chunking should either happen under the hood or some `keep-alive` headers should be leveraged (if that would fix it) to increase the possible size of the request or length of time it can take to complete.

**Comment by shopro** [comment]
I get the same error even with chunking enabled. It seems that the error comes from having a too large `worksheet.range()`. Example: `worksheet.range('A1:A10000')` works but `worksheet.range('A1:A30000')` results in Broken pipe error. Tried it with chunks as small as 5 and it made no difference once the range became too large (spreadsheet has +100k rows).

**Comment by aiguofer** [comment]
I just encountered this as well... although I'm getting the error on `worksheet.update_cells` instead. I can chunk the number of cells that get updated at a time to prevent this error. Interestingly enough, while I was playing around with different chunk sizes, I found a different error (trying 50k cells at a time):

```
<HEAD>
<TITLE>Request Entity Too Large</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Request Entity Too Large</H1>
<H2>Error 413</H2>
</BODY>
</HTML>
```

I ultimately went with 20k at a time.

That being said, it might be nice if these things were handled by `gspread` directly.

**Comment by aiguofer** [comment]
actually, the issue https://github.com/burnash/gspread/issues/384 relates to this last message I got... I'm now going with a batch size of 40k.

**Comment by aiguofer** [comment]
Well, I've now run into the problem with `range` when it's large enough, although instead I get the following error instead:
`ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))`

**Comment by shredding** [comment]
Did anyone encounter a solution to this problem?

**Comment by aiguofer** [comment]
The trick is to chunk the range request. You can see how I did it [here](https://github.com/aiguofer/gspread-pandas/blob/master/gspread_pandas/client.py#L334), but essentially, I look at how many cols are in the range, and what the max number of rows I can pull so that I don't exceed 200k cells, then I chunk the requests into rows. There might be other ways of doing it, but this works for me :)

**Comment by lavigne958** [comment]
as mentioned in #384 this has been fixed. 

Closing this issue.
