### ISSUE TITLE
Delete a range of Cells

### ISSUE THREAD

**Issue by FlorianHoevelmann** [burnash/gspread#376]
I'm trying to delete the Cell values in a specific range and so far I do it this way:

delete = wks.range('A2:U1000')
for cell in delete:
    cell.value = ""
wks.update_cells(delete)

But this is pretty slow because it first gets the values of the cells and then sets them to "". Is there a faster way to do this? I thought about creating a cell object myself which is always empty but could not figure out how.
Thanks in advance

**Comment by burnash** [comment]
Sorry for the delay. Unfortunately, currently there's no other way to update cells without retrieving them first. Some values required for the update are collected when retrieving the range.

I just check the API docs and it looks like it's feasible to do the update without requesting the range first. I don't clearly remember why I did it that way.

**Comment by FlorianHoevelmann** [comment]
No Problem. We are working with the workaround and since we have a corn job for the script it doesn't really matter how fast the delete is. 

I just wanted to know if there is a faster solution but if its a lot of work to add this then we will just stick with the workaround.

**Comment by burnash** [comment]
Related StackOverflow QA: http://stackoverflow.com/questions/40957821/gspread-update-multiple-cells-not-in-range

**Comment by varun9597** [comment]
I am trying to delete multiple rows using delete_row(x).
I am using a for loop to change the value of x.

My code is - 
`import json
import gspread
from oauth2client.service_account import ServiceAccountCredentials


json_key = json.load(open('Atcon Python-a698ebdacf53.json'))
scope = ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets']
credentials = ServiceAccountCredentials.from_json_keyfile_name('Atcon Python-a698ebdacf53.json', scope)
gc = gspread.authorize(credentials)
worksheet = gc.open('AC-1 meter24.06.xls').sheet1

for x in range(1,43):
	worksheet.delete_row(x)

`
Problem that i am facing is that the given code is deleting alternate rows from the Google Sheet.
Is there something wrong in my code?

**Comment by varun9597** [comment]
I am trying to delete multiple rows using delete_row(x).
I am using a for loop to change the value of x.

My code is -
```
import json
import gspread
from oauth2client.service_account import ServiceAccountCredentials

json_key = json.load(open('Atcon Python-a698ebdacf53.json'))
scope = ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets']
credentials = ServiceAccountCredentials.from_json_keyfile_name('Atcon Python-a698ebdacf53.json', scope)
gc = gspread.authorize(credentials)
worksheet = gc.open('AC-1 meter24.06.xls').sheet1

for x in range(1,43):
worksheet.delete_row(x)
```
Problem that i am facing is that the given code is **deleting alternate rows** from the Google Sheet.
Is there something wrong in my code?

**Comment by lavigne958** [comment]
This is now solved, one can use the following methods to clear the content of a cell: `batch_update`, `update`, `update_cells`.

closing this issue.
