### ISSUE TITLE
row_count of existing sheet with 10 actual rows is returned as 999

### ISSUE THREAD

**Issue by Bartvds** [burnash/gspread#383]
I open a sheet with just a few rows, but it says there are 999 rows :|

**Comment by burnash** [comment]
gspread is a Google Sheets API wrapper. The number is exactly as [Sheets API returns it](https://github.com/burnash/gspread/blob/4c80deb3e6a4f989ae18385de620ebced03a8359/gspread/models.py#L207). 999 rows is what you see on a newly created spreadsheet (try scrolling to the bottom of the page)
