### ISSUE TITLE
append_row to append at first empty row

### ISSUE THREAD

**Issue by Rostgnom** [burnash/gspread#388]
I am seeing an unexpected behavior for the `append_row` function: Rather than putting the row contents into the **first empty row**, it appends them at the very bottom of the spreadsheet. I do not really see the use case of that since it is very confusing to have ~900 empty rows until the line shows up in the 1001st. This behavior is also documented in the API Reference: http://gspread.readthedocs.io/en/latest/#gspread.Worksheet.append_row

I propose a way of checking for a number of consecutive blank rows in order to find the last row with content, or, more specifically, the first row with _no more_ content. That way, you can easily use append_row for automated logging into google spreadsheets. The way I described is also the behavior of the official Google Apps Script (see https://developers.google.com/apps-script/reference/spreadsheet/sheet#appendrowrowcontents).

A working example of this:
```
def first_empty_row():
    all = sheet.get_all_values()
    row_num = 1
    consecutive = 0
    for row in all:
        flag = False
        for col in row:
            if col != "":
                # something is there!
                flag = True
                break

        if flag:
            consecutive = 0
        else:
            # empty row
            consecutive += 1

        if consecutive == 2:
            # two consecutive empty rows
            return row_num - 1
        row_num += 1
    # every row filled
    return row_num
```

If you find this to be unexpected, too, I will be happy to file a Pull request with a documented version of this code snipped and the updated `append_row` method.

**Comment by burnash** [comment]
Good point. The question is how to efficiently find the first row with no more content. If this involves requesting all of the sheet's content (via `get_all_values()` or alike) this will dramatically slow `append_row` execution time for larger spreadsheets.

**Comment by Rostgnom** [comment]
I guess another primary problem is that the `insert_row` implementation is quite slow as stated in a couple of other issues. So since we need to rely on that method for appending the content _after_ finding out what is the last row to insert into, the whole method is going to be even slower. Until that is fixed, the bottleneck will be the amount of requests that are done by `insert_row` for the moment and not the (in memory) iteration with the method I described above, which is actually not that bad in comparison.

I am not very familiar with this library so do you think there is another way of implementing it instead of `get_all_values()`?

**Comment by burnash** [comment]
Correct, I didn't see any problem with iteration either. External requests are responsible for slowness.

> I am not very familiar with this library so do you think there is another way of implementing it instead of get_all_values()?

I don't see any other way to get the last row with no content other than retrieving all of the worksheet's values (e.g. calling `get_all_values()`). The Sheet's API recently has updated. I didn't get a chance to check if append row can be improved with new API methods.

One possible solution for logging to a spreadsheet without `insert_row` or empty rows search is to shrink the spreadsheet to 0 rows prior to calling append_row. This can be done with [Worksheet.resize()](http://gspread.readthedocs.io/en/latest/#gspread.Worksheet.resize)
