### ISSUE TITLE
gspread Has NO attribute authorize???

### ISSUE THREAD

**Issue by OmAnirudh** [burnash/gspread#391]
Hi !  Idk but I am unable to run the  following script

 which I saw from [http://gspread.readthedocs.io/en/latest/oauth2.html](url)

 
```
import gspread 

from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds']

credentials = ServiceAccountCredentials.from_json_keyfile_name('gspread-april-2cd … ba4.json', scope)

gc = gspread.authorize(credentials)

wks = gc.open("Where is the money Lebowski?").sheet1

```
The following error message!!!!

Traceback (most recent call last):
  File "C:\Users", line 1, in <module>
    import gspread

  File "C:\Users", line 8, in <module>
    gc = gspread.authorize(credentials)
AttributeError: module 'gspread' has no attribute 'authorize'
>>>

**Comment by burnash** [comment]
What's the name of your script? (the file you're executing)
