### ISSUE TITLE
KansasRpcExeption on creating worksapce

### ISSUE THREAD

**Issue by szymonm** [burnash/gspread#392]
Hey,

when trying to create workspace I get:
```
HTTPError: 500: b'com.google.kansas.KansasRpcException: APPLICATION_ERROR;Datatype marked as large: ritz_commands;AppErrorCode=34;StartTimeMs=1467626978801;ServerTimeSec=0.0014798641204833984;TCP;Deadline=30.0;CliLog=-1;SrvLog=256;FailFast;EndUserCredsRequested;ReqSecLevel=none;RespFormat=ZIPPY_COMPRESSED;/KansasServer.Mutate;LastReqID=249b3b065337a955;LastGlobalID=0;Server=10.79.111.16:9838'
```
Any ideas what does it mean?

**Comment by burnash** [comment]
[...It means buckle your seat belt, Dorothy, 'cause Kansas is going bye-bye.](https://www.youtube.com/watch?v=0-JJuHpfN5g)

Are you still getting the error?

**Comment by szymonm** [comment]
You're right!

It is because my spreadsheet seems to be a little bit overloaded (although I'm not hitting the cells limit). It is quite irresponsible even when editing in browser.

Tested on another sheet and it works fine.
