### ISSUE TITLE
ValueError: ('Unexpected credentials type', None, 'Expected', 'service_account')

### ISSUE THREAD

**Issue by xhx509** [burnash/gspread#393]
**My code is simple like this:**

import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json
scope = ['https://spreadsheets.google.com/feeds']
credentials = ServiceAccountCredentials.from_json_keyfile_name('client_secret_998298341239.json', scope)

**After I run that codes. It shows "ValueError: ('Unexpected credentials type', None, 'Expected', 'service_account')"

Can someone help me figure out that problem?  Thanks**

**Comment by paulz1** [comment]
What was a solution?
I have the same error and could not find how to fix it ?

**Comment by xhx509** [comment]
Did you Share your googlesheet link to your copied email address?

**Comment by paulz1** [comment]
Ok, thank you very much.
My client_secret.json was completely wrong. Once I get the right one and add the mail to spreasheet it starts working like charm. 
Thank you very much.

**Comment by vhaska** [comment]
What have you changed in your clien_secret.json Why google doesnt provide correct credentials in json files?

**Comment by rah003** [comment]
@vhaska just a guess, but what you have most likely created is "API Key" or "OAuth 2.0 client ID" json file, while what you need for gspread to work is "Service account key" json. Go back to the https://console.developers.google.com/apis/credentials and create new credentials and when selecting option, pick the last one - Service account key.

**Comment by jayoaoa** [comment]
@rah003 Your answer is so helpful!!!!! thanks!
