### ISSUE TITLE
Copying non empty rows

### ISSUE THREAD

**Issue by santiagosanti** [burnash/gspread#394]
I am trying to write code to copy non empty lines from a spread sheet. 

So far I have come up with this, but it still copies up to row 200 which is computationally expensive. 

` import gspread

from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds']

credentials = ServiceAccountCredentials.from_json_keyfile_name('Lagos 2016-42e5da11289f.json',scope)

gc = gspread.authorize(credentials)

sh = gc.open("Lagos2016")

worksheet = sh.get_worksheet(0)

values = []

for x in range(2,199):
	values_list =worksheet.row_values(x)
	if values_list != "":
		values.append(values_list)

print (values)`

I will appreciate any pointers on this

**Comment by burnash** [comment]
Try to use [`get_all_values ()`](https://github.com/burnash/gspread#getting-all-values-from-a-worksheet-as-a-list-of-lists). It'll do a single request to API. Then filter / clean your data.

*Note:*
1. It's easier to read well-formatted code. Please refer to [GFM guidelines](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown)
2. Usage questions should go to StackOverflow. Most of the time you'll get the answer faster on StackOverflow.
