### ISSUE TITLE
error  "SpreadsheetNotFound"

### ISSUE THREAD

**Issue by xhx509** [burnash/gspread#395]
**Here is my script:**

import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json
scope = ['https://spreadsheets.google.com/feeds']
credentials = ServiceAccountCredentials.from_json_keyfile_name('xxxx-524dfaa46d4e.json', scope)

gc = gspread.authorize(credentials)
wks = gc.open("my_test").sheet1

**It showed error "SpreadsheetNotFound" , when I run that script.**

**Could someone help me figure out that issue?  Thanks a lot.**

**Comment by burnash** [comment]
Did you share the spreadsheet with what you have as `client_email` in your json creds?

**Comment by xhx509** [comment]
No, I did not share the spreadsheet.  Do I need to share it?
Thank you.

Sincerely
Huanxin(Xavier)

**Comment by burnash** [comment]
Yes, please check [the guide](http://gspread.readthedocs.io/en/latest/oauth2.html#using-signed-credentials) for details. (Step 7)

**Comment by xhx509** [comment]
It works well now. I should read the documents carefully.

Thank you very much.

Sincerely
Huanxin(Xavier)

**Comment by burnash** [comment]
No problem. I'll try to figure out how to stress the sharing step in the docs.
