### ISSUE TITLE
Change listener?

### ISSUE THREAD

**Issue by patrickfuller** [burnash/gspread#398]
Does gspread have the functionality to detect changes in Google Sheets?

Thought process so far: From the Sheets menu, there's an email notification option. I'm not familiar with Google's scripting language, but I imagine that there's a change listener function on their side. From here, it seems that I could send a message to a running python server whenever the event is fired.

Related post on StackOverflow [here](http://stackoverflow.com/questions/38225812/gspread-change-listener).

**Comment by burnash** [comment]
I like the idea. This can be useful in many cases. However, in gspread there's no functionality to detect changes in the way you described in the SO post.

It's doable, though. From the quick glance at Apps Script docs I can see that this can be implemented with triggered events in Sheets' scripts. Indeed, Sheets let the user to track changes with [simple](https://developers.google.com/apps-script/guides/triggers/) or [installable](https://developers.google.com/apps-script/guides/triggers/installable) triggers. In a trigger function the user may fetch a custom URL and, as you suggest, send a message to a running python server. As far as I know fetching a URL is only available for installable triggers. Sending an email is an overkill in a case where a regular HTTP request will do. I'd use a `UrlFetchApp.fetch` instead.

**Comment by patrickfuller** [comment]
Thanks for the information. I was able to get this working by doing exactly what you said.

On Google Sheets:

```javascript
function onEdit (e) {
  UrlFetchApp.fetch("http://myaddress.com");
}
```

Python-side (w/ Tornado)

```python
import tornado.ioloop
import tornado.web

class MainHandler(tornado.web.RequestHandler):
    def get(self):
        on_edit()
        self.write('Updating.')

def on_edit():
    # Code here
    pass

app = tornado.web.Application([(r'/', MainHandler)])
app.listen(#port here)
tornado.ioloop.IOLoop.current().start()
```

I don't think this sort of functionality should be within the scope of gspread, but I hope the documentation helps others.

I'll copy-paste over to stackoverflow, and thanks for the help!

**Comment by burnash** [comment]
Thanks for sharing the actual code!
