### ISSUE TITLE
Return the title of a worksheet as a string

### ISSUE THREAD

**Issue by SpaceTuna8** [burnash/gspread#399]
Scenario: There is a worksheet at index 1 called "data_set1". I would like to be able to get a string value of  "data_set1".   
```python
>>> sht = client.open('my_spreadsheet')
>>> worksheet2 = sht.get_worksheet(1)

>>> print(worksheet2.get_string_title)

data_set1
```

**Comment by rai2048iiit** [comment]
`worksheet2.title` should return name of worksheet.

**Comment by SpaceTuna8** [comment]
So it does. Thank you.
Not sure how I missed that when I first looked.
