### ISSUE TITLE
idea : Update cells locally and push to google sheet all at once.

### ISSUE THREAD

**Issue by medyagh** [burnash/gspread#403]
is there any way that I can make gspread sheet do all the edits (update, add row...) to something on my local disk and then when all the changes are accumulated, I simply delete the sheet in the google and replace it with the local one ?

if I want to implement this, would you recommend using csv library ? I

**Comment by burnash** [comment]
gspread is a very simple API wrapper and at the moment the only method to accumulate changes is to use `Worksheet.range()` / `Worksheet.update_cells()` pair. 

However, the idea is good. I think many people may find it useful. Especially those who work with large spreadsheets or need a lot of small modifications but for some reason can not batch them with `Worksheet.update_cells()`.

If you want to implement this feature, you'll need a local storage for the data and a way to efficiently transmit this data to Google servers. As far as I can see csv module is not very useful for random access to the data so I wouldn't suggest using csv library for a local storage. A better alternative would be some kind of in-memory data structure or [some module that provide persistence on disk](https://docs.python.org/2/library/persistence.html). You need to research the possible [data size limits](https://support.google.com/drive/answer/37603?hl=en) to see if in-memory approach will work.

As for efficient data transmission to Google servers, there are two approaches. Batch cell update with `update_cells()` or CSV import from not yet merged #386. In theory, CSV import could be more efficient than batch cell update, I didn't make any benchmarks yet.

**Comment by cstarner** [comment]
The easiest (i.e. simplest from a user perspective) to implement this would be to subclass `Cell` and `Spreadsheet` with wrapper classes that keep track of the "dirty" cells, and then have a save method to push only the cells that were changed remotely.

As for the update method, I would think that `update_cells()` would be the most efficient in the worst-case scenario. If 5 cells are changed within a 1.5 million cell document, `update_cells()` would only need to push 5 cells, a CSV upload would require all 1.5 million cells.

This is something I could implement fairly rapidly, I believe. If this is something you want added, I will get to work and submit a PR

**Comment by burnash** [comment]
@cstarner The idea is good. I'm planning to move to Sheets API v4 soon. It looks like v4 has a lot more possibilities and improvements over v3 (the current API gspread is using). However, there could be some breaking changes. To avoid unnecessary double work, I'd say let's hold it for a while and come back to this feature after v4 is implemented.

**Comment by jak2030** [comment]
Excited to hear this may make it into v4. I would also add that similar functionality for an`update_rows` would be very useful for working with larger spreadsheets.

**Comment by tracicot** [comment]
What I'd really like to be able to do is upload a batch of rows. Currently I have several scripts for syncing data from one source into a sheet, for multiple sheets/sources. I clear the sheet, then insert the rows. Right now it's one row at a time, which is unnecessarily time consuming. It takes about 5 minutes to upload each row, whereas I know a batch would be able to do it in a matter of seconds.

**Comment by cstarner** [comment]
Is there still interest in this feature? Now that we support v4, I could start looking into making this happen

**Comment by JoshuaMathias** [comment]
I started trying to implement this before I saw this thread. I just want a read method that gets all the data for a sheet, use the data as a list of lists, and a write method that sends all the changes. However, it's looking too complex for me, and I don't have much experience with gspread. Are you still interested in doing this @cstarner?

**Comment by cstarner** [comment]
I would like to work on this; however I am currently working 6.5 days per week, and don't really have time to dedicate to it's solution right now

**Comment by lavigne958** [comment]
This is now implemented, one car get a range of `Cell`s, work with their values, then push an update of the cells at once.

Closing this issue.
