### ISSUE TITLE
gspread.Spreadsheet.worksheets() doesn't produce str list

### ISSUE THREAD

**Issue by willkuhn** [burnash/gspread#406]
Calling `gspread.Spreadsheet.worksheets()` should return a string list of titles for all worksheets in the Spreadsheet, but instead returns a list of gspread.models.Worksheet instances.

I'm a gitHub newby, so I'm just going to post the fix here and let someone else incorporate it:

Fix: change /gspread/models.py line 112 from '`return self._sheet_list[:]`' to '`return [i.title for i in self._sheet_list[:]]`'

### Environment info

Operating System: Windows 10 64-bit
Python version: 2.7.10 32-bit (via Python(x,y) 2.7.10.0)
gspread version: 0.4.1

### Steps to reproduce
```
import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds']
credentials = ServiceAccountCredentials.from_json_keyfile_name(
                json_file), scope)
gc = gspread.authorize(credentials)
sh = gc.open(sheet_name)
sh.worksheets()
```
Out: 
```
[<Worksheet 'Summary' id:od6>,
 <Worksheet 'Species tally' id:ohes2sm>,
 <Worksheet 'Species completed' id:ohcuwaa>,
 <Worksheet 'Species still needed' id:oikecdc>]
```

Thanks and cheers!

**Comment by srvanrell** [comment]
@willkuhn I think that a function that returns the list of worksheet titles would be useful. However, the gspread docs states clearly that `worksheets()`

> Returns a list of all `worksheets` in a spreadsheet.

Here is the link: http://gspread.readthedocs.io/en/latest/#gspread.Spreadsheet.worksheets

**Comment by burnash** [comment]
@srvanrell is right. `Spreadsheet.worksheets()` deliberately returns a list of objects, not strings. I don't see an issue here, so I'm closing the ticket.
