### ISSUE TITLE
No data being fetched.

### ISSUE THREAD

**Issue by prakhar21** [burnash/gspread#409]
Hi, I am trying to use gspread to perform a simple task of updating sheets.
After this step `gc = gspread.authorize(credentials)`
 I am getting a client object 
`<gspread.client.Client object at 0x7f509a9d2110>`

But now when I try to perform any other operation with `gc` then there is nothing getting displayed.
For Instance, I did, `gc.open_by_url()` the link is valid that I had fed in it. Nothing, no error comes, program exists, by going into Exception.

**Comment by burnash** [comment]
So you have an exception? Could you post a traceback?

**Comment by burnash** [comment]
I'm closing this for now. I can reopen it if I get a sample of traceback.
