### ISSUE TITLE
Spreadsheet not found, but only for a few minutes.

### ISSUE THREAD

**Issue by ilederman** [burnash/gspread#410]
I'm trying to understand why I'm getting a SpreadsheetNotFound exception, but after around 5 minutes it's found. It's always worked fine until a few days ago. To go around this, I currently add a time.sleep(300) just to pause for 5 minutes before loading by key. Let me know if there is some specific information I can provide. I'm using:

Python 2.7.9
gspread==0.4.1
google-api-python-client==1.5.3

**Comment by burnash** [comment]
Does the issue still persist?

**Comment by burnash** [comment]
Could it be an intermittent error? Closing the issue for now. Reopen it if the issue persists.

**Comment by ilederman** [comment]
Sorry, didn't see your comment. It does look like it's back to normal now, not sure what happened.

**Comment by burnash** [comment]
No problem. Hopefully, won't come back.

**Comment by harshajayaweeraXHJ** [comment]
This issue is still persists. It is working fine but after 10-15 hours Suddenly it throws the "SpreadsheetNotFound" error. Any idea why?

**Comment by harshajayaweeraXHJ** [comment]
My gspread=3.1.0 and Python version is 3.7.3
