### ISSUE TITLE
reading cell value with function

### ISSUE THREAD

**Issue by pysumin** [burnash/gspread#413]
hi i'm using python 2.7.3 on devian.

i was quite happy when i met gspread until i found that cell.value cannot read cell value with function.

if i use functions like count(), offset() etc on spreadsheet, cell.value returns wrong or none or error.

ex)  count() : cell.value ignore cells with function. it really count cell with original text or numbers.
i see 9 on spreadsheet, but 5 with cell.value.

does anyone have same problem with me?

**Comment by burnash** [comment]
Can't reproduce this issue. The cell with function gives me a properly calculated value. The raw formula itself is available under the `input_value` property of a cell. E.g. `cell.input_value`.
