### ISSUE TITLE
Make get_all_records return empty cells as None

### ISSUE THREAD

**Issue by valericus** [burnash/gspread#415]
Class `gspread.Worksheet` has nice method `get_all_records`. That method allows replace empty cells with zeros (parameter empty2zero) and I assume that would be great to teach it do same thing with `None`. Cause sometimes zero is not the same that nothing :-)

**Comment by burnash** [comment]
Good point. I think a better way would be for this method to provide something like `default_blank` parameter which defaults to `None` and could be set to zero or any other value.

**Comment by valericus** [comment]
Added pull request #423
