### ISSUE TITLE
How to set the color and size of the "Cell"

### ISSUE THREAD

**Issue by hhxx12ttxs** [burnash/gspread#419]
**GitHub Issues are for bugs and feature requests.**

Please do not post usage questions here. For general support from the community, see StackOverflow: http://stackoverflow.com/questions/tagged/gspread

Issues with usage questions will be closed.

For bugs please provide the following information.

### Environment info

Operating System:ubuntu
Python version:2.7.6
gspread version:latest

### Steps to reproduce
1.worksheet.acell('A1').setBackgroundColor("#ff0000")
2.Error: "AttributeError: 'Cell object has no attribute 'setBackgroundColor'"
So I want to know how to set the color of a cell, and I also wonder how to set the size of a cell.
Can anyone help me?

**Comment by burnash** [comment]
Please do not post usage questions here. For general support from the community, see StackOverflow: http://stackoverflow.com/questions/tagged/gspread

Issues with usage questions will be closed.
