### ISSUE TITLE
How to get the completed url of created worksheet?

### ISSUE THREAD

**Issue by hhxx12ttxs** [burnash/gspread#420]
**GitHub Issues are for bugs and feature requests.**

Please do not post usage questions here. For general support from the community, see StackOverflow: http://stackoverflow.com/questions/tagged/gspread

Issues with usage questions will be closed.

For bugs please provide the following information.

### Environment info

Operating System:ubuntu
Python version:2.7.6
gspread version:latest

### Steps to reproduce
1.    wks = gss_client.open_by_url("https://docs.google.com/spreadsheets/d/1z1clrZnd6JmiPmt38dDppawNhkkflI_M5Uv_diwJZwA/edit")
    worksheet = wks.add_worksheet(title="A worksheet", rows="100", cols="20")
2.the completed url of created worksheet is "https://docs.google.com/spreadsheets/d/1z1clrZnd6JmiPmt38dDppawNhkkflI_M5Uv_diwJZwA/edit#gid=1087954322"
3. I don't know how the get the completed url of created worksheet, ie the "gid".Can anyone help me?

**Comment by burnash** [comment]
Please post this question on StackOverflow and mark it with a `gspread` tag:
http://stackoverflow.com/questions/tagged/gspread
