### ISSUE TITLE
Set worksheet contents using Pandas DataFrame

### ISSUE THREAD

**Issue by robin900** [burnash/gspread#421]
For my own project work, I've written a function that sets the contents of a worksheet using a Pandas DataFrame. While similar in behavior to the feature offered by the `pgsheets` package, it has additional features, especially the automatic chunking of DataFrame content to avoid the "API call limit" on large Google Sheet writes.

May I offer a pull request to `gspread` to add this functionality?

**Comment by burnash** [comment]
Thanks for the suggestion and for the PR. I do use Pandas myself although not in conjunction with gspread.

We try to stick to the single responsibility principle in developing this library. At its best, it should only contain functionality related to accessing data and managing spreadsheets. Although widely accepted and used, Pandas is still not a core Python package. I don't see a reason why gspread should support DataFrames. 

That being said, I really don't want to discourage you. You can make your own package, import gspread, inherit and extend the functionality you need. You will own the DataFrames functionality and maintainers of gspread will have less code to support.

I also plan to rework the docs, and maybe put an examples / cookbook section. We have the ancient [GitHub Wiki pages](https://github.com/burnash/gspread/wiki/) for the project with a Cookbook section listing an example of handling DataFrames. We can update example and a link to your future library if it does better handling of DataFrames.

**Comment by robin900** [comment]
If I make this small, small package to allow gspread<->dataframe work, may I call it `gspread-dataframe`?

**Comment by burnash** [comment]
Looks good to me.

**Comment by robin900** [comment]
An alternative would be to include this in gspread, but as an optional subpackage install, so that people could put

`gspread[dataframe]`

in their setup.py requirements or requirements.txt files to have the dataframe module installed.

I can also change the dataframe test to use a mock DataFrame and thus provide test coverage without needing the Travis CI host to have pandas installed.

**Comment by burnash** [comment]
I never used subpackages before and I need some time to study this approach. I do aware of this syntax however and was planning to use it to provide a simple way to substitute `xml.etree` with `lxml`.

**Comment by robin900** [comment]
Their official name is "extras", and the implementation pattern is that an "extra" is in fact a list of additional dependencies needed to use the extra; the "extra" implementation code is always included in the package installation. In setup.py [one specifies these dependencies via `extras_requires`](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies). For example, for the dataframe extra, we could add

`extras_require={ 'dataframe': ['pandas>=0.14.0'] },`

to the `setup()` call in setup.py; then the `gspread.dataframe` module's code can remain as it currently is: raising an exception at runtime about a missing dependency for pandas if the extra features are used at runtime.

Here's an example of Django's use of extras: [the line in setup.py,](https://github.com/django/django/blob/master/setup.py#L51) and an [example of dynamic module loading](https://github.com/django/django/blob/3c447b108ac70757001171f7a4791f493880bf5b/django/contrib/auth/hashers.py#L179) related to the "argon2" and "bcrypt" extras defined in setup.py. You can see the pattern here: an extra is the list of dependencies it would require, and the package code handles the case where the extra's dependencies are installed and the case where they are not.

**Comment by robin900** [comment]
I've updated #422 to use the extras facility, naming the extra 'pandas' (the convention is to name the extra to describe the dependencies it uses, rather than the extra's functionality). I've also added documentation in the dataframe module and inclusion in index.rst.

**Comment by robin900** [comment]
Closing issue, as `gspread-dataframe` PyPI package has been in release for over a year now.
