### ISSUE TITLE
AttributeError: 'HTTPError' object has no attribute 'message'

### ISSUE THREAD

**Issue by alekaizer** [burnash/gspread#430]
I'm getting this error on those lines below, even though I followed all the steps in 
[http://gspread.readthedocs.io/en/latest/oauth2.html](url)
Latest gspread ver, I updated 10min ago to have the share method.
Running on Mac OS Sierra

    import gspread
    from oauth2client.service_account import ServiceAccountCredentials

     scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']

      credentials = ServiceAccountCredentials.from_json_keyfile_name('g_auth.json',
                                                               scope)

      gc = gspread.authorize(credentials)
      sh = gc.create('A new spreadsheet')
      sh_2 = gc.create('A new k')
      sh.share('email@email.com', perm_type='user', role='writer')

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gspread/client.py", line 378, in insert_permission
    self.session.post(url, json.dumps(data), params=params)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gspread/httpsession.py", line 78, in post
    return self.request('POST', url, params=params, data=data, headers=headers, files=files, json=json)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gspread/httpsession.py", line 68, in request
    response.status_code, response.content))
gspread.exceptions.HTTPError: 400: b'{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "parseError",\n    "message": "This API does not support parsing form-encoded input."\n   }\n  ],\n  "code": 400,\n  "message": "This API does not support parsing form-encoded input."\n }\n}\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/XXXXX/PycharmProjects/spreasheet/test.py", line 14, in <module>
    sh.share('email@email.com', perm_type='user', role='writer')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gspread/models.py", line 239, in share
    email_message=email_message
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gspread/client.py", line 380, in insert_permission
    raise RequestError(ex.message)
AttributeError: 'HTTPError' object has no attribute 'message'

Do somebody have any idea of what I'm doing wrong or missing, please ?

**Comment by alekaizer** [comment]
Looks like we need to set the headers in the session.post instruction if not it's sending _content_type_ as _form-encoded_

so I set the headers in **insert_permission**

**Comment by burnash** [comment]
Thanks for reporting, @mjdudak fixed this in #431, I've just released v0.6.1 in PyPi with this fix.

**Comment by burnash** [comment]
@alekaizer I've also removed a try / except that was throwing AttributeError.

**Comment by alekaizer** [comment]
thx @burnash will update my package

**Comment by burnash** [comment]
Is it working now?

**Comment by alekaizer** [comment]
Yes it's working now, perfectly 👍
