### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'json' when opening Sheet

### ISSUE THREAD

**Issue by davemachado** [burnash/gspread#433]
When attempting to open a spreadsheet with following function:

```
def openSS(bookName, sheetName):
        if not os.path.isfile(gsJSONFile):
                print("JSON client file does not exist!")
                sys.exit(2)
        scope = ['https://spreadsheets.google.com/feeds']
        credentials = ServiceAccountCredentials.from_json_keyfile_name(gsJSONFile, scope)
        gc = gspread.authorize(credentials)
        wks = gc.open(bookName).worksheet(sheetName)
        return wks
```
I'm getting this error, but I don't get it when running exact same file on a Macbook Pro:
```
  File "github/Scripts/Python/weather.py", line 268, in autoMode
    wks = openSS("Weather API", "Current")
  File "github/Scripts/Python/weather.py", line 51, in openSS
    wks = gc.open(bookName).worksheet(sheetName)
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 82, in open
    feed = self.get_spreadsheets_feed()
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 155, in get_spreadsheets_feed
    r = self.session.get(url)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 73, in get
    return self.request('GET', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 65, in request
    response = func(url, data=data, params=params, headers=request_headers, files=files, json=json)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```
Operating System: Ubuntu 14.04
Python version: 2.7.6
gspread version: just re-installed it with pip, so latest.

Thanks in advance!

**Comment by davemachado** [comment]
Also, just by simply commenting out previous lines, I know the error is being invoked from the `wks = gc.open(bookName).worksheet(sheetName)` statement.

**Comment by jackedgson** [comment]
Solved by updating requests package.

**Comment by oquidave** [comment]
Thanks similar issue on Ubuntu 14.04 LTS. Haven't found a way of solving it

**Comment by puneetjindal** [comment]
@jackedgson : I am also facing the same issue. My system is Ubuntu 14.04 Trusty. requests library package is 2.13.0 and python 3.4.
Need help if anybody solved?

**Comment by oquidave** [comment]
I solved the problem by moving to python 3.x and requests 2.4 and above. From your comment, you are using version 2.13.0 of the requests library. Just upgrade that for it to work.

**Comment by adamantic** [comment]
Solved this via sudo pip3 requests --upgarde as well

**Comment by lavigne958** [comment]
Old version of `requests` lib, old version of Ubuntu, related to python2, closing this issue.
