### ISSUE TITLE
Named Ranges Support

### ISSUE THREAD

**Issue by lcorsini** [burnash/gspread#435]
As of version 4 of Sheets API, now there is support for accessing named ranges objects
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#NamedRange

any plan to use them in gspread?

**Comment by burnash** [comment]
Sure, I plan to move to v4 and this looks like a good feature to add.

**Comment by atoth-hearsay** [comment]
is this feature available?

**Comment by burnash** [comment]
gspread uses v4 since #508 

Here's how you can use Named Ranges:

1. To get value or values from a named range:

```python
values = worksheet.get("my_named_range")
# values now a list of lists
```

2. To update a named range:

```python
worksheet.update('my_named_range', [[42], [43]])
```

`worksheet` in the examples is an instance of `Worksheet` class and represents a sheet in a sheet in a spreadsheet.

**Comment by danielpetroianu** [comment]
Hi, sorry to post on an old issue, but since the named range has the worksheet in it's definition eg: MyRange='Sheet 1'!A1:B2, shouldn't he API to use named ranges be on the spreadsheet?

**Comment by lavigne958** [comment]
Hi, the named range has the sheet and range in its definition but I don't think we can list all ranges and get their definitions unfortunately :disappointed: 

I am sorry but I think you have a typo in your message which makes it hard to understand, what you mean is: the API should use the name range ? or you mean we should get the name range and extract the sheet ID and the A1 notation ?

**Comment by danielpetroianu** [comment]
Sorry for the confusion. 
I wanted to call the API with the named range, like `spreadsheet.update('MyRange', [[1, 2], [3, 4]])`, so I can define the range in the spreadsheet and update it there if it needs to, without having to update the script that uses gspread.

From what I understand, right now I have to spreadsheet.worksheet("Sheet1") and then use the named range that is defined in Sheet1. 
Feels like this looses part of the functionality that Named Ranges provides.

**Comment by lavigne958** [comment]
I understand, and no you don't have to, this is a usual confusion about the way GSpread uses named ranges.
- yes, you must first get a sheet to access the method `update`.
- no you don't have to get the exact sheet that contains the named range when updating the values :wink: , named ranges are spreadSheet wide and not tight to a particular sheet, but the way GSpread is configured you can only have access to the method `update` from a `WorkSheet` instance.
But take the sheet `sheet1` and then using `update('MyRange', [[1, 2]])` knowing that `MyRange` is on sheet `sheet2` will work. 

We already have an issue open about this, to create a new function like `update_named_range` or `get_named_range` tight to a `SpreadSheet` object which will make more sense.

See: #876
