### ISSUE TITLE
update_cells is very slow

### ISSUE THREAD

**Issue by peczony** [burnash/gspread#437]
In fact I suspect that with the move to v4 API this issue could disappear, but still: I’m generating the content of [this spreadsheet](https://docs.google.com/spreadsheets/d/1WlLE9FPjVJMVBJjdAb9ehv71gIph1-NKxpwN1lr8bjY) automatically and even though it is not a particularly large table, the process takes more than 10 minutes, and when I write to local files instead of this spreadsheet, it takes seconds.

Do you have any advice to share for speeding up the uploading process? I thought about generating xlsx file locally and then uploading it to Google Sheets to replace the current spreadsheet (not sure if it is possible via gspread)...

**Comment by Zahar23** [comment]
I have the same issue, @peczony did manage to resolve it ?

**Comment by francixcoag** [comment]
My workarround was:
 - export from drive excel (mimetype stuff.. pydrive)
 - update the local excel file (using pygsheets)
 - import to the drive the updated local excel

**Comment by burnash** [comment]
gspread has been ported to the Sheets API v4. I believe @peczony is right, I haven't experienced slowness after upgrade to v4.

I'm closing this issue for now. Feel free to re-open if you have any questions.
