### ISSUE TITLE
Feature Request: import_csv(file_id, data, sheetName)

### ISSUE THREAD

**Issue by gschaefer3** [burnash/gspread#438]
Would like to see an enhancement to the import_csv() function.  Currently I believe import_csv only works for the first page of the spreadsheet.  It would be really helpful to be able to import into separate sheets of the spreadsheet.  

For example:

gc.import_csv("1gJhsybjxm8amZ...", someCSVdata, "MySecondSheet")    

Thanks for your consideration!

**Comment by ddxv** [comment]
Currently the information provided is slightly inaccurate.  

First, the readthedocs.io documentation is not up to date on the three requirements of `import_csv` ([readthedocs Source](http://gspread.readthedocs.io/en/latest/#gspread.Client.import_csv))

From the github Code (working):
`ef import_csv(self, file_id, data):
        """Imports data into the first page of the spreadsheet.
        :param data: A CSV string of data.
        """
        headers = {'Content-Type': 'text/csv'}
        url = '{0}/{1}'.format(DRIVE_FILES_UPLOAD_API_V2_URL, file_id)

        self.session.put(
            url,
            data=data,
            params={
                'uploadType': 'media',
                'convert': True
            },
            headers=headers
        )`


Second, from my testing `import_csv` removes all other worksheets and then entirely replaces the contents of the first worksheet. This should be reflected in the code comment above, as it implies that it will only replace the first sheet.

**Comment by bbrock25** [comment]
as @ddxv mentioned, this does in fact wipe the contents of the other sheets, it would be very nice if we could leave the others and update only a specific sheet so that charts can be dynamically populated (and other use cases I'm sure)

I am unaware if this is a limitation of the google sheets api or if its just the gspread implementation. If its only gspread, I'd love to take a crack at resolving this issue. Any thoughts?

**Comment by prakashatul1** [comment]
Please tell me why my code is not working 
===========================================

import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']

creds = ServiceAccountCredentials.from_json_keyfile_name('client_secret.json',scope)
client = gspread.authorize(creds)

sheet = client.open('Data').sheet1

csv = '''
a,b,c,d
1,2,3,4
Q,R,S,T
'''

client.import_csv(sheet,csv)
=====================================================
below  is my error log
========================================================
gspread.exceptions.RequestError: (404, '404: {\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "notFound",\n    "message": "File not found: \\u003cWorksheet \'Sheet1\' id:od6\\u003e",\n    "locationType": "other",\n    "location": "file"\n   }\n  ],\n  "code": 404,\n  "message": "File not found: \\u003cWorksheet \'Sheet1\' id:od6\\u003e"\n }\n}\n')

**Comment by mithunmanohar** [comment]
Is it still not possible to use import_csv functionality of gspread with a sheet name? The data is exported to the first sheet by default. Any suggestions are highly appreciated.

**Comment by alexanderreardon** [comment]
Any alternatives or workarounds? I'm thinking of just continuing to write it to it's own Google Sheets file, and then reference the data from other sheets.

**Comment by jmarkotter** [comment]
An addition to this import_csv() function
The ability to set "supportsTeamDrives" on / off

e.g.

```
    def import_csv(self, file_id, data, supportsTeamDrives = False):
        """Imports data into the first page of the spreadsheet.

        :param str data: A CSV string of data.

        Example:

        .. code::

            # Read CSV file contents
            content = open('file_to_import.csv', 'r').read()

            gc.import_csv(spreadsheet.id, content)

        .. note::

           This method removes all other worksheets and then entirely
           replaces the contents of the first worksheet.

        """
        headers = {'Content-Type': 'text/csv'}
        url = '{0}/{1}'.format(DRIVE_FILES_UPLOAD_API_V2_URL, file_id)

        self.request(
            'put',
            url,
            data=data,
            params={
                'uploadType': 'media',
                'convert': True,
                'supportsTeamDrives': supportsTeamDrives
            },
            headers=headers
        )
```

Have tested locally and this works, whereas before I received 404 - file not found errors from the Drive API.

**Comment by lavigne958** [comment]
Hi @gschaefer3 

This is a good feature request but we can't make it :disappointed: 

This is a limitation on google API side see the description h[ere below the code example](https://developers.google.com/drive/api/v2/manage-uploads?hl=en#import_to_google_docs_types)

Closing this issue.
