### ISSUE TITLE
some sheets are not able to be opened... 

### ISSUE THREAD

**Issue by jason79** [burnash/gspread#440]
It seems the recently created sheets are not able to be read. I have posted the question here 

http://stackoverflow.com/questions/42382847/gspread-spreadsheetnotfound-on-certain-workbooks

but after awhile, I think it is a APIv4 vs. v3 issue.

### Environment info

Operating System:
Python version: 2.7.13
gspread version: latest one

**Comment by lavigne958** [comment]
this issue should be resolved by #522 which will fetch all spreadsheets (within your quota of operations per seconds).

Closing this issue.
