### ISSUE TITLE
Feature Request: pass cell range into get_all_values() and get_all_records()

### ISSUE THREAD

**Issue by ryantuck** [burnash/gspread#441]
I've found I'm often pulling data from existing worksheets where data lives in a cell range that doesn't start at cell `A1`. It seems that a lot of users like to leave a buffer row and column in their spreadsheets and start at cell `B2`.

My use case always requires converting whatever I pull to a list of lists or list of dicts and manipulating from there. I've written a simple function to convert a list of `cell` objects to what I need but it feels like it should be baked into this module.

It'd be ideal if I could do any of the following:

```python
rows = sheet.get_all_values(range='B2:C20')
records = sheet.get_all_records(range='B2:C20')
```

It seems like this would be simple to implement since the `get_all_values()` method begins by extracting a list of `cell`s, which is also exactly what `range()` does, if I understand the module correctly.

I'd be happy to put in a PR with these changes, but wanted to know if this has already been considered out of scope and/or whether there are others who would definitely benefit from this.

**Comment by burnash** [comment]
Thanks for the suggestion. I like the idea, and it is definitely not out of scope. But I'm not sure how it goes with `get_all_records` method. Particularly `_all_` part of the method's name. I'm thinking of changing API a bit and renaming/reducing the number of methods. This feature could be a part of that change. 

For example, I think `get_values` would be a better name for `get_all_values` if the method accepts a `range` parameter. 

I'm planning to migrate gspread to Sheet API version 4 soon. v4 is a radical change in API and I expect it to reflect on gspread's API as well.

I suggest to hold this feature for a while and go back to it once the new API settles. I'm keeping the issue open.

**Comment by ushuz** [comment]
+1 for `get_records(range=)` and `get_values(range=)`

**Comment by burnash** [comment]
@ushuz Please stay tuned.
