### ISSUE TITLE
Optimized append_rows

### ISSUE THREAD

**Issue by sylvinus** [burnash/gspread#443]
I don't have the time to do a proper pull request but I figured this could help someone.

It can update thousands of rows in a few seconds (the main bottleneck in the current code is that cell values are read one by one, even with update_cells!)

```
def append_rows(worksheet, list_of_values):

  col_count = len(list_of_values[0])
  row_count = worksheet.row_count

  start_cell = worksheet.get_addr_int(row_count + 1, 1)
  end_cell = worksheet.get_addr_int(row_count + len(list_of_values), col_count)

  worksheet.add_rows(len(list_of_values))

  rng = worksheet.range('%s:%s' % (start_cell, end_cell))

  for cell in rng:
    cell.value = list_of_values[cell._row - row_count - 1][cell._col - 1]

  worksheet.update_cells(rng)
```

**Comment by philippe2803** [comment]
This deserve a pull request. It works very well, and is faster by possibly 2 orders of magnitude.

**Comment by mikejcorey** [comment]
This is an infinitely better/faster approach than adding lots of rows one at a time. Thank you for giving me my day back. ;-)

**Comment by lavigne958** [comment]
This issue is not relevant anymore, the latest code uses a single API call to append rows.

Closing this issue.
