### ISSUE TITLE
Feature Request: 'Protect range...'-equivalent. Manage permissions on cell level.

### ISSUE THREAD

**Issue by tomrijntjes** [burnash/gspread#447]
To use Google Sheets as data acquisition tool, it would be nice to have some sort of guarantee the cells did not change after retrieval, ie. by setting the permissions of the processed rows at read-only. 

Google Sheets provides this feature in their UI (right click: 'Protect Range...'). I briefly scanned the Drive API docs but couldn't find anything on cell level permissions. If this would be possible otherwise this would open up some interesting use cases.

**Comment by jeremyherbert** [comment]
Looks like this is now possible: https://developers.google.com/sheets/api/samples/ranges

**Comment by nineleaps-vijay** [comment]
@burnash can we start working on this one, I suppose many people might be needing this one and will be a good add-on to existing set of features. We can 

- create, delete and update a protectedRange
- clear sheet of all protectedRange
- get list of all protectedRange
- get list of protected Cells with each range

**Comment by nineleaps-vijay** [comment]
@burnash can we work on this feature, as this is quite useful and well needed. We can have create, update and delete a protectedRange now with the API.

**Comment by burnash** [comment]
@nineleaps-vijay sorry for the late response. Let me know if you are still interested in contributing.

**Comment by vijay-shanker** [comment]
hey @burnash yes will very much like to do it. Do you have any suggestions/input on starting it up. (nineleaps-vijay is my office GitHub profile )

**Comment by burnash** [comment]
Great, thanks for the response. When I left the comment I didn't notice that there's #720 which I believe is relevant. I haven't yet looked deeply into it though. If you have time, could please you review/test the PR?
