### ISSUE TITLE
Worksheet' object has no attribute 'gid' error

### ISSUE THREAD

**Issue by john-mak** [burnash/gspread#449]
**GitHub Issues are for bugs and feature requests.**

Please do not post usage questions here. For general support from the community, see StackOverflow: http://stackoverflow.com/questions/tagged/gspread

Issues with usage questions will be closed.

For bugs please provide the following information.

### Environment info

Operating System: CentOS 7
Python version: 2.7.5
gspread version: 0.6.2

### Steps to reproduce
1. Create new worksheet object using add_worksheet()
2. Try to access worksheet.gid
3. Receive error: Worksheet' object has no attribute 'gid'
According to the docs there is a 'gid' attribute.

**Comment by lavigne958** [comment]
Documentation has been update, their is no `gid` attribute anymore in a `WorkSheet` object, one can use the attribute `id` instead that will return the id of a `WorkSheet` object.

Closing this issue.
