### ISSUE TITLE
worksheet.range without explicitly pointing

### ISSUE THREAD

**Issue by enod** [burnash/gspread#451]
Hi,

I would like to get cells in specified range like: 
`cells = worksheet.range('C3:F')`
where F column is not defined explicitly but still returns the latest update. Google API v4 works in that way but gspread gives me gspread.exceptions.RequestError: (400, range error). Is it not compliant with v4 or am I doing it wrong?

**Comment by enod** [comment]
Currently I solved this issue by doing:
```
values_list = worksheet.col_values(3)
cells = worksheet.range('C3:F'+str(values_list.index('')))
```
But as you can see It might not best solution to have another API call. Any suggestion would be highly appreciated thanks!

**Comment by cryobry** [comment]
I worked around this using:
`cell_values = worksheet.col_values(1)
cells = worksheet.range('A4:A'+str(len(cell_values)))`

**Comment by lavigne958** [comment]
This can be solved using the following code:
```
max_row = worksheet.row_count
cells = worksheet.range("A4:A{}".format(max_row))
```

The only mandatory action here is to use any function that will first fetch the file metadata which could be one of (this is not the complete list)
- `Client.open(title="MySpreadSheet")`
- `SpreadSheet.title()`
- `SpreadSheet.get_worksheet(0)`
- `SpreadSheet.worksheets()`
- `SpreadSheet.worksheet("Sheet1")`
or the actual function
- `SpreadSheet.fetch_metadata()`

Closing this issue.
