### ISSUE TITLE
get_all_values() misses empty rows at bottom of worksheet

### ISSUE THREAD

**Issue by knyte** [burnash/gspread#453]
### Environment info

Operating System: Ubuntu 14.04 LTS
Python version: 2.7.12
gspread version: v0.6.2

### Steps to reproduce
1. Create a worksheet that ends with N empty rows (arbitrarily many, as long as they're the bottom rows in the sheet)

e.g., the worksheet would correspond to an array like the following:

```python
[["A", "B", "C", "D"],
 ["E", "F", "G", "H"],
 ["", "", "", ""]]
```

For this worksheet, the actual row count would be 3 but get_all_values() would only return the top 2 rows.

### Stack trace or other output that would be helpful

Assuming wks is a Worksheet object corresponding to the worksheet created in Step 1,
```python
len(wks.get_all_values())
```

will not equal
```python
wks.row_count
```

and get_all_values will miss the last N rows (the empty ones) in the sheet.

If the bottom row of the worksheet is non-empty, (as far as I know) this issue does not occur. It's only when the bottom row is purely empty. The row_values method still functions fine in this case.

I can't tell from the get_all_values() documentation whether this is intentional.

**Comment by burnash** [comment]
Thank you for raising the issue. I've updated the docs in c58d0e4fc0686f74939200936f3c69f55d120387 to make it clear that empty rows / columns omission is intentional.

I believe this behaviour should be default as it covers the majority of the use cases. I'm closing this issue and related PR #454.
