### ISSUE TITLE
Ability to distinguish between normal worksheets and hidden worksheets?

### ISSUE THREAD

**Issue by benjiwheeler** [burnash/gspread#457]
There doesn't seem to be any way to fetch only the non-hidden worksheets in a particular workbook. (It's unclear to me from reading Google's documentation whether that is even possible using their API.)

**Comment by lavigne958** [comment]
Hi the API provides a property for each sheet it is hidden or not, you can see [API V4 reference](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/sheets#sheetproperties).

One could implement a new PR to get that property when requesting to open a new Spreadsheet.
