### ISSUE TITLE
KeyError: 'access_token

### ISSUE THREAD

**Issue by danylokiz** [burnash/gspread#458]
**GitHub Issues are for bugs and feature requests.**

Please do not post usage questions here. For general support from the community, see StackOverflow: http://stackoverflow.com/questions/tagged/gspread

Issues with usage questions will be closed.

For bugs please provide the following information.

### Environment info

Operating System:
Python version:
gspread version:

### Steps to reproduce
1.When i run this code <code>from oauth2client.service_account import ServiceAccountCredentials
import requests, gspread
import os
import ast

def authenticate_google_docs():
    f = open(os.path.join('Checking.p12'), 'rb')
    SIGNED_KEY = f.read()
    f.close()
    scope = ['https://spreadsheets.google.com/feeds', 'https://docs.google.com/feeds']
    credentials = ServiceAccountCredentials('danylo.lin@gmail.com', SIGNED_KEY, scope)

    data = {
        'refresh_token' : '<refresh-token-copied>',
        'client_id' : '<client-id-copied>',
        'client_secret' : '<client-secret-copied>',
        'grant_type' : 'refresh_token',
    }

    r = requests.post('https://accounts.google.com/o/oauth2/token', data = data)
    credentials.access_token = ast.literal_eval(r.text)['access_token']

    gc = gspread.authorize(credentials)
    return gc

gc = authenticate_google_docs()

sh = gc.open_by_url('https://docs.google.com/spreadsheets/d/11WR6rwQhL4wUDN8I77ju_5rzZl8IglsUjtUDI6pZsAQ/edit#gid=0')</code> I got an error please help
2.Error <<KeyError: 'access_token>>
3.

**Comment by burnash** [comment]
Please follow the suggested template for reporting the issues and use code formatting in your markdown. It's not easy to read python without spaces. 

Check [GitHub's markdown reference](https://guides.github.com/features/mastering-markdown/).

I'm closing this for now.
