### ISSUE TITLE
Move / reorder worksheet index

### ISSUE THREAD

**Issue by PPGDa5id** [burnash/gspread#460]
Is there a way to change the worksheet properties so that I can reorder the worksheets?  
That or a way to create a new worksheet at index (n) ?
Or force the new worksheet to created at 0?
Thanks the API is awesome!

**Comment by rbnali** [comment]
Same issue here!

**Comment by avnidas** [comment]
Any luck here?

**Comment by PPGDa5id** [comment]
Just for the record.  I never got it to work.  I just kept updating my book mark to the tab I wanted... 
Buuuut when I was refactoring for python3 I ran across pygsheets.  https://pygsheets.readthedocs.io/en/stable/spreadsheet.html#pygsheets.Spreadsheet.add_worksheet
...It's a little work getting Google to play nice...Because Google.
It has worksheet indexing.

**Comment by pandrii000** [comment]
You can reorder worksheets index with `reorder_worksheets`:
https://gspread.readthedocs.io/en/latest/api.html#gspread.models.Spreadsheet.reorder_worksheets

**Comment by lavigne958** [comment]
as mentioned above you can re-order worksheets using the method mentioned above.

Closing this issue.
