### ISSUE TITLE
Improvement of append_row()

### ISSUE THREAD

**Issue by yoihito** [burnash/gspread#462]
Hello :)

I was looking at [append_row() method here](https://github.com/burnash/gspread/blob/master/gspread/models.py#L656) and found out that we can optimize it. Instead of requesting each cell of row one by one, we can request the whole row with one range query, similar to [insert_row() method approach](https://github.com/burnash/gspread/blob/master/gspread/models.py#L686).

What do you think? Do I miss something?

**Comment by faultyfuse** [comment]
It's like the issue with xrange and range, if you're working with small amounts of data that would be accepted but requesting a large set of data might have different issues (speed, memory & etc).

**Comment by yoihito** [comment]
@faultyfuse I see. I stumbled on this when I was appending a lot of rows to a worksheet. Each cell for empty row was loaded with a separate query, it was displayed in the log with debug log level. So I remember that there is [range() method](https://gspread.readthedocs.io/en/latest/#gspread.Worksheet.range) to get a list of cells for a specified range in one query.  

Can we use it to get cells instead of requesting each cell separately?

**Comment by faultyfuse** [comment]
I'd love to see someone implement it just for you, however, I won't be doing that since I don't believe that my programming skills are efficient or good enough to be implementing stuff like this. In Python3 xrange is removed and replaced with range (they stripped it out completely). Or you could fork it and make changes on your own. Hopefully, a developer can help you out on it.

**Comment by yoihito** [comment]
@faultyfuse oh, i should clarify that it's now about python's `range` and `xrange`. It's about `Worksheet.range()`.

**Comment by dmr** [comment]
Ok, so did anything happen here since May? I think append_row is still slow and I'm looking for ways to improve that

**Comment by dmr** [comment]
I didn't try it yet but might 
https://github.com/burnash/gspread/commit/217b43073e1abe9ceb1d65d2d0719d56f0a14642
improve the situation?

**Comment by lavigne958** [comment]
The API is now using the _value append URL_ which allows us to request the whole row to append in a single API call.

Closing this issue.
