### ISSUE TITLE
Instructions on Signed Credentials

### ISSUE THREAD

**Issue by peey** [burnash/gspread#463]
Hi, I think that the instructions on [signed credentials](http://gspread.readthedocs.io/en/latest/oauth2.html#using-signed-credentials) might be outdated. I had to use [drive API wizard link](https://console.developers.google.com/start/api?id=drive) from Google's [quickstart guide](https://developers.google.com/drive/v3/web/quickstart/python) to get my `client_secret.json` file

### Steps to reproduce
1. Log in to a Google account which has never been used to create any API accounts
2. Follow the guide at [readthedocs](http://gspread.readthedocs.io/en/latest/oauth2.html#using-signed-credentials). Create a new project as in step 1
3. Get lost on step 2 because the UI doesn't have any options like “API & auth” 

A screenshot of how the developer console UI looks like
![alt](http://i.imgur.com/npjV33U.png)

**Comment by Anthchirp** [comment]
I found this https://www.twilio.com/blog/2017/02/an-easy-way-to-read-and-write-to-a-google-spreadsheet-in-python.html to be extremely helpful.

**Comment by kornerr** [comment]
@Anthchirp  Thanks a lot! Sharing the document with the service account email was the one little thing I was missing to get GSpread up and running.

**Comment by lavigne958** [comment]
This is now correctly documented. See here in [GSpread doc](https://docs.gspread.org/en/latest/oauth2.html)

Closing this issue.
