### ISSUE TITLE
oauth2client is deprecated, can we use its replacement, google-auth?

### ISSUE THREAD

**Issue by herereadthis** [burnash/gspread#472]
### Environment info

Operating System: osx
Python version: 3.6
gspread version: latest

### Steps to reproduce

Oauth2client documentation says it's deprecated and we should be using [google-auth](https://google-auth.readthedocs.io/en/latest/index.html)

If you try to establish credentials with 

```python
credentials = service_account.Credentials.from_service_account_file(
    'service-account.json')

gc = gspread.authorize(credentials)
```

You'll get this error:

```python
Traceback (most recent call last):
  File "spreadsheet.py", line 19, in <module>
    gc = gspread.authorize(credentials)
  File "/usr/local/lib/python3.6/site-packages/gspread/client.py", line 402, in authorize
    client.login()
  File "/usr/local/lib/python3.6/site-packages/gspread/client.py", line 56, in login
    if not self.auth.access_token or \
AttributeError: 'Credentials' object has no attribute 'access_token'
```

Obviously, the google creditials json file doesn't have an 'access_token' key, so something is amiss there.

If I instead use the deprecated 

```python
scope = ['https://spreadsheets.google.com/feeds']
credentials = ServiceAccountCredentials.from_json_keyfile_name('service-account.json', scope)
gc = gspread.authorize(credentials)
```

It works fine.

**Comment by zenixls2** [comment]
if you want to integrate with google_auth,
I suggest you to do with the session provided by google_auth:

```python
from google.auth.transport.requests import AuthorizedSession
gc = gspread.Client(auth=credentials)
gc.session = AuthorizedSession(credentials)
sheet = gc.open_by_key(spreadsheetId)
print sheet.title
```
refer to https://google-auth.readthedocs.io/en/latest/user-guide.html
and this should work the same as before. just notice that session is from Requests and not httplib2.

**Comment by jaengelberg** [comment]
You can retrieve the credentials using the code found [here.](https://developers.google.com/sheets/api/quickstart/python)  The project could be modified to use this method for authentication.

```python
from __future__ import print_function
import gspread
import httplib2
import os

from apiclient import discovery
from oauth2client import client
from oauth2client import tools
from oauth2client.file import Storage

try:
    import argparse
    flags = argparse.ArgumentParser(parents=[tools.argparser]).parse_args()
except ImportError:
    flags = None

# If modifying these scopes, delete your previously saved credentials
# at ~/.credentials/sheets.googleapis.com-python-quickstart.json
SCOPES = 'https://www.googleapis.com/auth/spreadsheets'
CLIENT_SECRET_FILE = 'client_secret.json'
APPLICATION_NAME = 'Google Sheets API Python Quickstart'


def get_credentials():
    """Gets valid user credentials from storage.

    If nothing has been stored, or if the stored credentials are invalid,
    the OAuth2 flow is completed to obtain the new credentials.

    Returns:
        Credentials, the obtained credential.
    """
    home_dir = os.path.expanduser('~')
    credential_dir = os.path.join(home_dir, '.credentials')
    if not os.path.exists(credential_dir):
        os.makedirs(credential_dir)
    credential_path = os.path.join(credential_dir,
                                   'sheets.googleapis.com-python-quickstart.json')

    store = Storage(credential_path)
    credentials = store.get()
    if not credentials or credentials.invalid:
        flow = client.flow_from_clientsecrets(CLIENT_SECRET_FILE, SCOPES)
        flow.user_agent = APPLICATION_NAME
        if flags:
            credentials = tools.run_flow(flow, store, flags)
        else: # Needed only for compatibility with Python 2.6
            credentials = tools.run(flow, store)
        print('Storing credentials to ' + credential_path)
    return credentials

credentials = get_credentials()
client = gspread.authorize(credentials)
```

**Comment by andrewjmetzger** [comment]
Hi @whatareyoutalkingaboutyousoundinsane 

Please see [my response to you on #529](https://github.com/burnash/gspread/issues/529#issuecomment-384413067).

**Comment by mcarans** [comment]
pygsheets uses google-auth. Perhaps its code could provide inspiration: https://github.com/nithinmurali/pygsheets/blob/staging/pygsheets/authorization.py

**Comment by jacques1609** [comment]
> You can retrieve the credentials using the code found [here.](https://developers.google.com/sheets/api/quickstart/python) The project could be modified to use this method for authentication.
> 
> ```python
> from __future__ import print_function
> import gspread
> import httplib2
> import os
> 
> from apiclient import discovery
> from oauth2client import client
> from oauth2client import tools
> from oauth2client.file import Storage
> 
> try:
>     import argparse
>     flags = argparse.ArgumentParser(parents=[tools.argparser]).parse_args()
> except ImportError:
>     flags = None
> 
> # If modifying these scopes, delete your previously saved credentials
> # at ~/.credentials/sheets.googleapis.com-python-quickstart.json
> SCOPES = 'https://www.googleapis.com/auth/spreadsheets'
> CLIENT_SECRET_FILE = 'client_secret.json'
> APPLICATION_NAME = 'Google Sheets API Python Quickstart'
> 
> 
> def get_credentials():
>     """Gets valid user credentials from storage.
> 
>     If nothing has been stored, or if the stored credentials are invalid,
>     the OAuth2 flow is completed to obtain the new credentials.
> 
>     Returns:
>         Credentials, the obtained credential.
>     """
>     home_dir = os.path.expanduser('~')
>     credential_dir = os.path.join(home_dir, '.credentials')
>     if not os.path.exists(credential_dir):
>         os.makedirs(credential_dir)
>     credential_path = os.path.join(credential_dir,
>                                    'sheets.googleapis.com-python-quickstart.json')
> 
>     store = Storage(credential_path)
>     credentials = store.get()
>     if not credentials or credentials.invalid:
>         flow = client.flow_from_clientsecrets(CLIENT_SECRET_FILE, SCOPES)
>         flow.user_agent = APPLICATION_NAME
>         if flags:
>             credentials = tools.run_flow(flow, store, flags)
>         else: # Needed only for compatibility with Python 2.6
>             credentials = tools.run(flow, store)
>         print('Storing credentials to ' + credential_path)
>     return credentials
> 
> credentials = get_credentials()
> client = gspread.authorize(credentials)
> ```

Thanks a lot. This code saved my night.

**Comment by debu99** [comment]
'ServiceAccountCredentials' object has no attribute 'before_request'

> if you want to integrate with google_auth,
> I suggest you to do with the session provided by google_auth:
> 
> ```python
> from google.auth.transport.requests import AuthorizedSession
> gc = gspread.Client(auth=credentials)
> gc.session = AuthorizedSession(credentials)
> sheet = gc.open_by_key(spreadsheetId)
> print sheet.title
> ```
> 
> refer to https://google-auth.readthedocs.io/en/latest/user-guide.html
> and this should work the same as before. just notice that session is from Requests and not httplib2.

'ServiceAccountCredentials' object has no attribute 'before_request'

**Comment by sboisson** [comment]
@debu99 I had the same issue, and it was fixed by https://github.com/burnash/gspread/issues/664#issuecomment-574087200
