### ISSUE TITLE
Access GSheet named ranges?

### ISSUE THREAD

**Issue by dave-epstein** [burnash/gspread#473]
Hi,

I'm trying to access named ranges in spreadsheets but it seems like there's no support for this. A cursory glance at Google's Sheets API shows what appears to be support, so I was wondering if it's possible for this library to have that functionality added.

Thanks!

**Comment by lavigne958** [comment]
Hi @dave-epstein in the latest version of gspread you'll find a method in the object `Worksheet` `get_all_values(range_name="whatever")` which will return all values in the named range "whatever".

Hope this solves your issue.

Closing this issue.
