### ISSUE TITLE
ConnectionError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')",))

### ISSUE THREAD

**Issue by Spash194** [burnash/gspread#475]
my code:

import gspread
from oauth2client.service_account import ServiceAccountCredentials
import requests
import pandas as pd
import numpy as np
import time

scope = ['https://spreadsheets.google.com/feeds']
credentials = ServiceAccountCredentials.from_json_keyfile_name('My Project-7cdf7008ec6a.json', scope)
client = gspread.authorize(credentials)

sheet = client.open("FiatMoney")
worksheet = sheet.sheet1

a = time.time()

while(1):
        
    r = requests.get('https://poloniex.com/public?command=returnTicker')
    
    json = r.json()
   
    
    ticker = ['BCN', 'DOGE', 'SC',
              'BURST', 'PINK', 'FLDC',
              'DGB', 'STR']
              
    comment = ['(Bytecoin)', '(Dogecoin)','(Siacoin)',
               '(Burst)', '(Pinkcoin)', '(FoldingCoin)',
               '(Digibyte)','(Stellar)'] 
    
    buy_price = ['0.00000056', '0.00000069', '0.00000326',
                 '0.00000339', '0.00000491', '0.00000546',
                 '0.00000668', '0.00000731']
               
    buy_price = np.array(buy_price)
    buy_price = buy_price.astype(dtype=float)   
        
    ticker_index = []
    for i in range(len(ticker)):
        ticker_index.append(ticker[i] + ' ' + comment[i])
               
    columns_index = ['Buy price', 'All time Change', '24hr Change', 'Last price']
    
    df = pd.DataFrame(columns = columns_index, index = ticker_index)
    
    
    for i in range(len(ticker)):
        
        df.iloc[i][3] = float(json['BTC_' + ticker[i]]['last'])
        df.iloc[i][2] = float(json['BTC_' + ticker[i]]['percentChange'])*100
    
    
    df['Buy price'] = buy_price
    df['Buy price'] = ['{:,.8f}'.format(x) for x in df['Buy price']]
    
    df['All time Change'] = ((df['Last price'].values - buy_price)/buy_price)*100
    df['All time Change'] = ['{:,.2f} %'.format(x) for x in df['All time Change']]
    
    df['24hr Change'] = ['{:,.2f} %'.format(x) for x in df['24hr Change']]
    
    df['Last price'] = ['{:,.8f}'.format(x) for x in df['Last price']]
    
    

    for i in range(len(df.index)):
       
        worksheet.update_cell(2+i, 3, df.values[i][1])
            
        time.sleep(3)
            
    worksheet.update_cell(1, 1, time.ctime())   
    

    if time.time() - a > 1500.0:
        
        scope = ['https://spreadsheets.google.com/feeds']
        credentials = ServiceAccountCredentials.from_json_keyfile_name('My Project-7cdf7008ec6a.json', scope)
        client = gspread.authorize(credentials)

        sheet = client.open("FiatMoney")
        worksheet = sheet.sheet1
        
        print(time.time() - a)
        a = time.time()
            

question:

when i update 32 cell at once, my script works within 30 minutes and then i get an error:
ConnectionError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')",))

i decided to make authorization every 25 minutes and decrease number of cells untill 8 and my script has become to work within 2 hours and then again i'm getting the same error:
ConnectionError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')",))

what do i need to change in code in order to get updating cell 24 hours a 7 day in week without errors?

i've already searched in google, here in issues and in tagged 'gspread' -> found nothing

### Environment info

Operating System: windows 7 64
Python version: spyder, python 3.5.2, anaconda 4.2.0 64bit
gspread version: 0.6.2

**Comment by Spash194** [comment]
error happens always in line "worksheet.update_cell(2+i, 3, df.values[i][1])"

**Comment by camwas92** [comment]
Any idea how to fix this?

**Comment by test0z** [comment]
your program need sleep ,maybe 3 or 5 seconds
your requests was block by remote host

**Comment by lavigne958** [comment]
No answer from issue owner for a long time.
The scope has changed.

Closing this issue.
