### ISSUE TITLE
Update to Google Spreadsheet v4 API

### ISSUE THREAD

**Issue by seppestas** [burnash/gspread#482]
A while ago Google released v4 of the Google Sheets API. ["The v4 version is JSON-based, has an easier-to-use interface, and adds a substantial amount of functionality that is not possible in the v3 version."](https://developers.google.com/sheets/api/guides/migration).

Not only would it be interesting to support the new features in gspread, it seems like v4 of the Google Sheets API is currently more stable in terms of uptime.

[Today there were some some issues with the Google Drive API](https://www.google.com/appsstatus#hl=en-GB&v=issue&sid=4&iid=768deb9fad2a675680dbee7e8712bc41) and mostly v3 of the API seemed to be affected. During testing I found the v4 API was still working fine while the v3 API was down.

**Comment by oreniko26** [comment]
Is this planned soon?

**Comment by swoodford** [comment]
@seppestas is it still possible to use the code in this repo with v3 of the API?  where are the v3 endpoints listed since Google updated all their documentation to point to v4?  looking for sheets API in particular.  thanks!

**Comment by seppestas** [comment]
https://developers.google.com/sheets/api/v3/

As stated there though:
> We strongly recommend all developers use the Google Sheets API v4.
Version 3.0 (the version described here), is documented for legacy purposes only, and will eventually be deprecated. We no longer document v1 or v2.

**Comment by nithinmurali** [comment]
I have made an attempt in porting gspread to api v4 [here](https://github.com/nithinmurali/pygsheets). As v4 was substantially different from v3, it became an almost complete rewrite. Its still not as stable as gspread.

**Comment by burnash** [comment]
@seppestas Thank you for laying out the benefits of switching to v4.

`gspread` has been using API v4 by default since [2.0.0](https://github.com/burnash/gspread/releases/tag/v2.0.0) and version [3.0.0](https://github.com/burnash/gspread/releases/tag/v3.0.0) is API v4 only. I think it's safe to close this issue.
