### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Log_SetActiveTarget'

### ISSUE THREAD

**Issue by Rooojie** [burnash/gspread#494]
When running my py program, I face this problem in IDLE window. 
AttributeError: 'module' object has no attribute 'Log_SetActiveTarget'
I have installed wxpython module, however this didn't fix this problem.

Operating System:Windows 10
Python version: 2.7.8

Thanks

**Comment by burnash** [comment]
I believe this is unrelated to gspread. I'm closing this. Please provide more context / stack traceback and feel free to reopen the issue.
