### ISSUE TITLE
Read from public sheet. Is it real?

### ISSUE THREAD

**Issue by yurayakimenko** [burnash/gspread#495]
I add json email to sheet, that is public for web, but I'm not an owner of it. I can get access to my sheets, that I have shared to json email, but such thing don't work for other public sheets. Searched through all issues at StackOverflow and here, but hadn't found any solution!

Thanks a lot!

**Comment by Denielll** [comment]
interesting question

**Comment by lavigne958** [comment]
Hi @yurayakimenko , accessing public sheets works on the latest version of gspread. It works using public link 'Anyone with the link can (edit|view)'. depending on the setting you can either edit the sheet if the link authorize you so or only view it.

If you need any help with gspread check back on [stackOverflow](http://stackoverflow.com/questions/tagged/gspread?sort=votes&pageSize=50) with latest version of gspread.

closing this issue
