### ISSUE TITLE
Add ability to add/remove comments and notes for cells

### ISSUE THREAD

**Issue by archeg** [burnash/gspread#50]
It would be really nice to be able to work with comments or notes via gspread. To be honest, I have doubts whether this is possible with current Google API, but I never worked with it before so I could be wrong. 

If you have any idea, how this possibly could be done, but this feature doesn't fit your plans for the next release, please write it here - I will try to implement it myself. I need it for my own project, though it is not essential, but surely is nice to have.

And thanks for gspread, it is very cool :)

Best Regards,
Iurii

**Comment by msuozzo** [comment]
Comments are supported by the [Drive API](https://developers.google.com/drive/v2/reference/comments) so that would be an option. I couldn't find any reference to notes in any of the API documentation but it seems like @archeg already presented a workable way of doing this.

**Comment by abrkn** [comment]
https://www.bountysource.com/issues/1141847-add-ability-to-add-remove-comments-and-notes-for-cells

**Comment by abdulwahid24** [comment]
It would love to have this feature in `gspread` itself.

**Comment by hexvolt** [comment]
Not sure how it was before, but SpreadSheet API v4 does support this.
This is adapted to gspread https://gist.github.com/hexvolt/4eee9435b9398a17ddd1588ad6d830fe :
```
from gspread.urls import SPREADSHEETS_API_V4_BASE_URL


def insert_note(worksheet, label, note):
    """
    Insert note ito the google worksheet for a certain cell.
    
    Compatible with gspread.
    """
    spreadsheet_id = worksheet.spreadsheet.id
    worksheet_id = worksheet.id

    row, col = a1_to_coords(label)      # [0, 0] is A1

    url = f"{SPREADSHEETS_API_V4_BASE_URL}/{spreadsheet_id}:batchUpdate"
    payload = {
        "requests": [
            {
                "updateCells": {
                    "range": {
                        "sheetId": worksheet_id,
                        "startRowIndex": row,
                        "endRowIndex": row + 1,
                        "startColumnIndex": col,
                        "endColumnIndex": col + 1
                    },
                    "rows": [
                        {
                            "values": [
                                {
                                    "note": note
                                }
                            ]
                        }
                    ],
                    "fields": "note"
                }
            }
        ]
    }
    worksheet.spreadsheet.client.request("post", url, json=payload)
```

**Comment by cryptoteatime** [comment]
Replying in hopes it bumps this issue, since the API has been updated. Would be nice to have this as a simple add_note function to a cell object. 

To anyone else who may be discovering this, you can accomplish this with the latest version of gspread and the [batch_update method](https://gspread.readthedocs.io/en/latest/api.html#gspread.models.Spreadsheet.batch_update).

Your supplied dictionary parameter will be the same as the described parameter `payload` in hexvolts solution.

**Comment by burnash** [comment]
@cryptoteatime Thanks for bumping this.

If anyone is interested in implementing this I'm open for a PR.

**Comment by burnash** [comment]
@hexvolt would you be still interested?

**Comment by TomOnGit** [comment]
I won't be able to implement, but would very much like to be able to add/edit notes and comments via Gspread.

**Comment by lavigne958** [comment]
Hi guys I would be happy to have a look at it. It seems that what is missing is adapting the code snipet above to fit in gpsread then open a PR ?

**Comment by burnash** [comment]
@lavigne958 It's true. Please feel free to submit a PR
