### ISSUE TITLE
StopIteration raised when trying to update a worksheet without write-permission

### ISSUE THREAD

**Issue by suminb** [burnash/gspread#509]
### Environment info

Operating System: Mac OS X 10.13.3
Python version: 3.6.4
gspread version: 0.6.2

### Steps to reproduce
1. Create a Google Spreadsheet.
2. Give an OAuth user a read-only access to the spreadsheet.
3. Call `worksheet.update_cell()` on any worksheet in the spreadsheet.

### Stack trace or other output that would be helpful

When you try to update a cell, a `StopIteration` is raised.

```
  File "web/__main__.py", line 98, in update_geocoordinate                                                                                                                                                  
    worksheet.update_cell(row_index + 1, LATITUDE_COLUMN + 1, str(coordinate[0]))                                                                                                                           
  File ".../.virtualenvs/web/lib/python3.6/site-packages/gspread/models.py", line 515, in update_cell                                                                                              
    uri = self._get_link('edit', feed).get('href')                                                                                                                                                          
  File ".../.virtualenvs/web/lib/python3.6/site-packages/gspread/models.py", line 328, in _get_link                                                                                                
    feed.findall(_ns('link')))                                                                                                                                                                              
  File ".../.virtualenvs/web/lib/python3.6/site-packages/gspread/utils.py", line 27, in finditem   
    return next((item for item in seq if func(item)))                                                                                                                                                       
StopIteration
```

This won't happen if the OAuth user is given a writable-permission on the worksheet. It would be much easier to diagnose the cause of trouble if a more descriptive exception was raised.

**Comment by burnash** [comment]
Thanks for reporting this. I've just released a new gspread version which uses Sheets API v4. Among other significant changes, there's also a change in error reporting. I've tested the new release heavily myself but I'm also looking forward to the community feedback. Can you try the new version to see if it's better?

**Comment by suminb** [comment]
After upgrading gspread to `2.0.0`, it spits out the following error message, which is much more comprehensible than `StopIteration`.

```
(Pdb) worksheet.update_cell(row_index + 1, LATITUDE_COLUMN + 1, coordinate[0])
*** gspread.v4.exceptions.APIError: {
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

I guess I can go ahead and close this issue. Thanks for your work!

**Comment by burnash** [comment]
Great! Thanks for the update!
