### ISSUE TITLE
Quickest update methods

### ISSUE THREAD

**Issue by TravisJoe** [burnash/gspread#51]
I am using this API in a chunk of software for automated testing and uploading resulting data to a spreadsheet to share.

I am noticing some lag on uploads and I can easily work around it, but I want to make sure I am not doing it wrong or there is a much quicker way. Essentially I am updating a cell at a time. The row can change often so I figured it would be easier to go by row number over cell name like "A1".

``` python
workSheet.update_cell(conInfo[0],1,time.strftime("%Y-%m-%d %H:%M:%S", conInfo[1]))
workSheet.update_cell(conInfo[0],2,conInfo[2])
workSheet.update_cell(conInfo[0],3,conInfo[3])
workSheet.update_cell(conInfo[0],4,conInfo[4])
```

**Comment by Aro2220** [comment]
Is there a way to:

```
# Select a cell range
cell_list = worksheet.range('A1:A7')
```

except by using row number and col number instead of the alphanumeric A1, etc?

**Comment by ryantuck** [comment]
@Aro2220 a way to do this would be:

```python
start_col = 1
end_col = 6
start_row = 1
end_row = 30

cell_range = '{col_i}{row_i}:{col_f}{row_f}'.format(
    col_i=chr((start_col-1) + ord('A')),    # converts number to letter
    col_f=chr((end_col-1) + ord('A')),      # subtract 1 because of 0-indexing
    row_i=start_row,
    row_f=end_row)

cells = worksheet.range(cell_range)
```

**Comment by RichardJamesLopez** [comment]
Along the same lines, is there a way to update cells from a dataframe. Right now, I am appending rows to a spreadsheet?

However, my objective is to run this script and be able to overwrite the old values with new values from a df titled "coinArray". Right now, I have 

`
book = gc.open('<spreadsheetname>')
sheet = book.worksheet('<worksheetname>')

for row in coinArray.iterrows():
    sheet.append_row(row[1].tolist())
`

By appending the rows, I am just adding to a list and not replacing existing values.

**Comment by isrj5** [comment]
I have a list which i am updating by taking one element at a time.
`sheet.update_acell("D{}".format(next_row), data_list[0])`
like this. how can push all my list in one row at once.
ps: its a live data so it has to it continuously for each row
