### ISSUE TITLE
Connection Aborted when inserting rows into large spreadsheets

### ISSUE THREAD

**Issue by p-doyle** [burnash/gspread#510]
**Environment info**
Operating System: Windows 10, Ubuntu 16.04
Python version: 2.7.12
gspread version: 0.6.2

This is similar to https://github.com/burnash/gspread/issues/375 however I am receiving the error when trying to insert a row as opposed to updating cells.

When trying to insert a row into a spreadsheet with more than roughly 2000~ rows I get this error:

`('Connection aborted.', error(32, 'Broken pipe'))`

This does not occur when the rows are blank however, only when there is a certain amount of data or formatting...

When attempting to reproduce this error I get a slightly different version than the one I listed above...

**Steps to reproduce:**
1. Create new spreadsheet
2. Insert a row with some test data(this should work):
`sh.insert_row(['1','2','3'])`
3. At the bottom of the spreadsheet click the Add button to manually insert 1000 new rows
4. Try inserting a row with gspread again.  The error I get is:
`requests.exceptions.ConnectionError: ('Connection aborted.', error("(-1, 'Unexpected EOF')",))`

On a side note, deleting the 1000 rows seems to fix the issue...

**Comment by burnash** [comment]
Can you provide your environment info, as outlined in this template: https://github.com/burnash/gspread/blob/master/ISSUE_TEMPLATE.md

**Comment by p-doyle** [comment]
Sorry about that, updated...

**Comment by burnash** [comment]
No problem! Thank you. I see that you're using gspread version 0.6.2. I've just released a new version (2.0.0) which uses Sheets API v4. There are tons of improvement in API v4.  Can you try the new version to see if it fixes the issue?

**Comment by p-doyle** [comment]
Yep that fixed both issues and is so much faster!  Thanks for all your work on this!

The only issue I have is that I can no longer directly insert a datetime object with 2.0.0... I will create a separate ticket for this though.  If I have to convert it to a string on my end that is not the end of the world.

**Comment by burnash** [comment]
Great, I'm happy that it solves the issue!

Let's discuss the solutions for `datetime` in another ticket. I'm closing this.
