### ISSUE TITLE
gspread.v4.exceptions.APIError - Insufficient Permission

### ISSUE THREAD

**Issue by kostykoff** [burnash/gspread#512]
Hello.
After the OS was reinstalled, the script stopped working.
gspread 2.0.0
python 2.7.12

**code**
```
# -*- coding: utf-8 -*- 
import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds']
credentials = ServiceAccountCredentials.from_json_keyfile_name('123.json', scope)
gc = gspread.authorize(credentials)
wks = gc.open("123")
```

**error**
```
Traceback (most recent last call last):
  File "test.py", line 11, in <module>
    wks = gc.open ("123")
  File "/usr/local/lib/python2.7/dist-packages/gspread/v4/client.py", line 103, in open
    self.list_spreadsheet_files ()
  File "/usr/local/lib/python2.7/dist-packages/gspread/v4/client.py", line 80, in list_spreadsheet_files
    r = self.request ('get', url)
  File "/usr/local/lib/python2.7/dist-packages/gspread/v4/client.py", line 73, in request
    raise APIError (response)
gspread.v4.exceptions.APIError: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "insufficientPermissions",
    "message": "Insufficient Permission"
   }
  ],
  "code": 403,
  "message": "Insufficient Permission"
 }
}
```

**Comment by burnash** [comment]
Thanks for reporting this. 

It is probably related to the upgrade of gspread (2.0.0) which now uses Sheet API v4 (the newest version). Can you check if you have Sheets API enabled for the creds you're using in https://console.cloud.google.com/ ?

**Comment by kostykoff** [comment]
Thanks for the answer.
The Google Sheets API is included in https://console.cloud.google.com/ and there are queries.
But `gc.open ("NAME_SHEETS")` does not work for me, it works through only `open_by_key` and `open_by_url`. + problem with reading formulas, see the previous comment.

**Comment by burnash** [comment]
Interesting, I think we're getting close. Let's first figure out the permission problem and then fix the formulas issue. Can you try to enable not only Sheets API in https://console.cloud.google.com/  but also Drive API? (this is what `list_spreadsheet_files` relies on)

**Comment by kostykoff** [comment]
Drive API also included
![1](https://user-images.githubusercontent.com/13411278/37343270-fa2d4b20-2701-11e8-9f70-1fc98920eb2d.png)
![2](https://user-images.githubusercontent.com/13411278/37343271-fa561faa-2701-11e8-8704-9cfad58aa079.png)

**Comment by burnash** [comment]
Ok, not as close as I expected. What do you see when you call `gc.openall()`? The same error?
Can you also try to generate a new json keyfile and use it?

**Comment by abnd90** [comment]
I can confirm the exact same issue. I also tried regenerating service api creds.
``
Traceback (most recent call last):
  File "./main.py", line 94, in <module>
    main()
  File "./main.py", line 81, in main
    sh = gc.open(GSHEET_NAME)
  File "/home/abhinand/dev/pctogs/venv/lib/python3.6/site-packages/gspread/v4/client.py", line 103, in open
    self.list_spreadsheet_files()
  File "/home/abhinand/dev/pctogs/venv/lib/python3.6/site-packages/gspread/v4/client.py", line 80, in list_spreadsheet_files
    r = self.request('get', url)
  File "/home/abhinand/dev/pctogs/venv/lib/python3.6/site-packages/gspread/v4/client.py", line 73, in request
    raise APIError(response)
gspread.v4.exceptions.APIError: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "insufficientPermissions",
    "message": "Insufficient Permission"
   }
  ],
  "code": 403,
  "message": "Insufficient Permission"
 }
}
``

**Comment by burnash** [comment]
Ok, try to change your scope to the following:

```
scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']
```

**Comment by kostykoff** [comment]
Adding to the scope of the https://www.googleapis.com/auth/droke helped open with the help of open.
But the reading of the formulas still gives None.

**Comment by kostykoff** [comment]
temporarily rolled back to gspread == 0.6.2

**Comment by burnash** [comment]
There's a typo in the link in your comment (droke -> drive).

I'm glad we've figured out the issue with permissions. Let's fix the formula issue.

[`inputValue` is deprecated in API v4](https://developers.google.com/sheets/api/guides/migration#edit_a_cell), so I had to [deprecate `Cell.input_value` in gspread accordingly](https://github.com/burnash/gspread/blob/master/HISTORY.rst#200-2018-03-11). Here's the new method to retrieve formulas:

```
workheet.acell('R6', value_render_option='FORMULA').value
```

See, [Sheets API > ValueRenderOption](https://developers.google.com/sheets/api/reference/rest/v4/ValueRenderOption) for other possible values.

**Comment by soad1982** [comment]
I'm having the same issue `insufficientPermissions`  on Version: 2.0.0 adding the scope didn't solve it, just change the error message to:

```
argument 1 must be string or buffer, not None
```

Switching to version 0.6.2 fixes the issue.

The problem happens on an alpine:3.4 container, MAC os works just fine.

**Comment by burnash** [comment]
@soad1982 Please share your code sample and stack traceback

**Comment by Elextric** [comment]
Excellent I had the same problem. 
scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']

Solved it, maybe the scope requirement should be added to the main readme file for the project!

**Comment by Sur2801** [comment]
@burnash 
Dear Sir, 
Thanks a ton. for solving such a terrible "raise APIError(response)" error.

**Comment by petelah** [comment]
Adding the extra scope worked for me.
Also make sure you have sheets and drive api enabled.

**Comment by nibinv23** [comment]
Ha guys i see some of you have some issue with the permission . Just remember that when you enable the google drive api also enable google sheet api as well. It didnt work for me until i enable both the APIs

**Comment by QuiTran86** [comment]
I get the same troubles when I try to insert big data into google sheet, I've done this job before, (not enable drive api but it's not raise errror like this) but now, It raise error like this. I try to find out and figure out that I don't enable drive api, I try to do it and now it seems okay!

**Comment by amilakulathunga** [comment]
my process  is updating google sheet according to the data collection from other process .  data collection process taking time. google sheet update process keep updating the sheet when the other process is given data . This is recurring task . after half of the process i have received this . any idea ? 

gspread.exceptions.APIError: {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
