### ISSUE TITLE
getting 403 insufficient permission error on gspread v2 running fine on 0.6.2

### ISSUE THREAD

**Issue by ahsannaseem** [burnash/gspread#513]
**using credentials.json from google drive api crendtials**

its working without any issue on macbook and when try to amazon linux server it gives insufficent permission error
```
gspread.v4.exceptions.APIError: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "insufficientPermissions",
    "message": "Insufficient Permission"
   }
  ],
  "code": 403,
  "message": "Insufficient Permission"
 }

```
code to connect to sheet
```
import gspread
from oauth2client.service_account import ServiceAccountCredentials
scope = ['https://spreadsheets.google.com/feeds']
creds = ServiceAccountCredentials.from_json_keyfile_name('google_auth.json', scope)
client = gspread.authorize(creds)

sheet = client.open('MySheetName').sheet1
```

**Comment by burnash** [comment]
Looks like it's also related to the scope issue in updated API. As in #512 

Try to update the scope to see if it helps:

```
scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']
```
as in https://github.com/burnash/gspread/issues/512#issuecomment-372708065

**Comment by burnash** [comment]
I've also updated the docs: https://github.com/burnash/gspread/commit/60c5ee3e53558dc383c87a57e1f2ca09f4b1a315

**Comment by burnash** [comment]
@ahsannaseem Let me know if the solution works for you. In the meantime, I'm closing this issue. Feel free to reopen it if you have further information.

**Comment by xijianlim** [comment]
Thanks Burnash,
changing the scope to:

scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']

Worked a treat.

**Comment by seeya** [comment]
Setting the scope to this solves my problem too. Thanks
```
scope = ['https://spreadsheets.google.com/feeds',
'https://www.googleapis.com/auth/drive']
```

**Comment by aurlu** [comment]
Also got the permission denied error when I changed the scope

**Comment by Qcole5** [comment]
Kenny335/aurlu, Did you go on and enable the google drive API as well? I got this same error because I had only enabled the sheets API and not the drive API

**Comment by PiGrammer01** [comment]
Hey, I added second scope and I have enabled both API's but It still returns this error:
`Library/Python/3.4/lib/python/site-packages/gspread/models.py", line 629, in get_all_records
    keys = data[idx]
**IndexError: list index out of range**`

**Comment by pensebien** [comment]
Change the scope to have the two worked for me
` scope =  ['https://spreadsheets.google.com/feeds',
'https://www.googleapis.com/auth/drive']`

I created a **service api** for **Google Drive**. Although after seeing this error, I again created a service api for **Google Sheet**. I enabled **Google Sheet API**.

When I tried disabling it again, I get this error.

**Comment by arjmahadevan** [comment]
> 'https://www.googleapis.com/auth/drive'

This worked for me! Thank you so much @pensebien

**Comment by burnash** [comment]
> Using service_account from google.oauth2 does not give me problems when I'm just using the "https://www.googleapis.com/auth/spreadsheets", scope. I don't really quite understand why drive permissions are required just to retrieve the information of a spreadsheet...

For example, gspread uses drive to open a spreadsheet by its title. See [client.py](https://github.com/burnash/gspread/blob/master/gspread/client.py) for other examples.

**Comment by sp-luciano-chinke** [comment]
> > Using service_account from google.oauth2 does not give me problems when I'm just using the "https://www.googleapis.com/auth/spreadsheets", scope. I don't really quite understand why drive permissions are required just to retrieve the information of a spreadsheet...
> 
> For example, gspread uses drive to open a spreadsheet by its title. See [client.py](https://github.com/burnash/gspread/blob/master/gspread/client.py) for other examples.

Ok! I see now that i can instantiate the Client with my custom credentials scopes. I'll give it a try whenever I can. Thanks!
