### ISSUE TITLE
Batch update rows.

### ISSUE THREAD

**Issue by kunksed** [burnash/gspread#515]
It would be nice to be able to update/append multiple rows by passing a list of lists. Batching queries would take the load off having to make multiple queries, especially while operating over microservices.

**Comment by burnash** [comment]
I agree. It seems like Sheets API v4 is capable of this.

**Comment by crash5936** [comment]
What I did as a workaround was this

```
cells = []
for row_num, row in enumerate(array):
    for col_num, cell in enumerate(row):
        cells.append(gspread.Cell(row_num + 1, col_num + 1, list_of_lists[row_num][col_num]))

worksheet.update_cells(cells)
```

Where list_of_lists contains the values in a 2D array format. I think this could actually be implemented as a `gspread.models.Worksheet` method, I'll try to look into that.

**Comment by strogonoff** [comment]
> I think this could actually be implemented as a `gspread.models.Worksheet` method, I'll try to look into that.

I don’t know whether this aligns with the design principles behind gspread, or perhaps I’m missing an already existing way to do this, but I imagine the library could [offer a context processor](https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager) which would batch changes made by other methods (`insert_row()` et al) and commit them with one efficient `update_cells()` afterwards.

From user’s perspective it would be like

```python
with ws.batch_update():
  ws.insert_row(…)
  ws.insert_row(…)
```

…where mutating calls don’t get executed immediately—instead behind the scenes `batch_update()` keeps track of cell range affected, calculates a diff, builds a new cell array, and issues the minimum number of mutating calls possible (probably `update_cells()` in most cases).

Again, if the goal is to mimic raw Google Sheets APIs as closely as possible in Python then this might not fit the philosophy. That aside it could be a very convenient way.

**Comment by lavigne958** [comment]
This is a great idea, I'll keep this in mind but this is not easy to introduce **and** keep the current behavior.

If anyone is willing to start on it, feel free. otherwise it would have to wait a little bit, I first would like to finish sorting out the code, linting the code and enabling back the Test suite.

**Comment by lavigne958** [comment]
batch update already exists in latest version of gspread.

closing this issue.
