### ISSUE TITLE
append_row - APIError - cells limit

### ISSUE THREAD

**Issue by ilivans** [burnash/gspread#516]
### Environment info

Operating System: Ubuntu 16.04 LTS
Python version: Python 3.6.3
gspread version: 2.0.0

### Steps to reproduce
1. sheet = spreadsheet.add_worksheet("tmp", 1000, 26)
2. sheet.append_row(["Test"], value_input_option='RAW')

### Stack trace
```
~/.virtualenvs/cmn36/lib/python3.6/site-packages/gspread/v4/models.py in append_row(self, values, value_input_option)
    639         }
    640 
--> 641         return self.spreadsheet.values_append(self.title, params, body)
    642 
    643     def insert_row(

~/.virtualenvs/cmn36/lib/python3.6/site-packages/gspread/v4/models.py in values_append(self, range, params, body)
     96         url = SPREADSHEET_VALUES_APPEND_URL % (self.id, range)
     97         print(url, params, body)
---> 98         r = self.client.request('post', url, params=params, json=body)
     99         return r.json()
    100 

~/.virtualenvs/cmn36/lib/python3.6/site-packages/gspread/v4/client.py in request(self, method, endpoint, params, data, json, files)
     71             return response
     72         else:
---> 73             raise APIError(response)
     74 
     75     def list_spreadsheet_files(self):

APIError: {
  "error": {
    "code": 400,
    "message": "This action would increase the number of cells in the workbook above the limit of 2000000 cells.",
    "status": "INVALID_ARGUMENT"
  }
}

```

I know that the error says cells limit is exceeded, though there are no even close number of cells in the document, even in the whole Google Drive. What is strange is that I don't always get this error such way. And if I add a page manually in web browser, then append_row works fine.

Is there any idea of a reason?

**Comment by lavigne958** [comment]
This has been solved after upgrading the method `insert_row`.

Tested it on latest version and it works fine.

Closing this issue.
