### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'get_cells_feed'

### ISSUE THREAD

**Issue by Kirkman** [burnash/gspread#520]
### Environment info

Operating System: Windows
Python version: 2.7.14
gspread version: 2.0.0

I'm trying to run `sheetsync`, which is built on top of gspread. 

I had code using sheetsync and gspread which worked fine prior to upgrading. After upgrading to gspread 2.0.0, though, I get the following error:

````
  File "C:\Users\XXXXX\Envs\sheetsync-test\lib\site-packages\sheetsync\__init__.py", line 413, in __init__
    self._get_or_create_headers()
  File "C:\Users\XXXXX\Envs\sheetsync-test\lib\site-packages\sheetsync\__init__.py", line 705, in _get_or_create_headers
    for cell in self._cell_feed(row=self.header_row_ix):
  File "C:\Users\XXXXX\Envs\sheetsync-test\lib\site-packages\sheetsync\__init__.py", line 686, in _cell_feed
    raise e
AttributeError: 'Client' object has no attribute 'get_cells_feed'
````
I'm confused, because it seems like gspread 2.0.0's `client.py` is structured pretty much the same as before. It does still have a method `get_cells_feed()`. Can you give me any guidance? Is a change needed in sheetsync?

**Comment by burnash** [comment]
Correct. `client.py` is the same as in the previous version. However, in 2.0.0 authorize uses `gspread.v4.Client` by default:

https://github.com/burnash/gspread/blob/b466cc95d07c79e5842bde14101611a4c4d437e5/gspread/__init__.py#L28-L41

I think that's the key to this issue. 

Anyway thanks for bringing this up. I decided to default to Sheets API v4 in 2.0.0 to facilitate migration to the newer API, but it looks like I didn't consider enough gspread usage as a dependency.

**Comment by lavigne958** [comment]
This is an old issue, no response from issue owner, considered solved or not up to date with latest release.

@Kirkman if you still encounter this issue, please let us know here so we can investigate with a more recent version of gspread.

Closing this issue.
