### ISSUE TITLE
Single quotes being added to numbers in spreadsheet

### ISSUE THREAD

**Issue by mschulz** [burnash/gspread#524]
I just upgraded to 2.0.0. Now when numbers are added to the spreadsheet they are preceded with a ' but this did not happen in the previous version.

Is there a way to turn this feature off as I already add the ' to the numbers when needed?

**Comment by burnash** [comment]
Can you share the code snippet you're using for inserting the numbers?

**Comment by mschulz** [comment]
The code is spread across a number of classes.  The output change on the Google sheet is shown here (no code was change, just an update to the latest version to take adavantage of the huge increase in speed in accessing the sheets):
![image](https://user-images.githubusercontent.com/139973/37942136-0491f198-31b5-11e8-8ed3-5d989ab5a56b.png)

Note that the Date and time columns now have data preceded with the '.  You can see the additional ' in the phone number column.  String data does not appear to be affected.

The code which builds the array from the class data:

    def makeBookingList(self):
        valueList = []
        for key in self.values:
            if key in self.booking:
                valueList.append(self.booking[key])
            else:
                valueList.append('')
        return valueList

and the code to drop this data into the sheet is:

    def appendRow(self, values, year):
        self.getSheet(year)
        self.worksheet.append_row(values)

I am not sure if these snippets gives enough of a clue though.

**Comment by mschulz** [comment]
I have looked into this further and have a couple of observations.

When a row is appended to a sheet it does not inherit the existing formatting of the column, e.g., when a date cell is appended to a date column it is not recognized as a date cell. I am seeing the same for time cells, number cells and money cells.  They get appended as text strings.  I then need to go and apply the correct formatting for the cells manually.  This was not something I had to do with the previous version of gspread.

Is there a way for me to create the cells with the correct formatting while using append_row?

**Comment by andrewjmetzger** [comment]
@mschulz Creating cells with correct (date) formatting is indeed possible with `append_row()` and `update_cell()`.

Here's the code I use. It is not terribly efficient, but it works, and should point you in the right direction. Note that this assumes that you pass a name as `name: str` in double quotes and a date (in a format Sheets will recognise) as `my_date: str` in double quotes. For example, `makeBookingList("John Smith" "2017-03-21")`

This allows Sheets to properly format the date, for example in a format such as ISO 8601:
![image](https://user-images.githubusercontent.com/590246/38474425-ae054d7c-3b6c-11e8-93fe-683ddf2e211d.png)

```python
# Reset column variables for a new record
tmp_name = name
tmp_date = ""  # Note the empty str

# Create a list[] with an element each column in a record
tmp_row = [tmp_name, tmp_date]
# Append the row
worksheet.append_row(tmp_row)

# Find the row we just appended.
target_cell = worksheet.find(name)
target_row = target_cell.row

# Fix the date by overwriting the cell with the value of the (proper) date string you passed
# In this case, the date is in column 2
# This should remove the errant single-quote
sheet.update_cell(target_row, 2, my_date)
```

I hope this helps. Let me know if you have any questions. :-)

**Comment by CarlFredrik** [comment]
This can be solved by changing the input method to user entered:
E.g.
`worksheet.update_cells(cells, 'USER_ENTERED')`

Possible values:
https://developers.google.com/sheets/api/reference/rest/v4/ValueInputOption

**Comment by mschulz** [comment]
@andrewjmetzger @CarlFredrik Many thanks for your help with this issue.  Everything now works fine.

**Comment by shegokarm** [comment]
@CarlFredrik your answer resolved the issue. Thanks!

**Comment by kamel3d** [comment]
I have this issue when using php API, is there a solution to solve it on PHP side?

**Comment by andrewjmetzger** [comment]
@kamel3d gspread is a Python project, not PHP. Google Docs does provide a PHP API, but it is not supported here.

PHP API documentation: [https://developers.google.com/sheets/api/quickstart/php](https://developers.google.com/sheets/api/quickstart/php)

**Comment by kamel3d** [comment]
@andrewjmetzger thank you I found a solution shortly after my question is basically by using "USER_ENTERED" instead of "RAW" it is the same for both languages

**Comment by dfredmen** [comment]
> @CarlFredrik Thanks! `sheet.append_row(d, value_input_option='USER_ENTERED')` working fine for me.

when I try this, I am seeing the following error:

`TypeError: append_row() takes exactly 2 arguments (3 given)`

Any suggestions?

**Comment by dfredmen** [comment]
@burnash have you come across this at all? I am wondering if anything could have changed since this thread simmered down last and today. Gspread docs still indicate that this should work if I am on 3.6 - https://gspread.readthedocs.io/en/latest/api.html?highlight=insert_row

**Comment by lavigne958** [comment]
This is getting off-topic, The original issue has been resolved.

@dfredmen please open a new issue with content related to your problem and we'll solve it from there.
Your link points toward the latest release of the doc, so looking at it right now show the function `append_row` with 1 mandatory argument and your example seem to match the documentation (needs to be checked in the source code and tested too).

closing this issue.
