### ISSUE TITLE
gspread.v4.exceptions.APIError - UNAUTHENTICATED

### ISSUE THREAD

**Issue by ninoM** [burnash/gspread#528]
Python version: 3.6
gspread version: 2.0.0

Honestly I don't know what happened. One day it was working and the next day (today) authentication is failing. 

**Code**
```python
scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_name(
    "client-secret.json",
    scope
)
client = gspread.authorize(creds)
spreadsheet_key = "28934823459U24IR904RUI0924UR02834UR"
sheet = client.open_by_key(spreadsheet_key).worksheet("Log")
```

**Error**

    2018-04-03T09:40:08.062563+00:00 app[web.1]: gspread.v4.exceptions.APIError: {

    2018-04-03T09:40:08.062565+00:00 app[web.1]:   "error": {

    2018-04-03T09:40:08.062566+00:00 app[web.1]:     "code": 401,

    2018-04-03T09:40:08.062572+00:00 app[web.1]:     "message": "Request had invalid authentication      credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",

    2018-04-03T09:40:08.062573+00:00 app[web.1]:     "status": "UNAUTHENTICATED"

    2018-04-03T09:40:08.062574+00:00 app[web.1]:   }

    2018-04-03T09:40:08.062576+00:00 app[web.1]: }

I checked issue #512 but I already had the right scope from the very start.

**Comment by h0r1zon** [comment]
I'm also getting this error periodically, requires me to restart the code.

**Comment by andrewjmetzger** [comment]
I also get this issue constantly. It's temporarily resolved by a restart, but that's not viable long-term.

Versions:
 - python (3.6.3)
 - google-api-python-client (1.6.6)
 - gspread (2.0.1)

Here's the relevant code:

```python
    scope = ['https://spreadsheets.google.com/feeds',
             'https://www.googleapis.com/auth/drive']
    credentials = ServiceAccountCredentials.from_json_keyfile_name('credentials.json', scope)
    session = gspread.authorize(credentials)
    doc = session.open_by_key('<REDACTED>')
    sheet = doc.get_worksheet(1)
    logging.info("--------")
    logging.info("Opened doc: " + str(doc.title))
    logging.info("Selected sheet: " + str(sheet.title))
    logging.info("Number of rows: " + str(sheet.row_count))
    logging.info("--------")
```

Here's the relevant portion of my log:

```python
Ignoring exception in command track whois
Traceback (most recent call last):
  File "..\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "bot.py", line 409, in whois
    target_row = sheet.find(player_name).row
  File "..\lib\site-packages\gspread\v4\models.py", line 743, in find
    return self._finder(finditem, query)
  File "..\lib\site-packages\gspread\v4\models.py", line 717, in _finder
    data = self.spreadsheet.values_get(self.title)
  File "..\lib\site-packages\gspread\v4\models.py", line 107, in values_get
    r = self.client.request('get', url, params=params)
  File "..\lib\site-packages\gspread\v4\client.py", line 79, in request
    raise APIError(response)
gspread.v4.exceptions.APIError: {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "..\lib\site-packages\discord\ext\commands\core.py", line 634, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "..\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "..\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: APIError: {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}
```

**Comment by ninoM** [comment]
I found out the issue. It's because the oAuth key generated expires. That's why the restarts help. So just generate another oAuth key. In particular, these are the lines you'll have to run periodically

```python
creds = ServiceAccountCredentials.from_json_keyfile_name(
    "client-secret.json",
    scope
)
client = gspread.authorize(creds)
```

I think each key only lasts about an hour? Anyway this is an intended feature  when using Google's APIs.

**Comment by cryobry** [comment]
I'm having the same issue, even when regenerating a new OAuth key frequently within my looping script. I wonder if it pulls the same key through an hour and then needs to regenerated ON the hour or directly after it. I need some way to catch this exception so I can restart the loop immediately, otherwise my script hangs on this error.

**Comment by tongrow** [comment]
Same error for me. This code (executed periodically) doesn't help:
```
creds = ServiceAccountCredentials.from_json_keyfile_name(
    "client-secret.json",
    scope
)
client = gspread.authorize(creds)
ss = client.open_by_key('secret')
```

**Comment by Shubbler** [comment]
Hi, I'm having the same issue.

But only when using `find` or `findall`.

It seems that anyone who does have this issue is only having it when using one of these methods ^

Any suggestions?

**Comment by guztaka** [comment]
Hi, I think this will help you.
https://stackoverflow.com/questions/45914349/python-gspread-request-error-401

The access_token have a lifetime so you have to do a simple `gc.login()`

**Comment by raivatshah** [comment]
Why was this issue closed without a solution?
