### ISSUE TITLE
Feature request - formating of cells

### ISSUE THREAD

**Issue by FinnFrotscher** [burnash/gspread#531]
Is it possible to style cells?
Background, font-size, font-style?

I read that it was not, but that was in 2015. Does the negation still hold up?

**Comment by robin900** [comment]
With gspread's move to the v4 API, formatting of cells is now possible.

I have a working branch (no test coverage, but live interactive testing works great) that implements basic formatting of cells by range:

https://github.com/robin900/gspread/tree/support-cell-formats

**Comment by robin900** [comment]
@burnash Would you like me to turn https://github.com/robin900/gspread/tree/support-cell-formats into a pull request?

Here's a gist of a live test of the branch:

```
import gspread
from gspread.format import *

gc = gspread.authorize(your_credentials)

ssh = gc.open_by_key(your_sheet_key)

ws = ssh.sheet1

fmt = cellFormat(
    backgroundColor=color(1, 0.9, 0.9),
    textFormat=textFormat(bold=True, foregroundColor=color(1, 0, 1))
    )

ws.resize(frozen_rows=1)
ws.format_range('A1:J1', fmt)
```

**Comment by xhe123** [comment]
Is it possible to add the feature of Cell Formats recently? I am also waiting for this feature for a long time.

**Comment by xhe123** [comment]
After checked the @robin900's PR, I think it will be enough to format cell. Will it be merged recently?

**Comment by shrx** [comment]
@robin900 is it possible to get (read) the chosen cell's format?

**Comment by robin900** [comment]
@shrx This PR became its own PyPI package, `gspread-formatting`. That package provides `get_default_format(worksheet, label)` and `get_effective_format(worksheet, label)` to retrieve format for a particular cell:

```
from gspread_formatting import *

wsh = get_some_worksheet()
fmt = get_effective_format(wsh, 'A1')
```

https://pypi.org/project/gspread-formatting/

**Comment by burnash** [comment]
Basic implementation in #731 
For more elaborated use cases: [gspread-formatting](https://github.com/robin900/gspread-formatting)
