### ISSUE TITLE
Error installing gSpread with pip.  /tmp/pip-build-xxxxx/gspread/docs/index.txt No such file or directory.

### ISSUE THREAD

**Issue by CmdrSpiff** [burnash/gspread#535]
**GitHub Issues are for bugs and feature requests.**

Please do not post usage questions here. For general support from the community, see StackOverflow: http://stackoverflow.com/questions/tagged/gspread

Issues with usage questions will be closed.

For bugs please provide the following information.

### Environment info

Operating System:  Raspbian Stretch, updated today
Python version: 2.7.13
gspread version: 2.1.0

### Steps to reproduce
1. sudo pip install gspread
2. pip install gspread
3. sudo pip install gspread --no-cache-dir

### Stack trace or other output that would be helpful

![image](https://user-images.githubusercontent.com/38147119/38449482-ba81cc3c-39dd-11e8-8d2b-250418088845.png)

**Comment by CmdrSpiff** [comment]
In looking again, this seems to be very similiar to issue #533, but this is still occurring.

**Comment by JCardenete** [comment]
Happening to me as well.

**Comment by burnash** [comment]
@CmdrSpiff @JCardenete I think it has been fixed by @reallistic in #534. Can you please check if the fix works for you?

**Comment by CmdrSpiff** [comment]
This is working for me now.  Installed 2.1.1 successfully.  Thanks!

**Comment by burnash** [comment]
@CmdrSpiff thanks for the feedback and for the issue. Kudos to @reallistic for the fix
