### ISSUE TITLE
Write a dictionary in the sheet

### ISSUE THREAD

**Issue by Ricardosgeral** [burnash/gspread#540]
Hi
get_all_records is great but i don't think it does what i want.

I'm reading 20 sensors at once and i want to pass them to the sheet every 10 seconds.
Data is in a dictionary format.
If i update entries one by one it takes a long time ( >10 seconds).
Is there a way to use the gspread to write the data of a dictionary at once.

something like DictWriter in CSV module!

thanks

**Comment by burnash** [comment]
Can you share a snippet of code you're using? Feel free to remove/replace any sensitive parts. Just to get a better idea of the workflow.

**Comment by Ricardosgeral** [comment]
I Anton
I don't have any code, that's my problem

I have a dictionary like

```

```

and i want to write the dictionary in the sheet. It should use the keys has header and each row is placed below.

The workflow should be similar as that in writerdict used in csv module 
 

```
import csv

mydict = [ 'date':            date_,
             'time':             time_,
             'upstream':     p_up,
             'interface':      p_int,
             'download':    p_down,
          ]

with open('mycsvfile.csv', 'wb') as f: 
    w = csv.DictWriter(f, my_dict.keys())
    w.writeheader()
    w.writerow(my_dict)
```

that is it is necessary to define the Class Dictwriter and the module whiterow

Is there a way to do something similar in gspread at this time?

thanks

**Comment by Ricardosgeral** [comment]
https://github.com/python/cpython/blob/master/Lib/csv.py

**Comment by keliomer** [comment]
No need to write one value at a time, that's what [update_cells](http://gspread.readthedocs.io/en/latest/index.html?highlight=update_cells#gspread.models.Worksheet.update_cells) is for.

I use something similar to the code below (for new sheets):
```python
    # authorize
    gc=gspread.authorize(...)
    ss=gc.open(<sheet name>)
    # with a brand new sheet
    sheet = ss.add_worksheet('test',1,2)
    # The header
    header = ['col1', 'col2']
    sheet.append_row(header)
    # here's your 'data'
    test_data = [{'col1' :'1A', 'col2': '2A'}, {'col1': '1B', 'col2': '2B'}]
    # add the number of rows your data contains
    sheet.add_rows(len(test_data))
    # Find the first and last row in the range you'll be updating
    # We know what the range will be because we just made the sheet
    # If working with an existing sheet you'll need to do this differently to make sure you don't overwrite cells
    cell_range = sheet.range('A2:B3')
    # flatten the list of dicts into a list of values in order
    flattened_test_data = []
    for row in test_data:
        for column in header:
            flattened_test_data.append(row[column])

    for i, cell in enumerate(cell_range):
        cell.value = flattened_test_data[i]

    sheet.update_cells(cell_range)
```
You'll obviously need to tweak this to suit your needs but  this should get you headed in the **_write_** direction. 😁 

You could also use [import_csv](http://gspread.readthedocs.io/en/latest/index.html?highlight=update_cells#gspread.Client.import_csv), though that would require you to have a csv with the data locally. (Which probably isn't a bad idea anyway!)

**Comment by Ricardosgeral** [comment]
Thanks @keliomer
I will try

**Comment by lavigne958** [comment]
Issue is solved. Closing it
