### ISSUE TITLE
gspread.authorize not refreshing access token

### ISSUE THREAD

**Issue by cryobry** [burnash/gspread#541]
I have a looping script that takes approximately 5 minutes to run. At the beginning of every loop I rerun gspread.authorize with my service account key credentials. The script runs great for about an hour and then freezes and errors out with:
```
  File "/home/cryobry/.local/lib/python3.6/site-packages/gspread/client.py", line 
79, in request                                                                  
    raise APIError(response)                                                    
gspread.exceptions.APIError: {                                                  
  "error": {                                                                    
    "code": 401,                                                                
    "message": "Request had invalid authentication credentials. Expected OAuth 2
 access token, login cookie or other valid authentication credential. See https:
//developers.google.com/identity/sign-in/web/devconsole-project.",              
    "status": "UNAUTHENTICATED"                                                 
  }                                                                             
} 
```
There are two issues here:

1. The access token is not being refreshed correctly.

2. I use a try/except block to catch APIError exceptions in my script. This works great whenever I exceed the google api maxrequests USER-100s, so I can issue a cooldown. But the error I posted above is not picked up as an exception until I break the script manually.

**Comment by FranciscoJRSantos** [comment]
This is happening to me as well, and trying to reauthenticate whenever I need to write to the sheet isn't doing anything. Any solution to this?

**Comment by cryobry** [comment]
I refactored my code and the issue stopped happening, which is why I closed the issue. My guess is that there is some edge case regarding the frequency of API calls and reauthorization.

However, now after about three hours of running the new code, I've got this problem cropping up:

```
  File "/home/cryobry/.local/lib/python3.6/site-packages/gspread/__init__.py", line 38, in authorize
    client.login()
  File "/home/cryobry/.local/lib/python3.6/site-packages/gspread/client.py", line 51, in login
    self.auth.refresh(http)
  File "/usr/lib/python3.6/site-packages/oauth2client/client.py", line 545, in refresh
    self._refresh(http)
  File "/usr/lib/python3.6/site-packages/oauth2client/client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "/usr/lib/python3.6/site-packages/oauth2client/client.py", line 819, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Invalid JWT: No valid verifier found for issuer.
```

**Comment by FranciscoJRSantos** [comment]
Damn that helped a lot, I just remembered that I may be exceeding the quota of requests allowed by Google! Thanks a lot @cryobry  😃
