### ISSUE TITLE
Feature Request: Freezing Rows/Columns and Other Worksheet Formatting

### ISSUE THREAD

**Issue by starryjapostoli** [burnash/gspread#543]
I was thinking it would be really cool to implement a way to format worksheets using the gspread Worksheet class, like freezing rows/columns.  They could be class methods and calling something like worksheet-instance.freeze_row(n) could freeze the first n rows.

**Comment by aiguofer** [comment]
This should be fairly straightforward. I do this in gspread-pandas at https://github.com/aiguofer/gspread-pandas/blob/master/gspread_pandas/client.py#L706

Most of that stuff can be done with batch_update, but having easy to use functions is definitely useful. Another one I'm looking to add is the auto-filter. If I have time I'll look into back-porting them into gspread.

**Comment by motin** [comment]
Note: This is already achievable using a separate package: https://pypi.org/project/gspread-formatting/
