### ISSUE TITLE
Insufficient Permission (gspread)

### ISSUE THREAD

**Issue by ampifyx** [burnash/gspread#555]
**GitHub Issues are for bugs and feature requests.**

Please do not post usage questions here. For general support from the community, see StackOverflow: http://stackoverflow.com/questions/tagged/gspread

Issues with usage questions will be closed.

For bugs please provide the following information.

### Environment info

Operating System: macOS
Python version: 3
gspread version: newest? (just pip installed it)

### Steps to reproduce
1. Try run my code

### Stack trace or other output that would be helpful
This is my code I try to run

`import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope = {'https://spreadsheets.google.com/feeds/', 'https://docs.google.com/feeds'}

credentials = ServiceAccountCredentials.from_json_keyfile_name('sheetjson.json', scope)

gc = gspread.authorize(credentials)

wks = gc.open('mcresolve').sheet

print(wks.cell(1, 2))`
I'm very new to python and I'm trying to make a database searcher using google spreadsheet.
Now I'm trying to get information of a specific cell but it doesn't seem to connect.

**Comment by maiafernando** [comment]
Your `scope` variable should be a list, not a dictionary. Try defining it this way:

```python
scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
```

**Comment by ampifyx** [comment]
When I do that I get this error

` wks = gc.open('mcresolve').sheet
AttributeError: 'Spreadsheet' object has no attribute 'sheet'`

**Comment by maiafernando** [comment]
Maybe try `sheet1` instead of `sheet`.

**Comment by ampifyx** [comment]
That worked!

**Comment by maiafernando** [comment]
That's awesome @ampifyx! Now that the problem is solved, would you please close this issue? Thanks!

**Comment by burnash** [comment]
@maiafernando thank you very much for your help!

I'm closing this issue.
