### ISSUE TITLE
Hi,hope you are still providing support. 

### ISSUE THREAD

**Issue by arshiyak9** [burnash/gspread#559]
**GitHub Issues are for bugs and feature requests.**

Please do not post usage questions here. For general support from the community, see StackOverflow: http://stackoverflow.com/questions/tagged/gspread

Issues with usage questions will be closed.

For bugs please provide the following information.

### Environment info

Operating System: osx
Python version:2.7
gspread version: 3.00

### Steps to reproduce
1. gc = gspread.authorize(credentials)
2.spreadsheet = gc.open('file.csv')
    worksheet = spreadsheet.add_worksheet('data_'+ time.strftime("%Y%m%d %H:%M:%S"), 1000, 100)
3. worksheet.insert_row(['alpha','beta'], index=1, value_input_option='RAW')

### Stack trace or other output that would be helpful
File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gspread/models.py", line 737, in insert_row
    self.spreadsheet.batch_update(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gspread/models.py", line 93, in batch_update
    json=body
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gspread/client.py", line 79, in request
    raise APIError(response)
gspread.exceptions.APIError: {
  "error": {
    "code": 400,
    "message": "Requested writing within range ['data_20180617 01:48:18'!A2], but tried writing to column [B]",
    "status": "INVALID_ARGUMENT"
  }
}

works fine if I pass only one value in the list. I have already searched StackOverflow. couldn't find any solution.

**Comment by patcon** [comment]
Can we close this in favour of https://github.com/burnash/gspread/issues/551 (it seems this is a dup, and that one has more details :) )

**Comment by lavigne958** [comment]
This is duplicate closing this issue.
