### ISSUE TITLE
input_value to get formula not working

### ISSUE THREAD

**Issue by trandam11** [burnash/gspread#561]
### Environment info

Operating System: macOS 10.13.5
Python version: 2.7
gspread version: 3.0.0

### Steps to reproduce
worksheet.update_acell('B9','=HYPERLINK("google.com","Link to google.com")')
cell = worksheet.acell('B9')
print cell.input_value

Output shows as None

### Stack trace or other output that would be helpful
No errors

**Comment by northtree** [comment]
I had same issue with you. After reading the source code, I found _input_value_ is deprecated after Sheet API v4.
https://github.com/burnash/gspread/blob/c0a5a6d83083c467a647ab91bf1caaa1f829b5c7/gspread/models.py#L867

You could use `b3 = self.sheet.acell('B3', value_render_option='FORMULA')` to grab the formula.

**Comment by scastillo** [comment]
This is not on the documentation right?
