### ISSUE TITLE
Cannot access cell with unicode content

### ISSUE THREAD

**Issue by SuperCobra2017** [burnash/gspread#564]
### Environment info

Operating System: win10
Python version: 2.7.15
gspread version: 3.0.0

### Steps to reproduce
1. Googlesheet has column names in unicodes
2. Try to access it

### Stack trace or other output that would be helpful

<ipython-input-189-ad77334b8fa9> in read_googlesheets(gsnum, gsurl)
     13 
     14 #     return worksheet
---> 15     a = worksheet.cell(1, 1)
     16     print (a)
     17     return a

C:\Users\User\Anaconda2\lib\site-packages\gspread\models.pyc in cell(self, row, col, value_render_option)
    379         data = self.spreadsheet.values_get(
    380             range_label,
--> 381             params={'valueRenderOption': value_render_option}
    382         )
    383 

C:\Users\User\Anaconda2\lib\site-packages\gspread\models.pyc in values_get(self, range, params)
    107 
    108     def values_get(self, range, params=None):
--> 109         url = SPREADSHEET_VALUES_URL % (self.id, quote(range, safe=''))
    110         r = self.client.request('get', url, params=params)
    111         return r.json()

C:\Users\User\Anaconda2\lib\urllib.pyc in quote(s, safe)
   1296     if not s.rstrip(safe):
   1297         return s
-> 1298     return ''.join(map(quoter, s))
   1299 
   1300 def quote_plus(s, safe=''):

KeyError: u'\u042d'

**Comment by burnash** [comment]
Thanks for reporting this. The stack trace looks very similar to https://github.com/burnash/gspread/issues/544

Do you have a worksheet with unicode chars as well?

**Comment by SuperCobra2017** [comment]
Yes, I do.
Are you planning to fix that anytime soon?

**Comment by burnash** [comment]
Sure, sorry for the delay. Fixed in #610 and #628
Available in version 3.1.0
