### ISSUE TITLE
jupyter kernel dies when using gspread - no tracebacks

### ISSUE THREAD

**Issue by wttrz** [burnash/gspread#567]
Environment info:

OS - OS X 10.13.3
Python - 3.7
Gspread - 3.0.1

Steps:

Requirements: `pipenv`

- Create an empty folder
- Move in the folder and do the following

```
pipenv --three

pipenv install jupyter
pipenv run python3 -m ipykernel install --user --name=$PROJECT
pipenv install jupyterlab
```

- Install `pandas`, `gspread`, `oauth2client`
- Run the following

```
import gspread
import pandas as pd
import numpy as np
import datetime as dt
import itertools
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']

creds = ServiceAccountCredentials.from_json_keyfile_name('service.json', scope)

gc = gspread.authorize(creds)

records1 = gc.open('sheetname').get_worksheet(0).get_all_records()
records2 = gc.open('sheetname').get_worksheet(1).get_all_records()

df = pd.DataFrame(records1)
dt = pd.DataFrame(records2)

df.head()
```
Whent it's time to interact with the spreadsheet the kernel dies (or the scripts fail).

Outputs

<img width="1153" alt="screen shot 2018-07-17 at 10 10 41" src="https://user-images.githubusercontent.com/8994002/42807277-a6325530-89b0-11e8-874f-7c302b4fc99b.png">
<img width="900" alt="screen shot 2018-07-17 at 10 10 56" src="https://user-images.githubusercontent.com/8994002/42807278-a66103c6-89b0-11e8-809a-fb1e7227c8f0.png">

**Comment by 2af** [comment]
1 of my spreadsheets opens and reads normally,
**the other one kills kernel as soon as use get_all_records()**
any progress here?

**Comment by 2af** [comment]
> 1 of my spreadsheets opens and reads normally,
>...

**conda update pandas**
seems to have helped it!

**Comment by lavigne958** [comment]
Issue seems to be solved by user.

Closing issue.
