### ISSUE TITLE
Option to turn off automatic type conversion with get_all_records

### ISSUE THREAD

**Issue by adace123** [burnash/gspread#568]
I have a case where I need to keep the leading zeros of a numeric column. Therefore, I'd like to have the option to turn off type conversion. Thanks.

**Comment by gnilrets** [comment]
I ran into this one today and would also appreciate a way to handle this.  Looks like there was attempt to solve it here - https://github.com/burnash/gspread/issues/581, but the PR was closed for some unknown reason.

**Comment by burnash** [comment]
Implemented in #701
