### ISSUE TITLE
cell.value from cell_list adds a tick when setting a formula

### ISSUE THREAD

**Issue by nmmanas** [burnash/gspread#569]
### Environment info

Operating System: macOS Sierra Version 10.12
Python version: Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
gspread version: 3.0.1

### Steps to reproduce
```
i = 2
for cell in cell_list:
    cell.value = '=split(A'+str(i)+', "|")'
    i = i + 1
```
above code adds the the formula with a tick, thus make it a string and not to be evaluated as formula

the value being set is:
`=split(A2,"|")

But the below code works:
```
for i in log_progress(range(2,df.size+2),every=1):
    wks2.update_acell('B'+str(i), '=split(A'+str(i)+', "|")')
```
but the issue here is, it takes time since each cell is updated with a separate api all, and its done one by one as opposed to the method on top, which adds the data in one shot.

**Comment by robin900** [comment]
I assume that you are using `update_cells(cell_list)` to perform the update using the modified Cell objects? If so, try the `value_input_option` parameter with `'USER_ENTERED'`:

```python 
wks2.update_cells(cell_list, value_input_option='USER_ENTERED')
```

**Comment by robin900** [comment]
@nmmanas That fixed your problem? Let me know so that we can close this issue.

**Comment by nmmanas** [comment]
@robin900 just checked and it did fix the problem. thanks.
