### ISSUE TITLE
feature request: fetch specific row or column range

### ISSUE THREAD

**Issue by gholadr** [burnash/gspread#57]
the gdocs api doc talk about a way to fetch a range of columns or rows. I'm using Python so their online example doesnt help me much.
Wondering if adding this functionality is on your roadmap?

I didnt see anything in your worksheet api doc that suggest you already have this feature supported... and I'm not interested in the range() method which needs a defined boundary.
the google docs talks about a min_row/max_row and min_col/max_col attributes of the CellQuery object, but I could never get it working properly.

gdoc docs is here https://developers.google.com/google-apps/spreadsheets/#fetching_specific_rows_or_columns

I supposed I could always call the col_values() method for each column I need to fetch but that seems inefficient to me :)
thanks!

**Comment by msuozzo** [comment]
I'm going to assume this is `Worksheet.range` and say that this issue is fixed.

**Comment by arulmr** [comment]
@msuozzo If I want to get the value of the cell **B7**, how range method can be used?
