### ISSUE TITLE
"Insufficient tokens for quota 'ReadGroup' and limit 'USER-100s' of service 

### ISSUE THREAD

**Issue by muddi900** [burnash/gspread#583]
I have a code that works daily on both versions of API and was working as early as this morning(13th Aug '18). It took data from a bunch of sources and updates the sheet. It works on both v3 and v4 of the API.

### Environment info

Operating System: Windows 10 17134
Python version: 3.7
gspread version: 3.0.1 and 0.6.2

### Steps to reproduce
I have a bunch of sheets that all have the same format so I created a class to extract all the data I usually use. The class code is:

```
class gsheet():
    def __init__(self,myFile,mySheet,json=None):
        if json == None:
            clientKey = fileopenbox()
        else:
            clientKey = json
        scope = ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
        cred =  ServiceAccountCredentials.from_json_keyfile_name(clientKey,scope)
        client = gspread.authorize(cred)

        self.sheet = client.open(myFile).worksheet(mySheet)
        self.POs = self.sheet.col_values(1)
        self.rows = len(self.POs)
        self.orders = self.sheet.col_values(5)
        self.sup_orders = self.sheet.col_values(6)
        self.skus = self.sheet.col_values(8)
        self.tracking = self.sheet.col_values(26)
        self.shipmeth = self.sheet.col_values(27)
    def createRec(self, pl, row):
        for p in list(pl.keys()):
            vaL = pl[p]['value']
            col = pl[p]['sheetCol']
            self.sheet.update_cell(row,col,vaL)
```

and the actual execution code that four instances of the class, with all the calls for the attributes, and then pulls data from different sources and executes this code to update the appropriate cells:

```
if PO.startswith('C'):
                mySheet = mywb if index_of(mywb.POs,PO) > -1 else mywbn
            else:
                mySheet = my3p if index_of(my3p.POs,PO) > -1 else my3pn
            rowfill  = [i for i,x in enumerate(mySheet.POs) if x.startswith(PO)]
            for row in rowfill:
                thisRow = row+1
                if mySheet.sheet.cell(thisRow,38).value == 'Y':
                    continue
                mySheet.sheet.update_cell(thisRow,26,track)
                if handle == 3.95:
                    mySheet.sheet.update_cell(thisRow,19,handle/len(rowfill))
                if freight:
                    mySheet.sheet.update_cell(thisRow,18,float(freight)/len(rowfill))

```
### Stack trace or other output that would be helpful
```
 File "<stdin>", line 1, in <module>
  File "c:/Users/muddi/Google Drive/sheet python project/tracking.py", line 252, in <module>
    if mySheet.sheet.cell(thisRow,38).value == 'Y':
  File "c:\Users\muddi\AppData\Local\Programs\Python\Python37\lib\site-packages\gspread\models.py", line 381, in cell
    params={'valueRenderOption': value_render_option}
  File "c:\Users\muddi\AppData\Local\Programs\Python\Python37\lib\site-packages\gspread\models.py", line 110, in values_get
    r = self.client.request('get', url, params=params)
  File "c:\Users\muddi\AppData\Local\Programs\Python\Python37\lib\site-packages\gspread\client.py", line 79, in request
    raise APIError(response)
gspread.exceptions.APIError: {
  "error": {
    "code": 429,
    "message": "Insufficient tokens for quota 'ReadGroup' and limit 'USER-100s' of service 'sheets.googleapis.com' for consumer 'project_number:534908720134'.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/534908720134/apiui/credential"
          }
        ]
      }
    ]
  }
}
```

I have been using this code for the past 6 months. I have not had any issues with API calls, which is the reason this is not in stackoverflow. Please note that there is not traceback for 0.6.2 because it just crashes the terminal.

**Comment by amosbastian** [comment]
> This version of the Google Sheets API has a limit of 500 requests per 100 seconds per project, and 100 requests per 100 seconds per user. Limits for reads and writes are tracked separately. There is no daily usage limit.
>
>To view or change usage limits for your project, or to request an increase to your quota, do the following:
>
>1. If you don't already have a billing account for your project, then create one.
>2. Visit the Enabled APIs page of the API library in the API Console, and select an API from the list.
>3. To view and change quota-related settings, select Quotas. To view usage statistics, select Usage.

Source: https://developers.google.com/sheets/api/limits

**Comment by bbjunaid** [comment]
Did you figure this out?

**Comment by Ayushjha17** [comment]
Following up on amosbastian answer, you have to make sure that you don't have more than 100 requests in any 100s rolling window. One easy way, (makes your code slow though) is to explicitly make every request of 1 second.

from time import sleep
start_time = datetime.datetime.now()
col_value_1.append(wks.cell(i, 1).value)       --API Call
end_time = datetime.datetime.now()
if (end_time - start_time).total_seconds() < 1:
        sleep(1.01 - (end_time - start_time).total_seconds())

**Comment by weitieda** [comment]
> Following up on amosbastian answer, you have to make sure that you don't have more than 100 requests in any 100s rolling window. One easy way, (makes your code slow though) is to explicitly make every request of 1 second.
> 
> from time import sleep
> start_time = datetime.datetime.now()
> col_value_1.append(wks.cell(i, 1).value) --API Call
> end_time = datetime.datetime.now()
> if (end_time - start_time).total_seconds() < 1:
> sleep(1.01 - (end_time - start_time).total_seconds())

I let my loop sleep after each insert_row(), but still have the "429" and "USER-100s" error, looks like there's another limitation by Google?

**Comment by wlpm04pmuell** [comment]
Ran into this myself and it looks like you want to be careful with using gspreads' col_values which appears to execute an API read for every column in the spreadsheet whereas get_all_values counts as a single read.

**Comment by aidanthom** [comment]
Hi, I know this is an old query, but can anyone please clarify the following as I am wondering about increasing my sheets quota.
Goggle says:
"Usage Limits
This version of the Google Sheets API has a limit of 500 requests per 100 seconds per project, and 100 requests per 100 seconds per user. Limits for reads and writes are tracked separately. There is no daily usage limit."

I know this may sound ridiculous but can someone please define : seconds per project? and seconds per user?, 
my project making the api call to my own company account clearly exceeds the quota at 100/100 so I slow it down with thread.sleep code but this should not be necessary if I was allowed 500 request per 100 seconds.

Thanks in advance for your help, a

**Comment by mderrien29** [comment]
> 500 requests per 100 seconds per project

Limit for a single project, all users combined.

> 100 requests per 100 seconds per user

Limit for a single user (or service account).

So, you could do 500 requests / 100 if you were using different service accounts for each request.

**Comment by muddi900** [comment]
I just sidestepped this by using a semantic statement on the the `get_all_values()` output, instead of using `col_values()`.

For example, if you want the values of the 3rd column in a sheet:

```
x= myworkbook.mysheet.get_all_values()
column  = [i[2] for i in x]
```

This cuts down on requests a lot.

**Comment by automatingadwords** [comment]
> I just sidestepped this by using a semantic statement on the the `get_all_values()` output, instead of using `col_values()`.
> 
> For example, if you want the values of the 3rd column in a sheet:
> 
> ```
> x= myworkbook.mysheet.get_all_values()
> column  = [i[2] for i in x]
> ```
> 
> This cuts down on requests a lot.

Thank you, this helped. 

That, and sleeping/re-trying if there's an error...
```
...except Exception as e:
    if str(e).find("RESOURCE_EXHAUSTED")>-1:
        print "resource exhausted..."
        time.sleep(10)
```

**Comment by RegalCode** [comment]
> I just sidestepped this by using a semantic statement on the the `get_all_values()` output, instead of using `col_values()`.
> 
> For example, if you want the values of the 3rd column in a sheet:
> 
> ```
> x= myworkbook.mysheet.get_all_values()
> column  = [i[2] for i in x]
> ```
> 
> This cuts down on requests a lot.

This thread really helped a lot in cutting down request.

You mentioned how to get the 3rd row of a column using the get_all_values. I've been trying to figure out how to get the 3rd row instead?

**Comment by muddi900** [comment]
get_all_values() returns a list of lists; each element is a row in list
form.  So if x is your list of lists, then the third row would be x[2].

**Comment by RegalCode** [comment]
I understand, worked like a charm. Thank you!

**Comment by lavigne958** [comment]
issue is solved.

closing this issue.
