### ISSUE TITLE
Difference between V3 and V4

### ISSUE THREAD

**Issue by mschulz** [burnash/gspread#584]
Problem:

I have two separately running web server programs which access the same worksheet.  One runs under Python 2.7 and uses Version 3 of gspread and the other runs under Python 3.6 and uses version 4 of gspread. Both are running using Flask.

The Version 3 program reports the worksheet as having one row and the Version 4 of the program reports it as having 7 (correctly).  Same worksheet. Number of columns is reported correctly in both versions.

Question: Is this a known feature/bug? Is there something I should be aware of?

A couple of small (~10-15 line) programs I wrote to reproduce the issue don't have this problem - just the one quite large web server running under Flask.

NOTE that I can't upgrade Version 3 to 4 for the Python 2.7 as pip says I am up to date.

**Comment by eavalenzuela** [comment]
this might be a bug. I was having a similar issue where after updating to v4 one of my sheets was only returning one column.
Tried duplicating/copying/recreating the sheet with the same name to no effect.
I changed the sheet name in gsheets and that fixed it. Strange stuff.

**Comment by lavigne958** [comment]
API V3 is not used anymore. only API V4 which seems to return the correct value. 
Issue not relevant anymore then.

Closing this issue.
