### ISSUE TITLE
get_all_records() IndexError

### ISSUE THREAD

**Issue by jasongurwin** [burnash/gspread#590]
I recently upgraded to the latest version of gspread (v 3.0.1). Now when I request certain worksheets with get_all_records() - I get the following error.

This same scripts ran without issues before I upgraded.

```
gameValues = sheet.get_all_records()
File "/Library/Python/2.7/site-packages/gspread/models.py", line 471, in get_all_records
keys = data[idx]
IndexError: list index out of range
```

I'm making the follow request:

`sheet = client.open(MyWorkbook).worksheet(MyWorksheet)`

MyWorkbook being the Workbook name and MyWorksheet being the Worksheet name.

The library seems to be retreieving the worksheet object fine when I print it.

`<Worksheet u'Schedule' id:242452861>`

**Comment by jasongurwin** [comment]
I changed the name of the Worksheet from "Schedule" to "Games" and it is no longer sending the error. Maybe it's a restricted name in Sheets4 API?

Same thing happened when I had a sheet named "Locals" and changed it to "Networks".

**Comment by burnash** [comment]
Thanks for reporting this.

Could you check if you're actually trying to retrieve an empty worksheet? (as described in #629 )

**Comment by lavigne958** [comment]
No response from the issue owner, very most likely trying to get all records on an empty sheet. This has now been fixed.

Closing this issue.

**Comment by s2t2** [comment]
I am experiencing this issue!
