### ISSUE TITLE
AttributeError: 'module' object has no attribute 'APIError'

### ISSUE THREAD

**Issue by mateocam** [burnash/gspread#593]
### Environment info
Operating System: OS X El Capitan
Python version: Python 2.7.11
gspread version: 3.0.1

### Steps to reproduce
I am handling errors like this in my code: `except gspread.exceptions.APIError as e:` and after a while running I get this error: AttributeError: 'module' object has no attribute 'APIError'. 

I have a Worksheet class with different methods, but this error happens in all of them with my implementation of catching errors. this is the complete catch:

```
                        try:
				something ...
			except gspread.exceptions.APIError as e:
				if e[0] == 401:
					self.gc.login()
				elif e[0] == 500:
					time.sleep(10)
				else:
					print 'last row'
					print e
					break
			except requests.exceptions.ConnectionError as e:
				time.sleep(10)
			except requests.exceptions.ChunkedEncodingError as e:
				time.sleep(20)
```

**Comment by mateocam** [comment]
This is the entire traceback:
```
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    leads = controller_leads.calculate(client,since)
  File "/Users/mateocam/Desktop/!blah/dintDigital/DEV/proyectos/kpis_masis/controller_leads.py", line 50, in calculate
    fb_form_list = wksh.find_all("Lead Form")
  File "/Users/mateocam/Desktop/!blah/dintDigital/DEV/proyectos/kpis_masis/wksh.py", line 99, in find_all
    except gspread.exceptions.APIError as e:
AttributeError: 'module' object has no attribute 'APIError'
```
it seems like it fails in my code but I do not understand why. This is my worksheet class, which contains methods where the exception handling fails sometimes with the APIError:

```
from oauth2client.service_account import ServiceAccountCredentials
import time
import gspread
import requests
import os

DIRNAME = os.path.dirname(__file__)

class Wksh:

	credentials_google_sheet = ServiceAccountCredentials.from_json_keyfile_name(os.path.join(DIRNAME, 'credentials/gs_credentials.json'),['https://spreadsheets.google.com/feeds'])
	gc = gspread.authorize(credentials_google_sheet)	

	worksheet_id = None
	sheet_name = None
	sheet = None

	def __init__(self,wksh_id,sh_name):
		while True:
			try:
				self.worksheet_id = wksh_id
				self.sheet_name = sh_name
				self.sheet = self.gc.open_by_key(wksh_id).worksheet(sh_name)
				break
			except gspread.exceptions.APIError as e: 
				if e[0] == 401:
					self.gc.login()
				elif e[0] == 500:
					time.sleep(10)
				else:
					print 'init'
					print e
					break
			except requests.exceptions.ConnectionError as e:
				time.sleep(10)
			except requests.exceptions.ChunkedEncodingError as e:
				time.sleep(20)

	def write(self,cell,value):
		while True:
			try:
				self.sheet.update_acell(cell,value)
				break
			except gspread.exceptions.APIError as e:
				if e[0] == 401:
					self.gc.login()
				elif e[0] == 500:
					time.sleep(10)
				else:
					print 'write'
					print e
					break
			except requests.exceptions.ConnectionError as e:
				time.sleep(10)
			except requests.exceptions.ChunkedEncodingError as e:
				time.sleep(20)
```

am I missing an import ?

**Comment by burnash** [comment]
My guess is that you're using pre 3.0.0 version of gspread, although you specified that gspread version is 3.0.1. Could you double check gspread version? Please put this line in the same script (above  the try/except block):

```
print gspread.__version__
```

**Comment by mateocam** [comment]
@burnash you were right, I was using a previous version of gspread. sorry for the inconvenience and thank you very mush for your help !

**Comment by mateocam** [comment]
@burnash never mind, I just got the same error and I am using version 3.0.1.

**Comment by lavigne958** [comment]
This is strange, I don't think this issue is related to GSpread.

I ran the used the following code snippet:
```
import os
os.toto()
```

Which leads to the following error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'toto'
```

In this case python point out that the module 'os' has no attribute 'toto' in you stack trace the error message point out the object of name 'module' has no attribute 'APIError'. and it does not says anything about GSpread. I believe your python setup has a issue.
