### ISSUE TITLE
Fails if sheet contains non-ascii chars

### ISSUE THREAD

**Issue by ZhanaraDev** [burnash/gspread#595]
**Environment info**
Operating System: Ubuntu
Python version:2.7
gspread version:3.0.1

**Steps to reproduce**
1. Name a sheet with non-ascii chars
2. and try to get values from it
3. it wil give a keyError

**Possible solution**
It can be solved by encoding range in url, like here - url = SPREADSHEET_VALUES_CLEAR_URL % (self.id, quote(range.encode('UTF-8'), safe=''))

**Comment by burnash** [comment]
Thank you for reporting and for submitting the fix.
Related issues:  #605, #558 and #554.

**Comment by burnash** [comment]
Fixed in #610 and #628
Available in version 3.1.0
