### ISSUE TITLE
[Feature Suggestion] Multi-Row Append Function

### ISSUE THREAD

**Issue by eavalenzuela** [burnash/gspread#599]
The current append_row function actually works for multiple rows if the square brackets in
`values: [values]` are removed.

So if you copy-paste the function, remove the brackets, and call it 'append_rows', it now submits as many new rows to a sheet as you like.

e.g.
```
def append_rows(self, values, value_input_option='RAW'):
        """Adds multiple rows to the worksheet with values populated.
        The input should be a list of lists, with the lists each
        containing one row's values.
        Widens the worksheet if there are more values than columns.
        :param values: List of row lists.
        """
        params = {
                'valueInputOption': value_input_option
        }

        body = {
                'majorDimension': 'ROWS',
                'values': values
        }

        return self.spreadsheet.values_append(self.title, params, body)
```
Note that the majorDimension key isn't necessary, but makes it explicit instead of relying on gsheets to figure out it's not columns.

**Comment by Tethik** [comment]
I would like to see this too. I hit the rate limit pretty quickly without this functionality. Using the above function worked perfect for my use case (~20k rows).

**Comment by chicagobuss** [comment]
Same here, this is a decent workaround so it'd be good to see it get added as a standard feature.

**Comment by emlazzarin** [comment]
My code is monkey-patched to take advantage of this. It would be great for it to be pushed upstream.
