### ISSUE TITLE
spreadsheet.title should be a function

### ISSUE THREAD

**Issue by dgilman** [burnash/gspread#600]
The `Spreadsheet.title` property can potentially do network i/o and that network i/o can potentially fail, throwing a Requests exception. It is not considered pythonic to have getters and setters throw exceptions. Please change this property to a function call in the next API-breaking release of gspread.

Keeping it as a property can confuse API users into thinking that they don't need to write exception handling code for accesses to the `.title` property. And truthfully, they probably don't need to do so most of the time, you have to have a little bit of luck on your side to get your spreadsheet to open successfully but have the later call to .title to fail after a `._properties` cache miss. However, it can blow up just the same as any other function call and should be promoted to a function to communicate this to users.

I would also ask you to please avoid calling `.title` in internal code, such as in `Spreadsheet.__repr__`. I would argue that most people wouldn't expect a call to `str` on a valid Spreadsheet object to crash with network errors. I certainly didn't. I wrote an exception handler that wrapped and retried calls to `.title` only to see it blow up when I tried to log the Spreadsheet object with `str(spreadsheet)` in the exception handler.

**Comment by lavigne958** [comment]
Hi @dgilman  this is a good issue you point here. 

I will have a look and see, because this would be a braking change for other users. we can't just update it and leave other users with broken code.
