### ISSUE TITLE
GSpread lacks documentation of, or does not support, image uploading to Google Sheets

### ISSUE THREAD

**Issue by dakeenekid** [burnash/gspread#606]
I was trying to find documentation online for image support, but I didn't seem to find any. I know that it's possible to do this with the Google Drive API and JS, but if GSpread could wrap this functionality to allow image uploads to a google sheet that would be much appreciated.

**Comment by burnash** [comment]
Does someone want to research if it's possible with Sheets API v4 gspread is using?

**Comment by dakeenekid** [comment]
I would research myself but  I haven't the time. I'm sure that it's possible to add files to google drive, but I'm not sure if it's possible to add it directly into sheets into a specific cell.

**Comment by Logic-gate** [comment]
@dakeenekid Yup, uploading directly to Sheets is not possible. You could however add the image to Drive and then use `=IMAGE()` to insert it into a specific cell. `=IMAGE()` takes a link as a parameter, so Drive is not necessary, any link would do.

**Comment by dakeenekid** [comment]
> @dakeenekid Yup, uploading directly to Sheets is not possible. You could however add the image to Drive and then use `=IMAGE()` to insert it into a specific cell. `=IMAGE()` takes a link as a parameter, so Drive is not necessary, any link would do.

This sounds like exactly what I'm looking for! Can you call `=IMAGE()`  in gspread?

**Comment by AivanF** [comment]
> This sounds like exactly what I'm looking for! Can you call `=IMAGE()` in gspread?

This is just a formula, i.e some text, you can put it as any other value. You just should specify `value_input_option='USER_ENTERED'` because by default the formula will be set row text.

[Here you can find docs about IMAGE()](https://support.google.com/docs/answer/3093333?hl=en) formula.

**Comment by Logic-gate** [comment]
@dakeenekid what @AivanF said.

**Comment by dakeenekid** [comment]
Figured it out.

I can just use `sheet.append_row(['image1', '=IMGAE({})'.format(image_url)]` to get it to do what I want.

Thank you again!

**Comment by jgibz** [comment]
For anyone getting a ' at the beginning of their cell try: 
`sheet.append_row(['image1', '=IMAGE(\"{}\")'.format(image_url)], value_input_option='USER_ENTERED')`
