### ISSUE TITLE
Gspread support for value_render_option in get_all_values()

### ISSUE THREAD

**Issue by manjrekarom** [burnash/gspread#612]
Hello!

I am working on an [enchancement](https://github.com/getredash/redash/issues/2923) at [redash](https://github.com/getredash/redash) which uses **gspread** to support google spreadsheet data source. The feature should allow one to **specify formatting** via the [value_render_option](https://developers.google.com/sheets/api/reference/rest/v4/ValueRenderOption) query param for example to **load unformatted values** when using [get_all_values()](https://gspread.readthedocs.io/en/latest/#gspread.models.Worksheet.get_all_values) function.

It's a minor change that will allow *get_all_values()* to take one optional parameter. I am open to knowing other suggestions.

If gspread team approves of this enchancement I'll be happy to add it. Thanks!

**Comment by burnash** [comment]
Thanks for the suggestion! I think it's a good idea. Please go ahead with the PR. 
CI tests are failing (again), but the test suite should pass locally. 
I'm currently working on fixing CI. Please let me know if you have any questions regarding tests.

**Comment by mklaber** [comment]
@manjrekarom any success with this enhancement?
