### ISSUE TITLE
get_all_values () and get_all_records() doesn't work properly for Google sheets

### ISSUE THREAD

**Issue by Arumugapandian** [burnash/gspread#614]
Dear burnash
 
My Google sheet is very bigger in size with 30 columns and 4000 rows. 

When I tried to get the data using get_all_values() leads to data_rate error advice me to increase the rate, I tried but it's not working. 

When I pull the data using get_ all_records()
it lists only the 30th column. 

I am interested in import only 4,5,7th column. Is there any way to import multiple columns in this situation. Thanks for your help

**Comment by burnash** [comment]
Thanks for reporting this. 

What version of gspread are you using?

**Comment by Arumugapandian** [comment]
Thanks for your response.  I am using the gspread version 3.0.1 which is
released on Jun 30, 2018.

I tried to use the "Getting All Values From a Single Column" either 4 or 5
or 7 the data is imported properly.

**Comment by Arumugapandian** [comment]
Is it possible to import only specific multiple columns for this scenario. It will reduce the time to import all the data.

**Comment by burnash** [comment]
Can you paste the sample of your code and the "data_rate" error? 

> Is it possible to import only specific multiple columns for this scenario. It will reduce the time to import all the data.

Yes, you'd need to use a lower-level API method for this [`Spreadsheet.values_get()`](https://gspread.readthedocs.io/en/latest/api.html#gspread.models.Spreadsheet.values_get)

**Comment by Arumugapandian** [comment]
Kindly find the attached error below
![untitled](https://user-images.githubusercontent.com/43292227/47888532-f9952180-de6a-11e8-8d66-60a4a36f328b.png)

**Comment by burnash** [comment]
Sorry, I don't think it's a gspread issue.
Take a look at google search: https://www.google.de/search?q=iopub+data+rate+exceeded
And StackOverflow: https://stackoverflow.com/questions/43288550/iopub-data-rate-exceeded-in-jupyter-notebook-when-viewing-image

I'm closing this issue. Please see my comment above regarding the specific columns.
