### ISSUE TITLE
After 1 hour of working connection lost

### ISSUE THREAD

**Issue by paperplane90** [burnash/gspread#618]
**GitHub Issues are for bugs and feature requests.**

File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/callbackqueryhandler.py", line 143, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "./script_name.py", line 492, in button
    "spreadsheet_name").worksheet("worksheet").acell(
  File "/usr/local/lib/python3.7/site-packages/gspread/client.py", line 122, in open
    self.list_spreadsheet_files()
  File "/usr/local/lib/python3.7/site-packages/gspread/client.py", line 96, in list_spreadsheet_files
    res = self.request('get', url, params=params).json()
  File "/usr/local/lib/python3.7/site-packages/gspread/client.py", line 79, in request
    raise APIError(response)
gspread.exceptions.APIError: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }

Please do not post usage questions here. For general support from the community, see StackOverflow: http://stackoverflow.com/questions/tagged/gspread

Issues with usage questions will be closed.

For bugs please provide the following information.

### Environment info

Operating System: Ubuntu 16.04
Python version: 3.7
gspread version: 3.1

### Steps to reproduce
1. After 1 hour of working connection lost
2.
3.

**Comment by burnash** [comment]
Could you please post the example of your code? It's not apparent under what conditions you received this server response after one hour.

**Comment by paperplane90** [comment]
get_message_from_google_table = open_client.open("spreadsheet").worksheet(" templates").acell(
            sms_dict.get(query.data)).value

**Comment by paperplane90** [comment]
Yes, here are some parts:

    if query.data in sms_dict.keys():
        get_message_from_google_table = open_worsheet.worksheet("Table").acell(
            sms_dict.get(query.data)).value

        if sms_dict.get(query.data).startswith("C"):
            bot.edit_message_text(text=send_sms_kh(get_message_from_google_table,
                                                   get_numbers("table", cell_number)).format(query.data),
                                  chat_id=query.message.chat_id,
                                  message_id=query.message.message_id

and 

def get_numbers(worksheet_name, coll_value):
    data_from_options = open_worsheet.worksheet(
        worksheet_name).col_values(coll_value)
    list_of_numbers = []

    for x in range(len(data_from_options)):
        text = "<recipient>" + data_from_options[x] + "</recipient>"
        list_of_numbers.append(text)
    list_of_numbers.pop(0)
    return ('\n'.join(map(str, list_of_numbers)))

**Comment by burnash** [comment]
Could you please format your post? Please check https://guides.github.com/features/mastering-markdown/
It's not easy to read Python code when all the white space is missing.

**Comment by paperplane90** [comment]
Hello,

Any updates?

**Comment by 5rAA** [comment]
paperplane90 unfortunately you're not alone. I have the same problem. I'm using Raspberry Pi. Every minute I read a value from a sensor and than add that value to a spreadsheet. Exactly after one hour the connection is lost and the script fails. I get this error:

```
gspread.exceptions.APIError: {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}
```
I'musing Python 3.5.3

**Comment by paperplane90** [comment]
I'm using Telegram bot for it.

**Comment by paperplane90** [comment]
> paperplane90 unfortunately you're not alone. I have the same problem. I'm using Raspberry Pi. Every minute I read a value from a sensor and than add that value to a spreadsheet. Exactly after one hour the connection is lost and the script fails. I get this error:
> 
> ```
> gspread.exceptions.APIError: {
>   "error": {
>     "code": 401,
>     "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
>     "status": "UNAUTHENTICATED"
>   }
> }
> ```
> I'musing Python 3.5.3

I have found in files location of 1 hour time. But I don't know how it will affect lib.

**Comment by burnash** [comment]
Looks like the access token is getting expired. All methods except for `Client.login` do not refresh the token automatically. You could modify your code so it catches the `APIError` exception and calls `gc.login()`. Let me know if this works for you.

**Comment by paperplane90** [comment]
gc.login() - what do you mean?

I don't understand what argument I need to use.

**Comment by burnash** [comment]
Sorry, `gc.login()` means calling [`Client.login()`](https://gspread.readthedocs.io/en/latest/api.html#gspread.Client.login) on the `Client` instance. In your case it looks like it's called `open_client`.

**Comment by 5rAA** [comment]
client.login() WORKS :D

Every 59 minutes I call client.login() and the program runs as it should. Thank you!

**Comment by paperplane90** [comment]
> I call client.login(

share your code. I'm using try except and receive a lo of errors

**Comment by burnash** [comment]
@5rAA thank you for the input! Could you please indeed share a snippet or example of your code?

**Comment by 5rAA** [comment]
It's really simple!

```
import time
import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds',
'https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_name('key.json', scope)
client = gspread.authorize(creds)

gettime = time.time()

while(True):
    #SOME CODE THAT'S BEING EXECUTED 24/7 (MY JUST APPENDS TO SPREADSHEET)
    if(time.time() - gettime > 60* 59):
        client.login()
        gettime = time.time()

```

This code has been running for more than 24 hours.

**Comment by paperplane90** [comment]
I have one more option.
If I run auth inside the function instead of the global vars. The errors will not be raised.

**Comment by denny64** [comment]
any updates on why this is happening?

**Comment by ermusthofa** [comment]
Hi,

I have same problem with this, credential token get expired after 1 hour running my code. But I cant make it work just to use client.login(). Any workaround to solve this ?

**Comment by Greansilver** [comment]
Hi,
the Problem is like mentioned before that the Token expires after 1H. so to resolve this Problem i just wrote a Code do prevent this Error, if you want you can use it. I'm not sure if its better to cast the client.login() just in the exception but i have no time to test whats better. Hope this helps someone someday :)
I wrote a 
`def getCell(sheet, r, c, sheetName='e7data'):
    client.login()
    try:
        return client.open(sheetName).get_worksheet(sheet).cell(r,c).value      #Actual ACtion
        #print(action)
    except Exception as e:
        print(e)
        #client.login() (here better?)
        getCell(sheet, r, c, sheetName)`

**Comment by Greansilver** [comment]
Hi,
the Problem is like mentioned before that the Token expires after 1H. so to resolve this Problem i just wrote a Code do prevent this Error, if you want you can use it. I'm not sure if its better to cast the client.login() just in the exception but i have no time to test whats better. Hope this helps someone someday :)

```python
def getCell(sheet, r, c, sheetName='your_sheet'):
    client.login()
    try:
        return client.open(sheetName).get_worksheet(sheet).cell(r,c).value      #Actual Action
        #print(action)
    except Exception as e:
        print(e)
        #client.login() (here better?)
        getCell(sheet, r, c, sheetName)
```
