### ISSUE TITLE
Python3 not supported properly

### ISSUE THREAD

**Issue by mrsaicharan1** [burnash/gspread#620]
Does not get any cell information, basically does not get executed.
### Environment info

Operating System: Ubuntu 18.04 
Python version: 3
gspread version: 3.0.1

### Steps to reproduce
``` 
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pprint
import datetime
import argparse

today = datetime.date.today()
formatted_date = today.strftime("%m-%d-%Y")
print(formatted_date)

def mark_attendance(students):
    scope = ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
    creds = ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope)
    client = gspread.authorize(creds)

    sheet = client.open('face-attendance').sheet1

    result = sheet.get_all_records()
    # before attendance
    pp = pprint.PrettyPrinter()
    pp.pprint(result)
    # date-> col
    date_col_list = sheet.findall(formatted_date)
    date_col = date_col_list[0].col
    print(date_col)

    #roll_no_list ->row
    for student in students:
        cell_list = sheet.findall(student)
        for cell in cell_list:
            roll_number_row = cell.row
            sheet.update_cell(roll_number_row,date_col,'P')

    #Show sheet
    result = sheet.get_all_records()
    pp.pprint(result)

mark_attendance(['IIT2016075','BIM2016002','IHM2016005'])
```

Running the above gspread python script with python3

### Stack trace or other output that would be helpful
No output

**Comment by mrsaicharan1** [comment]
If anyone has a quick fix for this one, would really appreciate it.

**Comment by burnash** [comment]
Please be more specific on your Python version. Is it 3.6 or 3.7?

Also, I kindly ask you to be a bit more specific. There are many reasons why the code results in no input. It might be related to gspread, but it also might be related to the script that uses gspread. Could you try to scope the problem? E.g. "`sheet.get_all_records()` returns no results, while `sheet.findall()` works". The more specific is the question / problem description, the easier it'll be to identify the reason and help. Python3 not supported properly is a bit vague description.
