### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by RohanJnr** [burnash/gspread#624]
An error {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
has occured !

This is the error which i occur. The code is use is ⬇️ plz help me
#starts here
from discord.ext import commands
import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']

credentials = ServiceAccountCredentials.from_json_keyfile_name('cogs/gator-project-2-7460b2795c66.json', scope)
gc = gspread.authorize(credentials)

class CwlRegistration:

    def __init__(self, bot):
        self.bot = bot

    @commands.command()
    async def cwl(self, ctx, *, info_for_cwl):
        
        # print(info_for_cwl)
        try:
            wks_cwl = gc.open('cwl_roster').sheet1
            ign, th, yon, notes = info_for_cwl.split('-')
            wks_cwl.append_row([ign, th, yon, notes])
            await ctx.send('Your append was successful !')
        except Exception as e:
            await ctx.send('An error ' + str(e) + 'has occured !')

    @commands.command()
    async def cwlinfo(self, ctx, *, ign):
        
        try:

            wks_cwl = gc.open('cwl_roster').sheet1
            x = wks_cwl.find(str(ign)).row
            headings = wks_cwl.row_values(1)

            row_vals = wks_cwl.row_values(x)
            for f, b in zip(headings, row_vals):
                msg = '***' + f + '***' + ':' + b
                await ctx.send(msg)
        except:
            await ctx.send(ign + ' was not found !')

def setup(bot):
    bot.add_cog(CwlRegistration(bot))

**Comment by RohanJnr** [comment]
btw im using heroku to host my bot(additional info)

**Comment by burnash** [comment]
Thanks for reporting this.
I think it's similar to #618: it looks like your access token gets expired. I'm closing this ticket. Please follow #618

**Comment by RohanJnr** [comment]
thanks !
