### ISSUE TITLE
openall with a title filter doesn't filter

### ISSUE THREAD

**Issue by ADraginda** [burnash/gspread#630]
Issue: the `title` arg in `client.openall` is not used and the function does not filter.

PR in #572 

Creating a ticket so it's clear to everyone that this issue has been reported and has been worked on.

**Comment by burnash** [comment]
Thank you for reporting this!

**Comment by aiguofer** [comment]
#572 was merged in so this can be closed :)

**Comment by burnash** [comment]
👍
