### ISSUE TITLE
get_all_values returns single value when worksheet name is in A1 notation

### ISSUE THREAD

**Issue by grlbrwrg** [burnash/gspread#636]
Thanks @burnash for the great work! I've been using gspread a lot lately and think I came across a bug when a worksheet is named in A1 notation.

### Steps to reproduce
1. Create a new worksheet "A2" and populate with data
2. Call get_all_values() on the worksheet
3. Only the value in cell A2 will be returned

I have tried to fix the issue in https://github.com/grlbrwrg/gspread/commit/de5c3b4fc7cf56436226862e3c5e6c1d4adfdf8a but not sure if this is the right way to do things (it's my first contribution!)

Cheers
Walter

**Comment by burnash** [comment]
Thank you very much for reporting this. I can confirm it's a bug.

**Comment by burnash** [comment]
Thanks also for the suggested fix. I've checked the [A1 notation section](https://developers.google.com/sheets/api/guides/concepts#a1_notation) on Sheets API guide and it looks like wrapping the sheet name in a quotes is a way to go. 

I think it's best to follow the advice from the API docs though and wrap the name in quotes at all times.

> If the sheet name has spaces or starts with a bracket, surround the sheet name with single quotes ('), e.g 'Sheet One'!A1:B2. _For simplicity, it is safe to always surround the sheet name with single quotes._

That should also simplify the code. Would it be possible for you to rework the fix and submit it as a PR? There's one caveat: what if the name of the sheet already contains qoute character or characters?
