### ISSUE TITLE
AttributeError: type object 'ServiceAccountCredentials' has no attribute 'from_json_keyfile'

### ISSUE THREAD

**Issue by jlchulilla** [burnash/gspread#653]
Hello everyone,

I have tried a ginormous set of using examples of gspread, for no avail

my example code:

`import gspread`
`from oauth2client.service_account import ServiceAccountCredentials`
`scope = ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']`
`credentials = ServiceAccountCredentials.from_json_keyfile.name('client_secret.json', scope)`
`gc = gspread.authorize(credentials)`
`hoja = gc.open('testpy').sheet1`
`print(hoja.get_all_records())`

`client.secret.json` is renamed from secrey key json file obtained from service account credentials. it is something like this

`{`
`  "type": "service_account",`
`  "project_id": "personaltestpygshee6",`
`  "private_key_id": "29etcetc",`
`  "private_key": "-----BEGIN PRIVATE KEY-----\netcetc\n-----END PRIVATE KEY-----\n",`
`  "client_email": "project@project.iam.gserviceaccount.com",`
`  "client_id": 423etcetc",`
`  "auth_uri": "https://accounts.google.com/o/oauth2/auth",`
`  "token_uri": "https://oauth2.googleapis.com/token",`
`  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",`
`  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/project%40project.iam.gserviceaccount.com"`
`}`

when I run the script, this is the error message that I obtain

`File "5testgooshee.py", line 6, in <module>`
`    credentials = ServiceAccountCredentials.from_json_keyfile.name('client_secret.json', scope)`
`AttributeError: type object 'ServiceAccountCredentials' has no attribute 'from_json_keyfile'`

I have done my homework, I swear. Steam comes out of my ears. I cannot figure out what is the problem and why it works in a lot of examples except mine

Where is the failure? Why I cannot make it work?

Thanks in advance

**Comment by mr-mcox** [comment]
@jlchulilla Does `ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope)` work for you instead? (Note the underscore instead of a period before "name")

**Comment by jlchulilla** [comment]
Finally there is a (temporary?) solution for the problem. We need to keep in mind that OAuth2 is deprecated and that all solutions based on it such as GSpread can stop functioning.

Now, the solution:

1. As @Tanaike pointed out, the starting point was a typo on the call of service account credentials. It needs to be pointed out that in some tutos it is spelled as `ServiceAccountCredentials.from_json_keyfile.name('client_secret.json', scope)`, where it should be `ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope)`. There are tutorials over there in which this typo is reproduced.
2. Besides, there is another problem with Windows. You need to install `PyOpenSSL` with python. If you use a windows box or WSL, you need to install the complete version of `win32OpenSSL` https://stackoverflow.com/questions/14063124/importerror-cannot-import-name-signedjwtassertioncredentials http://slproweb.com/products/Win32OpenSSL.html You need to install it before PyOpenSSL... and **I have discovered that you have to install the same version as python, either 32 or 64 bits**. It can sound silly or trivial, but if you don't consider it, it will not work

Thanks all for your time and answers

**Comment by lavigne958** [comment]
Thank you @jlchulilla for that detailed investigation :slightly_smiling_face: 

GSpread has been updated and now  does not use oauth2 lib anymore but google-auth now.

It is good to know for window users too. Thank a lot.

Issue has been solved.

Closing this issue.
