### ISSUE TITLE
ServiceAccountCredentials.from_json not working

### ISSUE THREAD

**Issue by bhamshu** [burnash/gspread#655]
**GitHub Issues are for bugs and feature requests.**

Please do not post usage questions here. For general support from the community, see StackOverflow: http://stackoverflow.com/questions/tagged/gspread

Issues with usage questions will be closed.

For bugs please provide the following information.

### Environment info

Operating System: windows10
Python version: 3.6
gspread version: 3.1.0

### Steps to reproduce
```
import gspread
from oauth2client.service_account import ServiceAccountCredentials
scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json(client_secret)

```
### Stack trace or other output that would be helpful
KeyError: '_private_key_pkcs8_pem'

**Comment by AkshayJohn123** [comment]
Use **from_json_keyfile_dict**.
`
scope = ['https://spreadsheets.google.com/feeds',
        'https://www.googleapis.com/auth/drive']
credentials = ServiceAccountCredentials.from_json_keyfile_dict(your_secret_json, scope)
`

**Comment by lavigne958** [comment]
No response from the issue owner, potential fix has been given.

Closing this issue.
