### ISSUE TITLE
ModuleNotFoundError: No module named 'gspread'

### ISSUE THREAD

**Issue by alexsmedile** [burnash/gspread#657]
I have an issue with the gspread module, and I think with Python 3 too.

My code is something like that: `import blabla, gspread, etc...`

And if I try to run it `python3 myscript.py` every module seems to run fine, except _gspread._ I receive this error:
```
Traceback (most recent call last):
  File "z_schedule.py", line 3, in <module>
    from z_database import *
  File "/home/pi/Projects/InstaPy/z_database.py", line 3, in <module>
    import gspread, gspread_formatting
ModuleNotFoundError: No module named 'gspread'
```

I'm running python 3.7 and I installed gspread both with pip and pip3. I also installed oauth2 in the same way.

My code used to work great until I updated my Raspberry, InstaPy and Python. Somebody knows how to fix it? Thanks.

I'm running `gspread==3.1.0` on RaspianOS

**Comment by alexsmedile** [comment]
Up

**Comment by alexsmedile** [comment]
Up

**Comment by prostomarkeloff** [comment]
may be you install gspread to another version python?

**Comment by stcondon** [comment]
any resolution here? I experienced the same issue

**Comment by lavigne958** [comment]
No response from the issue owner.

closing this issue.
