### ISSUE TITLE
Organize Sheets to a Google Drive Folder

### ISSUE THREAD

**Issue by crearo** [burnash/gspread#665]
Is it possible to organize where the Google Sheets will be located?
Basically what I want to do is place all my Sheets in a specific Drive folder.

**Comment by fernandeznico** [comment]
(I use Google translator)

This worked for me:

Modify the "payload" like here: https://stackoverflow.com/questions/22934525/pydrive-cannot-write-file-to-specific-gdrive-folder

For example:

Replace: https://github.com/burnash/gspread/blob/0e8debe208095aeed3e3e7136c2fa5cd74090946/gspread/client.py#L181
`    def create(self, title, folder_id=None):`
Add after: https://github.com/burnash/gspread/blob/0e8debe208095aeed3e3e7136c2fa5cd74090946/gspread/client.py#L208
`        if folder_id:
            payload['parents'] = [{ "kind": "drive#fileLink", "id": folder_id }]`

Writer permissions will be needed in the folder.

**Comment by crearo** [comment]
Ah nice. I ended up using the default Drive API that Google provides. Worked well for my use-case. But gspread was super useful in doing csv manipulation!
