### ISSUE TITLE
Feature request: Fetch last added/updated worksheet from a spreadsheet having many worksheets.

### ISSUE THREAD

**Issue by qburst-gokul** [burnash/gspread#667]
Just like opening a worksheet by name, id or index, like:

```
import gspread
gc = gspread.authorize(credentials)

worksheet = sh.worksheet("January")
```
or

`worksheet = sh.sheet1`

It would be helpful to open the last added worksheet, something like:

`worksheet = sh.sheetLatest`

**Comment by lavigne958** [comment]
Hi @qburst-gokul

I am sorry I thought that feature would be very easy to do, unfortunately it is and its event worth, it can't be done 😕

The API simply does not provide the creation time of a worksheet. Without that information it can be done.

Closing this issue.
