### ISSUE TITLE
Error raised when using insert_row function

### ISSUE THREAD

**Issue by TryingOutSomething** [burnash/gspread#668]
Hi, I received this error after running insert_row function:

```raise APIError(response)
APIError: {
  "error": {
    "code": 400,
    "message": "Invalid value at 'data.values[0]' (type.googleapis.com/google.protobuf.ListValue), \"A\"",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "data.values[0]",
            "description": "Invalid value at 'data.values[0]' (type.googleapis.com/google.protobuf.ListValue), \"A\""
          }
        ]
      }
    ]
  }
}
```
Although the function inserts a new row according to the index, this error was raised.

The parameters along with the function in my code:  ```sheet.insert_row('A', index=18)```

**Comment by Paul-PADataAnalytics** [comment]
the answer to fix this would have been sheet.insert_row(['A'], index=18) in case you google your way into this.

**Comment by Crispas95** [comment]
I have received this error when trying to write json data into the google sheet

GaxiosError: Invalid values[0][1]: struct_value {
  fields {
    key: "name"
    value {
      string_value: "Jane Doe"
    }
  }
  fields {
    key: "urn"
    value {
      string_value: "tel:+26599******"
    }
  }
  fields {
    key: "uuid"
    value {
      string_value: "209c2ad9-5c28-40f1-8b27-a59b1ae39619"
    }
  }
}
