### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'update_acell'

### ISSUE THREAD

**Issue by mehul-jethva** [burnash/gspread#669]
File "gsheet.py", line 12, in <module>
    sheet.update_acell = ('B10', 'First addition from python to Google sheet')
AttributeError: 'NoneType' object has no attribute 'update_acell'

I get the following error when I am trying to update a cell or if I try to use the 'acell' function. I have no idea why this is happening

**Comment by burnash** [comment]
Hi there,
It means that for some reason, `sheet` is `None` and not an instance of the `Worksheet` class. 
Make sure that the `sheet` variable is not empty.
Hope this helps.
