### ISSUE TITLE
Gspread not Actively updating

### ISSUE THREAD

**Issue by dulfig** [burnash/gspread#670]
**GitHub Issues are for bugs and feature requests.**

For some reason as of tonight the gspread function has not actively refreshed. I made a discord bot which reaches to my spread sheet and reports data changes. However it consistently is working with a singular instance of the sheet. When I shut down my bot to check on my tester file the results over an hour have remained the same. The spreadsheet is constantly being updated however the cells are not transferring even when I run in a fresh environment. If you require other data let me know.

### Environment info

Operating System: Windows 10 X64
Python version: 3.7
gspread version: Most recent(Not sure version number)

**Comment by emlazzarin** [comment]
There isn't much of an explanation here, and it isn't clear that `gspread` is the issue.

**Comment by Asmeble** [comment]
Have you checked credentials every 5 mins?

**Comment by lavigne958** [comment]
No response from issue owner, closing this issue.
