### ISSUE TITLE
5s+ to read one sheet with 5 rows, is it normal? 

### ISSUE THREAD

**Issue by etienneleblan** [burnash/gspread#673]
Hello,

My read requests are surprisingly slow, taking around 5-10 second for a brain new sheet with 5 rows / columns in it and no additional logic, formatting and such. 
I've tried get_all_records, specific cell / row / column but same result. 

I am on macOS 10.14.4, running python 3.7.2 and gspread 3.1.0. I live in the EU if location matters.
My code: 

```
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import datetime

now = datetime.datetime.now()
print(now)
scope = ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope)

client = gspread.authorize(creds)

sheet = client.open('mysheet').sheet1

result = sheet.get_all_records()
#result = sheet.row_values(2)
now = datetime.datetime.now()
print(now)
```

Thanks in advance for the help!

**Comment by voglster** [comment]
you might want to time a few things to see what you are getting... but I don't see a 5 second delay on my side, < 2 seconds total so something else is amiss.

example code:

```
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime

start = datetime.now()
scope = ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope)
print("reading keyfile took", datetime.now() - start)

start = datetime.now()
client = gspread.authorize(creds)
print("authorizing took", datetime.now() - start)

start = datetime.now()
sheet = client.open('mysheet').sheet1
print("opening sheet took", datetime.now() - start)

start = datetime.now()
result = sheet.get_all_records()
print("getting records took", datetime.now() - start)
```

running that code with a different sheet with many more rows:
```
reading keyfile took 0:00:00.002890
authorizing took 0:00:00.241033
opening sheet took 0:00:01.483287
getting records took 0:00:00.558384
```

200mbit down/20mbit up pipe in US

**Comment by etienneleblan** [comment]
Hi James,
Thanks for the help! The performance remained the same for a couple of days until it improved to around 2.5 seconds, which is better - not exactly sure why. I'll close the issue.

**Comment by voglster** [comment]
Glad I could help!
