### ISSUE TITLE
worksheet.find and findall in gspread don't work. It looks like something changed in google api

### ISSUE THREAD

**Issue by osJedi** [burnash/gspread#675]
**GitHub Issues are for bugs and feature requests.**

Please do not post usage questions here. For general support from the community, see StackOverflow: http://stackoverflow.com/questions/tagged/gspread

Issues with usage questions will be closed.

For bugs please provide the following information.

### Environment info

Operating System:
Python version:
gspread version:

### Steps to reproduce
1.
2.
3.

**Comment by Logic-gate** [comment]
Mind sharing your code?

**Comment by osJedi** [comment]
I am sorry... The problem is found, gspread compares value on equal, but I
faced with a problem when data was changed and to the original data was
added whitespace

Don't worry, all fine :)

**Comment by Logic-gate** [comment]
Cheers, 

Please mark this as closed.
