### ISSUE TITLE
How I can to upload CSV to different sheets?

### ISSUE THREAD

**Issue by ua17** [burnash/gspread#676]
Hello.
```
import gspread
sh = gc.open("Nameofsheet")
content = open("file.csv", "r").read().encode("utf8")
gc.import_csv(sh.id, content)
```
This code to upload csv to google spreadsheets in first sheet.
```
worksheet = sh.worksheet("Sheet2")
```
But how I can to upload CSV to second sheets?

**Comment by Logic-gate** [comment]
I dont think there is a straight forward way through gspread--read https://gspread.readthedocs.io/en/latest/api.html#gspread.Client.import_csv

You could however read the contents of your file and append them your sheets without having to import. Not sure how effective this method is.
