### ISSUE TITLE
Feature request: Folder option for create and copy functions

### ISSUE THREAD

**Issue by fernandeznico** [burnash/gspread#678]
Hi, how I explain here: https://github.com/burnash/gspread/issues/665#issuecomment-488540191 it's posible specify a folder (by your id) in "copy" or "create" functions from easy way, adding a few lines of code.

Correction (tested):
`'parents': [{'id': folder_id}]`

**Comment by Abdellam1994** [comment]
Hello,
I also think that this feature would be really useful.
It will allow to create directly a spreadsheet into a folder. It will therefore avoid polluting the drive when creating spreadsheets at scale.
I can work on the feature :)

**Comment by burnash** [comment]
@Abdellam1994 would love to see this implemented, please do a PR.

**Comment by Abdellam1994** [comment]
Hello :)

I noticed that I only implemented the folder option for "create function" and not for the "copy function".
Could we reopen the issue ?
I will work on a PR asap :)

**Comment by burnash** [comment]
Hi there! Sure, would love to get a PR.
