### ISSUE TITLE
Invalid JSON payload received. Unexpected token. error when bulk uploading with update_cells(cell_list)

### ISSUE THREAD

**Issue by pptlim** [burnash/gspread#680]
Hello, 

I started getting the error when I updated to Python 3.7 two days ago. I use the following code to upload a pandas df to a gsheet - the error happens with any df. 

Re the error: this seems to pertain to some cells with value '180901_millbrae_1', may or may not be relevant. This exact same data and code used to work fine.

Any ideas?

Error:
```python
Traceback (most recent call last):

  File "<ipython-input-31-85b52784b441>", line 11, in <module>
    ws.update_cells(cell_list)

  File "/Users/../anaconda/lib/python3.7/site-packages/gspread/models.py", line 782, in update_cells
    'values': values_rect

  File "/Users/../anaconda/lib/python3.7/site-packages/gspread/models.py", line 176, in values_update
    r = self.client.request('put', url, params=params, json=body)

  File "/Users/../anaconda/lib/python3.7/site-packages/gspread/client.py", line 79, in request
    raise APIError(response)

APIError: {
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unexpected token.\nae\", 43344, \"None\", NaN], [\"180901_millb\n                    ^",
    "status": "INVALID_ARGUMENT"
  }
}
```

Code:
```python
n_rows, n_cols = df.shape
k = 1000
for i in range(n_rows//k + 1):    
    row0 = start_row + i*k
    col0 = start_col
    row1 = start_row + min((i+1)*k, n_rows-1)
    col1 = start_col + n_cols - 1
    cell_list = ws.range(inputRange(row0, col0, row1, col1))
    for cell in cell_list:
        val = df.iloc[cell.row-start_row, cell.col-start_col]
        cell.value = val
    ws.update_cells(cell_list)
```

Operating System: macOS Sierra 10.12.6
Python version: 3.7.0
gspread version: 3.1.0

**Comment by Logic-gate** [comment]
Hey, 

1 - is `val` a string? 

2 - I think this is your issue: `\nae", 43344, "None", NaN], ["180901_millb\n ^",` why is there a new line at the end. + where is this from. Are you sure that the original value is correctly formatted 

3 - Manually(through gspread) append the values, do they work?

**Comment by eanunez** [comment]
Hi,
I encountered the same problem. I tried filling up 'NaN' values to empty string. 
`df.fillna('', inplace=True)`

**Comment by burnash** [comment]
@eanunez thanks for the solution. Closing the issue.

**Comment by Imperssonator** [comment]
The solution posted above will convert any float-type columns into object-type, which causes problems for downstream numerical use in Sheets (all the numbers will be interpreted as strings). It seems like there needs to be a way for worksheet.update() to automatically leave NaN cells blank, or something.

**Comment by Imperssonator** [comment]
I found an alternate solution that preserves the numeric data type of numeric columns:

```
worksht.update(
    [df.columns.values.tolist()] + [[vv if pd.notnull(vv) else '' for vv in ll] for ll in df.values.tolist()]
)
```

Probably quite slow if your sheet is large but it works 🤷‍♂️

**Comment by naterattner** [comment]
For what it's worth, I got this same error due to having infinite values in my dataframe. Replacing those with 'NaN' values and then filling those 'NaN' values with empty strings, as suggested above, did the trick:

```
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.fillna('', inplace=True)
```

**Comment by HuuLane** [comment]
> Hi,
> I encountered the same problem. I filled up 'NaN' values with empty string,
> `df.fillna('', inplace=True)`
> and the problem was solved.

IDK why, but it works!! lol

**Comment by manugarri** [comment]
the fix is quite easy, we just need to setup the `allow_nan` flag of python json to False. However it seems like it requires some changes to the code since the [code](https://github.com/burnash/gspread/blob/52feb9a59883127da4069253c2e6f07b0f615269/gspread/utils.py#L533) only filters None (not NaN, or Infinity).

This is a very brittle solution to be honest.

**Comment by ViniciusARZ** [comment]
> Hi,
> I encountered the same problem. I filled up 'NaN' values with empty string,
> `df.fillna('', inplace=True)`
> and the problem was solved.

Worked fine for me too!

**Comment by Bonobo791** [comment]
This just leaves a big whitespace in the cell above the valule. Any other fixes??
