### ISSUE TITLE
Incorrect definition for .worksheet()

### ISSUE THREAD

**Issue by Kytareth** [burnash/gspread#682]
In documentation the definition of worksheet(title) says that title has to be int.
https://gspread.readthedocs.io/en/latest/api.html?highlight=worksheet#gspread.models.Spreadsheet.worksheet

But in the example the argument is  string 
https://gspread.readthedocs.io/en/latest/user-guide.html#selecting-a-worksheet

And, actually, it works with string. Perhaps the definition should be fixed?

**Comment by Tejaswgupta** [comment]
I'll have a look into it.

**Comment by burnash** [comment]
Thank you for spotting this. You're right. 
It was fixed in #690.
