### ISSUE TITLE
values.append appending in wrong column

### ISSUE THREAD

**Issue by yurividal** [burnash/gspread#689]
I have the following code:
    `spreadsheet.values_append('NAME!U2:U', params={'valueInputOption': 'RAW'}, body={"values": [[line]]})`

It was working fine. Values were being appended to column U.
Suddenty, now the values are going to column O, and it skips a line every now and then.

Didnt change anything. 

Did google change something on the API?

**Comment by Logic-gate** [comment]
I faced this problem with rows. It kept showing extra fields and inserting data in the wrong place. Ended up writing a helper script. 

[https://gist.github.com/Logic-gate/0caf685f6843f9e18dd93426c64a23c9#file-gspreadhelper-py-L91](url) 

Hope it helps.

**Comment by burnash** [comment]
Thanks for reporting this. It looks similar to #537 
Sheets API may put the data into a wrong "virtual table".

More details are in [my comment](https://github.com/burnash/gspread/issues/537#issuecomment-586622830) to #537 and in [Google Sheets API guide on appending values](https://developers.google.com/sheets/api/guides/values#appending_values).

Let me know if this helps. I'm closing the ticket for now.
