### ISSUE TITLE
Add support for creating cells/rows/columns

### ISSUE THREAD

**Issue by ghost** [burnash/gspread#7]
Right now, it is not possible to write to rows with rowindex>100 unless you manually create them.

worksheet.add_rows(number_of_rows) or something similar would be nice.

**Comment by sveisa** [comment]
Is it possible to add new rows at the very top of the spreadsheet?

Suppose I already have data in Row 1, and create a new empty row above it.  So that I can add new data to the 'new' and empty Row 1 without overwriting existing data.

**Comment by burnash** [comment]
Maybe [Worksheet.insert_row](http://gspread.readthedocs.org/en/latest/#gspread.Worksheet.insert_row) will work for you? Beware that it can be quite slow depending on the size of your spreadsheet.

**Comment by abdulwahid24** [comment]
@burnash I really appreciate your work, I was looking for a method `Worksheet.insert_col` but unfortunately it's not there, Please let me know how can I insert columns at any particular location.

**Comment by kennyl41291** [comment]
Bro @burnash! Any chances you will be adding a append_col method? Having a real difficulty trying to insert column data :(
