### ISSUE TITLE
Feature request: set file Properties as "timeZone"

### ISSUE THREAD

**Issue by gbonline** [burnash/gspread#703]
I would like to change the timeZone of spreadsheet file, presents in file Properties as listed in
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#SpreadsheetProperties

Setting it during create or after with set operation
Because I discovered that it influences the cells valued with dates.

**Comment by fiskhest** [comment]
I have the same use case, but for changing locale. @burnash is there any interest in adding a properties-method for the entire spreadsheet?

**Comment by fiskhest** [comment]
I managed to work around the issue by using batch_update:

```
        spreadsheet = gc.open_by_key(uploadfile['id'])
        spreadsheet.batch_update({
            'requests': {
                'updateSpreadsheetProperties': {
                    'properties': {
                        'locale': 'sv_SE'
                    },
                    'fields': 'locale'
                }
            }
        })
```

**Comment by lavigne958** [comment]
Hi @aiguofer

This is a great idea. It could be done of course.
I can't make it happen right now, if anyone is interested feel free to implement it.

Otherwise I might do it for version 5.1.0 of gspread.

Soon releasing version 5.0.0
