### ISSUE TITLE
Code returning 401 error after around 4 hours of running

### ISSUE THREAD

**Issue by CubeBlazer** [burnash/gspread#707]
I was running a program using gspread and discord.py, after a few hours, it gave me this error: 
![Screenshot (13)](https://user-images.githubusercontent.com/57646851/68636188-b1bac880-04c8-11ea-9b7e-25bba5057990.png)
![Screenshot (14)](https://user-images.githubusercontent.com/57646851/68636189-b1bac880-04c8-11ea-93da-4facd5182d75.png)
![Screenshot (15)](https://user-images.githubusercontent.com/57646851/68636190-b1bac880-04c8-11ea-814f-2dae4bcf94e6.png)
![Screenshot (16)](https://user-images.githubusercontent.com/57646851/68636191-b1bac880-04c8-11ea-9748-73721fac05e6.png)

But I have authenticated them beforehand:
![Screenshot (17)_LI](https://user-images.githubusercontent.com/57646851/68636319-255cd580-04c9-11ea-9656-70adda1ca67f.jpg)
![Screenshot (18)](https://user-images.githubusercontent.com/57646851/68636320-255cd580-04c9-11ea-9586-fe14dbeae473.png)

Can anyone tell me why it's unauthenticating my code? 
I am trying to run this code 24/7 on a Raspberry Pi, used VNC to manage it.

**Comment by PavelDemin** [comment]
Did you solve this problem?

**Comment by benjamindhimes** [comment]
What does your `sheetag.json` file look like?  With the secret data removed, obviously.

**Comment by CubeBlazer** [comment]
I figured out the problem, the authentication depends on the scopes, and they reset after an hour. I've tried to fix this problem by migrating to gspread-asyncio but then it's throwing off my important discord.py code; then attempting to move to pygsheets, but whenever I use find(), it lists all of the data compared to gspread. Right now, I'm going to try and authorize the credentials by putting it inside the loop whenever a command is executed. So yay for discord.py.

**Comment by CubeBlazer** [comment]
Found the solution on StackOverflow, for it to continue and refresh the token, I just needed to call `gc.login()` for it to refresh its token. I had a loop going on so I put `gc.login` inside that loop

StackOverflow info: https://stackoverflow.com/questions/45914349/python-gspread-request-error-401
