### ISSUE TITLE
How to skip hidden rows while iterating through Google Spreadsheet

### ISSUE THREAD

**Issue by eosfomogame** [burnash/gspread#710]
https://developers.google.com/apps-script/reference/spreadsheet/spreadsheet#isrowhiddenbyuserrowposition
Is it implemented?

**Comment by lavigne958** [comment]
I don't see it implemented in this repository.

the link you point to is about google appScripts which do a similar job but embedded code on google servers in javascripts, if you want details about what informations can be retrieved from the spreadsheet API look at this section: [sheet section](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/sheets) on the left side you have the other sections (cell, ...) have a look if you find what you are looking for.

**Comment by snusnuz** [comment]
Hello, I'm also interested in having this feature. 
Unfortunately I'm a Phyton newbie and I only tried to make some changes to the models.py, with no luck. 

Can anybody point me in the right direction in order to find a way to implement sheet.isRowHiddenByUser(row)?

**Comment by JonB451** [comment]
Is the question here: 

Can gspread recognise which rows are HiddenByUser?

**Comment by lavigne958** [comment]
I looked on the API reference and could not find anything about this.
Hidden row are simply not available from the API :disappointed:
