### ISSUE TITLE
[feature] Merge Cells

### ISSUE THREAD

**Issue by lavigne958** [burnash/gspread#712]
**Feature: add the action to merge cells**

It would be very usefull to have a function that permit to use the Google API 'mergeCells'.

### Environment info

Operating System: Linux
Python version: 3.7.4
gspread version: 3.1.0

### Steps to reproduce
1. not replicable

### Stack trace or other output that would be helpful
The function should take a worksheet and some coordonates and merge the cells accross the coordonates.

**Comment by eosfomogame** [comment]
I agree: https://github.com/burnash/gspread/issues/710

**Comment by lavigne958** [comment]
Thanks ! :-D
But, I am sorry I don't see the link with the issue: #710 :thinking: "please bring light where there is only darkness"

**Comment by eosfomogame** [comment]
I saw your pr, it's amazing. Can you help me with this https://developers.google.com/apps-script/reference/spreadsheet/spreadsheet#isrowhiddenbyuserrowposition 
Is there a way to implement it? 

Thanks
