### ISSUE TITLE
gspread.exceptions.APIError 500 "Internal error occured." when opening worksheet

### ISSUE THREAD

**Issue by kylecarow** [burnash/gspread#714]
**I have solved my problem, but I wanted to post it for posterity. Feel free to take this down or close it if need be.**

I had a mysterious issue when trying to open worksheets from a certain spreadsheet or copies of that spreadsheet. It ended up being due to someone changing permissions in my team drive and bumping the project account down to 'viewer.'

The issue was whenever I loaded any worksheet from a certain spreadsheet (later found out it was the whole team drive) I would get an error thrown by gspread. Other people say this internal error is usually from sending too many requests but I hadn't sent any before the error. I later found out that the project email was set to 'viewer' by one of the many people in the team drive.

Maybe there could be something done to make the solution easier to find? Like mentioning it might be a permissions issue?

The last bits of the mysterious error message (I am using the latest version of gspread):
```
File "C:\Users\*****\AppData\Local\Programs\Python\Python37\lib\site-packages\gspread\models.py", line 235, in worksheet
    sheet_data = self.fetch_sheet_metadata()
  File "C:\Users\*****\AppData\Local\Programs\Python\Python37\lib\site-packages\gspread\models.py", line 184, in fetch_sheet_metadata
    r = self.client.request('get', url, params=params)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python37\lib\site-packages\gspread\client.py", line 79, in request
    raise APIError(response)
gspread.exceptions.APIError: {
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
```

Thanks

**EDIT:** This error persists when copying affected files to team drives where the project account **does** have permission. The way around this is to copy each worksheet into a new spreadsheet by way of copy/paste.

**Comment by burnash** [comment]
@kylecarow thank you for sharing this.
I think that, unfortunately, the error returned by Sheets API is too ambiguous to do any sort of further automatic introspection to hint the user at possible permissions issue.

I'm closing the issue but I tag it as "Docs" so, later on, when we create a troubleshooting section in the docs we can extend it with this issue. (Of course, if you're interested in contributing such a
section to the docs, it's more than welcome. Let me know if interested.)

**Comment by scepeda78** [comment]
raise APIError(response)
gspread.exceptions.APIError: {'code': 500, 'message': 'Internal error encountered.', 'status': 'INTERNAL'} I've got the same error ...

**Comment by jacquespeeters** [comment]
Same since 13/03/2021 ...
