### ISSUE TITLE
oauth2client.client.HttpAccessTokenRefreshError: invalid_scope: http://www.googleapis.com/auth/drive is not a valid audience string, Getting this error why ?

### ISSUE THREAD

**Issue by gokulancv** [burnash/gspread#721]
Hello, I am getting this error while authenticating my gspread credentials. I have made sure about the following things before asking this question here:

Google sheet and google Drive APIs are enabled in my console.
so are Google cloud storage and Google cloud storage JSON APIs enabled
The google sheet which I am trying to perform the gspread operations on is shared with the client_id(mentioned in JSON file, downloaded after I created my credentials from google console)
I am behind a proxy and I am using http_proxy and https_proxy env. variables
(I am unable to rid this error, Please help me fix this error, I am new to python. I read many answers on StackOverflow and GitHub but nothing worked out for my case.)

My Code:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope=['https://www.googleapis.com/auth/spreadsheets.readonly']

creds=ServiceAccountCredentials.from_json_keyfile_name('GoogleProject2020.json', scope)

client= gspread.authorize(creds)

Sheet=client.open("spreadsheeet").sheet1

data=Sheet.get_all_records()
print(data)

ERROR:: I'm Getting was----
Traceback (most recent call last):
  File "C:/Users/nsew1/Desktop/pythonlearn/GOOGLE PROJECT/GOOGLEPROJECT.py", line 8, in <module>
    client= gspread.authorize(creds)
  File "C:\Users\nsew1\Anaconda3\lib\site-packages\gspread\__init__.py", line 38, in authorize
    client.login()
  File "C:\Users\nsew1\Anaconda3\lib\site-packages\gspread\client.py", line 51, in login
    self.auth.refresh(http)
  File "C:\Users\nsew1\Anaconda3\lib\site-packages\oauth2client\client.py", line 545, in refresh
    self._refresh(http)
  File "C:\Users\nsew1\Anaconda3\lib\site-packages\oauth2client\client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "C:\Users\nsew1\Anaconda3\lib\site-packages\oauth2client\client.py", line 819, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_scope: http://www.googleapis.com/auth/spreadsheets.readonly is not a valid audience string.

**Comment by burnash** [comment]
Hello,

I believe the error message is very explicit:

> invalid_scope: http://www.googleapis.com/auth/spreadsheets.readonly is not a valid audience string.

Change the `scope` to 

```
scope = [
    'https://spreadsheets.google.com/feeds', 
    'https://www.googleapis.com/auth/drive'
]
```

See details in [Using OAuth2 for Authentication](https://gspread.readthedocs.io/en/latest/oauth2.html)
