### ISSUE TITLE
issue with client email

### ISSUE THREAD

**Issue by gdrivetest123** [burnash/gspread#729]
Hi it seems that when sharing the spreadsheet with the client email in the credential file it does not actually send the email, checking my email it says failed to deliver. Is a different way of authentication needed?

**Comment by burnash** [comment]
Disregarding the failure to deliver, do you see this spreadsheet when you list spreadsheets in the client afterward? 
E.g. when you run `gc.openall()`?

**Comment by gdrivetest123** [comment]
Hi,

sorry i managed to get it working there where a few things that were missed, an additional scope was needed and also by enabling the google drive i assumed i wouldn't have to enable the google sheets API.

**Comment by burnash** [comment]
Great, I'm happy that it works. Closing the issue.
