### ISSUE TITLE
Allow `get_all_records()` function to pass `value_render_option` parameter)

### ISSUE THREAD

**Issue by damgad** [burnash/gspread#746]
I would like to fetch data from a worksheet using  `get_all_records()` function. The kind of data in the worksheet (dates & precise float numbers) forces me to use the following requests params in order to get the data regardless of the formating:

`{'valueRenderOption': "UNFORMATTED_VALUE"}`

I would like to have at least `value_render_option` parameter in the function `get_all_records()`. All the data should be then fetched with the render option passed by that parameter. In my specific case i would just call:

`my_worksheet.get_all_records(default_blank=None, value_render_option= "FORMATTED_VALUE")
`

The tricky part is what should happen with the "head" row - and therefore the keys of the dictionaries returned by `get_all_records()` function. I have no strong preference here, the keys could be fetched using the `value_render_option`.

Of course, there are alternative solutions to the issue as there are other functions that provide `value_render_option` parameter. The whole issue is more about convenience and consistency.

The fix for that issue is not that obvious as just passing a parameter as `numericise` function needs to be reconsidered in case of new types of data returned from the worksheet.

I will be happy to help with the issue. I can write the patch and create a PR, please just give me a green light (especially with the special treating of the "head" row).

**Comment by burnash** [comment]
@damgad It'd be great if you could implement this. Please make a PR.

I don't have strong preference regarding head behavior either. To keep it simple I'd have the head fetched along with the rest of the data as you suggest.

One implementation note: please take a look at how `value_render_option` and other arguments are passed to the new methods `Worksheet.get()` and `Worksheet.batch_get()` with `accepted_kwargs` decorator. I was planning to extend this decorator usage to `get_all_values` as well and this PR is a great chance to do this.

**Comment by damgad** [comment]
I've just pushed PR #776 implementing that feature.

Regarding the `accepted_kwargs` I've tried to use that pattern but IMO, it can't be safely done. That decorator may introduce breaking changes and I won't recommend using it, especially in existing API.

To show what I mean let's take an example. Let's say that currently there are two people using the function in the following ways:
1. `sheet.get_all_records(empty2zero=True)` 
2. `sheet.get_all_records(True)` 

Currently, both are valid and have same effect.

The current behavior of the `accepted_kwargs` will lead to the following consequences:
1. If we add only the `value_render_option` with the `@accepted_kwargs` decorator and left other parameters intact, `sheet.get_all_records(True)` will work as before but `sheet.get_all_records(empty2zero=True)` won't. The decorator will catch that as an unexpected keyword argument.
2. If we move all the parameters to be handled by `@accepted_kwargs` then `sheet.get_all_records(empty2zero=True)` will work but `sheet.get_all_records(True)` won't. As there are no positional arguments allowed.

**Comment by burnash** [comment]
Thank you for the PR. Your point regarding `accepted_kwargs` is very convincing. I agree it does not really fit the case for `get_all_records`.

**Comment by gregcron** [comment]
Hi - I think this relates to an issue I'm facing.
If the number in Sheets is 5.45454545, but the display value is only to two decimal places, only 5.45 is returned from get_all_records().
This is causing major issues with an accounting system.  I need to run reports/splits based on all key:value pairs in the row, so only fetching all row values is not an option ; I need to know the other values that correlate.

Is there any workaround for my use case?  I had hoped I could use unformatted_values to get the full number returned.

If I expand the displayed decimals way far out, the API returns the full number.  However, this makes the front end difficult to look at.

**Comment by damgad** [comment]
Hey @gregcron, that's exactly the problem that this issue describes. However, the PR https://github.com/burnash/gspread/pull/776 is not yet merged into master. @burnash any updates on this?

For now, I can share with you a monkeypatch that I'm currently using as a workaround. Be carefull as it's rather dummy and will overwrite the render option everywhere. Also, I've tested it with gspread version 3.1.0. Don't know if it's compatible with later versions. Place it after importing the gspread. 

```python
# BEGIN OF MONKEYPATCHING - WORKAROUND TO BE DELETED

import gspread.models
import gspread.utils
from gspread.models import SPREADSHEET_VALUES_URL, quote

"""To read accurate data from the spreadsheets we need to fetch unformatted values for
numbers and dates. Spreadsheets API provides that possibility but the gspread library doesn't
support that in convenient way. Until the issue https://github.com/burnash/gspread/issues/746
isn't done we need a temporary workaround. Monkeypatches below set the valueRenderOption
parameter to UNFORMATTED_VALUE.

For the documentation please refer to the original methods.
"""


def patched_numericise(
    value,
    empty2zero=False,
    default_blank="",
    allow_underscores_in_numeric_literals=False,
):
    if isinstance(value, str):
        if "_" in value and not allow_underscores_in_numeric_literals:
            return value
        try:
            value = int(value)
        except ValueError:
            try:
                value = float(value)
            except ValueError:
                if value == "":
                    if empty2zero:
                        value = 0
                    else:
                        value = default_blank

    return value


def patched_values_get(self, range, params=None):
    url = SPREADSHEET_VALUES_URL % (self.id, quote(range))
    r = self.client.request(
        "get", url, params={"valueRenderOption": "UNFORMATTED_VALUE"}
    )
    return r.json()


gspread.models.Spreadsheet.values_get = patched_values_get
gspread.utils.numericise = patched_numericise

# END OF MONKEYPATCHING - WORKAROUND TO BE DELETED
```

**Comment by gregcron** [comment]
> 
> 
> Hey @gregcron, that's exactly the problem that this issue describes. However, the PR #776 is not yet merged into master. @burnash any updates on this?
> 
> For now, I can share with you a monkeypatch that I'm currently using as a workaround. Be carefull as it's rather dummy and will overwrite the render option everywhere. Also, I've tested it with gspread version 3.1.0. Don't know if it's compatible with later versions. Place it after importing the gspread.
> 
> ```python
> # BEGIN OF MONKEYPATCHING - WORKAROUND TO BE DELETED
> 
> import gspread.models
> import gspread.utils
> from gspread.models import SPREADSHEET_VALUES_URL, quote
> 
> """To read accurate data from the spreadsheets we need to fetch unformatted values for
> numbers and dates. Spreadsheets API provides that possibility but the gspread library doesn't
> support that in convenient way. Until the issue https://github.com/burnash/gspread/issues/746
> isn't done we need a temporary workaround. Monkeypatches below set the valueRenderOption
> parameter to UNFORMATTED_VALUE.
> 
> For the documentation please refer to the original methods.
> """
> 
> 
> def patched_numericise(
>     value,
>     empty2zero=False,
>     default_blank="",
>     allow_underscores_in_numeric_literals=False,
> ):
>     if isinstance(value, str):
>         if "_" in value and not allow_underscores_in_numeric_literals:
>             return value
>         try:
>             value = int(value)
>         except ValueError:
>             try:
>                 value = float(value)
>             except ValueError:
>                 if value == "":
>                     if empty2zero:
>                         value = 0
>                     else:
>                         value = default_blank
> 
>     return value
> 
> 
> def patched_values_get(self, range, params=None):
>     url = SPREADSHEET_VALUES_URL % (self.id, quote(range))
>     r = self.client.request(
>         "get", url, params={"valueRenderOption": "UNFORMATTED_VALUE"}
>     )
>     return r.json()
> 
> 
> gspread.models.Spreadsheet.values_get = patched_values_get
> gspread.utils.numericise = patched_numericise
> 
> # END OF MONKEYPATCHING - WORKAROUND TO BE DELETED
> ```

Thanks for that - helpful.  I see what you mean about the risk of it applying everywhere.  Date fields are coming back numerical.  Thanks for sharing regardless!

**Comment by burnash** [comment]
@damgad sorry, totally forgot to merge it. On it.

**Comment by lavigne958** [comment]
this is been merged.

closing this issue.
