### ISSUE TITLE
Python 2 SyntaxError in 3.4.0 and 3.4.1

### ISSUE THREAD

**Issue by chrisburr** [burnash/gspread#751]
In https://github.com/burnash/gspread/commit/ad1e55e20e4c102017c9c08ce2f4f38c554fbc24 a keyword argument was added in combination with `*specs`. This Syntax is not supported in Python 2 therefore causing:

```
   File "/root/.local/lib/python2.7/site-packages/gspread/__init__.py", line 16, in <module>
    from .client import Client
  File "/root/.local/lib/python2.7/site-packages/gspread/client.py", line 16, in <module>
    from .models import Spreadsheet
  File "/root/.local/lib/python2.7/site-packages/gspread/models.py", line 1276
    def sort(self, *specs, range=None):
                               ^
SyntaxError: invalid syntax
```

This can also be seen in the CI for that commit: https://travis-ci.org/github/burnash/gspread/jobs/471597434?utm_medium=notification&utm_source=github_status

Dropping Python 2 support is entirely reasonable, but if it's intentional the metadata in `setup.py` should be updated to match. It would also be nice to mention it in the 3.4.0 release notes so it's clear what version constraint should be used.

**Comment by burnash** [comment]
Thanks for spotting this! No, it's not intentional, I've overlooked this. 

gspread is not dropping Python 2 support until next major release.

**Comment by burnash** [comment]
I'll release a fix soon. Please stay tuned.

**Comment by chrisburr** [comment]
Thank you for the extremely quick fix!

**Comment by burnash** [comment]
You're welcome. It actually owes to the precision of the bug report ;)
