### ISSUE TITLE
Copying worksheets from given spreadsheet into any given other spreadsheet.

### ISSUE THREAD

**Issue by JoachimKoenigslieb** [burnash/gspread#755]
I have different templates that I want to combine into one spreadsheet for editing. 

I think this could be achieved by copying the relevant worksheets from the spreadsheets, into a new spreadsheet.

I can manually create all the templates into one giant spreadsheet. I think this option is worse, as this does not allow for flexibility.

It seems that the underlying API allows this. https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.sheets/copyTo

**Comment by burnash** [comment]
Thank you for the suggestion. I like the idea. 
I think this could be a method on `Worksheet` class:

```python
worksheet.copy_to(spreadsheet_id="<SPREADSHEET_ID>")
```

Let me know if you're interested in implementing this method and submitting a PR.

**Comment by JoachimKoenigslieb** [comment]
I have written a method like this and will make a PR.

**Comment by abubelinha** [comment]
Thanks @burnash & @JoachimKoenigslieb 
I was looking for this functionality which I understand is already working.
Looking to the pull title "added duplicate_to", I understand there is now a [new function called `duplicate_to`](https://github.com/burnash/gspread/pull/758/commits/54e3165c5d40af37b5f7ee2303b4d43b1e0b81a9), but I don't know where I can see an usage example to learn its syntax. 
[Searched documentation for that](https://gspread.readthedocs.io/en/latest/search.html?q=duplicate&check_keywords=yes&area=default) name didn't find it.

Perhaps you changed its name later, and `copy_to` is now the correct method to use?
https://gspread.readthedocs.io/en/latest/api.html?highlight=duplicate#gspread.models.Worksheet.copy_to

Thanks

**Comment by JoachimKoenigslieb** [comment]
I think it is!

**Comment by nickolay** [comment]
Note that `copy_to` returns a dict, so you have to convert it to a proper `Worksheet` object manually, e.g.:
```
    src_ws = gsheet_client.open_by_key(src_gsheet_id).worksheet(src_ws_title)
    target_ws_props = src_ws.copy_to(target_gsheet_id)  # {'sheetId': 9999, 'title': 'Copy of ...', 'index': 2, 'sheetType': 'GRID', 'gridProperties': { ... }}
    target_ws = gspread.Worksheet(gsheet_client.open_by_key(target_gsheet_id), target_ws_props)
    target_ws.update_title("test")
```

There's also a bit of confusion because gspread follows Google's API in having a completely separate `duplicate_sheet` (#617) API for duplicating a sheet inside a spreadsheet.
