### ISSUE TITLE
Cell class should support conversion to A1 notation

### ISSUE THREAD

**Issue by tivaliy** [burnash/gspread#757]
Currently, there is no straightforward way to fetch data in `A1` notation from `Cell` object (of course one can use `utils` package explicitly). It will be a great to have this feature. 
Let's say you have the following steps to be performed:
1. Find some specific Cell by content.
2. Get a list of cells starting from previously found Cell.

**Comment by burnash** [comment]
I'm sorry I don't think I understand the problem. You can get a cell using A1 notation with `Worksheet.acell()`, aren't you? 
Could you please provide a code example to illustrate the case more clearly?

**Comment by tivaliy** [comment]
I mean that when you have `Cell` instance there is no way to represent it in `A1` notation for whatever reason, so I have to use numeric boundaries all the time.
Here is the case

```
sheet = some_sheet.sheet1
cell = sheet.find('AA')  # cell -> <Cell R2C1 'AA'>
```
Now I want to operate with `cell` in `A1` notation

**Comment by burnash** [comment]
I think I understand it now. Do you mean you want to get the cell address in A1 notation from the cell instance? 

As you said, at the moment the only option is to convert to A1 notation using `utils.rowcol_to_a1()`.
However, I think that having a property on the cell instance with address in A1 notation could be useful.

If you want you can make a pull request with the implementation of such property. I suggest naming it `address`.  So it would read `cell.address` in your example.

**Comment by tivaliy** [comment]
Ok, I will create PR soon.
