### ISSUE TITLE
TypeError:  Credentials need to be from either oauth2client or from google-auth

### ISSUE THREAD

**Issue by alecbw** [burnash/gspread#769]
**Describe the bug**
A change in version 3.4.0 broke my gspread.authorize(). I must use from_service_account_info (can't have a .json file in my environment), and rely upon [this hack](https://stackoverflow.com/questions/51618127/credentials-object-has-no-attribute-access-token-when-using-google-auth-wi/51808972) to enable it with a combo of google-auth and oauth2client.

**To Reproduce**
1. pip install --force-reinstall gspread==3.3.1
2. run the below code

3. pip install --force-reinstall gspread==3.4.0
4. run the below code and it breaks

[This Google Colab (Jupyter notebook service) demonstrates it, as well.](https://colab.research.google.com/drive/15N_i-rSimv-Qu3LZ0uQcYfJYEhVAYlMO)

**Expected behavior**
It should keep working? I am not clear why this is not working, but a minor version should not break my auth.

**Code example**
```py
import gspread
import google.auth.transport.requests
from oauth2client.service_account import ServiceAccountCredentials
from google.oauth2 import service_account
import os

class OAuth2ServiceAccountFromGoogleOAuth2(ServiceAccountCredentials):
    def __init__(self, google_oauth2_credentials):
        self.google_oauth2_credentials = google_oauth2_credentials
        self.access_token = google_oauth2_credentials.token

    def refresh(self, http):
        if self.access_token is None:
            request = google.auth.transport.requests.Request()
            self.google_oauth2_credentials.refresh(request)
            self.access_token = self.google_oauth2_credentials.token

def open_gsheet(sheet_name):
    auth = {
        "private_key": os.environ["GSHEETS_PRIVATE_KEY"].replace("\\n", "\n").replace('"', ''),
        "client_email": os.environ["GSHEETS_CLIENT_EMAIL"],
        "token_uri": "https://oauth2.googleapis.com/token",
    }
    scopes = ['https://www.googleapis.com/auth/spreadsheets']
    credentials = service_account.Credentials.from_service_account_info(auth, scopes=scopes)
    gc = gspread.authorize(OAuth2ServiceAccountFromGoogleOAuth2(credentials))
```
**Screenshots**
![Screen Shot 2020-04-24 at 5 28 51 PM](https://user-images.githubusercontent.com/23533756/80266508-276ab900-8651-11ea-8d29-8dee2cd4eabe.png)

**Environment info:**
Tested and reproduced both locally 
(MacOS High Sierra, 10.13.6, MBP mid 2014, Python 3.7.7, Pipenv, executed via [Serverless Invoke Local](https://serverless.com/framework/docs/providers/aws/cli-reference/invoke-local/)
and in a [Google Colab](https://colab.research.google.com/drive/15N_i-rSimv-Qu3LZ0uQcYfJYEhVAYlMO)
(Python 3.6.9)

The breaking change is for every version after (and including) 3.4.0.

**Comment by alecbw** [comment]
Guessing based on [these commits](https://github.com/burnash/gspread/pull/637/files) that oauth2client was intentionally deprecated and that's causing this auth to fail

If that's the case, can you:
* Update the error message to be more clear? It's currently `Credentials need to be from either oauth2client or from google-auth.`
* Provide an example of using `service_account.Credentials.from_service_account_info`? There is only a `from_service_account_file` example

**Comment by alecbw** [comment]
Closing this now, the solution was right in front of my face:

```py
    auth = {
        "private_key": os.environ["GSHEETS_PRIVATE_KEY"].replace("\\n", "\n").replace('"', ''),
        "client_email": os.environ["GSHEETS_CLIENT_EMAIL"],
        "token_uri": "https://oauth2.googleapis.com/token",
    }
    scopes = ['https://www.googleapis.com/auth/spreadsheets']
    credentials = service_account.Credentials.from_service_account_info(auth, scopes=scopes)
    gc = gspread.authorize(credentials)
```

Still think it's worth doing the two things in the comment above

**Comment by burnash** [comment]
Thank you for the input and for the detailed report. Totally agree on the suggestions.

The authentication topic is broad. Currently, I'm trying to make the auth as simple as possible (#762, #768). 

The library will greatly benefit if we have more cases covered in docs. Unfortunately, I can't cover a lot of cases from my own experience. 

> Update the error message to be more clear? It's currently Credentials need to be from either oauth2client or from google-auth.

Could you suggest a better message? This is something we can implement right away.

> Provide an example of using service_account.Credentials.from_service_account_info? There is only a from_service_account_file example

I'm open to accepting a PR for this one. As I said, more detailed docs for auth are certainly needed. We can start by adding something like "Custom Authentication" to [Authentication](https://gspread.readthedocs.io/en/latest/oauth2.html) docs.
