### ISSUE TITLE
Documentation: does get_all_values save on API requests?

### ISSUE THREAD

**Issue by MichaelChirico** [burnash/gspread#770]
I ran into a rate-limiting issue when using (essentially) `[sheet.row_values(i) for i in range(n)]`.

As a workaround, I found the `get_all_values` method, but it's not clear from the documentation that this can actually work for the purpose of saving API requests.

I had a look at the source code and it _looks_ like it will only make a single request, but anyway I think this is something important enough to warrant declaring directly in the documentation (as well as maybe on the examples page? https://gspread.readthedocs.io/en/latest/user-guide.html)

**Comment by burnash** [comment]
Sure, you can always improve the documentation and examples. Pull requests are very welcome :)

**Comment by aiguofer** [comment]
Hmm it's documented there: https://gspread.readthedocs.io/en/latest/user-guide.html#getting-all-values-from-a-worksheet-as-a-list-of-lists

That being said, some comments about pros/cons and differences between different methods of retrieving data would probably be useful.

**Comment by MichaelChirico** [comment]
@aiguofer I'm still not seeing it on that page... I see `get_all_values` mentioned twice:

> Getting All Values From a Worksheet as a List of Lists

usage without comment

> Using gspread with NumPy

Uses `get_all_values` indirectly while discussing interface with NumPy -- nothing specific to `get_all_values`.

**Comment by MichaelChirico** [comment]
> you can always improve the documentation and examples

@burnash thanks for the response. Usually I would be more than happy to file such PR, but truth be told, I wasn't even using the package myself -- this issue came up during a code review I was doing -- so I am particularly unqualified in this case.

**Comment by burnash** [comment]
@MichaelChirico thanks for elaborating. I'm closing the issue for now.

**Comment by burnash** [comment]
@MichaelChirico could you take a look at #771 to see if this clears things up a bit? (Proofreading is  also appreciated, English is not my first language.)
