### ISSUE TITLE
Library is not updated in conda

### ISSUE THREAD

**Issue by akashvyom** [burnash/gspread#772]
The last publish to conda was made 1 year and 4 months back can we publish all the latest version to conda as well
![image](https://user-images.githubusercontent.com/8558879/81547340-585d2480-9399-11ea-804c-c637ee02198c.png)

**Comment by burnash** [comment]
Thanks for the info. I believe you're referring to this URL: https://anaconda.org/conda-forge/gspread

I'll be glad if the latest version of gspread is available on conda.
Unfortunately, I didn't publish gspread to conda myself. There's no information about the maintainer of the conda package available so I hope it's automatic. 

I'm happy to get help with this issue.

**Comment by burnash** [comment]
It looks like this is the source repo for the conda package https://github.com/conda-forge/gspread-feedstock

Again, I would appreciate if someone could help to figure out why the package is not updating in conda.

**Comment by akashvyom** [comment]
@burnash I will take a look at this as this is something I need with one of our projects as well

**Comment by burnash** [comment]
@akashvyom thank you very much!

**Comment by akashvyom** [comment]
@burnash previous PRs were never merged in conda-forge and newer ones are failing the test because of missing dependencies during the run cycle, I have raised an issue with them for the same
https://github.com/conda-forge/gspread-feedstock/issues/17
this should be a simple fix will update here once this is done

**Comment by burnash** [comment]
Thank you very much, @akashvyom

**Comment by akashvyom** [comment]
@burnash thank you for agreeing on being a maintainer for the conda forge repo, I will publish all the packages till the latest version which were left out, once done will mark this as resolved.

**Comment by akashvyom** [comment]
@burnash I have pushed the latest package to anaconda cloud any new releases should automatically be pushed now, I am closing this issue.

**Comment by burnash** [comment]
Thank you very much for your help!
