### ISSUE TITLE
Issue https://github.com/burnash/gspread/issues/697 re-appeared since 18th May 2020

### ISSUE THREAD

**Issue by rathegod1992** [burnash/gspread#777]
Hi @burnash , i am using python 3.7.1 with **gspread** library version 3.1.0. 
I tried with gspread 3.6.0 but it is the same issue.

Until the 17th of May 2020, every time i shared a spreadsheet with a user, that user received an email notification. My share function is like this:

def share_spreadsheet_with_users(self, users_to_share_with):
    """

    :param users_to_share_with: the users with whom the spreadsheet will be shared
    :return:
    """
    for user in users_to_share_with:
        **self.spreadsheet.**share(user, perm_type='user', role='writer')

In the code above, the self.spreadsheet is a newly created spreadsheet and has type: gspread.Client

Ever since 18th May the user is only shared the spreadsheet (which can be seen in the google drive) but the user is NOT also notified on email. What could be the issue ?

This is a follow up to issue #697

**Comment by burnash** [comment]
Answered in #697. Most likely an API backend issue.

**Comment by rathegod1992** [comment]
Hi @burnash ,

It seems that the google service for mail notification is working again. Starting from 2 June 2020.

Thanks.

**Comment by Muskan-ai** [comment]
Hi @burnash  , 

I was able to notify others when i shared the spreadsheet until 3 December 2020. Today I am unable to do it
How can we fix it?

**Comment by lavigne958** [comment]
I tried a quick test: shared a spreadsheet with a new user:
- used a valid email address
- perm_type='user'
- role='writer'

worked fine.
email was sent to the user. 

closing this issue
