### ISSUE TITLE
Feature request: Authentication from service account key in memory

### ISSUE THREAD

**Issue by offlinemark** [burnash/gspread#779]
The current auth API takes a filename

```
gspread.service_account(filename='./X.json')
```

In some environments, it's much easier to pass configuration via the environment, rather than the filesystem. An example is Heroku.

It would be nice if the `service_account` API allowed passing the *contents* of that json file, instead of a filesystem path to it.

To implement it gspread would just need to use the `Credentials.from_service_account_info` API. It should be pretty simple. Here's a snippet that illustrates this. In this example, the json file is base64 encoded and loaded into the env variable `GSHEET_CRED_B64`. It's then decoded, parsed into a python dict, and passed into `from_service_account_info`.

```
GSHEET_CRED_B64 = os.environ['GSHEET_CRED_B64']
GSHEET_CRED = base64.b64decode(GSHEET_CRED_B64)
blob = json.loads(GSHEET_CRED)
creds = Credentials.from_service_account_info(blob, scopes=gspread.auth.DEFAULT_SCOPES)
gc = Client(auth=creds)
```

**Comment by burnash** [comment]
Great idea, totally agreed.
