### ISSUE TITLE
Overwriting a sheet with fewer rows currently requires 2 (non-atomic) operations

### ISSUE THREAD

**Issue by adamcunnington** [burnash/gspread#781]
I think the Google Sheets API for updating cells against an entire sheet range is unintuitive. If my sheet has 100 rows and I wish to replace it with 10 rows, I would expect that providing 10 rows to gspread.worksheet.update would do this. At first, i thought this was a bug in gspread because of how the default range parameter is handled (by the way, the way you guys have implemented the range parameter being optional is hacky as heck; reminds me of python 2.x's range method - don't do this, just use proper python named optional parameters! e.g. range=None, values=None...). ANYWAY, it's not a gspread bug, it's stupid behaviour from google sheets API; if you overwrite with fewer rows, they don't drop the remaining rows.

This means that we have to do this in at least 2 operations, either:
- clear sheet first, then insert/update - BAD idea because if insert/update fails, you remove the data before the operation succeeds. You could add some hackery to store the current data and restore that as a 3rd operation after but hey, that could fail to.
- update and then delete the remaining rows - BETTER but still bad because the deletion could fail in which case we've now got dirty data.

It would be helpful if gspread could provide better support for this - I don't think it can be foolproof so long as the google sheets api can't handle this simple operation atomically... but you could have various "restore" fallbacks to save me writing this code.

P.s. let me know if you want me to file a bug against google sheets api behaviour instead.

**Comment by bastienboutonnet** [comment]
@adamcunnington I've suffered from this recently too and ended up doing exactly what you outline in your first bullet. Clean, and recreate. But, of course, the recreate failed and I ended up with an empty sheet so I ended up doing:
1. store data
2. clear the sheet
3. recreate
--if an error was thrown try to recreate the sheet with the stored data from before clearing
4. check the sheet isn't empty (which really should be check the sheet either match what you wanted to put in there)
--if empty (or doesnt match) add your previous data back and throw some error.


It's indeed pretty painful and would make sense to have some good practices and standardisation on the upstream side of things (i.e. in `gspread` in my opinion).

However, I have no idea how `gspread` could make this truely atomic. It'd probably have to do something similar to your bullet points right? I'm also not a python guru so maybe I don't know how to make atomic-like transactions. BUT, if there was interest and some pointers it would be a super cool thing to bake into `gspread` however hacky it is as it would at least prevent everyone else to come up with equally or worse hacky solutions on their end.

**Comment by lavigne958** [comment]
Hi @adamcunnington thank you for pointing out this issue.
As mentioned this is not on our side, we can only rely on the API provided by google.
Since they do not provide an atomic API to empty a sheet *AND* fill it, we can't do anything.
Even if we send both requests one after an other with the shortest time between each, there is a possibility that someone else update the sheet in between or empty the sheet or anything else.

It simply can't be done.

Thank for poiting out the `range_name` parameter in the `update()` method, I fixed the docstring, it is mandatory parameter and the docstring was not updated.
