### ISSUE TITLE
.batch_update: Tries writing in wrong column

### ISSUE THREAD

**Issue by LennartOschika** [burnash/gspread#792]
So I am trying to optimize my Code and i figured that one of the best ways of reducing API calls was to use the batch_update function on my spreadsheet. 

What I am using it for: 
I basically have a bunch of topics in my spreadsheet that I want to assign a # to in the column next to it. 
So in column b there is some topic let's say and next to it (in column a) I want to just keep track of how many topics there have been. (The row numbers aren't viable for this). So for example in Row 1104 there is topic 989.

Code: 
`values = [1, 2, 3, 4] # different depending on how far down i am in the spreadsheet of course
 range = 'A1:A4'

 worksheet.batch_update([{
        'range': range,
        'values': [values],
    }])`

I get the actual Values in a slightly different way but it comes out to the same results no matter what.

So I would think that 1-4 would now be added in order to column 'A'.
           A
Row 1: 1
Row 2: 2
Row 3: 3
Row 4: 4

However it gives me this error:
`gspread.exceptions.APIError: {'code': 400, 'message': "Invalid data[0]: Requested writing within range ['All Rambles'!A1112:A1131], but tried writing to column [B]", 'status': 'INVALID_ARGUMENT'}`

I don't get how/why it tries to write something in column B since this is all the Code that is running in the time that I am trying to optimize this (I commented out the rest of my code). 

Maybe I am just missing something that is really obvious or there is some error in the batch_update function.

Anyways, have a nice day

**Comment by erakli** [comment]
I think you could fix it in the following way:

```python
rows = [
    [1],
    [2],
    [3],
    [4]
]
range = 'A1:A4'

worksheet.batch_update(
    [
        {'range': range, 'values': rows}
    ]
)
```

I suppose that `batch_update()` only works with rows as major dimension.

**Comment by lavigne958** [comment]
@LennartOschika 

The way this method works is:
- provide some values
- provide a range
- Gspread will write the values at the specified range

the values must be given as a list (parent list).
the list contains: list of values (child list).
the child lists will contain values over the specified range row.
So the first child list contains the first row, next child list the second row etc.
If you want to write values to A1:A4 range you must use the example given by @erakli and have a list with a single value for each row.

Closing this issue.
