### ISSUE TITLE
Inserting columns

### ISSUE THREAD

**Issue by AlexeyDmitriev** [burnash/gspread#798]
I want to insert new columns (between existing columns)

It seems that it's supported by underlying API but not in the provided

I just need inserting empty column, but it's probably makes sense to make the API the same as with insert_row/insert_rows

I'm ready to provide a PR for that if it's fine

**Comment by burnash** [comment]
I'll be happy to get a PR for this. Please call the method `insert_columns()` for consistency. It would be great if the method signature is consistent with `insert_rows()`. I also think that having only one (multi) method should be enough as it can handle both single and multi-column insertions.
