### ISSUE TITLE
Specify destination folder for copy() result

### ISSUE THREAD

**Issue by ScDor** [burnash/gspread#805]
**Is your feature request related to a problem? Please describe.**
When using copy(), I couldn't set the destination folder (where the copy is saved)

**Describe the solution you'd like**
allowing a specified folder in _copy()_, similar to the way it's done in _create()_.

**Describe alternatives you've considered**
using the google drive API for renaming and moving the file

**Additional context**
I've already implemented the change - PR to follow.
My implementation requires sending the copy request using Google API V3 (or, at least, I couldn't tell how to do it with API V2)

**Comment by burnash** [comment]
Thank you for the suggestion, the PR is welcome :) 
Please use API v3, `create()` already uses it.

**Comment by Abolfazl** [comment]
> Thank you for the suggestion, the PR is welcome :)
> Please use API v3, `create()` already uses it.

I am not sure I follow.. [Create()](https://gspread.readthedocs.io/en/latest/api.html#gspread.Client.create) only requires a `title` and `folder_id` and [Copy()](https://gspread.readthedocs.io/en/latest/api.html#gspread.Client.copy) requires `file_id` and `title`.

What would I have to do to copy a complete worksheet into `folder_id`

**Comment by ScDor** [comment]
> > Thank you for the suggestion, the PR is welcome :)
> > Please use API v3, `create()` already uses it.
> 
> I am not sure I follow.. [Create()](https://gspread.readthedocs.io/en/latest/api.html#gspread.Client.create) only requires a `title` and `folder_id` and [Copy()](https://gspread.readthedocs.io/en/latest/api.html#gspread.Client.copy) requires `file_id` and `title`.
> 
> What would I have to do to copy a complete worksheet into `folder_id`

The way i implemented it so far (will push and PR soon) it, there's an extra argument _folder_id_ (default=None) you need to supply. 
Your comment reminded me to test the behavior when it's None - my gut says it'll do fine, I'll update.
Thanks

**Comment by punnerud** [comment]
I created a pull request to fix this. Have tested it with folder_id, None, random values etc.
The code is based on way create() add parent folder, but had to add some changes to the way parents is added to payload (ref. id).

For me it is an important feature because it enable the use of templates.
