### ISSUE TITLE
worksheet.insert_row not updating with a value list

### ISSUE THREAD

**Issue by Dmdv** [burnash/gspread#806]
I tried to find a solution, there weren't any

---

**when I try to insert a row at index = 2 with a range of values it throws an exception**
In docs they say that values should be a value list

![image](https://user-images.githubusercontent.com/805238/89862364-74e34580-dbb0-11ea-90d6-129708da44e5.png)

**Environment info:**
- Operating System Windows:
- Python version = 3.8
- gspread version = the last one

**Comment by Dmdv** [comment]
It works only if I insert a single value

**Comment by ideacco** [comment]
I also encountered the same problem, if I can insert a two-dimensional list such as [[],[],[]]... so I can update multiple pieces of data into the document at once

**Comment by Dmdv** [comment]
@lavigne958 I'm sorry, I don't own the code now for reproduction. Sure, you can close it

**Comment by lavigne958** [comment]
No worries, thanks for taking a look though.
