### ISSUE TITLE
 Function get_all_records() having issue when we pass head parameter greater than 1

### ISSUE THREAD

**Issue by grkamarnath** [burnash/gspread#810]
Suppose i have a google sheet with 3 rows like shown below.

Header1  Header2    Header3
value1      value2       value3
value4     value5       value6

then, we called function get_all_records(head=2), it will return 1 row but keys of the row is not correct.
output:    [{value1:value4, value2:value5, value3:value6}]

Expected/Correct output: [{Header1:value4, Header2:value5, Header3:value6}]

**Comment by yberezkin** [comment]
In my understanding of documentation for code it is works as it supposes to work. 
"""Returns a list of dictionaries, all of them having the contents of
        the spreadsheet with the head row as keys and each of these
        dictionaries holding the contents of subsequent rows of cells as
        values.
”””

What @grkamarnath you are talking about is to skip 1rst row, which logically not a head.

**Comment by grkamarnath** [comment]
Thank you @yberezkin 

I miss understood the head parameter purpose..
