### ISSUE TITLE
value_render_option Has No Effect for Hyperlinks

### ISSUE THREAD

**Issue by jjorissen52** [burnash/gspread#812]
When trying to use the shown pattern for a cell that contains a hyperlink, the text is returned instead of the formula:
https://github.com/burnash/gspread/blob/c0a5a6d83083c467a647ab91bf1caaa1f829b5c7/tests/test.py#L561 

**To Reproduce**
1. Have a worksheet with a hyperlink
2. Access it as a cell with `value_render_option="FORMULA"`
3. See content is the text of the hyperlink instead of the formula.

**Expected behavior**
I expect the value of the cell to be a formula

**Code example**
```python3
print(worksheet.acell('J9', value_render_option="FORMULA"))
# <Cell R9C10 'Facebook'>
```

**Environment info:**
- macOS
- Python 3.7.4
- gspread == 3.6.0

**Stack trace or other output that would be helpful**

Some values printed from `Spreadsheet.values_get` before the `Cell` is created:

https://github.com/burnash/gspread/blob/c0a5a6d83083c467a647ab91bf1caaa1f829b5c7/gspread/models.py#L108-L111
```
# params
{'valueRenderOption': 'FORMULA'}
# r.json()
{'range': "'...'!J9", 'majorDimension': 'ROWS', 'values': [['Facebook']]}
```

**Additional context**
I have read only access to this spreadsheet.

**Comment by lavigne958** [comment]
Hi @jjorissen52 you can't have a formula and a hyperlink. you must choose between or the other.
gspread can't change anything in this case, we only get what the API provides. In any cases it returns: the text of the hyperlink.
I tried multiple scenarios and found no use of `value_render_option` to obtain the hyperlink.

closing this issue.
