### ISSUE TITLE
Intermittent Deprecation Warning on Import in Google App Engine

### ISSUE THREAD

**Issue by amanda-ruby** [burnash/gspread#815]
**Describe the bug**
Intermittently, import of gspread in a GAE application is producing the following warning: `/env/lib/python3.7/site-packages/gspread/auth.py:38: DeprecationWarning: invalid escape sequence \g """`.  Why it is intermittent is so far unclear.

**To Reproduce**
1. Run an application with gspread in GAE.
2. Wait.

**Expected behavior**
No deprecation warning.

**Code example***
Around line 38 in gspread's auth.py, there's a comment that contains the implicated `\g` character.  
`"""Construct a config dir path.

    By default:
        * `%APPDATA%\gspread` on Windows
        * `~/.config/gspread` everywhere else

    """`

**Environment info:**
- Operating System [e.g. Linux, Windows, macOS]: Google App Engine Standard
- Python version - 3.7
- gspread version - 3.6.0

**Additional context**
We have code in place that only actually instantiates a gspread client when it's needed, but this module is imported every time the class is instantiated.  It's unclear why this deprecation warning is only intermittent.  It appears to be a Python deprecation warning and does not appear when running unit tests locally.

**Comment by lavigne958** [comment]
Hi @amanda-ruby-nyt thank you for pointing out this issue.

Unfortunately there is not much we can do here, this is a text in a comment, and this comment applies to windows user which uses back slashes for path and not forward slashes (like any unix system, aka: linux, macOS etc). on the top of it, this kind of a comments are actual python strings, but they are meant to be comments (or docstring) and not actual regular code comments, so they are strings and they receive the same warnings as strings but they are not suppose to :slightly_frowning_face: 

it is strange though as I run GSpread very often and never see such warnings.

**Comment by lavigne958** [comment]
I had a look and since then the comment has been updated and the string comment is now a `raw string` so the backslash `\` in not interpreted and does not need to be escaped.

closing this issue.
