### ISSUE TITLE
AttributeError: module 'gspread' has no attribute 'service_account'

### ISSUE THREAD

**Issue by arditoibryan** [burnash/gspread#817]
Hello, I just installed gspread in Google Collaboratory:

`pip install gspread`

Then I tried to run the code following the instructions:

```
import gspread

gc = gspread.service_account()

output:
AttributeError: module 'gspread' has no attribute 'service_account'
```

Thank you

**Comment by DatanamixSR** [comment]
I am running into this as well, did you ever solve the issue?

**Comment by burnash** [comment]
Could you please share the gspread version you're using?

```
>>> gspread.__version__
```

**Comment by DatanamixSR** [comment]
> Could you please share the gspread version you're using?
> 
> ```
> >>> gspread.__version__
> ```

can't speak for ardito, but I am on gspread 3.1.0

**Comment by burnash** [comment]
In this case, you'd need to upgrade gspread, as `service_account()` was added in [3.6.0](https://github.com/burnash/gspread/blob/master/HISTORY.rst#360-2020-04-30)

**Comment by saad-sifar** [comment]
I found a fix, I had this exact problem and I could not find a solution anywhere, then when I removed a file called secrets.py from my working directory it worked perfectly fine. Make sure that you have no other files with common names in your cwd

**Comment by rahul-soshte** [comment]
Don't name any of your files inside your directory as gspread.py. I had named the same thing and it was giving me an error. I changed the name to something else and it worked.

**Comment by burnash** [comment]
@rahul-soshte Thank you for the update. I believe this should resolve the issue.

**Comment by lassebenni** [comment]
> Don't name any of your files inside your directory as gspread.py. I had named the same thing and it was giving me an error. I changed the name to something else and it worked.

Thanks, it was actually in the error: `circular import`.

**Comment by nikett** [comment]
In the working directory, there was a file `secrets.json`, renaming it worked.
