### ISSUE TITLE
insert_row produces APIError if the selected sheet has ":" in its name

### ISSUE THREAD

**Issue by bqback** [burnash/gspread#822]
**Describe the bug**
Trying to insert_row to a sheet with ":" in its name seems to cause the name to be interpreted as a range

**To Reproduce**
1. Create a sheet with ":" in its name
2. insert_row() to it

**Expected behavior**
A row with given values is inserted into the sheet

**Code example***
```
from gspread import service_account, exceptions

def main():
    client = service_account(filename = 'client.json')
    spreadsheet = client.open('Spreadsheet')
    spreadsheet.add_worksheet('foo:bar', 1, 2, index = 0)
    sh = spreadsheet.get_worksheet(0)
    try:
        sh.insert_row(['test', 'tset'])
    except exceptions.APIError as error:
        spreadsheet.del_worksheet(sh)
        print(error)
        print('insert_row failed')

if __name__ == '__main__':
    main()
```

**Environment info:**
- Operating System: Windows 10
- Python version: 3.6
- gspread version: 3.6.0

**Stack trace or other output that would be helpful**
The received APIError contains message `Requested writing within range ['foo:bar'!A1], but tried writing to column [B]`

**Additional context**
No idea if other functions have this issue, I only tried this one.

**Comment by lavigne958** [comment]
After looking around online, I found the open issue on google side, they left a comment saying:
> reproduced the error, an internal issue has been filled.

Thas was in april this year.
[Here is the link to the issue tracker](https://issuetracker.google.com/issues/36761154)

What we can do until then is prevent sheet title creation that contains a colon `:`.
