### ISSUE TITLE
Set formula

### ISSUE THREAD

**Issue by NicoWithManyO** [burnash/gspread#823]
Hello. first big thank you for the job :) I try to insert in a cell instead of values ​​(the same way we do worksheet.update). I'm just starting out and maybe I haven't seen a simple solution? thank you for your possible answers;)

**Comment by lavigne958** [comment]
Hi @NicoWithManyO,
first thank you for your support :slightly_smiling_face: 

no worries everyone start somewhere :wink: 

In GSpread when you read the value of a cell using some method like `WorkSheet.cell()` or `WorkSheet.range()`
then GSpread returns an object of type `Cell`. This object contain some details about the actual cell (row, column, value)
but if you update the value it is not reflected to the worksheet (nor the spreadsheet), you have an object that is a copy of the cell you are looking at. If you wish to update it's value you must use one of the following methods:
- update_acell
- update_cell
- update_cells
- update
- append_row
- append_rows
- insert_row
- insert_rows
- insert_cols

some of the above methods take a cell coordinates, there you can get it from the `Cell` object you have. 
(This is a basic example)
```
sheet = gc.open("mySpreadSheet").sheet1
cell = sheet.cell(1,1)
sheet.update_cell(cell.row, cell.col, "NewValue")
```

I am closing this answer as this kind of issue is usually answered on [StackOverFlow](https://stackoverflow.com/questions/tagged/gspread)
