### ISSUE TITLE
format_cells()?

### ISSUE THREAD

**Issue by nejko** [burnash/gspread#825]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I need to change the background color of many unconnected cells in a sheet, and I have to do as many API calls as the number of colored cells.

**Describe the solution you'd like**
As we have update_cells() to update many cells with a single API call, it would be ideal to have format_cells() to change the format of many cells at once, with a single API call.

**Describe alternatives you've considered**
Waiting for hours for my script to do all the color changes.

Thanks!

**Comment by burnash** [comment]
[gspread offers only basic formatting](https://gspread.readthedocs.io/en/latest/user-guide.html#formatting). For anything complex please check [gspread-formatting](https://github.com/robin900/gspread-formatting).
