### ISSUE TITLE
Allow `gspread.oauth()` to look for file in another directory

### ISSUE THREAD

**Issue by bastienboutonnet** [burnash/gspread#826]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but I got bitten a bit by it. I used to be using a service account and `service_account` allows users to store google credentials where they want. This is particularly relevant for the flow I have implemented in my CLI tool to import google sheets to SQL databases ([`sheetwork`](https://github.com/bastienboutonnet/sheetwork)) where I require users to put credentials into a `.sheetwork` folder.

`gspread.oauth` doesn't take arguments for filename, but since it uses `load_credentials()` https://github.com/burnash/gspread/blob/master/gspread/auth.py#L93 I would assume this is possible.

Is there a reason why this might not be allowed? Could it break a few things?

**Describe the solution you'd like**
allow `oaut()` to take a `filename` argument that is passed to `load_credentials`

If you agree that this would be possible, I'd be happy to contribute to the change.

**Comment by bastienboutonnet** [comment]
Hey @burnash I was wondering if you'd be open to this minor feature.

My feeling is that `gspread.oauth()` could take a `filename` that defaults to the `DEFAULT_AUTHORIZED_USER_FILENAME` value but that could be overriden if a user or an app using `gspread` required to dump credentials in other places.

Since your `CONTRIBUTING.md` guidelines stress the fact of needing a greenlight before starting the work I don't want to open up a PR but I think (unless I miss some nuance somewhere) that this could be a really easy and handy solution that is entirely backward compatible with the current flow.

Let me know what you think.

**Comment by a-kochkarev** [comment]
> **Is your feature request related to a problem? Please describe.**
> Not really a problem, but I got bitten a bit by it. I used to be using a service account and `service_account` allows users to store google credentials where they want. This is particularly relevant for the flow I have implemented in my CLI tool to import google sheets to SQL databases ([`sheetwork`](https://github.com/bastienboutonnet/sheetwork)) where I require users to put credentials into a `.sheetwork` folder.
> 
> `gspread.oauth` doesn't take arguments for filename, but since it uses `load_credentials()` https://github.com/burnash/gspread/blob/master/gspread/auth.py#L93 I would assume this is possible.
> 
> Is there a reason why this might not be allowed? Could it break a few things?
> 
> **Describe the solution you'd like**
> allow `oaut()` to take a `filename` argument that is passed to `load_credentials`
> 
> If you agree that this would be possible, I'd be happy to contribute to the change.

I faced the same problem when strart to use gspread.  I change default creds location by modifying gspread settings and default function parameters. Not very elegant, but working solution:

`
import gspread.auth as ga
import mysettings as cfg

def changeUserCredsStorage():
    '''
    Workaround to change default creds location for gspread.
    Not needed if service account used.
    '''
    ga.DEFAULT_CONFIG_DIR = cfg.DEFAULT_SECRETS_DIR

    ga.DEFAULT_CREDENTIALS_FILENAME = os.path.join(
        ga.DEFAULT_CONFIG_DIR, 'credentials.json'
    )
    ga.DEFAULT_AUTHORIZED_USER_FILENAME = os.path.join(
        ga.DEFAULT_CONFIG_DIR, 'authorized_user.json'
    )
    ga.DEFAULT_SERVICE_ACCOUNT_FILENAME = os.path.join(
        ga.DEFAULT_CONFIG_DIR, 'service_account.json'
    )

    ga.load_credentials.__defaults__ = (ga.DEFAULT_AUTHORIZED_USER_FILENAME,)
    ga.store_credentials.__defaults__ = (ga.DEFAULT_AUTHORIZED_USER_FILENAME, 'token')
`

But now i switch to service accounts and do not use this.

**Comment by bastienboutonnet** [comment]
@a-kochkarev ah yeah that's a good idea for a workaround! Thanks. Obviously I would still think maybe @burnash would be interested in making `oauth` work similarly to `service_account` so I'll leave this open and see.

**Comment by bastienboutonnet** [comment]
Ok @a-kochkarev I just tried it and I can confirm that your workaround works. Thanks for this!

**Comment by aa-dank** [comment]
Would like to reiterate interest in this feature. I had trouble using the authentication in a single script to be used in a google colab notebook and as a standalone.

**Comment by bastienboutonnet** [comment]
Would be happy to help if this feature fits in the maintainer's vision for sure!

**Comment by abubelinha** [comment]
I also agree this would be very useful.
I have some scripts I use in different computers and I do not want leave my google user credentials stored in each of them.

Porting scripts + credentials files in my usb disk is much more convenient.

**Comment by abubelinha** [comment]
Thanks a lot @akochkarev for your workaround. 
I also agree with @bastienboutonnet that allowing `gspread.oaut()` to take filename arguments is a must (not only for `DEFAULT_CREDENTIALS_FILENAME`, but also for taking control of where `DEFAULT_AUTHORIZED_USER_FILENAME` will be stored).
I hope @burnash agrees with us.  

My use case:

Like @aa-dank I have some scripts I use in different computers (some of them shared with other people). 
So I can't leave my Google user credentials stored in any of them.
Porting scripts + credentials files in my usb disk and running from there is much more convenient.

**Comment by abubelinha** [comment]
Thanks a lot @akochkarev for your workaround. 
I also agree with @bastienboutonnet that allowing `gspread.oaut()` to take filename arguments is a must (not only for `DEFAULT_CREDENTIALS_FILENAME`, but also for taking control of where `DEFAULT_AUTHORIZED_USER_FILENAME` will be stored).

My use case:

Like @aa-dank I have some scripts I use in different computers (some of them shared with other people). 
So I can't leave my Google user credentials stored in any of them.
Porting scripts + credentials files in my usb disk and running from there is much more convenient.

I hope @burnash agrees.

**Comment by burnash** [comment]
Hey @bastienboutonnet. Sorry for the slow response. Yes, I'm open to this feature.

**Comment by bastienboutonnet** [comment]
@burnash awesome! I'll have a look over the weekend :)

**Comment by bastienboutonnet** [comment]
@burnash I had a go at this in this PR: https://github.com/burnash/gspread/pull/847 let me know if you have any comments

**Comment by malachibazar** [comment]
Any updates on the PR? I would love this feature.

**Comment by bastienboutonnet** [comment]
I believe when @burnash gets around to giving another look at the PR it should be good as all the changes they asked for have been implemented.
