### ISSUE TITLE
'Worksheet' object has no attribute 'get' in Colab

### ISSUE THREAD

**Issue by g3blv** [burnash/gspread#827]
I want to read a range from a Google Sheet using `gspread` in Python in Colab.

This is my code

```python
spreadsheet = gc.open_by_url('https://docs.google.com/spreadsheets/,,.')
worksheet = spreadsheet.get_worksheet(4)
worksheet.get('B1:AK22')
```

It returns the error
```
---> worksheet.get('B1:AK22')
     
AttributeError: 'Worksheet' object has no attribute 'get'
```

From what I understand from the documentation [get()](https://gspread.readthedocs.io/en/latest/api.html#gspread.models.Worksheet.get) it should be possible to use `get()` on a `worksheet`.

`worksheet.id` and `worksheet.title` returns `id` and `title` as expected.

`!python3 --version Python 3.6.9`
`print(gspread.__version__) 3.0.1`

**Comment by jpsanr** [comment]
Hello, I'm facing the same issue. Did you manage to fix it?
