### ISSUE TITLE
append_row() adds row which starts not from first column

### ISSUE THREAD

**Issue by a-kochkarev** [burnash/gspread#828]
**How to reproduce:** 
1. Make worksheet with one row and empty cell:
1 | 2 | <empty_cell> | 3 
 
2. Insert row with:  
worksheet.append_row(['a','b','c'])

3. Row was inserted starting from D column:
1 | 2 | <empty_cell> | 3 
   |    |                        | a | b | c 

**Expected behavior:**
Expected row insertion from first (A) column

**What we get:**
![image](https://user-images.githubusercontent.com/429784/99142100-72e3c380-2684-11eb-8c2a-ebf6ba0f2d7f.png)

**Environment info:**
- Windows 7 x86
- Python 3.7
- gspread 3.6.0

**Comment by Gitarth** [comment]
[Check this link out ;)](https://github.com/burnash/gspread/issues/537#issuecomment-586622830
)
This may help you resolve the issue. This seems to be a Google Sheets API thing which you can check out at [the google sheets documentation.](https://developers.google.com/sheets/api/guides/values#appending_values)

**Comment by a-kochkarev** [comment]
@Gitarth, thanks a lot for pointing out to this resolved issue!
