### ISSUE TITLE
pipy version doesn't seem to match Github

### ISSUE THREAD

**Issue by yniu** [burnash/gspread#837]
Pip install says version is 3.6.0, but models.py for get_all_records() is missing 'value_render_option' as an argument, which is inconsistent with what's in github.

**Comment by lavigne958** [comment]
make sens, the parameter you speak about has been added shortly after the release of 3.6.0.

Here is the commit that introduces the option 959613d320ed60502eb7db15ee2934bfd0c51933

Here is the release [link](https://github.com/burnash/gspread/releases/tag/v3.6.0) where you can see that the release is just a couple of month earlier.

**Comment by burnash** [comment]
@lavigne958 is right. The update wasn't released. 3.7.0 is out now. Please upgrade gspread.
