### ISSUE TITLE
insert_col ?

### ISSUE THREAD

**Issue by AirQs** [burnash/gspread#842]
It's very easy to modify the entire row data with insert_row, however, I couldn't find a way to modify the entire column as easily as "insert_row" does.

It could be good to create a function like "insert_column".

**Comment by lavigne958** [comment]
Hi a function already exists in the laster master branch to do so.
Checkout master branch or commit 52eef450910046a4fdac641aed456dbe986defe3

:wink:

**Comment by burnash** [comment]
The method is now available in the release 3.7.0. Please upgrade to the latest version. 
Documentation: [Worksheet.insert_cols()](https://gspread.readthedocs.io/en/latest/api.html#gspread.models.Worksheet.insert_cols)
