### ISSUE TITLE
how to work over cached versions of Gsheet files (even offline)?

### ISSUE THREAD

**Issue by abubelinha** [burnash/gspread#846]
**Is your feature request related to a problem? Please describe.**
I need to handle lots of google sheets from different providers, to backup data from certain columns to a database.
Each time I am testing my code (which should go across all these different files) I want to avoid sending unnecessary http requests to Google. All those data could be already in my computer, I guess.
So I could make changes and test my python gspread scripts even when I am working completely offline.

**Describe the solution you'd like**
A way to **use gspread over a cached version** of a Google Sheet file (which does contain a number of different worksheets inside).
So I can request the whole file once (the first time I launch my script), and in further script calls all my gspread functions will make use of the cached version.
Probably this is something which can be done outside gspread ... but I still couldn't figure out the simplest way to do it:

**Describe alternatives you've considered**
- I expected it to be possible to do this myself, and tried using [pickle](https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled) python package.  
But I am hitting with previous [issues related to it](https://github.com/burnash/gspread/issues/455#issuecomment-775096345).  
A somehow related [conversation](https://python-forum.io/Thread-Write-object-to-file?pid=109133#pid109133) in a Python forum.
- Not sure if [this issue](https://github.com/burnash/gspread/issues/90) was asking the same thing as me, but it's closed.
- Perhaps things like [beaker](https://beaker.readthedocs.io/en/latest/) or [dogpile.cache](https://github.com/sqlalchemy/dogpile.cache) could be useful, but they seem too complicated for my current programming level.

**Comment by abubelinha** [comment]
Thanks @lavigne958 for the detailed answer. 
I don't catch the meaning of "_CI_", but I get the idea.

All this sounds very interesting. 
Probably too hi-tech for my programming skills, but I will try to look at it.

Just one question: when you say pyvcr, do you mean this project?  
https://github.com/kevin1024/vcrpy

Name is different but description is similar.

**Comment by lavigne958** [comment]
CI means Continuous Integration, it is the test suite that runs every time we push a new commit or open a new PR. to make sure
we don't introduce any regressions.

Have look, I advise you to start small, with the tutorial/examples on the python pyvcr website.

Yes I do, that is the library we use.
Ho yes sorry it might be vcrpy :smile:, apologies
