### ISSUE TITLE
Feature Request: get_note()

### ISSUE THREAD

**Issue by marcusbeckerman** [burnash/gspread#849]
There is a a clear_note() method, and insert_note() method, and an update_note() method, but there doesn't seem to be a method to get the note of a cell(s). Can this be added?

**Comment by burnash** [comment]
Open for a PR

**Comment by water-ghosts** [comment]
I've created a PR for this feature, added test cases, and confirmed that the test suite runs successfully.

This is my first time contributing to this project, so let me know if there are additional steps I'm missing, or if you'd prefer I step aside and let someone more experienced handle this request 🙂
