### ISSUE TITLE
delete_rows, delete_dimension does not remove the right indexes.

### ISSUE THREAD

**Issue by isaacaudet** [burnash/gspread#850]
I am trying to delete unused rows in a template. However I need to keep the last 20 lines in the sheet. I have tried using delete_rows, as well as looping through indexes in reverse order. It seems when I delete rows it messes up the indexes, and ends up deleting much more than intended. Any way around this? Don't have time to provide my code right now but I could upload the excerpt if someone would like to see.

Thanks

**Comment by isaacaudet** [comment]
`    worksheet.delete_rows(index, index + end_index)
          row = worksheet.row_values(index)
          print(row)
          if row == ['', '#N/A', '-', '#N/A', '#N/A', '#N/A', '#N/A', '', '#N/A', '#N/A', '', '#N/A', '#N/A', '#N/A']:
              worksheet.delete_rows(index) `

**Comment by isaacaudet** [comment]
With that line of code I check if the row is the value I want to delete because the indexes are inconsistent, however it deletes two rows at that index. But only in one of my spreadsheets. The rows aren't combined. It seems tied to even vs odd staring index, unsure though.

**Comment by lavigne958** [comment]
Hi @isaacaudet thank you for pointing out this issue.

I still need to investigate a bit, but I believe what happens to you is:
- you get the worksheet
- you ask to delete row X
- it is done, online. but your local copy does not know about it, what you think is the next row at index X+1 is now online at row X
  then you delete the row at X+1 (which is X+1 online, but X+2 for your local copy).
and so on...

This is a known issue, there is the following issue open to track it: #881 

About the original issue, I advise you to first call `delete_rows` then get the new values of the spreadsheet, by using like `range()` or `get_values`.

**Comment by lavigne958** [comment]
Closing this issue since it is tracked by #881.
