### ISSUE TITLE
No insert_cols in 3.7

### ISSUE THREAD

**Issue by ryan-pixel** [burnash/gspread#853]
For whatever reason, I am unable to find the Worksheet insert_cols function in gspread's 3.7.0 version. I've updated the package and even when I go through the various functions via the autocomplete function for the worksheet model I cannot find the function.

**Comment by burnash** [comment]
I suggest double checking gspread version. E.g. `print(gspread __version__)` somewhere in the code you're using.

**Comment by lavigne958** [comment]
@ryan-pixel I double checked and the method `insert_cols` is here in version 3.7.0.

I would suggest you to double check your editor's settings.

function is present in mentioned (latest) version, closing this issue.
