### ISSUE TITLE
Cloning existing tables

### ISSUE THREAD

**Issue by moonzlo** [burnash/gspread#863]
I couldn't find any mention of this feature in the official google sheet documentation, but I can't believe that this task didn't occur to others. I need to copy a formatted table (template), and build more than a hundred other related tables based on it. To do this manually, as you understand, is simply useless, and I do not understand how to automate this process. Tell me how you can do this?

**Comment by moonzlo** [comment]
I'm sorry, I didn't immediately notice that this method was implemented. From the bottom of my heart, I express my gratitude to the one who made it.

**Comment by lavigne958** [comment]
Hi now worries @moonzlo , thank you for closing this issue as it is already solved :slightly_smiling_face:
