### ISSUE TITLE
Add ability to change formatting (bold/italics/underline) and justification (left/right/centre) of a cell's text

### ISSUE THREAD

**Issue by abmohan** [burnash/gspread#87]
Add the ability to make the contents of a cell bold, italics and/or underlined as well as to change the left/right/centre justification. 

I'm happy to help write the code

**Comment by jeetp13465** [comment]
has this feature been implemented as of now in the current version ?

**Comment by burnash** [comment]
@jeetp13465 No, this feature has not been implemented yet.
