### ISSUE TITLE
add CellNotFound exception to __init__.py

### ISSUE THREAD

**Issue by pjames5** [burnash/gspread#88]
Hello! Love the package and I have a suggestion - I have run into issues when I get a CellNotFound exception and have been unable to gracefully handle this exception with the code as is. I have solved it by adding CellNotFound to the __init__.py -> "from .exceptions import" statement and I think that others would benefit from this quick fix as well. 

Thanks! Keep up the good work ;)

Peter

**Comment by KeremKaratas** [comment]
It seems this issue persists today. Great workaround, thank you. I hope someone will change the file "__init__.py" to import CellNotFound from exceptions for future users of this great API.

**Comment by msuozzo** [comment]
Putting imports/code in \_\_init\_\_.py is discouraged style in Python. Does `from gspread.exceptions import CellNotFound` not work?

**Comment by krmkaratas** [comment]
That is the problem @msuozzo. To make that work CellNotFound should have been imported in __init__.py but I am guessing it was forgotten as all other exceptions are there.
