### ISSUE TITLE
Allow OAuth authentication for end users with JSON where I choose

### ISSUE THREAD

**Issue by joaocasarin** [burnash/gspread#880]
Hi, as it's already available for services accounts, it would be great if the method **gspread.oauth()** had the **filename** parameter, where the developer could pass the path to the credentials.json file, instead of locking it to **on Windows: %APPDATA%/gspread/**.

**Comment by lavigne958** [comment]
H @joaocasarin 

This feature has just been merged in master branch. It has not yet been released to pipy repository.

You can find the associated PR here #847 

At the moment your solution would be:
- update your current version to latest version from master branch
- wait a little bit for a new release on pipy repository

**Comment by joaocasarin** [comment]
Hi @lavigne958 !

Thanks for the answer, I didn't find that PR before.
