### ISSUE TITLE
Add method for service accounts within Google Functions

### ISSUE THREAD

**Issue by TehFamine** [burnash/gspread#886]
**Is your feature request related to a problem? Please describe.**
Yes. The problem is using an authentication method where you want to deploy gspread to a Google Function that is tied to a service account and do not want to store the service account key in the function itself for security purposes. It seems using ServiceAccountCredentials is not allowed with spread authentication.

**Describe the solution you'd like**
A method to use default service accounts with authentication.

**Describe alternatives you've considered**
I've used ServiceAccountCredentials that references the file itself. This works. But, does not work with default application methods.

**Additional context**
I could be missing something here being Google has 5008505853803803508 methods to authenticate versus AWS. But, I would love an easy way to use gspread with Google Functions, where the authentication can happen from the service account tied to the Google Function itself.

**Comment by lavigne958** [comment]
Can't do anything for this particular setup. Provided an alternative to it.

Closing this issue.
