### ISSUE TITLE
oauth() is missing the keyword argument 'authorized_user_filename' in gspread 3.7.0

### ISSUE THREAD

**Issue by mananyev** [burnash/gspread#890]
Hi,
I am sorry to create an issue but I wasn't able to find any similar issues described on the Internet.
I am trying to connect to google spreadsheets using the OAuth Client ID and I get a TypeError when passing the filename to oauth().

**Expected behavior**
I expected to get connected to the drive as it happens with gspread.oauth() (with the default location of the credentials file).

**Code example***
`gc = gspread.oauth(authorized_user_filename=gc_file)`

**Environment info:**
- Operating System [e.g. Linux, Windows, macOS]: Windows 10
- Python version 3.8.3
- gspread version 3.7.0

**Stack trace or other output that would be helpful**

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-49-4434cb025c8d> in <module>
>       1 gc_file = os.path.join(env_loc.replace('.env',''), 'creds', 'credentials.json')
> ----> 2 gc1 = gspread.oauth(authorized_user_filename=gc_file)
> 
> TypeError: oauth() got an unexpected keyword argument 'authorized_user_filename'

**Additional context**
The authentification worked properly when the credentials file is located in the `%APPDATA%/gspread/`.

**Comment by lavigne958** [comment]
Hi @mananyev , 
unfortunately using the latest released version of GSpread (Version 3.7.0) does not allow you to pass a filename to the method `oauth()`. the file must be located at the expected path `%APPDATA%\gspread\credentials.json`. 

the next release will allow you to pass the filename, if you do not want to wait you could download and use the latest (still in development) version of GSpread which already includes that new feature. it is up to you :slightly_smiling_face: 

I will close this issue, you can still comment here you thought or any other comment you may have about your issue.

**Comment by mananyev** [comment]
Hi @lavigne958,
Thank you very much for a quick reply!

> the next release will allow you to pass the filename, if you do not want to wait you could download and use the latest (still in development) version of GSpread which already includes that new feature. it is up to you 🙂
I can wait, no problem! :)
You're doing a great job! ^^
