### ISSUE TITLE
Query Result Caching

### ISSUE THREAD

**Issue by Bengt** [burnash/gspread#90]
Working with gspread is cumbersome, because requests are very slow. I have used apiclient and httplib2 before, which was fast enough not to interfere with developing.

My workaround was to pickle every data structure I created and restart in a new file, using the data structures, I had collected. So I ended up with a set of scripts that need to be executed in sequence to refresh the data. This speed up development a good bit, but is still cumbersome.

**Comment by burnash** [comment]
Closing this issue.
gspread has been ported to Sheets API v4 in [2.0.0](https://github.com/burnash/gspread/blob/master/HISTORY.rst#200-2018-03-11). I believe upgrading to the latest version should solve performance problems.
