### ISSUE TITLE
Please update the library on conda-forge/pypi

### ISSUE THREAD

**Issue by yathish1618** [burnash/gspread#900]
A new function get_worksheet_by_id  was added in the model - https://github.com/burnash/gspread/commit/011b44c0d64d10aa7f939b7c3b8bf0b99195b9dc

But I'm not able to use it in python environment because it's not yet updated on the conda/pip repositories. Can you please update it there?

Raising issue here based on the suggestion on my stackoverflow question regarding the same - 
https://stackoverflow.com/questions/68538824/gspread-package-not-updated-on-pip-or-conda/68539777

Thanks

**Comment by lavigne958** [comment]
Hi @yathish1618 ,

you are right this new function has not been published to PyPi yet.

It will very soon, we are discussing ,with @burnash , the new release. I think it be available in a few days.

**Comment by yathish1618** [comment]
Great, thanks!
