### ISSUE TITLE
Case when %APPDATA% on Windows does not exist

### ISSUE THREAD

**Issue by rlshuhart** [burnash/gspread#907]
I'm happy to see custom credential path now allowed for **credentials_filename** and **authorized_user_filename**  in the oauth function. Thanks, @slmtpz!

Unfortunately, the calling of get_config_dir() before consideration of the custom path still can be problematic.

https://github.com/burnash/gspread/blob/82eaf4ae56547449523fc3e8e30bb82769122b6f/gspread/auth.py#L31-L57

I have a use case where a python script executes as a specified service account user on a remote Windows server. In this situation, there is no APPDATA environment variable to retrieve and, therefore, I'm resulting in a ```KeyError: 'APPDATA'```.

Any creative ideas to a minimal change that would resolve this problem?

**Comment by burnash** [comment]
Thanks for reporting this. I haven't been using Windows for a while, so unfortunately I'm not familiar with the environment. 
I didn't expect that there could be a case where `APPDATA` is missing from the environment. That makes it a bug.

Before it gets fixed I guess the minimal change would be to add `APPDATA` key to `os.environ` before gspread gets imported. In Linux you can do this in the command line with something like `APPDATA=/path/to/dir python your_script.py`. I believe [something similar](https://superuser.com/questions/223104/setting-and-using-variable-within-same-command-line-in-windows-cmd-exe) exists in Windows. Alternatively you may set `APPDATA` in your Python script before importing gspread:

```python
import os
os.environ["APPDATA"] = "/path/to/dir"

import gspread
```

Open for a bugfix from someone who has expertise and access to Windows environment.

**Comment by rlshuhart** [comment]
@burnash thank you for the suggestion. It inspired what I think I will do as a work-around:

```
import os
if os.getenv("APPDATA") is None:
    os.environ["APPDATA"] = 'C:\my\path\to\cred\dir' 

import gspread
```

**Comment by lavigne958** [comment]
Hi @rlshuhart this looks like a great solution. 
I looked around online for python/windows %appdata% unset... and not much luck it seems that it should be set anyway by the operating system itself when you script start.

User has found a solution, closing this issue.

**Comment by rlshuhart** [comment]
Thanks for looking into it and all the other great work!
