### ISSUE TITLE
how i can execute the sheet formulas with gspread?

### ISSUE THREAD

**Issue by NitinNR** [burnash/gspread#911]
I want to find the value of certain column value and according to that need to update the other column value only with one api call
,like we do in MySQL update query.

and is there any way to execute the sheet formulas with gspread?

**Comment by lavigne958** [comment]
Hi @NitinNR ,

If I understand correctly what you try to achieve you need at least 2 API calls to do so:
1. to fetch the values, so you can read them
2. to update the appropriate cell based on the first values you have.

About your second point:
This is not really up to gspread to execute anything, but if one of your cells contain a formula then you can request to obtain the value of that cell and you can ask to get the result of the formula, or the formula itself. it is all located in the parameters of the function, like:

 ```python
worksheet.get_values("A1:A2", value_render_option="FORMATTED_VALUE")
```

here the `FORMATTED_VALUE` will ensure the content you get is the result of formula and its local currency/number format (if applicable) applied to it.

For any other question not related to an issue or feature requests directly impacting the code/the doc/the CI etc please refer to [stackOverflow#gspread](lhttps://stackoverflow.com/questions/tagged/gspread) you'll get a much quicker answer and with more details.

I'll close the issue as this is not a issue related to the source code itself :-) but feel free to comment if you need to.

Closing this issue
