### ISSUE TITLE
add batch_format method to Worksheet eliminating the need for multi request for formatting cells

### ISSUE THREAD

**Issue by Hagkal** [burnash/gspread#929]
**Is your feature request related to a problem? Please describe.**
i recently made a small program with this package. it is a great experience!
the issue came when i needed to format some cells in arbitrary places (not in a range).
that forced me to make lots of `Worksheet.format` calls (which results in an api fired to google). that method proved ok until my the formatting need exceeded my quota (or other network/time constrains).

i eventually made a helper function and class for storing format requests and then fired them with `Spreadsheet.batch_update`.

i would love to share my solution via PR if it would also aid anyone here (`CONTRIBUTING.md` asked to put an issue first))

**Describe the solution you'd like**
i would like a solution that stores format requests and then be able to fire all of them at once (with a single api call to google).

**Describe alternatives you've considered**
simply wait until i can make another api calls to google and them continue the program (this is BAD)

i have already made the solution to my project, would love to share it.

**Comment by ericbn** [comment]
I've also worked on a solution for this locally, making `Worksheet.format` accept both a scalar or a list, so both
```
worksheet.format("A4", {"textFormat": {"bold": True}})
worksheet.format(["A1", "A4"], {"textFormat": {"bold": True}})
```
work.

Having a `Worksheet.batch_format` instead is maybe a better option, closer to the already existing ones for accepting a list of ranges.

**Comment by lavigne958** [comment]
Hi @Hagkal Have you consider opening a PR ? if not I can do it and update gspread as follow:

1. update the method `worksheet.format` to accept a scalar or a list, as mentioned by @ericbn 
2. add a new method `worksheet.batch_update` that can take a list of dictionaries in the form
    ```json
    {
      "range": "A1:B1",
      "format": {
        "horizontalAlignment": "CENTER",
      },
    }
    ```

This should solve the following points:
1. users that want to apply a format to multiple non contiguous cells will only need a single API call
2. users that want to apply different format on multiple non contiguous ranges will only need a single API call,
    but they will be required to forge most of the requests manually (see above JSON sample).

**Comment by lavigne958** [comment]
@ericbn perhaps you would like to take a look at this issue and open a PR ? 

Otherwise I'll do the PR to make sure we close this issue before 1st of June.
