### ISSUE TITLE
READ TIMEOUT: HTTPSConnectionPool(host='sheets.googleapis.com', port=443): Read timed out. (read timeout=120)

### ISSUE THREAD

**Issue by ronpatel916** [burnash/gspread#940]
Issue:

There is a timeout on the server side that is preventing me from uploading data to a google sheet.

**Describe the bug**

HTTPSConnectionPool(host='sheets.googleapis.com', port=443): Read timed out. (read timeout=120)

The connection is closed on the server side. Is there a way to increase the read timeout limit?

**Code example***
`client = gspread.authorize(credentials)

    wb = client.open(title)
    sheet = wb.worksheet(name)

    sheet.clear()
    result = sheet.update(df)`

Request times out on the result = sheet.update(df) line.

**Environment info:**
- Operating System [e.g. Linux, Windows, macOS]: Windows
- Python 3.8.8
- gspread version

**Comment by lavigne958** [comment]
no response from issue owner, not an error from gspread.

closing this issue.
