### ISSUE TITLE
gspread cannot write data to google sheet if rows over 10,000 records

### ISSUE THREAD

**Issue by pbunluesin** [burnash/gspread#950]
I got this error when write data to google sheet over 10,000 records on google sheet

`gspread.exceptions.APIError: {'code': 400, 'message': 'Invalid requests[0].updateSheetProperties: This action would increase the number of cells in the workbook above the limit of 5000000 cells.', 'status': 'INVALID_ARGUMENT'}`

**To Reproduce**
1.  Clean existed data on sheet with worksheet.clear()
2.  write new data with pandas data frame gd.set_with_dataframe(worksheet=worksheet,dataframe=df,include_index=False,include_column_header=True,resize=True)

**Expected behavior**
all data should be put on google sheet no matter data is over than 10,000 rows but I got that error when the data over than 10,000 records.

**Code example***
If applicable, provide a code example to help explain your problem.

**Screenshots**

**Environment info:**
- Operating System: WIndows
- Python version: 3.9.1
- gspread version: 3.6.0

**Stack trace or other output that would be helpful**
`PS E:\python\AuthorizeWithATK> python student_write_data_gspread.py
Traceback (most recent call last):
  File "E:\python\AuthorizeWithATK\student_write_data_gspread.py", line 97, in <module>
    result = export_to_sheets(df,'w')
  File "E:\python\AuthorizeWithATK\student_write_data_gspread.py", line 81, in export_to_sheets
    gd.set_with_dataframe(worksheet=worksheet,dataframe=df,include_index=False,include_column_header=True,resize=True)
  File "C:\Program Files\Python39\lib\site-packages\gspread_dataframe.py", line 280, in set_with_dataframe
    worksheet.resize(y, x)
  File "C:\Users\phatthab\AppData\Roaming\Python\Python39\site-packages\gspread\models.py", line 1272, in resize
    return self.spreadsheet.batch_update(body)
  File "C:\Users\phatthab\AppData\Roaming\Python\Python39\site-packages\gspread\models.py", line 145, in batch_update
    r = self.client.request(
  File "C:\Users\phatthab\AppData\Roaming\Python\Python39\site-packages\gspread\client.py", line 73, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 400, 'message': 'Invalid requests[0].updateSheetProperties: This action would increase the number of cells in the workbook above the limit of 5000000 cells.', 'status': 'INVALID_ARGUMENT'}
PS E:\python\AuthorizeWithATK>`

**Comment by lavigne958** [comment]
Hi @pbunluesin

As the error mentions it, this is not a gspread error 🙄
This is a Google spreadsheet limit.

Basicly, as mentioned in the error message: Google prevents you from from having more than 5 million cells in a workbook.

Closing this issue as this is not a gspread error.
