### ISSUE TITLE
Reduce API request number for API call limitation reasons.

### ISSUE THREAD

**Issue by sandl99** [burnash/gspread#963]
Hi, 
After reading your lib, I appreciate your contribution to an easy, fast Google SpreadSheet API.
I saw in class `SpreadSheet`, you call every single `spreadsheets.get` for every single function `get_workspace`. I think you should update all of workspace metadata in `__init__` method of `SpreadSheet` class for reducing call gg API.

Thanks again

**Comment by lavigne958** [comment]
Hello @sandl99 ,

Thabk you very much we are happy that you like gspread.

I don't understand what's you mean sorry, you mention `wo4kspaces` but we don't have such objects, do you mean `worksheets`?

**Comment by sandl99** [comment]
Ops I'm sorry about that. I mean `worksheets`.
In class `Spreadsheet`, `__init__` `get_worksheet` `worksheet` call the same google api `spreasheet.get`. So I think you can cache response of google api `spreasheet.get`.

**Comment by lavigne958** [comment]
I checked the methods you mention, yes we call the method `fetch_sheet_metadata` each time.
But in the case of `__init__` we only keep the `properties` section and in the other cases we only keep the `sheet` section.

We could keep the list of sheets from the `sheet` section in the `__init__` but gspread is asyncrhonous and does not handle concurrency. So if we get the list of sheets at `__init__` and later try to get a sheet, it might have change, it might not exists anymore. This is why when you request a specific sheet using `get_worksheet` or `worksheet` we must call the API again and retrieve the latest informations.

This is why we can't cache the response from the GET request.

**Comment by sandl99** [comment]
> So if we get the list of sheets at `__init__` and later try to get a sheet, it might have change, it might not exists anymore.

Sorry, I didn't get what you mean here. What things `not exists` ? 
About asynchronous, I think it doesn't relate with seperating api to many call times.

**Comment by lavigne958** [comment]
I found the issue that tracks that matter: #881 

I made a proposal for a solution, I'll add your proposal too: having a boolean flag at init of a spreadsheet that activate some caching mechanism

**Comment by sandl99** [comment]
Yeah, Thank you again.
If some apps do many jobs like crawling on the large numbers of static or rarely updated SpreadSheet, this options will should be applied.
