### ISSUE TITLE
Non destructive import_csv for worksheets

### ISSUE THREAD

**Issue by kd-mariyan** [burnash/gspread#965]
For `client.import_csv(...)` this imports data into the first worksheet, but it also deletes everything that is contained in the spreadsheet. Is there a reason that one could not specify which worksheet to import the CSV to and avoid deleting all the contents of the spreadsheet?

**Comment by lavigne958** [comment]
Hi @kd-mariyan 

Sorry we can't, this behavior is fromm google API.
The way CSV is loaded is:
- take the CSV content
- create/replace spreadsheet file with the content.

It is documented [here](https://developers.google.com/drive/api/v3/manage-uploads?hl=en#python_1)

Quote from the documentation:

> When you upload and convert media during an update request to a Google Doc, Sheet, or Slide, the full contents of the document are replaced.

**Comment by kd-mariyan** [comment]
Thanks for the reply! Aha I see, it is strange that that is the only behaviour they allow. It is possible to do manually when working on the sheets in drive but yeah they’ve limited the API. Going to have to find another way.

**Comment by lavigne958** [comment]
I noticed that they mention something about updating the file, use the PUT request.

I'll open an issue in Google cloud platform to check with them if this is can be looked at.

Closing this issue in the mean time.

**Comment by kd-mariyan** [comment]
Thats a good idea! Would you be able to drop a link to the issue if you decide to open it? Thanks
