### ISSUE TITLE
Import spreadsheet

### ISSUE THREAD

**Issue by finoptimal-dev** [burnash/gspread#97]
It would be REALLY cool if we could pass a path to a function that would perform the 'upload' function in Google Drive, converting the file to a Google spreadsheet. The new Google doc's name or key or both could be returned.

The opposite functionality would be great too, of course.

**Comment by msuozzo** [comment]
This is possible with the [Google Drive API](https://developers.google.com/drive/web/manage-uploads). Also, this feels like it fits within the scope of gspread. I'll add it as a feature request :-)

**Comment by burnash** [comment]
:+1:

**Comment by lavigne958** [comment]
this issue sould be closed right @burnash ?

**Comment by burnash** [comment]
@lavigne958 exactly, thanks for the reminder

**Comment by burnash** [comment]
@lavigne958 would you be interested in joining gspread as a co-maintainer?

**Comment by lavigne958** [comment]
yes thanks that would be great, thanks :-) is you e-mail in the commit up to date ? to speak about it ?

**Comment by burnash** [comment]
Yes, it is.
