### ISSUE TITLE
Add column headers validation for `get_all_records`

### ISSUE THREAD

**Issue by filip-31** [burnash/gspread#973]
The current implementation of `get_all_records` lacks header validation to make sure headers are unique. If two `key` row values are the same the dictionary takes just the second value as dictionaries require unique key: value pairs and the second value just overrides the first one

I'd suggest adding validation for the `keys` row that checks if all the values in this row are unique.

Alternatively, to avoid making multiple calls to google API (first for `get_all_values` then `get_all_records`) this function could accept already pulled list of values as an optional argument and allow the user to pull the values, perform his own validation, and then convert the list of values from `get_all_values` to records

**Comment by lavigne958** [comment]
Hi @filip-31 

thank you for bringing that issue, this is concerning.

I agree, we must add some kind of validation to make sure every `key` in the dict is unique.

About the second point this is a bit more complexe. this is a complete new feature to introduce.

I will open a new issue to track you second idea which is:

- break the method `get_all_records` in 2 parts
  1. pull all the values
  2. generate the list of dicts
- update the current method/add a new method that can accept already pulled values
- from there call the part 2 of the `get_all_records` that will generate the list of dicts from the values
  (values that would be given by the user *or* pulled by the function)

In the meantime I will keep this issue to track the original bug: each key must be unique.

thanks for your help.
