### ISSUE TITLE
Add copy_comments argument in Client.copy() method 

### ISSUE THREAD

**Issue by Targolo** [burnash/gspread#978]
Hi,

The Client.copy() method currently has copy_permissions option, but lacks the copy_comments option.
It is an option that you have when you make a copy in the Google Sheet itself in the browser

Thanks
David

**Comment by lavigne958** [comment]
Hi @Targolo ,

thank you for bring that improvement.

This can be achieved, using the [Drive API](https://developers.google.com/drive/api/v3/reference/comments#resource)

I'll will plan it in the coming releases.

**Comment by Targolo** [comment]
Hi,
I am not sure that the link you sent is related to what I am talking about. I am not talking about the comment on the file, in Google Drive.

I would like to copy the comments that are in the sheet itself, on cells or groups of cells.
In fact, I cannot imagine to copy a GoogleSheet and not copy the comments that are inside. I do not understand why this is not the default behavior of the API that copies the file.

Thanks

**Comment by lavigne958** [comment]
Hi, I strongly believe that comments on a google drive file (Sheet, presentation, docs, ...) are a special resource that are handled by the google drive API. I need to test it to confirm it.

In that case, copying a google spreadsheet does not copy the comments because they are a different resource, but they are linked to each others in some way (same, I need to check to understand that link).

That's why I sent you this link.

I'll come back to you after some test :wink:

**Comment by lavigne958** [comment]
Hi @Targolo 

I have a great news, I ran some tests using the Drive API, I managed to list all the comments of a spreadsheet and then manually push the same comment to a new spreadsheet, at the exact same location.

I'll open a PR when I get a chance.

**Comment by abubelinha** [comment]
Hi @lavigne958 
As you did something similar in your tests, I wonder if it is possible to somehow copy all comments in a Gsheet to a python object. i.e. a dictionary 
```
{"sheet name 1": [
   {"cell":"A:4", "user":"abubelinha", "date":"2022-06-09_21:10:30", "comment":"blah blah"}, 
   {... another comment ...},
   {... another comment ...},
    ...
   ], 
"sheet name 2": [
   {... another comment ...},
   {... another comment ...},
    ...
  ]
}
```
I regularly backup a bunch of collaborative Google sheets to pandas dataframes, but I don't want to miss all comments made by different users about particular cells.

Do you have any clues about how to save them?
Thanks a lot
@abubelinha

**Comment by lavigne958** [comment]
Oh ok no worries then.

sure sure I can, in fact All I did is follow [this](https://developers.google.com/drive/api/v3/reference/comments/list) API.

When using gspread, the google client is already created, so you'll need to do this part manually, then I tried something like this:

```python
file_id = "abcdefg1340598abcedef"
url = "https://www.googleapis.com/drive/v3/files/{}/comments".format(file_id)
params = {
    "fields": "*",
}

res = session.get(url, params=params)
response = res.json()
```
then the object `response` is a `dict` object that follows the JSON format describe in the link above in the section [resposne body](https://developers.google.com/drive/api/v3/reference/comments/list#response)

change the value of `fields` to choose want you'd like to get in the response, `*` means _everything_, but you can filter out if needed.

**Comment by abubelinha** [comment]
Thanks for sharing that!

I have always used [PyDrive](https://github.com/googlearchive/PyDrive)/[PyDrive2](https://github.com/iterative/PyDrive2) projects to simplify Gdrive access from Python, so I have not clear how to get that `session` object in your example. I guess it's related to Google authentication but if you don't mind to share your authentication method code it would be great (that's always a nightmare for me).

Or can I grab it from some other linkable part of gspread code? I used gspread in the past, but I don't remember a `session` object when authenticating there either. I always got a `gc` (Google credentials) object like [explained here](https://docs.gspread.org/en/latest/oauth2.html):
```
gc = gspread.oauth(
    credentials_filename='path/to/the/credentials.json',
    authorized_user_filename='path/to/the/authorized_user.json'
)
```

Unrelated question: I understand your example will be valid for listing comments from any other Gdrive documents, right?  (not only Google sheets, but also Google docs or any other)

Thanks a lot for your help!

**Comment by lavigne958** [comment]
Hi I see you opened an issue in the repository PyDrive2, this is the best way to go.

I had a look at PyDrive2 and they use a completely different approach. In gspread we use only HTTP requests to get/update/delete any data. PyDrive2 uses a google dedicated library to interact with google drive itself, so you won't have access to a `session` object. 

You are right in gspread we use the `gc` object (which the class `Client`), behind the scene you are right we use the google library that provide the class `AuthorizedSession` which returns a `sessions` object that can send HTTP requests.

You could getaway with the `gc` object and use its `requests` method but it's not the best way to go "as a developer". I'll suggest you to use the `AuthorizedSession` (you can copy/paste what we in gspread to login and get the session object). then you can do as mentioned above `session.requests(....)`. This would a much cleaner way and you won't have to rely on gspread (which might change in the future etc).

**Comment by lavigne958** [comment]
yes I faced that issue last time I tried to work with comments. the `anchor` is encoded and somewhere in the documentation it mentions that this is proprietary to Google.

It could be if this Excel library can provide you with the coordinates of the comment.

Anyway I'm glad you managed to get what you where looking for, even though it seems not as useful as expected due to the `anchor`.
