### ISSUE TITLE
update_cell problem

### ISSUE THREAD

**Issue by mgiuglio** [burnash/gspread#98]
Hello,

I have a system updating Google drive with 3G connection.
I realized that when my connection drops while updating a cell my program freezes in the update cell function forever.
Can this be fixed?

Thanks a lot.

Marcelo.

**Comment by msuozzo** [comment]
Hello Marcelo,
Can you provide any more information about the the issue? Has it persisted? There is a known issue (#280) that gspread does not support timeouts so lost requests will fair to return. It's possible your problem may be related.
