### ISSUE TITLE
Duplicate column names with get_all_records()

### ISSUE THREAD

**Issue by tanjt107** [burnash/gspread#986]
When there are duplicate column names in the spreadsheet. The return does not contain all columns and only return the last occurrence of the same column name

I added something like this in my code
```
def initialize_cols(ws: gspread.Worksheet) -> None:
    """Rename duplicate column names for identification."""
    names = ws.row_values(1)
    counts = {}

    for i, col in enumerate(names):
        cur_count = counts.get(col, 0)

        if cur_count > 0:
            ws.update_cell(1, i + 1, f"{col}.{cur_count}")
            print(f"Renamed '{col}' to '{col}.{cur_count}'")

        counts[col] = cur_count + 1
```

Can this add to the package?

**Comment by filip-31** [comment]
Validation for column headers was added in [this](https://github.com/burnash/gspread/pull/984) PR and it will be introduced in the 5.2.0 milestone. Here's an open issue on future work on `get_all_records`: https://github.com/burnash/gspread/issues/976 (correct me if I'm wrong here @lavigne958 👍 )

**Comment by lavigne958** [comment]
You're right that's exactly the case. In next release the function will raise of headers are duplicated.

The above solution works for your scenario but can't be added to gspread because it does not fit everyone's scenario. We never change user's spreadsheet content.

**Comment by lavigne958** [comment]
closing this issue as duplicate.

**Comment by janderamancio** [comment]
I'm trying to print my dataframe and the error appears:
sh = gc.open('name')

worksheet = sh.sheet1

df = pd.DataFrame(worksheet.get_all_records())
print(df)

File "C:\Users\Usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\gspread\worksheet.py", line 520, in get_all_records
    raise GSpreadException("the given 'expected_headers' are not uniques")
gspread.exceptions.GSpreadException: the given 'expected_headers' are not uniques

**Comment by lavigne958** [comment]
Hi this means the headers in your worksheet are not unique. Because this method returns a dict where the keys are based on the header row, they must be unique or must pass the indices of columns you know won't be unique and that you will ignore/skip.
