### ISSUE TITLE
Add ability to batch add/remove comments and notes for cells 

### ISSUE THREAD

**Issue by achyutjoshi** [burnash/gspread#988]
**Is your feature request related to a problem? Please describe.**
We have an `insert_note` function, however, this happens at an individual cell level. I need to batch add comments and I always exceed the API limit. 

**Describe the solution you'd like**
Similar to Batch-add cells, we can have the `batch_insert_note` function. 

**Describe alternatives you've considered**
I currently run a loop and use a try-catch to handle for APIError. However, this is not a suitable way of doing things. 

**Additional context**

**Comment by achyutjoshi** [comment]
Yes, that will be perfect!!

**Comment by dr-bright** [comment]
Let me propose a plan:

1) add gspread.Cell.note field
  - sheet.update_cells can now be used to modify cell notes
  - all cell-returning methods now automatically support notes
2) add gspead.Worksheet.update_notes(range,  notes: list[list]) method
  - now uploading notes is as simple as uploading values though worksheet.update(). Can easily be merged with numpy and pandas
3) add gspread.Worksheet.get_notes(range)
  - and now downloading notes is also easy and can feed numpy and pandas


Possible issues:
  - update_notes(...) can unintentionally override some notes. update(...) seems to ignore None entires in input matrix to avoid this issue, so update_notes should do that as well.

Further improvement:

4) add batch_get_notes and etc. to mirror their value-oriented counterparts
5) maybe batch_* methods section as a whole would benefit from some rework. Feels like lots of upcoming painful backwards-compatibility issues
6) maybe Cell class would benefit from richer functionality like notes and formatting

**Comment by ebenahar** [comment]
Hi @lavigne958 @dr-bright my project would highly benefit from such improvement. Is there any preliminary WIP work for that I can refer to?

**Comment by lavigne958** [comment]
Hi I wanted to introduce it in the 6.0.0 and move it to the cell object.

If you need it I'll introduce it in the coming release with #1185 

When I get a chance (hopefully soon)
