### ISSUE TITLE
add method to change tab color

### ISSUE THREAD

**Issue by lavigne958** [burnash/gspread#996]
## Overview

add method to change the color of a tab

## Details

The api provide a way to change the color of a worksheet tab: [sheet API v4](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/sheets#SheetProperties)

expose necessary methods to change that tab color.

**Comment by cgkoutzigiannis** [comment]
Hey! I would really like to implement this, I just have one quick question. When you say tab do you mean the spreadsheet column?

**Comment by lavigne958** [comment]
Hi, no sorry the tab is the little rectangular thing at the bottom of the spreadsheet (when using your web browser) that shows you the name of the sheet.

**Comment by lavigne958** [comment]
BTW I just found out there is a bug in the Google API, if you read the doc you'll see that the API accepts 2 possible fields to change the color of  tab: `tabColor` and `tabColorStyle`.

the field `tabColor` is deprecated in favor of `tabColorStyle`. After running some sample codes I noticed that the new field `tabColorStyle` does not work, so currently we must use the old deprecated entry field `tabColor` instead.

I opened a new issue on google side to track that issue: https://issuetracker.google.com/issues/236109669

In order to make it easy for us to update when they fix it, please fill the request object with **both** entry field (don't forget about the entry `fields` that contains the fields we want to update) so when It works we'll only need to remove the old deprecated entry.

may the force be with you :ringed_planet: , if you need any assistance feel free to comment here :smile:

**Comment by cgkoutzigiannis** [comment]
Thanks for pointing that out! I think we should expose a new function on the ```Worksheet``` class. So this is what I'm thinking for the implementation:
```python
def update_color(self, color):
        body = {
            "requests": [
                {
                    "updateSheetProperties": {
                        "properties": {
                            "sheetId": self.id,
                            "tabColor": {"red": color["red"], "green": color["green"], "blue": color["blue"]},
                            "tabColorStyle": {
                                "rgbColor": {"red": color["red"], "green": color["green"], "blue": color["blue"]}
                            },
                        },
                        "fields": "tabColor.tabColorStyle",
                    }
                }
            ]
        }

        response = self.spreadsheet.batch_update(body)
        return response
```
I do have a few questions:
1. Do you think we should expose a method to get the current tab color?
2. I don't really know how I should test this with my own sheets, to check if it works. Any pointers?

**Comment by lavigne958** [comment]
it looks fine :wink:  open a PR and I'll review it and put my comments there.

for your questions:

1. yes we should, that would be awesome, you can make it in the same PR, just a separate commit
2. That's any issue, you should know what you are coding for :slightly_smiling_face: , what you are coding is for changing the color of the tab, the tab is the little grey rectangle at the bottom of the sheet, it contains the name of the current sheet (online on a web browser). So sending the above request should trigger a color change on that area. exactly just below the name of the sheet.
